### PR TITLE
[Long-format table annotation Part 3] annotator R CLI

### PR DESCRIPTION
**Pull request by logstar**
### Purpose/implementation Section

#### What scientific question is your analysis addressing?

Create application programming interface (API) and command line interface (CLI) for handling [long-format tables](https://en.wikipedia.org/wiki/Wide_and_narrow_data#Narrow) that are generated by analysis modules. API provides analysis module developers with functions that can be imported into their own scripts via R `source('path/to/the/function/file.R')` or Python `import os, sys; sys.path.append(os.path.abspath("path/to/the/function/dir")); import function_filename_but_no_dot_py`. CLI provides analysis module developers with scripts that can be executed in their own run-module shell script with either `Rscript --vanilla path/to/the/script.R arg long.tsv long_edited.tsv` or `python3 path/to/the/script.py arg long.tsv long_edited.tsv`.

This module is suggested by @jharenza and @kgaonkar6 in Slack at <https://opentargetspediatrics.slack.com/archives/C021Z53SK98/p1626290031138100?thread_ts=1626287625.133600&cid=C021Z53SK98>, in order to alleviate the burdens of analysis module developers for adding annotations and keeping track of what annotations need to be added. This module could also potentially handle large file storage issues at a later point, since the file size limit of GitHub is 100MB.

| Sub-module name                                               | Implemented function                    | Available interface(s)                                                                                 |
|---------------------------------------------------------------|-----------------------------------------|--------------------------------------------------------------------------------------------------------|
| `annotator` | Add gene and `cancer_group` annotations | R API, R CLI |

This pull request is the third part of the `long-format-table-utils` module, which implements the `annotator` R CLI.

#### What was your approach?

The `long-format-table-utils/annotator/annotator-cli.R` file provides an R CLI for using the API to annotate long-format tables.

Check input long-format tables have the following columns:

| Column name       | Description                                                                                                                                              |
|-------------------|----------------------------------------------------------------------------------------------------------------------------------------------------------|
| `Gene_symbol`     | HUGO symbols, e.g. PHLPP1, TM6SF1, and DNAH5.                                                                                                            |
| `Gene_Ensembl_ID` | Ensembl ENSG IDs without `.#` versions, e.g. ENSG00000039139, ENSG00000111261, and ENSG00000169710                                                       |
| `Disease`         | The `cancer_group` in the `histologies.tsv`, e.g. Adamantinomatous Craniopharyngioma, Atypical Teratoid Rhabdoid Tumor, and Low-grade glioma/astrocytoma |

Add one or more of the following gene annotations, by specifying the `columns_to_add` parameter in the `annotate_long_format_table` function, or specifying the `-c` option when running `annotator-cli.R`.

| Annotation column name | Non-missing value                                                                                                                                                                                                                                                      | Source data                                                                                         |
|------------------------|------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|-----------------------------------------------------------------------------------------------------|
| `RMTL`                 | `Relevant Molecular Target (RMTL version 1)` or `Non-Relevant Molecular Target (RMTL version 1)`                                                                                                                                                                       | `data/ensg-hugo-rmtl-v1-mapping.tsv`                                                                |
| `Gene_type`            | A sorted comma separated list of one or more of the following gene types: `CosmicCensus`, `Kinase`, `Oncogene`, `TranscriptionFactor`, and `TumorSuppressorGene`. Example values: `CosmicCensus`, `CosmicCensus,Kinase`, and `CosmicCensus,Kinase,TumorSuppressorGene`. | `analyses/fusion_filtering/references/genelistreference.txt`                                        |
| `OncoKB_cancer_gene`   | `Y` or `N`                                                                                                                                                                                                                                                             | `analyses/long-format-table-utils/annotator/annotation-data/oncokb-cancer-gene-list.tsv`            |
| `OncoKB_oncogene_TSG`  | `Oncogene`, or `TumorSuppressorGene`, or `Oncogene,TumorSuppressorGene`                                                                                                                                                                                                | `analyses/long-format-table-utils/annotator/annotation-data/oncokb-cancer-gene-list.tsv`            |
| `Gene_full_name`       | A single string of gene full name, e.g. `cytochrome c oxidase subunit III` and `ATP synthase F0 subunit 6`                                                                                                                                                             | `analyses/long-format-table-utils/annotator/annotation-data/ensg-gene-full-name-refseq-protein.tsv` |
| `Protein_RefSeq_ID`    | A sorted comma separated list of one or more protein RefSeq IDs, e.g. `NP_004065.1`, `NP_000053.2,NP_001027466.1`, and `NP_000985.1,NP_001007074.1,NP_001007075.1`                                                                                                     | `analyses/long-format-table-utils/annotator/annotation-data/ensg-gene-full-name-refseq-protein.tsv` |

The `RMTL` information is obtained from PediatricOpenTargets/OpenPedCan-analysis data release.

Note: only add `Gene_type` to gene-level tables, which can be implemented by leaving `"Gene_type"` out of the `columns_to_add` parameter of the `annotate_long_format_table` function in `annotator-api.R`. The `Gene_type` information is obtained from `../fusion_filtering/references/genelistreference.txt`, and its sources are described at <https://github.com/d3b-center/annoFuse#prerequisites-for-cohort-level-analysis>.

The `OncoKB_cancer_gene` and `OncoKB_oncogene_TSG` information is listed in `annotator/annotation-data/oncokb-cancer-gene-list.tsv`, which is downloaded from <https://www.oncokb.org/cancerGenes>. The last update of the table is on 06/16/2021. To update the table, re-download the updated table from <https://www.oncokb.org/cancerGenes>.

The `Gene_full_name` and `Protein_RefSeq_ID` information is downloaded from <https://mygene.info/> using the [mygene package](https://bioconductor.org/packages/release/bioc/html/mygene.html).

Add the following disease(/`cancer_group`) annotations:

Add one or more of the following disease(/`cancer_group`) annotations, by specifying the `columns_to_add` parameter in the `annotate_long_format_table` function, or specifying the `-c` option when running `annotator-cli.R`.

| Annotation column name | Non-missing value                                                                         | Source data              |
|------------------------|-------------------------------------------------------------------------------------------|--------------------------|
| `EFO`                  | A single string of EFO code, e.g. `EFO_1000069`, `EFO_1002008`, and `EFO_1000177`         | `data/efo-mondo-map.tsv` |
| `MONDO`                | A single string of MONDO code, e.g. `MONDO_0002787`, `MONDO_0020560`, and `MONDO_0009837` | `data/efo-mondo-map.tsv` |

The `EFO` and `MONDO` information is obtained from PediatricOpenTargets/OpenPedCan-analysis data release.

Use the long-format table annotator CLI in an analysis module with the following steps:

1. If `"Gene_symbol", "Gene_Ensembl_ID", "Disease"` are not all present in the column names of the table to be annotated, add new columns or rename existing ones to have all these required columns.
2. Output the table that needs to be annotated in TSV format.
3. Change the working directory to be `OpenPedCan-analysis` or a subdirectory of `OpenPedCan-analysis`. This allows the `annotator-cli.R` to locate the `annotator-api.R`.
4. Run the `annotator-cli.R` script with `Rscript --vanilla path/to/annotator-cli.R` and proper options. The `Rscript` command can be invoked by R `system("Rscript --vanilla path/to/annotator-cli.R -h")` (if the annotator R API is not preferred) or Python (>= 3.5) `import subprocess; subprocess.run("Rscript --vanilla analyses/long-format-table-utils/annotator/annotator-cli.R -h".split())`. For more information about R `system`, <https://stat.ethz.ch/R-manual/R-devel/library/base/html/system.html>. For more information about Python (>= 3.5) `subprocess.run`, <https://docs.python.org/3/library/subprocess.html#subprocess.run>.
5. Read the annotated table TSV file.
6. Rename, select, and reorder the columns of the annotated table for output in TSV, or JSON, or JSONL formats.

Following is an example usage in the `rna-seq-expression-summary-stats` module `01-tpm-summary-stats.R`.

```text
> getwd()
[1] "/home/rstudio/OpenPedCan-analysis/analyses/rna-seq-expression-summary-stats"
> class(m_tpm_ss_long_tbl)
[1] "tbl_df"     "tbl"        "data.frame"
> colnames(m_tpm_ss_long_tbl)
 [1] "gene_symbol"                          "gene_id"                             
 [3] "cancer_group"                         "cohort"                              
 [5] "tpm_mean"                             "tpm_sd"                              
 [7] "tpm_mean_cancer_group_wise_zscore"    "tpm_mean_gene_wise_zscore"           
 [9] "tpm_mean_cancer_group_wise_quantiles" "n_samples"                           
> 
> renamed_m_tpm_ss_long_tbl <- dplyr::rename(
+   m_tpm_ss_long_tbl, Gene_symbol = gene_symbol, Gene_Ensembl_ID = gene_id,
+   Disease = cancer_group)
> 
> readr::write_tsv(
+   renamed_m_tpm_ss_long_tbl,
+   "../../scratch/renamed_m_tpm_ss_long_tbl.tsv")
> 
> system(paste(
+   "Rscript --vanilla ../long-format-table-utils/annotator/annotator-cli.R",
+   "-r -v -c MONDO,RMTL,EFO",
+   "-i ../../scratch/renamed_m_tpm_ss_long_tbl.tsv",
+   "-o ../../scratch/annotated_renamed_m_tpm_ss_long_tbl.tsv"))
Read ../../scratch/renamed_m_tpm_ss_long_tbl.tsv...
Annotate ../../scratch/renamed_m_tpm_ss_long_tbl.tsv...
Output ../../scratch/annotated_renamed_m_tpm_ss_long_tbl.tsv...
Done.
> 
> annotated_renamed_m_tpm_ss_long_tbl <- readr::read_tsv(
+   "../../scratch/annotated_renamed_m_tpm_ss_long_tbl.tsv",
+   na = character(),
+   col_types = readr::cols(.default = readr::col_guess()))
|==================================================================================================| 100%  222 MB
> m_tpm_ss_long_tbl <- dplyr::rename(
+   annotated_renamed_m_tpm_ss_long_tbl,
+   gene_symbol = Gene_symbol, gene_id = Gene_Ensembl_ID,
+   cancer_group = Disease)
> m_tpm_ss_long_tbl <- dplyr::select(
+   m_tpm_ss_long_tbl, gene_symbol, RMTL, gene_id,
+   cancer_group, EFO, MONDO, n_samples, cohort,
+   tpm_mean, tpm_sd,
+   tpm_mean_cancer_group_wise_zscore, tpm_mean_gene_wise_zscore,
+   tpm_mean_cancer_group_wise_quantiles)
```

#### What GitHub issue does your pull request address?

<https://github.com/PediatricOpenTargets/ticket-tracker/issues/112>

### Directions for reviewers. Tell potential reviewers what kind of feedback you are soliciting.

#### Which areas should receive a particularly close look?

Whether the code in `annotator/annotator-cli.R` works as expected?

#### Is the analysis in a mature enough form that the resulting figure(s) and/or table(s) are ready for review?

Yes.

### Results

#### What types of results are included (e.g., table, figure)?

No result.

#### What is your summary of the results?

No result.

#### Reproducibility Checklist

<!-- Check all those that apply or remove this section if it is not applicable.-->

- [x] The dependencies required to run the code in this pull request have been added to the project Dockerfile.
- [NA. CI is not available yet.] This analysis has been added to continuous integration.

#### Documentation Checklist

<!-- Please review https://github.com/AlexsLemonade/OpenPBTA-analysis#documenting-your-analysis -->

- [x] This analysis module has a `README` and it is up to date.
- [x] This analysis is recorded in the table in `analyses/README.md` and the entry is up to date.
- [x] The analytical code is documented and contains comments.

### CODE REVIEW

**Review by jharenza — APPROVED** [review]
This works as expected. Tested below:

```
setwd("~/OT/analyses/rna-seq-expression-summary-stats/")

library(tidyverse)
zscores <- read_tsv("~/OT/analyses/rna-seq-expression-summary-stats/results/long_n_tpm_mean_sd_quantile_gene_wise_zscore.tsv.gz") %>%
  rename(Gene_symbol = gene_symbol, Gene_Ensembl_ID = gene_id, Disease = cancer_group) %>%
  select(Gene_symbol, Gene_Ensembl_ID, cohort, Disease, tpm_mean, tpm_sd, n_samples, tpm_mean_gene_wise_zscore, tpm_mean_cancer_group_wise_quantiles) 
write_tsv(zscores, "../../scratch/renamed_zscores.tsv")

system(paste(
  "Rscript --vanilla ../long-format-table-utils/annotator/annotator-cli.R",
  "-r -v -c MONDO,RMTL,EFO",
  "-i ../../scratch/renamed_zscores.tsv",
  "-o ../../scratch/ann_zscores.tsv"))

ann_zscores <- read_tsv("../../scratch/ann_zscores.tsv", na = character(0))
head(ann_zscores)
```

**Comment by logstar** [comment]
> This works as expected. Tested below:
> 
> ```
> setwd("~/OT/analyses/rna-seq-expression-summary-stats/")
> 
> library(tidyverse)
> zscores <- read_tsv("~/OT/analyses/rna-seq-expression-summary-stats/results/long_n_tpm_mean_sd_quantile_gene_wise_zscore.tsv.gz") %>%
>   rename(Gene_symbol = gene_symbol, Gene_Ensembl_ID = gene_id, Disease = cancer_group) %>%
>   select(Gene_symbol, Gene_Ensembl_ID, cohort, Disease, tpm_mean, tpm_sd, n_samples, tpm_mean_gene_wise_zscore, tpm_mean_cancer_group_wise_quantiles) 
> write_tsv(zscores, "../../scratch/renamed_zscores.tsv")
> 
> system(paste(
>   "Rscript --vanilla ../long-format-table-utils/annotator/annotator-cli.R",
>   "-r -v -c MONDO,RMTL,EFO",
>   "-i ../../scratch/renamed_zscores.tsv",
>   "-o ../../scratch/ann_zscores.tsv"))
> 
> ann_zscores <- read_tsv("../../scratch/ann_zscores.tsv", na = character(0))
> head(ann_zscores)
> ```

Thank you for reviewing and test-running this PR. This PR will be merged after <https://github.com/PediatricOpenTargets/OpenPedCan-analysis/pull/56> is merged.

**Review by NHJohnson — APPROVED** [review]
In testing this I had to drop the columns `EFO`, `RMTL`, and `MONDO` from my dataframe and then re-added them using the CLI:
```
> colnames(renamed_m_tpm_ss_long_tbl)
 [1] "Gene_symbol"                         
 [2] "RMTL"                                
 [3] "Gene_Ensembl_ID"                     
 [4] "Disease"                             
 [5] "EFO"                                 
 [6] "MONDO"                               
 [7] "n_samples"                           
 [8] "cohort"                              
 [9] "tpm_mean"                            
[10] "tpm_sd"                              
[11] "tpm_mean_cancer_group_wise_zscore"   
[12] "tpm_mean_gene_wise_zscore"           
[13] "tpm_mean_cancer_group_wise_quantiles"
> df = subset(renamed_m_tpm_ss_long_tbl, select=-c(RMTL, EFO, MONDO))
> df
# A tibble: 1,304,002 x 10
   Gene_symbol Gene_Ensembl_ID Disease      n_samples cohort  tpm_mean   tpm_sd 
   <chr>       <chr>           <chr>            <int> <chr>   <chr>      <chr>  
 1 MT-CO3      ENSG00000198938 Adamantinom…        17 all_co… 1756.4535… 375.67…
 2 MT-CO2      ENSG00000198712 Adamantinom…        17 all_co… 1135.0694… 286.78…
 3 MT-ATP6     ENSG00000198899 Adamantinom…        17 all_co… 1436.9035… 390.86…
 4 MT-ND4      ENSG00000198886 Adamantinom…        17 all_co… 1289.7276… 340.09…
 5 MT-CO1      ENSG00000198804 Adamantinom…        17 all_co… 2242.3652… 540.44…
 6 MT-RNR2     ENSG00000210082 Adamantinom…        17 all_co… 44.031176… 53.194…
 7 MT-CYB      ENSG00000198727 Adamantinom…        17 all_co… 982.33941… 242.37…
 8 MT-ND2      ENSG00000198763 Adamantinom…        17 all_co… 911.12764… 257.67…
 9 MT-ND1      ENSG00000198888 Adamantinom…        17 all_co… 1009.3635… 280.03…
10 MT-ATP8     ENSG00000228253 Adamantinom…        17 all_co… 2390.9552… 846.68…
# … with 1,303,992 more rows, and 3 more variables:
#   tpm_mean_cancer_group_wise_zscore <chr>, tpm_mean_gene_wise_zscore <chr>,
#   tpm_mean_cancer_group_wise_quantiles <chr>
> colnames(df)
 [1] "Gene_symbol"                         
 [2] "Gene_Ensembl_ID"                     
 [3] "Disease"                             
 [4] "n_samples"                           
 [5] "cohort"                              
 [6] "tpm_mean"                            
 [7] "tpm_sd"                              
 [8] "tpm_mean_cancer_group_wise_zscore"   
 [9] "tpm_mean_gene_wise_zscore"           
[10] "tpm_mean_cancer_group_wise_quantiles"
> readr::write_tsv(df, "../../scratch/renamed_m_tpm_ss_long_tbl.tsv")
> system(paste("Rscript --vanilla ../long-format-table-utils/annotator/annotator-cli.R", "-r -v -c MONDO,RMTL,EFO", "-i ../../scratch/renamed_m_tpm_ss_long_tbl.tsv", "-o ../../scratch/annotated_renamed_m_tpm_ss_long_tbl.tsv"))
```

In the annotated frame I seem to see `MONDO` is `MONDO_0002787` for all genes, `EFO` is `EFO_1000069`, and `RMTL` appears to be blank. Not sure if my specific test makes sense, but I wanted to let you know in case this behavior is unexpected.

**Comment by logstar** [comment]
> In testing this I had to drop the columns `EFO`, `RMTL`, and `MONDO` from my dataframe and then re-added them using the CLI:
> 
> ```
> > colnames(renamed_m_tpm_ss_long_tbl)
>  [1] "Gene_symbol"                         
>  [2] "RMTL"                                
>  [3] "Gene_Ensembl_ID"                     
>  [4] "Disease"                             
>  [5] "EFO"                                 
>  [6] "MONDO"                               
>  [7] "n_samples"                           
>  [8] "cohort"                              
>  [9] "tpm_mean"                            
> [10] "tpm_sd"                              
> [11] "tpm_mean_cancer_group_wise_zscore"   
> [12] "tpm_mean_gene_wise_zscore"           
> [13] "tpm_mean_cancer_group_wise_quantiles"
> > df = subset(renamed_m_tpm_ss_long_tbl, select=-c(RMTL, EFO, MONDO))
> > df
> # A tibble: 1,304,002 x 10
>    Gene_symbol Gene_Ensembl_ID Disease      n_samples cohort  tpm_mean   tpm_sd 
>    <chr>       <chr>           <chr>            <int> <chr>   <chr>      <chr>  
>  1 MT-CO3      ENSG00000198938 Adamantinom…        17 all_co… 1756.4535… 375.67…
>  2 MT-CO2      ENSG00000198712 Adamantinom…        17 all_co… 1135.0694… 286.78…
>  3 MT-ATP6     ENSG00000198899 Adamantinom…        17 all_co… 1436.9035… 390.86…
>  4 MT-ND4      ENSG00000198886 Adamantinom…        17 all_co… 1289.7276… 340.09…
>  5 MT-CO1      ENSG00000198804 Adamantinom…        17 all_co… 2242.3652… 540.44…
>  6 MT-RNR2     ENSG00000210082 Adamantinom…        17 all_co… 44.031176… 53.194…
>  7 MT-CYB      ENSG00000198727 Adamantinom…        17 all_co… 982.33941… 242.37…
>  8 MT-ND2      ENSG00000198763 Adamantinom…        17 all_co… 911.12764… 257.67…
>  9 MT-ND1      ENSG00000198888 Adamantinom…        17 all_co… 1009.3635… 280.03…
> 10 MT-ATP8     ENSG00000228253 Adamantinom…        17 all_co… 2390.9552… 846.68…
> # … with 1,303,992 more rows, and 3 more variables:
> #   tpm_mean_cancer_group_wise_zscore <chr>, tpm_mean_gene_wise_zscore <chr>,
> #   tpm_mean_cancer_group_wise_quantiles <chr>
> > colnames(df)
>  [1] "Gene_symbol"                         
>  [2] "Gene_Ensembl_ID"                     
>  [3] "Disease"                             
>  [4] "n_samples"                           
>  [5] "cohort"                              
>  [6] "tpm_mean"                            
>  [7] "tpm_sd"                              
>  [8] "tpm_mean_cancer_group_wise_zscore"   
>  [9] "tpm_mean_gene_wise_zscore"           
> [10] "tpm_mean_cancer_group_wise_quantiles"
> > readr::write_tsv(df, "../../scratch/renamed_m_tpm_ss_long_tbl.tsv")
> > system(paste("Rscript --vanilla ../long-format-table-utils/annotator/annotator-cli.R", "-r -v -c MONDO,RMTL,EFO", "-i ../../scratch/renamed_m_tpm_ss_long_tbl.tsv", "-o ../../scratch/annotated_renamed_m_tpm_ss_long_tbl.tsv"))
> ```
> 
> In the annotated frame I seem to see `MONDO` is `MONDO_0002787` for all genes, `EFO` is `EFO_1000069`, and `RMTL` appears to be blank. Not sure if my specific test makes sense, but I wanted to let you know in case this behavior is unexpected.

Thank you for reviewing and test-running this PR @NHJohnson .

I wonder if the whole table has `MONDO_0002787`, `EFO_1000069`, and blank `RMTL`, which would be unexpected.

The EFO and MONDO maps to the Disease column, and the values shown in your output are matching to the values in the source annotation data.

```text
$ grep 'Adamantinom' ../../../../data/efo-mondo-map.tsv 
Adamantinomatous Craniopharyngioma      EFO_1000069     MONDO_0002787
```

The RMTL maps to Gene_Ensembl_ID, and the values shown in your output are matching to the values in the source annotation data.

```text
$ grep -P 'ENSG00000198938|ENSG00000198712|ENSG00000198899|ENSG00000198886|ENSG00000198804|ENSG00000210082|ENSG00000198727|ENSG00000198763|ENSG00000198888|ENSG00000228253' ../../../../data/ensg-hugo-rmtl-v1-mapping.tsv 
ENSG00000198712 MT-CO2  NA      NA
ENSG00000198727 MT-CYB  NA      NA
ENSG00000198763 MT-ND2  NA      NA
ENSG00000198804 MT-CO1  NA      NA
ENSG00000198886 MT-ND4  NA      NA
ENSG00000198888 MT-ND1  NA      NA
ENSG00000198899 MT-ATP6 NA      NA
ENSG00000198938 MT-CO3  NA      NA
ENSG00000210082 MT-RNR2 NA      NA
ENSG00000228253 MT-ATP8 NA      NA

# to show header
$ head ../../../../data/ensg-hugo-rmtl-v1-mapping.tsv
ensg_id gene_symbol     rmtl    version
ENSG00000000003 TSPAN6  NA      NA
ENSG00000000005 TNMD    NA      NA
ENSG00000000419 DPM1    NA      NA
ENSG00000000457 SCYL3   NA      NA
ENSG00000000460 C1orf112        NA      NA
ENSG00000000938 FGR     NA      NA
ENSG00000000971 CFH     NA      NA
ENSG00000001036 FUCA2   NA      NA
ENSG00000001084 GCLC    NA      NA
```

**Comment by NHJohnson** [comment]
Ok thanks, that makes sense. I now see that once you get past the craniopharyngiomas the MONDO and EFO values are different.

**Comment by logstar** [comment]
Added WIP label to this PR.

I will incorporate changes in the part 2 PR <https://github.com/PediatricOpenTargets/OpenPedCan-analysis/pull/56>.

I will also add tests to the CLI.

**Comment by logstar** [comment]
@jharenza @NHJohnson I have made a couple of changes to this PR.

- Handled `Rscript --vanilla ../annotator-cli.R -c '' -i input/path.tsv -o output/path.tsv` properly. See commit <https://github.com/PediatricOpenTargets/OpenPedCan-analysis/pull/59/commits/ebcc6acf2833f198eb095521e6245db96dac60b4> for more details.
- Enabled project root finding in git linked working trees. See commit <https://github.com/PediatricOpenTargets/OpenPedCan-analysis/pull/59/commits/eca90e5447d05c2bc5924b6c0184d45aeafbb836> for more details.
- Merged changes from the part 2 PR <https://github.com/PediatricOpenTargets/OpenPedCan-analysis/pull/56>.
- Added tests for `annotator-cli.R`. See commit <https://github.com/PediatricOpenTargets/OpenPedCan-analysis/pull/59/commits/52ff63e7fabedbeaff0d0fcbd629ba88bd05a0eb> for more details. All tests passed in the Docker image/container and a recently created R environment.

**Comment by logstar** [comment]
@jharenza @NHJohnson I have made a couple of changes to this PR.

- Only replace `NA` with empty string for columns that have `NA` in them, if `-r`/`--replace-na-with-empty-string` is set in CLI or `replace_na_with_empty_string = TRUE` in API. See commit <https://github.com/PediatricOpenTargets/OpenPedCan-analysis/pull/59/commits/0545a41e17db280b0df2aa8e146c612042da88ab> for more details.
- Added tests for the API `replace_na_with_empty_string` parameter in commit <https://github.com/PediatricOpenTargets/OpenPedCan-analysis/pull/59/commits/f87a4c360ded4e32e5d8083f6b3fb4d0d1988e5d>.
- Added tests for the CLI `-r`/`--replace-na-with-empty-string` option in commit <https://github.com/PediatricOpenTargets/OpenPedCan-analysis/pull/59/commits/dd72ce63bae8e107691efbc6c9a19accef473623>.

All tests passed in the Docker image/container and a recently created R environment.

**Review by NHJohnson — APPROVED** [review]
Thanks for making these improvements! All tests pass in Docker environment.

**Comment by logstar** [comment]
@NHJohnson Thank you for reviewing and test-running this PR!

**Pull request merged**
