### PR TITLE
Update DESeq module to add HPC scripts

### PR DESCRIPTION
**Pull request by sangeetashukla**
### Purpose/implementation Section
Created a new directory for deseq module with scripts compatible for HPC execution

#### What scientific question is your analysis addressing?
Perform differential exoression analysis for each pair of cancer histology type vs. all GTEX as well as each individual GTEX tissue (subgroup), where clinical data is available for 3 or more participants.

#### What was your approach?
Develop a new module that uses the DESeq2 (R) package to perform this analysis.

#### What GitHub issue does your pull request address?
[Issue 26](https://github.com/PediatricOpenTargets/ticket-tracker/issues/26)

### Directions for reviewers. Tell potential reviewers what kind of feedback you are soliciting.
This module should be run on HPC. Directions for the data that needs to be loaded is provided in the README.md

#### Which areas should receive a particularly close look?
For testing purposes, a new indices.txt file can be created, similar to the indices.txt that the `run_Generate_Hist_GTEx_indices_file.sh` execution will generate. This new file can have a smaller set of pairs of GTEx and Hist index values to run the differential expression analysis on.
Please let me know if more information is needed.

#### Is the analysis in a mature enough form that the resulting figure(s) and/or table(s) are ready for review?
Yes. This module will generate all the expected result files in the format discussed on the [ticket](run_Generate_Hist_GTEx_indices_file)

#### What types of results are included (e.g., table, figure)?
`.tsv` and `.jsonl` files will be generated

#### Reproducibility Checklist

- [ ] The dependencies required to run the code in this pull request have been added to the project Dockerfile.
- [ ] This analysis has been added to continuous integration.

#### Documentation Checklist

- [Y] This analysis module has a `README` and it is up to date.
- [Y] This analysis is recorded in the table in `analyses/README.md` and the entry is up to date.
- [Y] The analytical code is documented and contains comments.

 Yes

### CODE REVIEW

**Comment by jharenza** [comment]
Hi @sangeetashukla - I'm removing review requests for both @runjin326 and myself since this cannot run within this repo. I've been thinking about how to include this in GitHub - I suggest @afarrel reviews this, and perhaps even @ewafula if he uses the HPC. 

You will also be adding a separate PR for the code that went into CAVATICA module, correct? It would be good to add that code in a PR that we can review with the file structure here, with an option to run a sub sample of the data, as recommended in your old PR a few months ago.

**Comment by jharenza** [comment]
@sangeetashukla - some minor requests about the code structure:

- To make this module consistent with the rest of the repo, can you rename it as `tumor-normal-differential-expression` so that it is more descriptive? 
- All code and directories should use hyphens instead of underscores
- Scripts should be numbered in order of usage or order of calling from the shell script as per [this section](https://github.com/PediatricOpenTargets/OpenPedCan-analysis#folder-structure) of the README
- Remove commented out sections of code/comment as much code as possible

Thank you!

**Comment by afarrel** [comment]
@sangeetashukla just noting our discussions here on slack. Two changes are being made to the code. (1) Changing the order of the Cancer Group/Histology and GTEx subgroup in the DESeq function so that the values in the table and heat maps will be more intuitive and read as the Tumor's Expression's Fold change in relation to normal tissue. And (2) fixing the labeling of "all-cohorts" in for records that are made up of multiple datasets.

**Comment by afarrel** [comment]
Hi @sangeetashukla. I'm reviewing your PR and it looks very good. 
Just a few minor updates need to be made. (1) In the 'run-deseq-analysis.R' we can go ahead and change RMTL to PMTL in the final table. (2) Remove the non-descriptive commented-out lines of code from the script that are not being used.
(3) Add script to convert TSV file to RDS file. (4) Ammend Readme with instructions on CAVATICA workflow also.

It looks Great! Almost there!

**Comment by afarrel** [comment]
Hi @sangeetashukla Upon the reviewing the output table, the EFO codes for ALL, AML, and chordoma do not appear in the final table. Can you review the workflow to see why they might have been left out. Thanks
cc @logstar

**Comment by sangeetashukla** [comment]
> @sangeetashukla - some minor requests about the code structure:
> 
> * To make this module consistent with the rest of the repo, can you rename it as `tumor-normal-differential-expression` so that it is more descriptive?
> * All code and directories should use hyphens instead of underscores
> * Scripts should be numbered in order of usage or order of calling from the shell script as per [this section](https://github.com/PediatricOpenTargets/OpenPedCan-analysis#folder-structure) of the README
> * Remove commented out sections of code/comment as much code as possible
> 
> Thank you!

Thank you @jharenza for the comments. I have made some final changes to the module, including all the ones you suggested.

**Comment by sangeetashukla** [comment]
> Hi @sangeetashukla. I'm reviewing your PR and it looks very good. Just a few minor updates need to be made. (1) In the 'run-deseq-analysis.R' we can go ahead and change RMTL to PMTL in the final table. (2) Remove the non-descriptive commented-out lines of code from the script that are not being used. (3) Add script to convert TSV file to RDS file. (4) Ammend Readme with instructions on CAVATICA workflow also.
> 
> It looks Great! Almost there!

Thank you @afarrel , I have updated the final table to reflect the change from RMTL to PMTL, removed non-descriptive commented-out lines from various scripts, added new script to convert TSV to RDS file, and the README also includes links to the CAVATICA app.

**Comment by afarrel** [comment]
Hi @sangeetashukla. Looks good. Can you just remove the "print" commands throughout the code which I think we used for troubleshooting errors. Then I think it's good to go. Thanks for working so hard on this.

**Comment by sangeetashukla** [comment]
> Add scripts for HPC Tumor-Normal-Differential-Expression analysis #148



> Hi @sangeetashukla. Looks good. Can you just remove the "print" commands throughout the code which I think we used for troubleshooting errors. Then I think it's good to go. Thanks for working so hard on this.

@afarrel I removed the "print" statements that I maintained for troubleshooting purposes. If everything else looks okay, @runjin326 can merge this.

**Comment by runjin326** [comment]
@sangeetashukla thanks so much for preparing this. I just have a few high level questions:
1) I see there is a docker file that is independent of what we use for OpenPedCan repo. Is it just for running on HPC and hence different? What is the different between the versions of softwares used here vs. used in our current docker? E.g., I see that the R version is 4 but in OpenPedCan we are using 3.6. Just trying to figure out whether that would be an issue for our current procedure 
2) Would this module ever be run locally? If so, what docker file would be used?

cc: @jharenza @afarrel

**Comment by sangeetashukla** [comment]
> @sangeetashukla thanks so much for preparing this. I just have a few high level questions:
> 
> 1. I see there is a docker file that is independent of what we use for OpenPedCan repo. Is it just for running on HPC and hence different? What is the different between the versions of softwares used here vs. used in our current docker? E.g., I see that the R version is 4 but in OpenPedCan we are using 3.6. Just trying to figure out whether that would be an issue for our current procedure
> 2. Would this module ever be run locally? If so, what docker file would be used?
> 
> cc: @jharenza @afarrel

@runjin326 

1. The dockerfile in the branch is for loading the dependencies for the DESeq Cavatica app to run smoothly. This dockerfile is used to create the docker image, hosted on docker hub, to which the Cavatica app is linked. Additionally, the data files are available as a separate Cavatica project, so they are not inlcuded in the docker image.
To run the module manually, the data files will need to be loaded on HPC, and that can run without dockerfile. Since I primarily developed/ran the module on Respublica, I used the more recent R version available.
2. The module is CPU heavy, using HPC is recommended instead of running it locally.

Let me know if this makes sense.

**Comment by runjin326** [comment]
@sangeetashukla, thanks for the explanation - that makes sense! 
I guess my question then is do we want to use the docker file that you list here or should we use what we have for OpenPedCan? Normally for modules that we need to run on EC2 for OpenPedCan, we normally pull the docker as if we are building it locally initially and we use that docker file. That way, they are reproducible and version controlled. I guess my question is for this particular module, should we do that as well? Or is it ok to use a separate docker. Maybe @afarrel and @jharenza can help with the decision making here.

**Comment by runjin326** [comment]
Based on the discussion in OT Monday meeting, separate docker files will be used (and they will have different softwares versions compared to the OT channel) - hence this is ready to be merged.
@sangeetashukla, could you please merge the most up-to-date dev branch to your development branch? I will merge right after.

**Comment by runjin326** [comment]
Closing - since we will be merging #148 instead of this.

**Pull request closed without merging**
