### PR TITLE
update methyl pre-processing

### PR DESCRIPTION
**Pull request by ewafula**
#### What scientific question is your analysis addressing?
Update [methylation-preprocessing module](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/tree/dev/analyses/methylation-preprocessing) and associated CAVATICA workflow to simplify and standardize the  Illumina methylation array pre-processing analysis.

#### What was your approach?
- Move methylation beta/m-values matrix generation process from the downstream methylation-summary module to the methylation-preprocessing module
- Move methylation Genecode array probe annotation process from the downstream methylation-summary module to the methylation-preprocessing module
- generate copy number values from methylation arrays
- The module currently relies on the defaults implemented in the preprocessing packages to determine bad samples to be excluded. Update the code to keep all samples considering they have already been QC-ed at NCI. 
- implement options for normalization from minfi package -  quantile normalization for tumor-only datasets and functional normalization for datasets containing either tumor/normal samples, multiple cancer groups or both. 
- Updated the CAVATICA workflow code 

#### What GitHub issue does your pull request address?
- https://github.com/PediatricOpenTargets/ticket-tracker/issues/404

#### Which areas should receive a particularly close look?
- Review both the module and the workflow code
- test the module on a small subset of the data locally. 
- complete dataset needs to be run on a large memory machine i.e., on CAVATICA, CHOP HPC, or EC2 instance

#### Is there anything that you want to discuss further?
Non

#### Is the analysis in a mature enough form that the resulting figure(s) and/or table(s) are ready for review?
Yes

#### What types of results are included (e.g., table, figure)?
matrices

#### What is your summary of the results?
- `results/methyl-beta-values.rds`
- `results/methyl-m-values.rds`
- `results/methyl-cn-values.rds`

#### Reproducibility Checklist

- [ ] The dependencies required to run the code in this pull request have been added to the project Dockerfile.
- [ ] This analysis has been added to continuous integration.

#### Documentation Checklist

- [x] This analysis module has a `README` and it is up to date.
- [ ] This analysis is recorded in the table in `analyses/README.md` and the entry is up to date.
- [x] The analytical code is documented and contains comments.

### CODE REVIEW

**Comment by chinwallaa** [comment]
Needs to be review @dmiller15 app, and @afarrel review tables

**Comment by dmiller15** [comment]
So I notice the workflow is just 1 step right now. That means you should probably just delete the workflow. That means you can just delete the workflow and run the tool as the "workflow".

**Comment by ewafula** [comment]
> So I notice the workflow is just 1 step right now. That means you should probably just delete the workflow. That means you can just delete the workflow and run the tool as the "workflow".

Yes, @dmiller15. It is only one step standardized for any incoming methylation array dataset.  I'll delete the workflow directory and update the PR.

**Review by dmiller15 — APPROVED** [review]

**Review by afarrel — APPROVED** [review]
Thanks for working this!
Checked, the code. Looks okay, M and beta tables looks good. I spot checked a few genes in different diseases.
CN table isn't very quantitative and shouldn't be used without a proper normal (and even so - I question the data). I approve and recommend we move forward with methylation tables (M and beta values) and hold off on releasing and using the CN table for now.

Great work!

**Pull request merged**
