### PR TITLE
[Update `rna-seq-expression-summary-stats` module for v7 Part 2] rerun using v7 data release

### PR DESCRIPTION
**Pull request by logstar**
### Purpose/implementation Section

Rerun `rna-seq-expression-summary-stats` module using v7 data and independent sample lists.

#### What was your approach?

- Changed `ensg-hugo-rmtl-v1-mapping.tsv` to `ensg-hugo-rmtl-mapping.tsv`, in commit <https://github.com/PediatricOpenTargets/OpenPedCan-analysis/commit/eba42aec8db819e8adc8515ba31a4fbd8b780318>.
- Used `annotator` API to replace `NA` with empty string, in commit <https://github.com/PediatricOpenTargets/OpenPedCan-analysis/commit/5897fb1acf600689fee9edde50be10e686b91b72>.
- Used annotator column names in output tables, in commit <https://github.com/PediatricOpenTargets/OpenPedCan-analysis/commit/33bdacf92de75c13d12b8aede7a1d5c61dcfb942>.
- Removed wide table TSV files and long table JSON files from output, in commits <https://github.com/PediatricOpenTargets/OpenPedCan-analysis/commit/80f088d55bf144c1a7a3ff0e3bc9c109cbc3d503> and <https://github.com/PediatricOpenTargets/OpenPedCan-analysis/commit/d8d9a7cb4366d42bffcddeb97a049f780cc6b256>.
- Updated results for v7 data release, in commit <https://github.com/PediatricOpenTargets/OpenPedCan-analysis/commit/8687eb51b2084cbeed03e1cf7fd37c619ea11108>.
- Updated README.md for v7 data release, in commit <https://github.com/PediatricOpenTargets/OpenPedCan-analysis/commit/ad93391a8263c20aeb48f459717e38492059e8b1>

#### What GitHub issue does your pull request address?

<https://github.com/PediatricOpenTargets/ticket-tracker/issues/130>

#### Which areas should receive a particularly close look?

Are the updates expected?

#### Is there anything that you want to discuss further?

(EDIT 07/27/2021 YZ)

The results can be reproduced with the annotator API on the current dev branch, which is merged in commit <https://github.com/PediatricOpenTargets/OpenPedCan-analysis/pull/67/commits/627db9042e27c3ee00c0581a2627b25b2e261cec>.

#### Is the analysis in a mature enough form that the resulting figure(s) and/or table(s) are ready for review?

Yes. Review after PR <https://github.com/PediatricOpenTargets/OpenPedCan-analysis/pull/64> is reviewed and merged.

#### What types of results are included (e.g., table, figure)?

Tables

#### What is your summary of the results?

```text
$ ls -lh results/
total 215M
-rw-r--r-- 1 ubuntu ubuntu 38K Jul 26 17:59 cancer_group_all_cohort_sample_metadata.tsv
-rw-r--r-- 1 ubuntu ubuntu 37K Jul 26 18:01 cancer_group_individual_cohort_sample_metadata.tsv
-rw-r--r-- 1 ubuntu ubuntu 60M Jul 26 18:05 long_n_tpm_mean_sd_quantile_gene_wise_zscore.jsonl.gz
-rw-r--r-- 1 ubuntu ubuntu 52M Jul 26 18:03 long_n_tpm_mean_sd_quantile_gene_wise_zscore.tsv.gz
-rw-r--r-- 1 ubuntu ubuntu 56M Jul 26 18:05 long_n_tpm_mean_sd_quantile_group_wise_zscore.jsonl.gz
-rw-r--r-- 1 ubuntu ubuntu 48M Jul 26 18:03 long_n_tpm_mean_sd_quantile_group_wise_zscore.tsv.gz
```

#### Reproducibility Checklist

- [x] The dependencies required to run the code in this pull request have been added to the project Dockerfile.
- [NA. CI is not available.] This analysis has been added to continuous integration.

#### Documentation Checklist

- [x] This analysis module has a `README` and it is up to date.
- [x] This analysis is recorded in the table in `analyses/README.md` and the entry is up to date.
- [x] The analytical code is documented and contains comments.

### CODE REVIEW

**Review by afarrel — APPROVED** [review]
Tested changes in code. I found no issues. 
(I know it's late but I wonder if the two tables (gene and group quantiles) can be combined. I know we discussed this but can't remember why we kept them separate)
Did not test son to jsonl conversion bash scripts but based on conversation with @logstar and Sangeeta yesterday it looks good.
Looked at output jsonl tables. Looks good.

**Comment by logstar** [comment]
Thank you for reviewing and test-running this PR @afarrel !

@jharenza suggested to generate two separate tables for cancer-group-wise z-scores and gene-wise z-scores in a Slack discussion at <https://opentargetspediatrics.slack.com/archives/C021Y7H1X8U/p1624618655206600?thread_ts=1624575696.202100&cid=C021Y7H1X8U>, but I am also not sure about the exact reasons, probably because these two tables will be used to create two views on the PedOT website, and the gene-wise table needs extra versioning, according to the following two Slack threads:

- <https://opentargetspediatrics.slack.com/archives/C021Y7H1X8U/p1624362999121700>
- <https://opentargetspediatrics.slack.com/archives/C021Z53SK98/p1625685209070000> (item 3) and <https://opentargetspediatrics.slack.com/archives/C021Z53SK98/p1625685875074300> (item 3)

Just to keep a note here. If we would proceed with the discussion to merge cancer-group-wise and gene-wise tables, we would probably need to involve the FNL team as well, because I think the FNL team has started working on loading two separate tables into the PedOT database.

I was also looking into directly outputting JSONL from R, and the following code gets each `[{...}]` record each line, which might be helpful to the DESeq module.

```text
> out_df <- data.frame(a = c(1,2,3,4,5), b = c('a', 'b', '', 'd', 'e'))
> print(purrr::pmap_chr(out_df, function(...) jsonlite::toJSON(data.frame(...))))
[1] "[{\"a\":1,\"b\":\"a\"}]" "[{\"a\":2,\"b\":\"b\"}]" "[{\"a\":3,\"b\":\"\"}]"  "[{\"a\":4,\"b\":\"d\"}]"
[5] "[{\"a\":5,\"b\":\"e\"}]"
```

**Comment by logstar** [comment]
@afarrel @jharenza I will merge this PR shortly. I have merged with the latest dev branch, and the results can still be reproduced identically.

If we would like to further discuss merging cancer-group-wise and gene-wise tables, maybe we could continue our discussion in the `#ot-portal-content` channel to coordinate with the FNL team.

**Comment by afarrel** [comment]
Thanks @logstar. And thanks for the jsonl code. We can keep the tables separate for now.

**Pull request merged**
