### PR TITLE
pedCBio CNV file preparation module 

### PR DESCRIPTION
**Pull request by runjin326**
#### What scientific question is your analysis addressing?
Currently, the annotated CNV file loaded to pedcbio does not contain samples that do not have CNVs.
Also for samples that do have CNV calls, for segments that are diploid, those segments are not in the file either.
We want to load a more comprehensive annotated CNV file with diploid/neutral calls added back.

#### What was your approach?
First, find the unique ensembl + gene_symbol + cytoband available in the annotated CNV file - this is used as available segments.

For WGS samples:

- For samples that are in cnv-consensus.seg.gz but not in the annotated CNV (consensus_wgs_plus_cnvkit_wxs.tsv.gz), annotate status == neutral, copy number and tumor ploidy as 2 for all available segments
- For samples that are in the annotated CNV file, for any segments within available segments that do NOT have entries, also annotate status == neutral, copy number and tumor ploidy as 2

For WXS samples:

- For samples that are in cnv-cnvkit.seg.gz but not in the annotated CNV (consensus_wgs_plus_cnvkit_wxs.tsv.gz), annotate status == neutral, copy number and tumor ploidy as 2 for all available segments
- For samples that are in the annotated CNV file, for any segments within available segments that do NOT have entries, also annotate status == neutral, copy number and tumor ploidy as 2

Additionally, note that for segments in either X or Y, we need to use germline_sex_estimate to fill in the information:
- For female, X segment (2-2) and Y segment (0-0)
- For male, both X and Y segments are (1-1)

#### What GitHub issue does your pull request address?
https://github.com/PediatricOpenTargets/ticket-tracker/issues/240

#### Which areas should receive a particularly close look?
- Please check to see the logic for adding back the segments make sense.
- The results are not pushed since they are too big - will upload to pedcbio S3 bucket once the PR is merged. 
- `pedcbio_cnv_prepare.html` contains QC codes to count the number of segments for samples added + all samples there to see whether they have expected number of segments. 

#### Is there anything that you want to discuss further?
No.

#### Is the analysis in a mature enough form that the resulting figure(s) and/or table(s) are ready for review?
Yes.

#### What types of results are included (e.g., table, figure)?
```
consensus_wgs_plus_cnvkit_wxs.tsv.gz		
consensus_wgs_plus_cnvkit_wxs_x_and_y.tsv.gz
consensus_wgs_plus_cnvkit_wxs_autosomes.tsv.gz
```

#### What is your summary of the results?
This module also generates a html file as a QC documentation - basically, counting the number of segments for samples added + all samples there to see whether they have expected number of segments. 
See - `pedcbio_cnv_prepare.html` 

#### Reproducibility Checklist

- [x] The dependencies required to run the code in this pull request have been added to the project Dockerfile.
- [ ] This analysis has been added to continuous integration.

#### Documentation Checklist

- [x] This analysis module has a `README` and it is up to date.
- [ ] This analysis is recorded in the table in `analyses/README.md` and the entry is up to date.
- [x] The analytical code is documented and contains comments.

### CODE REVIEW

**Review by ewafula — CHANGES_REQUESTED** [review]
@runjin326, thanks for working on this module.  I have reviewed and the logic that makes sense, but I have a suggestion to consider and a question. 

- please consider creating the output `results` directory before writing into it. The notebook will fail if users run it from scratch unless they manually create the directory. Currently, it is hardcoded.
```
# write out results 
consensus_cnvkit_xy %>% 
  readr::write_tsv("results/consensus_wgs_plus_cnvkit_wxs_x_and_y.tsv.gz")

# write out results
consensus_cnvkit_auto %>% 
  readr::write_tsv("results/consensus_wgs_plus_cnvkit_wxs_autosomes.tsv.gz")

# annotate germline sex estimate of those samples and write out the results
bind_rows(consensus_cnvkit_xy, consensus_cnvkit_auto) %>% 
  left_join(germline_sex_estimate_df) %>%
  distinct() %>% 
  write_tsv("results/consensus_wgs_plus_cnvkit_wxs.tsv.gz")
```
- Based on the documentation and ticket, my is understanding is that the BS_ids for `v10/consensus_wgs_plus_cnvkit_wxs_x_and_y.tsv.gz`   and `v10/consensus_wgs_plus_cnvkit_wxs_autosomes.tsv.gz`  should be subsets of `results/consensus_wgs_plus_cnvkit_wxs_x_and_y.tsv.gz`   and `results/consensus_wgs_plus_cnvkit_wxs_autosomes.tsv.gz`.  I am finding `BS_4SCDT7M9` in both v10 `xy` and `autosome` consensus files, but missing in PR module results.  It is present in the v10 histologies file. 
```
> xy_v10 <- read_tsv("../../../data/consensus_wgs_plus_cnvkit_wxs_x_and_y.tsv.gz") %>% pull(biospecimen_id) %>%  unique()

> xy_PR <- read_tsv("results/consensus_wgs_plus_cnvkit_wxs_x_and_y.tsv.gz") %>% pull(biospecimen_id) %>% unique()

> xy_v10[!(xy_v10 %in% xy_PR)]
   [1] "BS_4SCDT7M9"
```

```
> auto_v10 <- read_tsv("../../../data/consensus_wgs_plus_cnvkit_wxs_autosomes.tsv.gz") %>% pull(biospecimen_id) %>%  ​unique()

> auto_PR <- read_tsv("results/consensus_wgs_plus_cnvkit_wxs_autosomes.tsv.gz") %>% pull(biospecimen_id) %>%  unique()

>  auto_v10[!(auto_v10 %in% auto_PR)]
[1] "BS_4SCDT7M9"
````

```
> read_tsv("../../../data/histologies.tsv", guess_max = 100000) %>% filter(Kids_First_Biospecimen_ID == "BS_4SCDT7M9") %>% select(Kids_First_Biospecimen_ID, sample_type, experimental_strategy, cohort) 
Parsed with column specification:
cols(
  .default = col_character(),
  OS_days = col_double(),
  age_last_update_days = col_double(),
  normal_fraction = col_double(),
  tumor_fraction = col_double(),
  tumor_ploidy = col_double()
)
See spec(...) for full column specifications.
# A tibble: 1 x 4
  Kids_First_Biospecimen_ID sample_type experimental_strategy cohort
  <chr>                     <chr>       <chr>                 <chr> 
1 BS_4SCDT7M9               Tumor       WXS                   PBTA  
````

**Comment by runjin326** [comment]
@ewafula, thanks so much for reviewing! I have now added lines to create `results` folder if it is not already there. 
For `BS_4SCDT7M9`, it actually is not present in the cnvkit seg (given it is a WXS sample - this is what we are using for generating the annotated file) so it really should not be present in the output since we use that file to generate the annotated file - wondering what the issue there is. 

Could you please do the following and see whether it is in your v10 `cnv-cnvkit.seg.gz`:
```
cnvkit_seg <- readr::read_tsv(file.path(data_dir, "cnv-cnvkit.seg.gz"))
cnvkit_seg_id <- cnvkit_seg$ID %>% unique()
"BS_4SCDT7M9" %in% cnvkit_seg_id
```
If it is also not in your file, we might want to pull in Bo to see how the discrepancies come about - good catch!

**Comment by ewafula** [comment]
@runjin326,  very interesting!  `BS_4SCDT7M9` is not the `v10/cnv-cnvkit.seg.gz`.  How did it into v10 consensus files if the `cnv-cnvkit.seg.gz` is the source file used in generating them?  Maybe @zhangb1 investigate. I am approving the PR considering this single sample is not an issue for the module.  Thank you!

**CNVkit seg file**
```
> cnvkit_seg <- readr::read_tsv(file.path("cnv-cnvkit.seg.gz"))                                                 
> cnvkit_seg_id <- cnvkit_seg$ID %>% unique()
> "BS_4SCDT7M9" %in% cnvkit_seg_id
[1] FALSE
```
**consensus autosomes**
```
> consensus_df <- readr::read_tsv(file.path("consensus_wgs_plus_cnvkit_wxs_autosomes.tsv.gz"))
> consensus_id <- consensus_df$biospecimen_id %>% unique()
> "BS_4SCDT7M9" %in% consensus_id
[1] TRUE
```
**consensus x_and_y**
```
> consensus_df <- readr::read_tsv(file.path("consensus_wgs_plus_cnvkit_wxs_x_and_y.tsv.gz"))
> consensus_id <- consensus_df$biospecimen_id %>% unique()
> "BS_4SCDT7M9" %in% consensus_id
[1] TRUE
```
**consensus merged**
```
> consensus_df <- readr::read_tsv(file.path("consensus_wgs_plus_cnvkit_wxs.tsv.gz"))
> consensus_id <- consensus_df$biospecimen_id %>% unique()
> "BS_4SCDT7M9" %in% consensus_id
[1] TRUE
```

**Review by ewafula — APPROVED** [review]
Looks and good now, @runjin326. Thank you!

**Comment by jharenza** [comment]
>BS_4SCDT7M9 is not the v10/cnv-cnvkit.seg.gz. How did it into v10 consensus files if the cnv-cnvkit.seg.gz is the source file used in generating them?

For CNV consensus files, remember that we take the CNVkit results for WXS only samples and add them into the CNV consensus file, so maybe this is what is happening.

**Comment by runjin326** [comment]
> For CNV consensus files, remember that we take the CNVkit results for WXS only samples and add them into the CNV consensus file, so maybe this is what is happening.

@jharenza, thanks for looking into this - ya so that is the puzzling part. This sample is not in the CNVkit results (not in the `cnv_cnvkit.seg.gz`) so it really shouldn't be in the combined file. And I checked, it also wasn't in the consensus seg file either - hence a bit puzzling.

**Comment by jharenza** [comment]
Hmm, I think that it probably should be in the CNVkit file. Looks like there is a tumor ploidy of 3, so definitely has some CNV changes and this indicates the CNV tools were run on it.

**Comment by jharenza** [comment]
@runjin326 may be worth a QC to be sure all WXS are in the CNVkit file and thus the consensus file

**Comment by runjin326** [comment]
Figured out what the situation is with `BS_4SCDT7M9` - it is a sample from PNOC that were sequenced twice. Went back and forth deciding which sample to use and hence, some discrepancies between `consensus_wgs_plus_cnvkit_wxs.tsv.gz` and `cnv-cnvkit.seg.gz` (`consensus_wgs_plus_cnvkit_wxs.tsv.gz` is the right one and this sample should be in `cnv-cnvkit.seg.gz` - will fix in v11 release). 

Since this is a one-off situation, I will leave the code as is and merge the PR but would fix the results files to include `BS_4SCDT7M9` for pedcbio.

**Comment by runjin326** [comment]
@afarrel, could you please also review this whenever you get a chance? Thanks!

**Review by afarrel — APPROVED** [review]
Hi @runjin326. Thanks for working on this and resolving the issue. The code/logic looks good and I agree with leaving the code as is since it's a one-off case.  (We might have to discuss how to select samples with duplicate runs at the pipeline level for downstream analysis taking into consideration parameters like sequencing depth, etc.)

**Comment by runjin326** [comment]
> Hi @runjin326. Thanks for working on this and resolving the issue. The code/logic looks good and I agree with leaving the code as is since it's a one-off case. (We might have to discuss how to select samples with duplicate runs at the pipeline level for downstream analysis taking into consideration parameters like sequencing depth, etc.)

thanks so much for reviewing this! yes - we can have discussion about how to select samples later on. Currently to my understanding, it is only PNOC samples that we are doing the selection and it is largely selected based on sequencing center. for all other samples, we just use as they are. 
Merging now since 2 reviewers approved.

**Pull request merged**
