### PR TITLE
Update cnv frequency tables with V11 data

### PR DESCRIPTION
**Pull request by adilahiri**
#### What scientific question is your analysis addressing?
Rerun `cnv-frequencies `module with V11 data. 

#### What was your approach?
@ewafula ran the analysis and filtered out records with Unknown/NA values in the status column of the consesus file that broke the code previously. 

Changed the files names in lines 33 to 36 of the 01-cnv-frequencies.py file.  The file names were derived from this [page](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/tree/dev/analyses/independent-samples).
#### What GitHub issue does your pull request address?
[Issue #363](https://github.com/PediatricOpenTargets/ticket-tracker/issues/363)

### Directions for reviewers. Tell potential reviewers what kind of feedback you are soliciting.
The filename changes are reflected in lines 33 to 36 of the `01-cnv-frequencies.py` file. Please note I have used WGS files , if WXS files need to be used please let me know.

#### Which areas should receive a particularly close look?
Lines 33 to 36 of the `01-cnv-frequencies.py` file.

#### Is there anything that you want to discuss further?
No

#### Is the analysis in a mature enough form that the resulting figure(s) and/or table(s) are ready for review?
Results are too large to be included on Github, results are uploaded by @ewafula at S3 Bucket. 

#### What types of results are included (e.g., table, figure)?
Tables 

#### What is your summary of the results?
Updated tables with V11 data. 

#### Reproducibility Checklist

- [ ] The dependencies required to run the code in this pull request have been added to the project Dockerfile.
- [ ] This analysis has been added to continuous integration.

#### Documentation Checklist

- [ ] This analysis module has a `README` and it is up to date.
- [ ] This analysis is recorded in the table in `analyses/README.md` and the entry is up to date.
- [ ] The analytical code is documented and contains comments.

### CODE REVIEW

**Comment by jharenza** [comment]
@adilahiri can you uncomment the cnv-frequencies module from the YAML file here 

https://github.com/PediatricOpenTargets/OpenPedCan-analysis/blob/877f39457de8c3cafd864e5b5b8fd3f2c122fc95/.github/workflows/run-analysis.yml#L169-L173

and commit that change to your branch?

**Comment by adilahiri** [comment]
@jharenza  Yes will do so.

**Comment by jharenza** [comment]
@ewafula I am going to convert this to draft? Also with the latest merge, can you resolve the run analysis conflict?

**Comment by ewafula** [comment]
> @ewafula I am going to convert this to draft? Also with the latest merge, can you resolve the run analysis conflict?

@jharenza,  I am not able to resolve this conflict.  I think the update was from. @adilahiri  above. Has to do with `.github/workflows/run-analysis.yml`file.

@adilahiri, can you resolve this?
```
To https://github.com/PediatricOpenTargets/OpenPedCan-analysis.git
 ! [remote rejected]   v11-cnv-tables -> v11-cnv-tables (refusing to allow a Personal Access Token to create or update workflow `.github/workflows/run-analysis.yml` without `workflow` scope)
error: failed to push some refs to 'https://github.com/PediatricOpenTargets/OpenPedCan-analysis.git'
```

**Comment by adilahiri** [comment]
@ewafula : I uncommented the lines 169-173 in `run-analysis.yml` file. I pushed the commits yesterday on to this PR and it failed 'build_and_run` at the first try but ran successfully on the second try. Let me see how I can resolve it.

**Comment by adilahiri** [comment]
Ok I have uncommented the lines with conflict, waiting for checks to run.

**Comment by jharenza** [comment]
@ewafula - this module is failing GA because of the gzip asking Y/N to overwrite the old file, and is not overwriting. Can you add a step to remove all old gz files first? Thanks

**Comment by ewafula** [comment]
@jharenza, looks good now. Passed GA.

**Review by sangeetashukla — APPROVED** [review]
@adilahiri @jharenza 
The script changes look good. I was able to run the module without issues on EC2 and reproduce the results. 
I reviewed the files, and compared md5sums, and they were identical.

**Review by jharenza — APPROVED** [review]
just spot checked a few genes here, and looks good to go. We can merge after this passes GA

**Pull request merged**
