### PR TITLE
V11 Release (1/N)

### PR DESCRIPTION
**Pull request by jharenza**
#### What GitHub issue does your pull request address?
Fixes https://github.com/PediatricOpenTargets/ticket-tracker/issues/239

### Data Release Checklist
- [x] Is the table in doc/data-file-descriptions.md up to date?
- [x] Is doc/data-format.md up to date?
- [x] Is doc/release-notes.md up to date?
- [x] Is download-data.sh up to date?
- [x] Was download-data.sh tested and did it complete without error?

### CODE REVIEW

**Comment by jharenza** [comment]
Fixes https://github.com/PediatricOpenTargets/ticket-tracker/issues/234
Fixes https://github.com/PediatricOpenTargets/ticket-tracker/issues/239
Fixes https://github.com/PediatricOpenTargets/ticket-tracker/issues/248
Fixes https://github.com/PediatricOpenTargets/ticket-tracker/issues/249
Fixes https://github.com/PediatricOpenTargets/ticket-tracker/issues/251
Fixes https://github.com/PediatricOpenTargets/ticket-tracker/issues/253
Fixes https://github.com/PediatricOpenTargets/ticket-tracker/issues/254
Fixes https://github.com/PediatricOpenTargets/ticket-tracker/issues/261
Fixes https://github.com/PediatricOpenTargets/ticket-tracker/issues/270
Fixes https://github.com/PediatricOpenTargets/ticket-tracker/issues/278
Fixes https://github.com/PediatricOpenTargets/ticket-tracker/issues/285
Fixes https://github.com/PediatricOpenTargets/ticket-tracker/issues/290
Fixes https://github.com/PediatricOpenTargets/ticket-tracker/issues/298
Fixes https://github.com/PediatricOpenTargets/ticket-tracker/issues/299
Fixes https://github.com/PediatricOpenTargets/ticket-tracker/issues/303
Fixes https://github.com/PediatricOpenTargets/ticket-tracker/issues/304
Fixes https://github.com/PediatricOpenTargets/ticket-tracker/issues/309
Fixes https://github.com/PediatricOpenTargets/ticket-tracker/issues/316
Fixes https://github.com/PediatricOpenTargets/ticket-tracker/issues/320
Fixes https://github.com/PediatricOpenTargets/ticket-tracker/issues/333
Fixes https://github.com/PediatricOpenTargets/ticket-tracker/issues/341
Fixes https://github.com/PediatricOpenTargets/ticket-tracker/issues/365
Fixes https://github.com/PediatricOpenTargets/ticket-tracker/issues/366
Fixes https://github.com/PediatricOpenTargets/ticket-tracker/issues/360
Fixes https://github.com/PediatricOpenTargets/ticket-tracker/issues/359
Fixes https://github.com/PediatricOpenTargets/ticket-tracker/issues/352
Fixes https://github.com/PediatricOpenTargets/ticket-tracker/issues/257
Fixes https://github.com/PediatricOpenTargets/ticket-tracker/issues/370

**Review by logstar — APPROVED** [review]
I have downloaded v11 release using `download-data.sh` in this PR branch. All md5sum checks are OK, and all symbolic links are created in the `data` folder.

**Comment by jharenza** [comment]
@kelseykeith thanks so much for catching those! I updated all 3 files (caught a few other things as well). Can you delete the md5sum and release notes from your download and rerun the script?

**Comment by kelseykeith** [comment]
Looks good to me now! Download and md5sums were still fine and the changes for those files look good

**Comment by jharenza** [comment]
Here we go! 🚀

**Pull request merged**
