### PR TITLE
Rerun fusion filtering

### PR DESCRIPTION
**Pull request by runjin326**
### Purpose/implementation Section
Re-run fusion filtering module with TARGET RNA samples

#### What was your approach?

- For this particular re-run - we skipped 00, 03, and 06 and z-scores were not added to the final table 
- Since we skipped 03, the input for 04 were modified to `scratch/standardFusionExp_QC_expression_filtered_annotated.RDS`
- For 02, there are some specimens in fusion results that does not have `sample_type == "Tumor"` - hence removed to avoid warning messages. 

#### What GitHub issue does your pull request address?
https://github.com/PediatricOpenTargets/ticket-tracker/issues/126

#### Is there anything that you want to discuss further?
1. Will create a ticket to generate tissue type specific z-score normalization for TARGET specimens
2. When looking at fusion results for PBTA samples - instead of 4285 results, 4203 results were returned. Could it be due to [this step](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/blob/80698349238e2857d5830b1687e5c764215a38a0/analyses/fusion_filtering/04-project-specific-filtering.Rmd#L256-L280)? 

#### Is the analysis in a mature enough form that the resulting figure(s) and/or table(s) are ready for review?
Yes

### Results
A total of 30070 putative fusion events were reported. 

#### What types of results are included (e.g., table, figure)?
`results/FilteredFusion.tsv`
`results/fusion-putative-oncogenic.tsv`

#### What is your summary of the results?

> wc -l 
` 66601 FilteredFusion.tsv
   30071 fusion-putative-oncogenic.tsv`

#### Reproducibility Checklist

- [x] The dependencies required to run the code in this pull request have been added to the project Dockerfile.
- [x] This analysis has been added to continuous integration.

#### Documentation Checklist

- [x] This analysis module has a `README` and it is up to date.
- [x] This analysis is recorded in the table in `analyses/README.md` and the entry is up to date.
- [x] The analytical code is documented and contains comments.

### CODE REVIEW

**Comment by runjin326** [comment]
This re-run results were compared to the [results in the current `dev` branch ](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/blob/dev/analyses/fusion_filtering/results/fusion-putative-oncogenic.tsv). v7 of histologies.tsv files are used to extract PBTA `Kids_First_Biospecimen_ID`. Instead of 4285 results, 4203 results were returned. The list of those differences are attached here. [old_vs_rerun_82diff.txt](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/files/6874077/old_vs_rerun_82diff.txt)

The differences were probably due to the fact that we filter out fusions that are present in >4 broad histologies. With the introduction of TARGET data and more broad histologies group, the chance that a fusion is present in >4 broad histologies increased and hence are more likely to get filtered based on that parameter. To look into that, we looked at the following:

- This is the current list of fusions that are present in >4 broad histologies group 
[fusion_filtered_names.txt](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/files/6874078/fusion_filtered_names.txt)

- Among all of the 82 differences, 23 of them are filtered due to this filter - listed here: 
[filtered_due_to_over4.txt](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/files/6874081/filtered_due_to_over4.txt)

- For the rest of 59 differences, 36 of them are [local rearrangement](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/blob/80698349238e2857d5830b1687e5c764215a38a0/analyses/fusion_filtering/04-project-specific-filtering.Rmd#L207-L211), 11 of them has [fusion type “other”](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/blob/80698349238e2857d5830b1687e5c764215a38a0/analyses/fusion_filtering/04-project-specific-filtering.Rmd#L215-L216) and [10 of them only called by one caller](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/blob/80698349238e2857d5830b1687e5c764215a38a0/analyses/fusion_filtering/04-project-specific-filtering.Rmd#L220-L224). It is a bit puzzling to me why they were retained in the previous results.

- The other two belongs to the same sample, and is non-oncogenic. That one is filtered out because with [TARGET, it is now found in multiple cancer groups](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/blob/80698349238e2857d5830b1687e5c764215a38a0/analyses/fusion_filtering/04-project-specific-filtering.Rmd#L257-L262). 

A separate ticket that does the investigation will open to understand this better. 
cc: @jharenza, @kgaonkar6

**Review by jharenza — COMMENTED** [review]
now that #62 is in, will you merge dev into this branch and do a fresh rerun?

**Comment by runjin326** [comment]
> now that #62 is in, will you merge dev into this branch and do a fresh rerun?

@jharenza, completed now!

**Review by kgaonkar6 — APPROVED** [review]
Code update looks good, missing PBTA calls will be reviewed after v7

**Pull request merged**
