### PR TITLE
Updated analysis: change biospecimen filtering procedure in `snv-frequencies` module

### PR DESCRIPTION
**Pull request by logstar**
#### What scientific question is your analysis addressing?

`snv-frequencies` module needs to be updated to change the biospecimen filtering procedure.

Currently, the biospecimen filtering procedure takes the following steps:

1. Keep only biospecimens in MAF file that have `sample_type == 'Tumor'` in histology file.
2. Keep only non-synonymous variant rows in MAF file. Biospecimens that only have synonymous variants will be removed.
3. Keep only biospecimens in histology file that are also in the MAF file.
4. Keep only biospecimens in independent sample lists that are also in histology file.

In the current biospecimen filtering procedure, biospecimens that only have synonymous variants will not be included in the results.

To keep the biospecimens that only have synonymous variants, change the biospecimen filtering procedure to the following:

1. Keep only biospecimens in MAF file that have `sample_type == 'Tumor'` in histology file.
2. Keep only biospecimens in histology file that are also in the MAF file.
3. Keep only biospecimens in independent sample lists that are also in histology file.
4. Keep only non-synonymous variant rows in MAF file. Biospecimens that only have synonymous variants will be removed, but they will be counted in the results, because histology file and independent sample lists are used to total number of subjects or tumors.

#### What was your approach?

Rearrange the following code, according to the updated biospecimen filtering procedure described above.

<https://github.com/PediatricOpenTargets/OpenPedCan-analysis/blob/05a08b0855314ada934deab8fe65837730c65f9c/analyses/snv-frequencies/01-snv-frequencies.R#L697-L777>

#### What GitHub issue does your pull request address?

<https://github.com/PediatricOpenTargets/ticket-tracker/issues/287>

#### Which areas should receive a particularly close look?

Does the code updates in 01-snv-frequencies.R make sense?

Note that the results are generated using v10 data release, except the histology.tsv file is replaced with an updated one at <https://github.com/ewafula/D3b-codes/blob/6d8724c871b75fc64da404a5752684ea9859e573/v11-OpenPedCan/v11/histologies.tsv>.

#### Is there anything that you want to discuss further?

**1. Tumor biospecimens in MAF file that only have synonymous variants**

Following are the numbers of tumor biospecimens that only have synonymous variants:

```text
  cohort cancer_group                 experimental_strategy     n
  <chr>  <chr>                        <chr>                 <int>
1 PBTA   Craniopharyngioma            WGS                       1
2 PBTA   Low-grade glioma/astrocytoma WGS                       1
3 TARGET Neuroblastoma                Targeted Sequencing     141
```

The 141 TARGET Neuroblastoma Targeted Sequencing biospecimens only have 1-6 rows in the MAF file:

```text
  n_rows_per_biospecimen_in_MAF_file n_biospecimens
                               <int>          <int>
1                                  1             60
2                                  2             31
3                                  3             21
4                                  4             15
5                                  5              9
6                                  6              5
```

As MTP will not update for any new data before release, I was wondering if we should exclude the biospecimens that only have synonymous variants in pedcbio v10 dataset, to make the number of patients consistent between pedcbio and MTP. Here is the list of v10 biospecimens that only have synonymous variants, [v10_maf_histology_biospecimens_with_only_synonymous_variants.txt](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/files/8475380/v10_maf_histology_biospecimens_with_only_synonymous_variants.txt).

For future releases, I was wondering if we need to handle Targeted Sequencing biospecimens differently, so that they will not always be counted in SNV frequencies. Assuming Targeted Sequencing only check a couple of genes, only the checked genes should include the number of Targeted Sequencing biospecimens.

**2. Histology file is incompatible with independent sample lists**

The following cohort-cancer_groups will have patients/subjects not counted in primary/relapse tumor samples, in the result files. The [latest `snv-frequencies` module update](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/pull/156) and this PR use v11 histology file, v10 MAF file, and v10 independent sample lists. v11 histology file has patients in v10 MAF file but not in v10 independent sample lists, so v11 added patients and their biospecimens are not counted in the primary/relapse tumor samples. For example, TARGET Acute Lymphoblastic Leukemia has 712 total patients, 659 primary tumors, and 17 relapse tumors.

```text
  cohort cancer_group         n_v11_patients_not_in_v10_independent_sample_lists
  <chr>  <chr>                                                             <int>
1 GMKF   Neuroblastoma                                                         1
2 PBTA   Ewing sarcoma                                                         1
3 PBTA   High-grade glioma/astrocytoma                                         3
4 PBTA   Meningioma                                                            2
5 PBTA   Neurofibroma/Plexiform                                                2
6 TARGET Acute Lymphoblastic Leukemia                                         36
7 TARGET Neuroblastoma                                                         2
```

This issue should not cause any difference between `snv-frequencies` and pedcbio, assuming v11 histology file and v10 MAF file are used to load pedcbio, and pedcbio does not use independent sample lists.

I will create a new issue to assert compatibility in `01-snv-frequencies.R` between histology file and independent sample lists for the next update.

#### Is the analysis in a mature enough form that the resulting figure(s) and/or table(s) are ready for review?

Yes.

#### What types of results are included (e.g., table, figure)?

```text
analyses/snv-frequencies/results/gene-level-snv-consensus-annotated-mut-freq.jsonl.gz
analyses/snv-frequencies/results/gene-level-snv-consensus-annotated-mut-freq.tsv.gz
analyses/snv-frequencies/results/variant-level-snv-consensus-annotated-mut-freq.jsonl.gz
analyses/snv-frequencies/results/variant-level-snv-consensus-annotated-mut-freq.tsv.gz
```

#### What is your summary of the results?

NA.

#### Reproducibility Checklist

- [x] The dependencies required to run the code in this pull request have been added to the project Dockerfile.
- [NA] This analysis has been added to continuous integration.

#### Documentation Checklist

- [x] This analysis module has a `README` and it is up to date.
- [x] This analysis is recorded in the table in `analyses/README.md` and the entry is up to date.
- [x] The analytical code is documented and contains comments.

### CODE REVIEW

**Comment by jharenza** [comment]
@logstar can you merge dev into this and do a rerun since #162 is in

**Comment by logstar** [comment]
> @logstar can you merge dev into this and do a rerun since #162 is in

@jharenza Thank you for checking. Will do.

**Comment by logstar** [comment]
@jharenza I have merged latest `PediatricOpenTargets/OpenPedCan-analysis/dev` branch to this PR's branch.

Rerunning this module reproduced the results, except the UUID columns that expected to be different in different runs.

**Comment by kelseykeith** [comment]
Can I get an updated link to the histology file used? The link in the request is broken for me

**Comment by jharenza** [comment]
> Can I get an updated link to the histology file used? The link in the request is broken for me

@kelseykeith just added you

**Review by kelseykeith — CHANGES_REQUESTED** [review]
Using the v10 versions of all the files, the module ran correctly. However, and I may have been using the wrong version of the histology file, when I tried running using the histology file at https://github.com/d3b-center/D3b-codes/blob/master/OpenPedCan_histologies/results/histologies.tsv.gz, the module failed at the check at line 749  in `01-snv-frequencies` to make sure there was one unique line for each sample in the histology file.

```
stopifnot(identical(
  nrow(maf_sample_htl_df),
  length(unique(maf_sample_htl_df$Kids_First_Biospecimen_ID))
))
```
After looking at the histology file, this was because the version of the histology file I was using has some samples that were sequenced at multiple centers. All samples have the same ID but there was more than one line for them because they had multiple values in the `seq_center` column. 

This could be quickly fixed by selecting and distincting only the necessary columns for the module from the histology file. Or I could be using the wrong histology file with an extra column in which case the module can be approved.

**Comment by logstar** [comment]
@kelseykeith - Thank you for reviewing this PR. I agree with the issue and solution in your review. However, the issue may need to be addressed in a separate PR, because the histology file at <https://github.com/d3b-center/D3b-codes/blob/master/OpenPedCan_histologies/results/histologies.tsv.gz> is not used in this PR. If we encounter any similar issue in future updates of the `snv-frequencies` module, we should resolve it with the proposed solution.

Could you try re-running this PR with this histology file at <https://github.com/ewafula/D3b-codes/blob/6d8724c871b75fc64da404a5752684ea9859e573/v11-OpenPedCan/v11/histologies.tsv>? This histology file is also used to generate v10 results in <https://github.com/PediatricOpenTargets/OpenPedCan-analysis/pull/156>.

**Comment by kelseykeith** [comment]
That link is still 404 for me. When @jharenza added me to D3b-codes I thought it was the histology file in that repo. Can you send me the file directly or provide a different link?

**Comment by ewafula** [comment]
> That link is still 404 for me. When @jharenza added me to D3b-codes I thought it was the histology file in that repo. Can you send me the file directly or provide a different link?

https://github.com/ewafula/D3b-codes/blob/v11-OpenPedCan/v11-OpenPedCan/v11/histologies.tsv

**Comment by kelseykeith** [comment]
Thanks, but that link is 404 as well. Do you need to add me to the repo?

**Comment by ewafula** [comment]
> Thanks, but that link is 404 as well. Do you need to add me to the repo?

@jharenza will need to add you to the D3b-codes repo. Seems you have no access. Here is the ongoing v11 histologies file from [PR #53](https://github.com/d3b-center/D3b-codes/pull/53)
[histologies.tsv.zip](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/files/8679103/histologies.tsv.zip)

**Comment by kelseykeith** [comment]
Thanks for sending the file directly! I can get this finished up now

**Comment by logstar** [comment]
> Thanks for sending the file directly! I can get this finished up now

@kelseykeith @ewafula - The histology file shared by @ewafula is still different from what I used, which might cause additional issues. Sorry that I did not know that you still have no access to <https://github.com/ewafula/D3b-codes/blob/6d8724c871b75fc64da404a5752684ea9859e573/v11-OpenPedCan/v11/histologies.tsv>.

Here is the histology file I used in this PR, [histologies.tsv.zip](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/files/8679319/histologies.tsv.zip), which is downloaded from <https://github.com/ewafula/D3b-codes/blob/6d8724c871b75fc64da404a5752684ea9859e573/v11-OpenPedCan/v11/histologies.tsv>.

**Comment by kelseykeith** [comment]
Ok, thank you I will use this one

**Review by kelseykeith — APPROVED** [review]

**Comment by kelseykeith** [comment]
Re-run with correct histology file is good!

For reference, to allow access to files in repository forks I had to be both a member of the organization and a repository member. Once I was added to D3b I could see the file.

**Comment by logstar** [comment]
@kelseykeith - Thank you for the review and note.

I will merge this PR after syncing with the `dev` branch.

cc @jharenza

**Comment by logstar** [comment]
@jharenza @kelseykeith - I have merged the latest `dev` branch to this PR, rerun the `snv-frequencies` module, and reproduced the results.

I will merge this PR shortly.

**Pull request merged**
