### PR TITLE
GSEA PBTA pull + OT update

### PR DESCRIPTION
**Pull request by runjin326**
#### What scientific question is your analysis addressing?
GSEA module from OpenPBTA was pulled from the most up-to-date version and edited to be compatible with OpenPedCan data files. 
Also, the module is generalized to iterate through each possible `RNA_library` instead of hard-coding RNA library name.

#### What was your approach?
- Instead of taking 2 separate gene expression file (polya and stranded), the combined `gene-expression-rsem-tpm-collapsed.rds` was used 
- After filtering out `TCGA` and `GTEx` cohorts from the gene expression file, we then iterate through each `RNA_library` in the dataset, run expression z-score and do GSVA analysis with the subset datasets.
- The scores are then combined into one file (`gsva_scores.tsv`) with an additional column indicating which RNA library it is from. (previously, `polya` and `stranded` were separated)
- For 02 script where ANOVA and TUKEY tests were ran, similarly, we iterate through all possible RNA library types and calculate scores for `cancer_group` and `harmonized_diagnosis`. (previously, we used `display_group` but it was changed to `cancer_group` for OT)

#### What GitHub issue does your pull request address?
https://github.com/PediatricOpenTargets/ticket-tracker/issues/96

#### Which areas should receive a particularly close look?
Please check to see whether the iteration makes sense.

#### Is there anything that you want to discuss further?
Currently, in order to run the module, we need a parameter `BPPARAM=SerialParam(progressbar=verbose)` in the GSVA function which is only compatible with R >4.0. 
Our docker has R 3.6, which means we cannot run this on the docker - we will have to run locally.
Please test the run script without using the docker. 

#### Is the analysis in a mature enough form that the resulting figure(s) and/or table(s) are ready for review?
Yes.

#### What types of results are included (e.g., table, figure)?
`gsva_scores.tsv`

#### What is your summary of the results?
NA.

#### Reproducibility Checklist

- [x] The dependencies required to run the code in this pull request have been added to the project Dockerfile.
- [ ] This analysis has been added to continuous integration.

#### Documentation Checklist

- [x] This analysis module has a `README` and it is up to date.
- [ ] This analysis is recorded in the table in `analyses/README.md` and the entry is up to date.
- [x] The analytical code is documented and contains comments.

### CODE REVIEW

**Comment by komalsrathi** [comment]
@runjin326 Apparently I faced the same issue last year (totally skipped because I keep creating tickets lol) can you try this solution: https://github.com/rcastelo/GSVA/issues/17

**Comment by runjin326** [comment]
> @runjin326 Apparently I faced the same issue last year (totally skipped because I keep creating tickets lol) can you try this solution: [rcastelo/GSVA#17](https://github.com/rcastelo/GSVA/issues/17)

Thanks so much @komalsrathi, I will give it a try!

**Comment by runjin326** [comment]
@komalsrathi , I made the recommended changes and now it runs!

**Comment by komalsrathi** [comment]
> @komalsrathi , I made the recommended changes and now it runs!

Awesome!!

**Review by ewafula — COMMENTED** [review]
@runjin326,  I work through the update code and the logic looks okay. Here are a few suggestions and comments. 

- need to either `library(tidyverse)` or `dplyr::pull(`)  in script `01-conduct-gsea-analysis.R` to avoid this error:
```
Delimiter: "\t"
chr (41): Kids_First_Biospecimen_ID, sample_id, aliquot_id, Kids_First_Parti...
dbl  (5): OS_days, age_last_update_days, normal_fraction, tumor_fraction, tu...

i Use `spec()` to retrieve the full column specification for this data.
i Specify the column types or set `show_col_types = FALSE` to quiet this message.
Error in pull(., RNA_library) : could not find function "pull"
Calls: %>% -> unique
Execution halted
```
- I am getting 130601 entries in the  output file `results/gsva_scores.tsv` using v10 data release while in you PR the entries  `209601`. Likely because we are using different input files. I changed  `histologies-base.tsv` to `histologies.tsv` in `run-gsea.sh` script because the former does not exist in OpenPedCan v10. 
- When running in default mode without setting `OPENPBTA_BASE_SUBTYPING=1`. which executes the `2-model-gsea.Rmd` notebook, I get the following error message shown below. Is this expected ?
```
Quitting from lines 136-193 (02-model-gsea.Rmd) 
Error: Can't subset columns that don't exist.
x Column `comparison` doesn't exist.
Backtrace:
     x
  1. +-rmarkdown::render("02-model-gsea.Rmd", clean = TRUE, params = list(is_ci = 0))
  2. | \-knitr::knit(knit_input, knit_output, envir = envir, quiet = quiet)
  3. |   \-knitr:::process_file(text, output)
  4. |     +-base::withCallingHandlers(...)
  5. |     +-knitr:::process_group(group)
  6. |     \-knitr:::process_group.block(group)
  7. |       \-knitr:::call_block(x)
  8. |         \-knitr:::block_exec(params)
  9. |           \-knitr:::eng_r(options)
 10. |             +-knitr:::in_dir(...)
 11. |             \-knitr:::evaluate(...)
 12. |               \-evaluate::evaluate(...)
 13. |                 \-evaluate:::evaluate_call(...)
 14. |                   +-evaluate:::timing_fn(...)
 15. |                   +-base:::handle(...)
 16. |                   +-base::withCallingHandlers(...)
 17. |                   +-base::withVisible(eval(expr, envir, enclos))
 18. |                   \-base::eval(expr, envir, enclos)
 19. |                     \-base::eval(expr, envir, enclos)
 20. +-global::gsva_anova_tukey(...)
 21. | \-`%>%`(...)
 22. +-dplyr::mutate(...)
 23. +-dplyr::rename(., pathway_score_difference = estimate, tukey_p_value = adj.p.value)
 24. +-dplyr::select(., hallmark_name, comparison, estimate, adj.p.value)
 25. \-dplyr:::select.data.frame(...)
 26.   \-tidyselect::eval_select(expr(c(...)), .data)
 27.     \-tidyselect:::eval_select_impl(...)
 28.       +-tidyselect:::with_subscript_errors(...)
 29.       | +-base::tryCatch(...)
 30.       | | \-base:::tryCatchList(expr, classes, parentenv, handlers)
 31.       | |   \-base:::tryCatchOne(expr, names, parentenv, handlers[[1L]])
 32.       | |     \-base:::doTryCatch(return(expr), name, parentenv, handler)
 33.       | \-tidyselect:::instrument_base_errors(expr)
 34.       |   \-base::withCallingHandlers(...)
 35.       \-tidyselect:::vars_select_eval(...)
 36.         \-tidyselect:::walk_data_tree(expr, data_mask, context_mask)
 37.           \-tidyselect:::eval_c(expr, data_mask, context_mask)
 38.             \-tidyselect:::reduce_sels(node, data_mask, context_mask, init = init)
 39.               \-tidyselect:::walk_data_tree(new, data_mask, context_mask)
 40.                 \-tidyselect:::as_indices_sel_impl(...)
 41.                   \-tidyselect:::as_indices_impl(x, vars, strict = strict)
 42.                     \-tidyselect:::chr_as_locations(x, vars)
 43.                       \-vctrs::vec_as_location(x, n = length(vars), names = vars)
 44.                         \-(function () ...
 45.                           \-vctrs:::stop_subscript_oob(...)
 46.                             \-vctrs:::stop_subscript(...)

Execution halted
```
- Cohort subsetting below is not utilized in the `01-conduct-gsea-analysis.R` script`. Consider removing. 
```
cohort_list <- histology_rna_df %>% pull(cohort) %>% unique()
```

**Comment by runjin326** [comment]
@ewafula, thanks so much for reviewing this and making the change suggestions.
1) I now changed the library called from `tidyr` to `tidyverse` and the `pull` function no longer gives an error
2) Yes, when I re-ran with v10 histologies, it is also 130600 (+1 column names) entries
3) For running 02 script, I realized it needs to be ran in the docker (maybe a newer version of some of the packages is causing the error message?) - so maybe running `Rscript -e "rmarkdown::render('02-model-gsea.Rmd', clean = TRUE, params=list(is_ci = 0))"` in docker after running 01 locally would be fine. 
4) If you want to try running the module in run script - you can remove `BPPARAM=SerialParam(progressbar=T)` on line 146 (and the comma before it) - and then run in EC2. I tried that and it worked. I think I might actually remove that line and state that this module needs to be run in EC2 if that works for you. 
5) I would not change `histologies-base.tsv` - this is for when we are running for subtyping and we would run on base histologies file.

**Review by ewafula — APPROVED** [review]
@runjin326,  running `02-model-gsea.Rmd` in the OpenPedCan docker works okay without errors. Maybe just update the README with instructions on how to run the module - the first script, `01-conduct-gsea-analysis.R` outside docker because it depends on R >= 4.0.0, not installed in the docker container, and `02-model-gsea.Rmd` in docker - pending the building of a new docker image that can work with both. Running the wrapper script `run-gsea.sh` with the `OPENPBTA_BASE_SUBTYPING=1` environment variable is currently not possible for the reasons mentioned above.  Also, consider adding `histologies-base.tsv` in OpenPedCan data releases if it is a requirement for running subtyping. Approving.

**Pull request merged**
