### PR TITLE
Created new module to track changes to ensg-hugo-pmtl-mapping.tsv file

### PR DESCRIPTION
**Pull request by sangeetashukla**
### Purpose/implementation Section
Update  ensg-hugo-rmtl-mapping.tsv file per recent discussions with FNL.

#### What was your approach?

- Split existing file into IDs and gene_symbol combinations with and without update.
- Map and update ENSG IDs  as per PMTLv1.1 to existing file

#### What GitHub issue does your pull request address?
[Issue 206](https://github.com/PediatricOpenTargets/ticket-tracker/issues/206)

### Directions for reviewers. Tell potential reviewers what kind of feedback you are soliciting.

- Review the steps/logic in the `update-rmtl-to-pmtl.R` script
- Review the new mapping file
- Note: The file name of the new `results/ensg-hugo-rmtl-mapping.tsv` is changed to ensg-hugo-pmtl-mapping.tsv. Please let me know if we need to change it back.

#### Is the analysis in a mature enough form that the resulting figure(s) and/or table(s) are ready for review?
Yes

#### What types of results are included (e.g., table, figure)?
New file is included, which once PR is approved, must be added to v10

#### Reproducibility Checklist

- [ ] The dependencies required to run the code in this pull request have been added to the project Dockerfile.
- [ ] This analysis has been added to continuous integration.

#### Documentation Checklist

- [ ] This analysis module has a `README` and it is up to date.
- [ ] This analysis is recorded in the table in `analyses/README.md` and the entry is up to date.
- [ ] The analytical code is documented and contains comments.

### CODE REVIEW

**Comment by sangeetashukla** [comment]
@afarrel @chinwallaa 

Edited this module to undo changes from Pediatric Molecular Target --> Relevant Molecular Target as per discussion [pull_129](PR), also for the same [issue 206](https://github.com/PediatricOpenTargets/ticket-tracker/issues/206) that this PR.

This PR is now ready for review.

Note: Only the results/ensg-hugo-rmtl-mapping.tsv needs to be added to v10 data release. No other scripts must be merged.

**Comment by logstar** [comment]
> @afarrel @chinwallaa
> 
> Edited this module to undo changes from Pediatric Molecular Target --> Relevant Molecular Target as per discussion [pull_129](PR), also for the same [issue 206](https://github.com/PediatricOpenTargets/ticket-tracker/issues/206) that this PR.
> 
> This PR is now ready for review.
> 
> Note: Only the results/ensg-hugo-rmtl-mapping.tsv needs to be added to v10 data release. No other scripts must be merged.

@sangeetashukla Thank you for the updates.

Do you mean only results/ensg-hugo-pmtl-mapping.tsv needs to be added to v10 data release? The latest <https://github.com/PediatricOpenTargets/OpenPedCan-analysis/pull/129/files> uses `ensg-hugo-pmtl-mapping.tsv`:

<https://github.com/PediatricOpenTargets/OpenPedCan-analysis/blob/c5d6ff34acf3d1070849b6e5e508d13c60b2cdb6/analyses/long-format-table-utils/annotator/annotator-api.R#L330-L332>

**Comment by sangeetashukla** [comment]
> > @afarrel @chinwallaa
> > Edited this module to undo changes from Pediatric Molecular Target --> Relevant Molecular Target as per discussion [pull_129](PR), also for the same [issue 206](https://github.com/PediatricOpenTargets/ticket-tracker/issues/206) that this PR.
> > This PR is now ready for review.
> > Note: Only the results/ensg-hugo-rmtl-mapping.tsv needs to be added to v10 data release. No other scripts must be merged.
> 
> @sangeetashukla Thank you for the updates.
> 
> Do you mean only results/ensg-hugo-pmtl-mapping.tsv needs to be added to v10 data release? The latest https://github.com/PediatricOpenTargets/OpenPedCan-analysis/pull/129/files uses `ensg-hugo-pmtl-mapping.tsv`:
> 
> https://github.com/PediatricOpenTargets/OpenPedCan-analysis/blob/c5d6ff34acf3d1070849b6e5e508d13c60b2cdb6/analyses/long-format-table-utils/annotator/annotator-api.R#L330-L332

@logstar Yes, once this PR is reviewed and approved, only the mapping file must be added to v10 release, but not the R script from this module.
Thank you for bringing up [Pull 129](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/pull/129#issuecomment-926138082) that uses the mapping file. I will go ahead and rename that file back from `ensg-hugo-pmtl-mapping.tsv` to `ensg-hugo-rmtl-mapping.tsv` in that module. 
Please review/approve this PR and then use the file for testing  [Pull 129](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/pull/129#issuecomment-926138082)

**Comment by logstar** [comment]
> > > @afarrel @chinwallaa
> > > Edited this module to undo changes from Pediatric Molecular Target --> Relevant Molecular Target as per discussion [pull_129](PR), also for the same [issue 206](https://github.com/PediatricOpenTargets/ticket-tracker/issues/206) that this PR.
> > > This PR is now ready for review.
> > > Note: Only the results/ensg-hugo-rmtl-mapping.tsv needs to be added to v10 data release. No other scripts must be merged.
> > 
> > 
> > @sangeetashukla Thank you for the updates.
> > Do you mean only results/ensg-hugo-pmtl-mapping.tsv needs to be added to v10 data release? The latest https://github.com/PediatricOpenTargets/OpenPedCan-analysis/pull/129/files uses `ensg-hugo-pmtl-mapping.tsv`:
> > https://github.com/PediatricOpenTargets/OpenPedCan-analysis/blob/c5d6ff34acf3d1070849b6e5e508d13c60b2cdb6/analyses/long-format-table-utils/annotator/annotator-api.R#L330-L332
> 
> @logstar Yes, once this PR is reviewed and approved, only the mapping file must be added to v10 release, but not the R script from this module.
> Thank you for bringing up [Pull 129](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/pull/129#issuecomment-926138082) that uses the mapping file. I will go ahead and rename that file back from `ensg-hugo-pmtl-mapping.tsv` to `ensg-hugo-rmtl-mapping.tsv` in that module.
> Please review/approve this PR and then use the file for testing [Pull 129](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/pull/129#issuecomment-926138082)

EDIT 09/24/2021 YZ. Keep mapping file name as `ensg-hugo-pmtl-mapping.tsv`, according to @runjin326's comment at <https://github.com/PediatricOpenTargets/OpenPedCan-analysis/pull/127#issuecomment-926928394>.

Thank you for the quick reply. I recommend keeping only one mapping file in this new module, ~~either `ensg-hugo-rmtl-mapping.tsv` or~~ `ensg-hugo-pmtl-mapping.tsv`, so we could reduce mistakes when uploading the wrong one.

~~I am not sure if we want to change the `ensg-hugo-pmtl-mapping.tsv` back to `ensg-hugo-rmtl-mapping.tsv` though, but either one should be fine.~~

I have not looked at the code in this PR at all, so I would leave others to review the code of this PR and approve. I am only testing whether the updated `annotator` would work.

**Comment by runjin326** [comment]
@sangeetashukla, thanks for preparing the PR! @chinwallaa, @afarrel and I had a quick discussion before - we want to keep the name as `ensg-hugo-pmtl-mapping.tsv` - but since this file is used by different modules, the name change will trigger modifying downstream modules that uses this file. We will submit tickets for making those change. So please keep the name as is.

**Comment by sangeetashukla** [comment]
> @sangeetashukla, thanks for preparing the PR! @chinwallaa, @afarrel and I had a quick discussion before - we want to keep the name as `ensg-hugo-pmtl-mapping.tsv` - but since this file is used by different modules, the name change will trigger modifying downstream modules that uses this file. We will submit tickets for making those change. So please keep the name as is.

Thank you @runjin326 for the message. I have reviewed the branch for appropriate file name usage. 
This PR is now ready for review.

**Comment by logstar** [comment]
@sangeetashukla - @ewafula and I have found the following gene symbols are present in v9 `gene-expression-rsem-tpm-collapsed.rds` but absent in the latest [ensg-hugo-pmtl-mapping.tsv](https://raw.githubusercontent.com/PediatricOpenTargets/OpenPedCan-analysis/9928f2d9356ba3e8e1ff72aca8a1b0627e69fe69/analyses/ensg-hugo-rmtl-mapping/results/ensg-hugo-pmtl-mapping.tsv). Could you check why these symbols are absent in the latest ensg-hugo-pmtl-mapping.tsv? Would it be possible to add them back, as some of them are RMTLs?

```text
"H3F3B"    "TMEM173"  "ZNRD1"    "H3F3A"    "SEPT6"    "TWISTNB"  "CD3EAP"   "TUBB8P12" "HIST2H3C"
```

These gene symbols are present in v9 ensg-hugo-rmtl-mapping.tsv.

```text
> es_df <- read_tsv('../../data/ensg-hugo-rmtl-mapping.tsv')
> missing_symbs <- c("H3F3B","TMEM173","ZNRD1","H3F3A","SEPT6","TWISTNB","CD3EAP","TUBB8P12","HIST2H3C") 
> es_df %>% filter(gene_symbol %in% missing_symbs)                                                                                                                                                    
# A tibble: 9 × 4
  ensg_id         gene_symbol rmtl                      version         
  <chr>           <chr>       <chr>                     <chr>           
1 ENSG00000203811 HIST2H3C    NA                        NA              
2 ENSG00000163041 H3F3A       Relevant Molecular Target RMTL version 1.0
3 ENSG00000184584 TMEM173     Relevant Molecular Target RMTL version 1.0
4 ENSG00000066379 ZNRD1       Relevant Molecular Target RMTL version 1.0
5 ENSG00000105849 TWISTNB     Relevant Molecular Target RMTL version 1.0
6 ENSG00000132475 H3F3B       NA                        NA              
7 ENSG00000117877 CD3EAP      Relevant Molecular Target RMTL version 1.0
8 ENSG00000125354 SEPT6       Relevant Molecular Target RMTL version 1.0
9 ENSG00000173213 TUBB8P12    Relevant Molecular Target RMTL version 1.0


> es_pmtl_df <- read_tsv('ensg-hugo-pmtl-mapping.tsv')                                                                                                                                                
> es_pmtl_df %>% filter(gene_symbol %in% missing_symbs)                                                                                                                                               
# A tibble: 0 × 4
# … with 4 variables: ensg_id <chr>, gene_symbol <chr>, pmtl <chr>, version <chr>
```

**Comment by sangeetashukla** [comment]
> @sangeetashukla - @ewafula and I have found the following gene symbols are present in v9 `gene-expression-rsem-tpm-collapsed.rds` but absent in the latest [ensg-hugo-pmtl-mapping.tsv](https://raw.githubusercontent.com/PediatricOpenTargets/OpenPedCan-analysis/9928f2d9356ba3e8e1ff72aca8a1b0627e69fe69/analyses/ensg-hugo-rmtl-mapping/results/ensg-hugo-pmtl-mapping.tsv). Could you check why these symbols are absent in the latest ensg-hugo-pmtl-mapping.tsv? Would it be possible to add them back, as some of them are RMTLs?
> 
> ```
> "H3F3B"    "TMEM173"  "ZNRD1"    "H3F3A"    "SEPT6"    "TWISTNB"  "CD3EAP"   "TUBB8P12" "HIST2H3C"
> ```
> 
> These gene symbols are present in v9 ensg-hugo-rmtl-mapping.tsv.
> 
> ```
> > es_df <- read_tsv('../../data/ensg-hugo-rmtl-mapping.tsv')
> > missing_symbs <- c("H3F3B","TMEM173","ZNRD1","H3F3A","SEPT6","TWISTNB","CD3EAP","TUBB8P12","HIST2H3C") 
> > es_df %>% filter(gene_symbol %in% missing_symbs)                                                                                                                                                    
> # A tibble: 9 × 4
>   ensg_id         gene_symbol rmtl                      version         
>   <chr>           <chr>       <chr>                     <chr>           
> 1 ENSG00000203811 HIST2H3C    NA                        NA              
> 2 ENSG00000163041 H3F3A       Relevant Molecular Target RMTL version 1.0
> 3 ENSG00000184584 TMEM173     Relevant Molecular Target RMTL version 1.0
> 4 ENSG00000066379 ZNRD1       Relevant Molecular Target RMTL version 1.0
> 5 ENSG00000105849 TWISTNB     Relevant Molecular Target RMTL version 1.0
> 6 ENSG00000132475 H3F3B       NA                        NA              
> 7 ENSG00000117877 CD3EAP      Relevant Molecular Target RMTL version 1.0
> 8 ENSG00000125354 SEPT6       Relevant Molecular Target RMTL version 1.0
> 9 ENSG00000173213 TUBB8P12    Relevant Molecular Target RMTL version 1.0
> 
> 
> > es_pmtl_df <- read_tsv('ensg-hugo-pmtl-mapping.tsv')                                                                                                                                                
> > es_pmtl_df %>% filter(gene_symbol %in% missing_symbs)                                                                                                                                               
> # A tibble: 0 × 4
> # … with 4 variables: ensg_id <chr>, gene_symbol <chr>, pmtl <chr>, version <chr>
> ```

@logstar Sure, I will look into it.

**Comment by jharenza** [comment]
@logstar @sangeetashukla @afarrel those genes had other aliases in the FNL file and had been updated to use our gene symbols, per the D3b codes repo- https://github.com/d3b-center/D3b-codes/blob/master/gene_match/add_rmtl_ens_hugo.Rmd -please look over that code and if updating within this repo, carry over. Thanks!

**Comment by sangeetashukla** [comment]
Closing this PR, since the issue is now resolvable with [another module](https://github.com/d3b-center/D3b-codes/tree/master/gene_match) in D3B-Codes repo and @runjin326 has created [this PR](https://github.com/d3b-center/D3b-codes/pull/52).

**Pull request closed without merging**
