### PR TITLE
Evaluate the use of empirical negative control genes for batch correction

### PR DESCRIPTION
**Pull request by logstar**
#### What scientific question is your analysis addressing?

Evaluate the effectiveness of using empirically defined negative control housekeeping genes for batch effect correction. The empirically defined negative control housekeeping genes show stable expression levels in poly-A and ribo-deplete-stranded RNA-seq libraries prepared from the same biological samples, which are selected in the [PR 11](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/pull/11).

#### What was your approach?

1. Select `Kids_First_Biospecimen`s with the same `sample_id`s and both ribo-deplete-stranded and poly-A `RNA_library`s.
    Index | Kids_First_Biospecimen_ID | sample_id | experimental_strategy | RNA_library | cohort
    ------|---------------------------|-----------|-----------------------|-------------|--------
    1     | BS_HE0WJRW6               | 7316-1455 | RNA-Seq               | stranded    | CBTN
    2     | BS_HWGWYCY7               | 7316-1455 | RNA-Seq               | poly-A      | CBTN
    3     | BS_SHJA4MR0               | 7316-161  | RNA-Seq               | stranded    | CBTN
    4     | BS_X0XXN9BK               | 7316-161  | RNA-Seq               | poly-A      | CBTN
    5     | BS_FN07P04C               | 7316-255  | RNA-Seq               | stranded    | CBTN
    6     | BS_W4H1D4Y6               | 7316-255  | RNA-Seq               | poly-A      | CBTN
    7     | BS_8QB4S4VA               | 7316-536  | RNA-Seq               | stranded    | CBTN
    8     | BS_QKT3TJVK               | 7316-536  | RNA-Seq               | poly-A      | CBTN
    9     | BS_7WM3MNZ0               | A16915    | RNA-Seq               | poly-A      | PNOC003
    10    | BS_KABQQA0T               | A16915    | RNA-Seq               | stranded    | PNOC003
    11    | BS_68KX6A42               | A18777    | RNA-Seq               | poly-A      | PNOC003
    12    | BS_D7XRFE0R               | A18777    | RNA-Seq               | stranded    | PNOC003
2. Run DESeq2 default differential gene expression (DGE) analysis to compare ribo-deplete-stranded and poly-A RNA-seq `rsem-expected_count`s.
3. Run DESeq2 DGE analysis with RUVSeq estimated batch effect in the design to compare ribo-deplete-stranded and poly-A RNA-seq `rsem-expected_count`s. The batch effect is estimated using [empirically defined negative control housekeeping genes](https://github.com/logstar/OpenPedCan-analysis/blob/rna-seq-protocol-dge-fourth/analyses/rna-seq-protocol-dge/results/uqpgq2_normalized/stranded_vs_polya_stably_exp_genes.csv) selected in the [PR 11](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/pull/11), using the RUVg workflow demonstrated in the section "2.4 Empirical control genes" in the [RUVSeq vignette](https://bioconductor.riken.jp/packages/3.0/bioc/vignettes/RUVSeq/inst/doc/RUVSeq.pdf).
4. Plot the distributions of DGE p-values computed from step 2 and 3.

#### What GitHub issue does your pull request address?

<https://github.com/PediatricOpenTargets/ticket-tracker/issues/39>

#### Which areas should receive a particularly close look?

Is RUVSeq correctly used in the following code:

```R
seq_expr_set <- newSeqExpressionSet(
    round_cnt_mat,
    phenoData = data.frame(group, row.names = colnames(round_cnt_mat)))


seg_df <- read.csv(
    'input/uqpgq2_normalized_stranded_vs_polya_stably_exp_genes.csv',
    stringsAsFactors = FALSE, row.names = 1)


ruvg_res <- RUVg(seq_expr_set, seg_df$gene, k=1)


suppressMessages(
    ruv_dds <- DESeq2::DESeqDataSetFromMatrix(
        countData = counts(ruvg_res),
        colData = pData(ruvg_res),
        design = ~ W_1 + group)
)
# From DESeq2 documentation:
# DESeq2::DESeq performs a default analysis through the steps:
# - estimation of size factors: estimateSizeFactors
# - estimation of dispersion: estimateDispersions
# - Negative Binomial GLM fitting and Wald statistics: nbinomWaldTest
suppressMessages(
    ruv_dds <- DESeq2::DESeq(ruv_dds)
)
```

Link to the above code, <https://github.com/logstar/OpenPedCan-analysis/blob/6825965de148eda8240f105504caeedcaf66f605/analyses/rna-seq-protocol-ruvseq/01-protocol-ruvseq.R#L137-L160>.

#### Is there anything that you want to discuss further?

If more datasets are required in the <https://github.com/PediatricOpenTargets/ticket-tracker/issues/39>, I will update the analysis code to include them.

#### Is the analysis in a mature enough form that the resulting figure(s) and/or table(s) are ready for review?

Yes.

#### What types of results are included (e.g., table, figure)?

Tables and figures.

#### What is your summary of the results?

- `plots/stranded_vs_polya_dge_deseq2_nbinom_wald_test_pvals_histogram.png`: DESeq2 DGE p-value histogram without RUVSeq estimated batch effect in the design.
    - dge
- `plots/plots/stranded_vs_polya_dge_ruvg_k1_deseq2_nbinom_wald_test_pvals_histogram.png`: DESeq2 DGE p-value histogram with RUVSeq estimated batch effect in the design.
    - ruvg_dge
- `results/stranded_vs_polya_dge_deseq2_nbinom_wald_test_res.csv`: DESeq2 DGE result table without RUVSeq estimated batch effect in the design.
- `results/stranded_vs_polya_dge_ruvg_k1_deseq2_nbinom_wald_test_res.csv`: DESeq2 DGE result table with RUVSeq estimated batch effect in the design.

#### Reproducibility Checklist

- [ ] The dependencies required to run the code in this pull request have been added to the project Dockerfile.
- [ ] This analysis has been added to continuous integration.

Dockerfile will be updated in a new PR to install RUVSeq.

#### Documentation Checklist

- [x] This analysis module has a `README` and it is up to date.
- [x] This analysis is recorded in the table in `analyses/README.md` and the entry is up to date.
- [x] The analytical code is documented and contains comments.

### CODE REVIEW

**Comment by logstar** [comment]
Updates for this PR:

Added DIPG and NBL datasets for poly-A vs stranded DGE analysis, according to <https://github.com/PediatricOpenTargets/ticket-tracker/issues/39#issuecomment-859751927>. The results and plots of each dataset are saved in its corresponding subdirectory, e.g. `results/nbl/stranded_vs_polya_dge_ruvg_k1_deseq2_nbinom_wald_test_res.csv`. The p-value histograms are shown in <https://github.com/logstar/OpenPedCan-analysis/blob/rna-seq-protocol-ruvseq/analyses/rna-seq-protocol-ruvseq/README.md>.

**Review by afarrel — APPROVED** [review]
Yes. RUVSeq seems to be used correctly here. I used the latest RUVSeq vignette (which includes differential expression analysis with DESeq2 sec 2.5) to confirm workflow/usage and tested the code:
http://bioconductor.org/packages/release/bioc/vignettes/RUVSeq/inst/doc/RUVSeq.pdf
(Other comments welcomed)

**Comment by logstar** [comment]
> Yes. RUVSeq seems to be used correctly here. I used the latest RUVSeq vignette (which includes differential expression analysis with DESeq2 sec 2.5) to confirm workflow/usage and tested the code:
> http://bioconductor.org/packages/release/bioc/vignettes/RUVSeq/inst/doc/RUVSeq.pdf
> (Other comments welcomed)

Thank you for reviewing the code and confirming the RUVSeq usage!

**Comment by jharenza** [comment]
thanks @afarrel !

**Pull request merged**
