### PR TITLE
Update `snv-frequencies` module for v7 data release

### PR DESCRIPTION
**Pull request by logstar**
### Purpose/implementation Section

Update `snv-frequencies` module for v7 data release.

- Use `long-format-table-utils/annotator` submodule to add annotations.
- Rerun using v7 release data.
- Remove gene-level pedcbio plot URLs from the variant-level table.

#### What was your approach?

Use `long-format-table-utils/annotator` in `01-snv-frequencies.R` to add annotations, in commit <https://github.com/PediatricOpenTargets/OpenPedCan-analysis/commit/62085d35640477473baf371e4d805c65afb8bf0f>. However, `Protein_RefSeq_ID` and `Gene_full_name` are still added directly using the [R mygene package](https://www.bioconductor.org/packages/release/bioc/html/mygene.html), and relevant code is adapted from `long-format-table-utils/annotator/download-annotation-data.R`, because annotator only have `Protein_RefSeq_ID` and `Gene_full_name` for `Gene_Ensembl_ID`s that are in `ensg-hugo-rmtl-mapping.tsv`. `snv-consensus-plus-hotspots.maf.tsv.gz` has `Gene_Ensembl_ID`s that are not in `ensg-hugo-rmtl-mapping.tsv`, e.g. ENSG00000284770 and ENSG00000285053. See <https://github.com/PediatricOpenTargets/ticket-tracker/issues/146> for more details. `Protein_RefSeq_ID` and `Gene_full_name` may be added through `annotator` at a later point, after the missing gene symbol and ENSG ID mapping issue is resolved.

Removed gene-level `PedcBio_PedOT_oncoprint_plot_URL` and `PedcBio_PedOT_mutations_plot_URL` columns from the variant-level table, in commit <https://github.com/PediatricOpenTargets/OpenPedCan-analysis/commit/0f430c36aba15e428328710bc3dc5a051900a213>.

Removed `input/oncokb_cancer_gene_list.tsv`. OncoKB annotations are added using annotator.

Generated results using v7 data and independent sample lists.

In commit <https://github.com/PediatricOpenTargets/OpenPedCan-analysis/commit/f20f96fd907310277424ddc639531e72767cf086> `run-snv-frequencies.sh`, gzipped `results/variant-level-snv-consensus-annotated-mut-freq.tsv`, because it exceeds the 100MB size limit of GitHub.

Updated README.md.

#### What GitHub issue does your pull request address?

- <https://github.com/PediatricOpenTargets/ticket-tracker/issues/144>
- <https://github.com/PediatricOpenTargets/ticket-tracker/issues/123>

#### Which areas should receive a particularly close look?

Do the changes in `01-snv-frequencies.R` make sense?

#### Is there anything that you want to discuss further?

Fixed a minor bug in this PR by integrating annotator. In previous result tables, string `"NA"` (not missing `NA`) values in `Gene_full_name` column were introduced in the previous code by `name = paste(unique(name), collapse = ', ')` when querying mygene.info. This bug was fixed in the `long-format-table-utils/annotator` submodule development, and the fixed `annotator` code is adapted in `01-snv-frequencies.R` to add `Protein_RefSeq_ID` and `Gene_full_name`. All other parts of the results are identical to the results generated before the bug fix, which is checked by the following bash commands.

```text
# change working directory to snv-frequencies
#
# If Gene_full_name column is removed, there is no difference between results generated before and after bug fix.
#
# 7th column is Gene_full_name
$ diff <(git show HEAD:./results/gene-level-snv-consensus-annotated-mut-freq.tsv | cut -f 1-6,8-21) <(cut -f 1-6,8-21 results/gene-level-snv-consensus-annotated-mut-freq.tsv) | wc -l
0
# 14th column is Gene_full_name
$ diff <(git show HEAD:./results/variant-level-snv-consensus-annotated-mut-freq.tsv.gz | gunzip -c | cut -f 1-13,15-27) <(gunzip -c results/variant-level-snv-consensus-annotated-mut-freq.tsv.gz | cut -f 1-13,15-27) | wc -l
0

# No difference in Gene_full_name before and after bug fix, if "NA" values are replaced with blank strings
$ diff <(git show HEAD:./results/gene-level-snv-consensus-annotated-mut-freq.tsv | cut -f 7 | sed -e 's/"NA"//g') <(cut -f 7 results/gene-level-snv-consensus-annotated-mut-freq.tsv) | wc -l
0

$ diff <(git show HEAD:./results/variant-level-snv-consensus-annotated-mut-freq.tsv.gz | gunzip -c | cut -f 14 | sed -e 's/"NA"//g') <(gunzip -c results/variant-level-snv-consensus-annotated-mut-freq.tsv.gz | cut -f 14) | wc -l
0

# Number of lines with different values in Gene_full_name
$ diff <(git show HEAD:./results/gene-level-snv-consensus-annotated-mut-freq.tsv | cut -f 7) <(cut -f 7 results/gene-level-snv-consensus-annotated-mut-freq.tsv) | grep '^>' | wc -l
338

$ diff <(git show HEAD:./results/variant-level-snv-consensus-annotated-mut-freq.tsv.gz | gunzip -c | cut -f 14) <(gunzip -c results/variant-level-snv-consensus-annotated-mut-freq.tsv.gz | cut -f 14) | grep '^>' | wc -l
574

# Number of lines with "NA" in Gene_full_name in previous result TSVs
$ git show HEAD:./results/gene-level-snv-consensus-annotated-mut-freq.tsv | cut -f 7 | grep '"NA"' | wc -l
338

$ git show HEAD:./results/variant-level-snv-consensus-annotated-mut-freq.tsv.gz | gunzip -c | cut -f 14 | grep '"NA"' | wc -l
574

# No "NA" in current result TSVs
$ grep -P '"NA"' results/gene-level-snv-consensus-annotated-mut-freq.tsv | wc -l
0
$ gunzip -c results/variant-level-snv-consensus-annotated-mut-freq.tsv.gz | grep '"NA"' | wc -l
0
```

#### Is the analysis in a mature enough form that the resulting figure(s) and/or table(s) are ready for review?

Yes

#### What types of results are included (e.g., table, figure)?

Tables

#### What is your summary of the results?

```text
$ ls -lh results/
total 52M
-rw-r--r-- 1 ubuntu ubuntu 4.1M Jul 31 01:00 gene-level-snv-consensus-annotated-mut-freq.jsonl.gz
-rw-r--r-- 1 ubuntu ubuntu  27M Jul 31 01:00 gene-level-snv-consensus-annotated-mut-freq.tsv
-rw-r--r-- 1 ubuntu ubuntu  12M Jul 31 01:00 variant-level-snv-consensus-annotated-mut-freq.jsonl.gz
-rw-r--r-- 1 ubuntu ubuntu 9.9M Jul 31 00:59 variant-level-snv-consensus-annotated-mut-freq.tsv.gz
```

#### Reproducibility Checklist

- [x] The dependencies required to run the code in this pull request have been added to the project Dockerfile.
- [NA] This analysis has been added to continuous integration.

#### Documentation Checklist

- [x] This analysis module has a `README` and it is up to date.
- [x] This analysis is recorded in the table in `analyses/README.md` and the entry is up to date.
- [x] The analytical code is documented and contains comments.

### CODE REVIEW

**Review by jharenza — APPROVED** [review]
This looks good - the overall frequencies match what are in pedcbio. I just have one comment but this may be annotator-related. For the `OncoKB_oncogene_TSG`, I would advocate switching this to Y/N just like `OncoKB_cancer_gene`.

**Comment by logstar** [comment]
> This looks good - the overall frequencies match what are in pedcbio. I just have one comment but this may be annotator-related. For the `OncoKB_oncogene_TSG`, I would advocate switching this to Y/N just like `OncoKB_cancer_gene`.

Thank you for reviewing the PR.

This would be annotator related. To clarify, if a gene is `Oncogene`, or `TumorSuppressorGene`, or both, it takes Y in `OncoKB_oncogene_TSG`; otherwise, it takes N in `OncoKB_oncogene_TSG`.

I can submit a ticket and create another annotator PR for this update. Once it is merged, we could re-generate the tables immediately or after the next data release.

**Comment by jharenza** [comment]
>This would be annotator related. To clarify, if a gene is Oncogene, or TumorSuppressorGene, or both, it takes Y in OncoKB_oncogene_TSG; otherwise, it takes N in OncoKB_oncogene_TSG.

I figured that, but it is not a binary Y/N in `OncoKB_oncogene_TSG` currently, rather it is a blank or `TumorSuppressorGene`.

**Comment by logstar** [comment]
> > This would be annotator related. To clarify, if a gene is Oncogene, or TumorSuppressorGene, or both, it takes Y in OncoKB_oncogene_TSG; otherwise, it takes N in OncoKB_oncogene_TSG.
> 
> I figured that, but it is not a binary Y/N in `OncoKB_oncogene_TSG` currently, rather it is a blank or `TumorSuppressorGene`.

Sorry for the confusion.

Right. Currently, The `OncoKB_oncogene_TSG` column takes one of the following four values: `Oncogene`, or `TumorSuppressorGene`, or `Oncogene,TumorSuppressorGene`, or blank string (`""` in JSONL and nothing in TSV, as they are not Oncogene or TumorSuppressorGene). 

What I meant was to replace these values with Y/N according to their current values. If a gene currently has `Oncogene`, or `TumorSuppressorGene`, or  `Oncogene,TumorSuppressorGene` in the `OncoKB_oncogene_TSG` column, it is going to take `Y` in `OncoKB_oncogene_TSG` in the revised annotator; if a gene currently has blank string in the `OncoKB_oncogene_TSG` column, it takes `N` in `OncoKB_oncogene_TSG` column in the revised annotator.

Another issue that is relevant here is whether we want to split the `OncoKB_oncogene_TSG` column into the following two columns `OncoKB_oncogene` and `OncoKB_TSG`. I imagine this would require extensive refactoring of annotator, analysis modules, and FNL ETL code.

**Comment by jharenza** [comment]
Ahh, nevermind- I was reading that too fast as in that was a column specific to TSG, and didn't look at the levels. We should leave how it is for now! Feel free to merge.

**Comment by logstar** [comment]
> Ahh, nevermind- I was reading that too fast as in that was a column specific to TSG, and didn't look at the levels. We should leave how it is for now! Feel free to merge.

Got it. Thank you for checking. Sounds good!

I will merge this PR shortly. I will also upload the new results to the box folder and update changelog.

**Pull request merged**
