### PR TITLE
Exclude descriptions from MTP disease mapping

### PR DESCRIPTION
**Pull request by ewafula**
#### What was your approach?
- excluded disease description in `mtp-diseases-mapping.tsv`. 
- some are formatted over several lines
- some are several paragraphs longs
- Only retaining `id`, `name`,  and `dbXRefs` columns because at no time is the disease description going to be utilized 

#### Which areas should receive a particularly close look?
Check to make sure the disease mapping file is formatted correctly

#### Is there anything that you want to discuss further?
NA

#### Is the analysis in a mature enough form that the resulting figure(s) and/or table(s) are ready for review?
 Yes 

#### What types of results are included (e.g., table, figure)?
Tables

#### What is your summary of the results?
- mtp-diseases-mapping.tsv.gz  
- mtp-targets-mapping.tsv.gz

#### Reproducibility Checklist

- [x] The dependencies required to run the code in this pull request have been added to the project Dockerfile.
- [x] This analysis has been added to continuous integration.

#### Documentation Checklist

- [x] This analysis module has a `README` and it is up to date.
- [ ] This analysis is recorded in the table in `analyses/README.md` and the entry is up to date.
- [x] The analytical code is documented and contains comments.

### CODE REVIEW

**Review by sangeetashukla — APPROVED** [review]
@ewafula I reviewed the changes, and verified the results format in the file.
`input_dir <- "results"
mtp_disease <- read_tsv(file.path(input_dir,"mtp-diseases-mapping.tsv.gz"))
ID_type <- strsplit(mtp_disease$id,"_") %>%
  lapply(., `[[`, 1) %>%
  unlist() %>%
  unique()
`

`
> ID_type
 [1] "DOID"     "EFO"      "HP"       "MONDO"    "Orphanet" "GO"       "OBA"      "OTAR"     "OBI"      "OGMS"     "NCIT"     "MP"      
> 
`

This makes sense now. Approving.

**Comment by ewafula** [comment]
> 

@sangeetashukla, thank you for reviewing!

**Review by zzgeng — APPROVED** [review]
Look good to me! Approving!

**Comment by ewafula** [comment]
> Look good to me! Approving!

@zzgeng, thank you for reviewing!

**Pull request merged**
