### PR TITLE
update Table S1 - histologies README

### PR DESCRIPTION
**Pull request by jharenza**
#### What scientific question is your analysis addressing?
This PR adds/edits columns for v12 histologies and reruns the histologies file README script

#### What was your approach?
Added new columns and definitions, renamed old methylation columns to new values.

#### What GitHub issue does your pull request address?
NA

#### Which areas should receive a particularly close look?
Double check all columns exist in this file, nothing looks awry

#### Is there anything that you want to discuss further?
no

#### Is the analysis in a mature enough form that the resulting figure(s) and/or table(s) are ready for review?
yes

#### What types of results are included (e.g., table, figure)?
Excel table with histologies file readme

#### Reproducibility Checklist

- [ ] The dependencies required to run the code in this pull request have been added to the project Dockerfile.
- [ ] This analysis has been added to continuous integration.

#### Documentation Checklist

- [x] This analysis module has a `README` and it is up to date.
- [x] This analysis is recorded in the table in `analyses/README.md` and the entry is up to date.
- [x] The analytical code is documented and contains comments.

### CODE REVIEW

**Comment by zzgeng** [comment]
Four rows in readme do not match the columns in histologies file. 
I think we change `PFS_days` to `EFS_days`. 
Also, there are no longer `RF_purity_ABSOLUTE`, `RF_purity_ESTIMATE`, and  `RF_purity_LUMP`.

**Comment by jharenza** [comment]
Thanks so much for catching those @zzgeng ! Reran with the updates.

**Comment by jharenza** [comment]
@zzgeng this is ready for re-review

**Comment by sangeetashukla** [comment]
@jharenza I downloaded v12 data (had 1 checksum not match), and ran the script `tables/output_tables.Rmd`.
I used the `results/TableS1-histologies.xlsx` file to compare the column values from histologies.tsv 
I found `clinical_status_at_event` column present in the `histologies.tsv` file but missing in the excel.

**Review by sangeetashukla — CHANGES_REQUESTED** [review]
@jharenza I downloaded v12 data, and ran the script `tables/output_tables.Rmd`.
I used the `results/TableS1-histologies.xlsx` file to compare the column values from histologies.tsv 
I found `clinical_status_at_event` column present in the `histologies.tsv` file but missing in the excel.

**Comment by jharenza** [comment]
thanks so much @sangeetashukla - added, can you re-review?

**Review by sangeetashukla — APPROVED** [review]
@jharenza  Everything looks good now.

**Comment by jharenza** [comment]
Merging without checks, as this does not get run in GA

**Pull request merged**
