### PR TITLE
SNV frequencies module update

### PR DESCRIPTION
**Pull request by ewafula**
#### What scientific question is your analysis addressing?
- update the  `snv-frequencies` module to compute `all cohorts` and `each cohort` mutation frequencies using different independent samples created by the `independent-samples`  module 
- use the annotator from the `long-format-table-utils` module the  to add `Protein_RefSeq_ID` and `Gene_full_name` which were previously being added directly using the R `mygene` package

#### What was your approach?
Mutation frequencies of `all cohorts` are calculated using the following independent samples:
- `../../data/independent-specimens.wgswxspanel.primary.tsv`
- `../../data/independent-specimens.wgswxspanel.relapse.tsv`

Mutation frequencies of `each cohort` are calculated using the following independent samples:
- `../../data/independent-specimens.wgswxspanel.primary.eachcohort.tsv`
- `../../data/independent-specimens.wgswxspanel.relapse.eachcohort.tsv`

#### What GitHub issue does your pull request address?
- https://github.com/PediatricOpenTargets/ticket-tracker/issues/173
- https://github.com/PediatricOpenTargets/ticket-tracker/issues/137

#### Which areas should receive a particularly close look?
Check the update show the code section below of the `01-snv-frequencies.R` script
`lines 644 - 668`
```
# primary all cohorts independent sample data frame
primary_ac_indp_sdf <- read_tsv(
  file.path('../..', 'data',
            'independent-specimens.wgswxspanel.primary.tsv'),
  col_types = cols(
    .default = col_guess()))

# primary each cohorts independent sample data frame
primary_ec_indp_sdf <- read_tsv(
  file.path('../..', 'data',
            'independent-specimens.wgswxspanel.primary.eachcohort.tsv'),
  col_types = cols(
    .default = col_guess()))

# relapse all cohorts independent sample data frame
relapse_ac_indp_sdf <- read_tsv(
  file.path('../..', 'data',
            'independent-specimens.wgswxspanel.relapse.tsv'),
  col_types = cols(
    .default = col_guess()))

# relapse each cohorts independent sample data frame
relapse_ec_indp_sdf <- read_tsv(
  file.path('../..', 'data',
            'independent-specimens.wgswxspanel.relapse.eachcohort.tsv'),
```
` lines: 799 - 821`
```
    if(str_detect(cgcs_row$cohort, '&')) {
      # Call function for variant level all cohorts that have the cancer_group
      var_level_tbl <- get_cg_ch_var_level_mut_freq_tbl(
        maf_df, td_htl_dfs$overall_htl_df, td_htl_dfs$primary_ac_htl_df,
        td_htl_dfs$relapse_ac_htl_df, c_cancer_group, c_cohorts,
        pcb_pot_case_set_id_vec)
      # Call function for gene level all cohorts that have the cancer_group
      gene_level_tbl <- get_cg_ch_gene_level_mut_freq_tbl(
        maf_df, td_htl_dfs$overall_htl_df, td_htl_dfs$primary_ac_htl_df,
        td_htl_dfs$relapse_ac_htl_df, c_cancer_group, c_cohorts,
        pcb_pot_case_set_id_vec)
    }else{
      # Call function for variant level each cohort and cancer_group
      var_level_tbl <- get_cg_ch_var_level_mut_freq_tbl(
        maf_df, td_htl_dfs$overall_htl_df, td_htl_dfs$primary_ec_htl_df,
        td_htl_dfs$relapse_ec_htl_df, c_cancer_group, c_cohorts,
        pcb_pot_case_set_id_vec)
      # Call function for gene level each cohort and cancer_group
      gene_level_tbl <- get_cg_ch_gene_level_mut_freq_tbl(
        maf_df, td_htl_dfs$overall_htl_df, td_htl_dfs$primary_ec_htl_df,
        td_htl_dfs$relapse_ec_htl_df, c_cancer_group, c_cohorts,
        pcb_pot_case_set_id_vec)
    }
```
`lines: 854 - 866`
```
var_level_mut_freq_tbl <- annotate_long_format_table(
  var_level_mut_freq_tbl,
  columns_to_add = c(
    'EFO', 'MONDO',
    'RMTL', 'OncoKB_cancer_gene', 'OncoKB_oncogene_TSG',
    'Gene_full_name', 'Protein_RefSeq_ID'))

gene_level_mut_freq_tbl <- annotate_long_format_table(
  gene_level_mut_freq_tbl,
  columns_to_add = c(
    'EFO', 'MONDO',
    'RMTL', 'Gene_type', 'OncoKB_cancer_gene', 'OncoKB_oncogene_TSG',
    'Gene_full_name', 'Protein_RefSeq_ID'))
```

#### Is the analysis in a mature enough form that the resulting figure(s) and/or table(s) are ready for review?
YES

#### What types of results are included (e.g., table, figure)?
- `results/gene-level-snv-consensus-annotated-mut-freq.json.gz`
- `results/gene-level-snv-consensus-annotated-mut-freq.tsv.gz`
- `results/variant-level-snv-consensus-annotated-mut-freq.json.gz`
- `results/variant-level-snv-consensus-annotated-mut-freq.tsv.gz`

#### Reproducibility Checklist

- [x] The dependencies required to run the code in this pull request have been added to the project Dockerfile.
- [ ] This analysis has been added to continuous integration.

#### Documentation Checklist

- [x] This analysis module has a `README` and it is up to date.
- [ ] This analysis is recorded in the table in `analyses/README.md` and the entry is up to date.
- [x] The analytical code is documented and contains comments.

### CODE REVIEW

**Comment by ewafula** [comment]
Updated `ped_opentargets_2021_pedcbio_case_set_ids.json` from the `PedcBioPortal Web API` and regenerated results. Thanks, @logstar for reminding me!

**Review by runjin326 — COMMENTED** [review]
@ewafula, thanks so much for preparing the PR! All the changes make sense to me and I was able to re-run with no issues. 
I actually do have a question though for @logstar. For this file, `ped_opentargets_2021_pedcbio_case_set_ids.json`, as mentioned through the ticket that you linked, it is based on v7? But we are currently on V9 for the SNV data file. Would that ben an issue?

**Comment by logstar** [comment]
> I actually do have a question though for @logstar. For this file, `ped_opentargets_2021_pedcbio_case_set_ids.json`, as mentioned through the ticket that you linked, it is based on v7? But we are currently on V9 for the SNV data file. Would that ben an issue?

@runjin326 Thank you for checking. This is not an issue. The latest version of ped_opentargets_2021 dataset on pedcbio is based on v7 release.

**Comment by ewafula** [comment]
> @ewafula, thanks so much for preparing the PR! All the changes make sense to me and I was able to re-run with no issues. 
> 
> I actually do have a question though for @logstar. For this file, `ped_opentargets_2021_pedcbio_case_set_ids.json`, as mentioned through the ticket that you linked, it is based on v7? But we are currently on V9 for the SNV data file. Would that ben an issue? 

@runjin326,not sure if this is a solution though. I updated the file from PedcBioPortal using the instruction @logstar provided in the README and regenerated the results i in the last update of the PR.

**Comment by runjin326** [comment]
@logstar, @ewafula, thank you both for answering! I saw that the file has num of samples listed so I got confused since we added more samples in V8 - but actually these are not annotated in the final output so that is fine!
And I think we can keep using this file unless there are changes in the names of the cancer groups (or addition of cancer group), @logstar?

**Comment by jharenza** [comment]
Just want to comment (without looking at the output!)- we should use the v9 annotator here and add the additional samples from v8, but we will only have pedcbio links for PBTA, TARGET AML, TARGET NBL, and GMKF NBL (v7 samples).

**Comment by ewafula** [comment]
> Just want to comment (without looking at the output!)- we should use the v9 annotator here and add the additional samples from v8, but we will only have pedcbio links for PBTA, TARGET AML, TARGET NBL, and GMKF NBL (v7 samples). 

@jharenza, that what I did. Used the current annotator and updated pedcbio JSON file. May be am mistaken and more needs to be done! @logstar?

**Comment by jharenza** [comment]
Ok great!

**Review by runjin326 — APPROVED** [review]
Confirmed with @logstar that we are only using the names of cancer group from the PedcBio json file and since there is no change between v7 and v9 in terms of cancer group - there would be no compatibility issue! Approving now.
@ewafula, could you please do one last merge? Also, just to confirm, you have performed the lintr test as well, correct?

**Comment by logstar** [comment]
> Just want to comment (without looking at the output!)- we should use the v9 annotator here and add the additional samples from v8, but we will only have pedcbio links for PBTA, TARGET AML, TARGET NBL, and GMKF NBL (v7 samples).

@jharenza Thank you for checking.

The results will have v8 additional samples, if @ewafula used v9 release data to run the module. 

The annotator module uses any version of data that are in the `annotator/annotation-data` and `../../data` directory, so the annotator is not strictly versioned by release version. However, the current annotator may be incompatible with certain releases. For example, the current annotator module cannot use v7 data, due to the gene ENSG and symbol mapping file changes. If a new release has changes in the gene ENSG and symbol mapping file, the annotation data update script needs to be rerun. The release v9 did not change the mapping file, so the annotation data do not need to be updated.

**Pull request merged**
