### PR TITLE
Generate isoform rsem matrix

### PR DESCRIPTION
**Pull request by sangeetashukla**
### Purpose/implementation Section
Use the merged isoform file for all cohorts and clean it up for downstream use.

#### What was your approach?
Create an Isoform expression table of TPM values using Isoform Ensembl IDs as rows, and KF Biospecimen IDs as columns.

#### What GitHub issue does your pull request address?
[Issue 339](https://github.com/PediatricOpenTargets/ticket-tracker/issues/339)

#### Which areas should receive a particularly close look?
The ENST IDs have not be used as rowname labels in the result file, since they are not unique.

#### Is there anything that you want to discuss further?
The `results\non_unique_enst_ids.tsv` file contains 158 ENST_IDs that were found duplicated. We should investigate how and why duplication exists, and if/how it can be fixed.

#### Is the analysis in a mature enough form that the resulting figure(s) and/or table(s) are ready for review?
Yes

#### What types of results are included (e.g., table, figure)?
One table in `results\rna-isoform-expression-rsem-tpm_out.rds` and a list of duplicated ENST IDs in `results\non_unique_enst_ids.tsv`

#### What is your summary of the results?
The merged isoform data is cleaned up to create a new table with the transcript id, and enst id in separate columns, for each sample id.

#### Reproducibility Checklist

- [ ] The dependencies required to run the code in this pull request have been added to the project Dockerfile.
- [ ] This analysis has been added to continuous integration.

#### Documentation Checklist

- [x] This analysis module has a `README` and it is up to date.
- [ ] This analysis is recorded in the table in `analyses/README.md` and the entry is up to date.
- [ ] The analytical code is documented and contains comments.

### CODE REVIEW

**Review by jharenza — CHANGES_REQUESTED** [review]
@sangeetashukla can you please update this to use the data release? Your base branch will be v11-release. The input file will come from data and not input. Thanks!

**Comment by sangeetashukla** [comment]
> @sangeetashukla can you please update this to use the data release? Your base branch will be v11-release. The input file will come from data and not input. Thanks!

Got it, I will make the changes

**Comment by sangeetashukla** [comment]
> > @sangeetashukla can you please update this to use the data release? Your base branch will be v11-release. The input file will come from data and not input. Thanks!
> 
> @jharenza  Got it, I will make the changes

**Comment by jharenza** [comment]
Noting that the duplicated transcript ids are actually `PAR_Y` transcripts - those are psuedoautosomal regions, so there is a copy of the transcript in the mapped region and in a PAR. Those can just be removed and then the transcript rows uniqued. In addition, if we merge these in the beginning without gene symbols, which I will propose, then this is not required. Closing so that this is handled upstream in data preparation.

**Pull request closed without merging**
