### PR TITLE
Update SNV frequencies module

### PR DESCRIPTION
**Pull request by ewafula**
#### What scientific question is your analysis addressing?
- Rename SNV frequencies table headers 

#### What GitHub issue does your pull request address?
- https://github.com/PediatricOpenTargets/ticket-tracker/issues/252

#### Which areas should receive a particularly close look?
Confirm that the result tables now have the required header names

#### Is there anything that you want to discuss further?
No

#### Is the analysis in a mature enough form that the resulting figure(s) and/or table(s) are ready for review?
Yes

#### What types of results are included (e.g., table, figure)?
TSV and JSONL tables

#### What is your summary of the results?
- results/gene-level-snv-consensus-annotated-mut-freq.tsv.gz
- results/gene-level-snv-consensus-annotated-mut-freq.jsonl.gz
- results/variant-level-snv-consensus-annotated-mut-freq.tsv.gz
- results/variant-level-snv-consensus-annotated-mut-freq.jsonl.gz

#### Reproducibility Checklist

- [x] The dependencies required to run the code in this pull request have been added to the project Dockerfile.
- [ ] This analysis has been added to continuous integration.

#### Documentation Checklist

- [x] This analysis module has a `README` and it is up to date.
- [ ] This analysis is recorded in the table in `analyses/README.md` and the entry is up to date.
- [x] The analytical code is documented and contains comments.

### CODE REVIEW

**Review by runjin326 — APPROVED** [review]
@ewafula , thanks so much for preparing this - the code changes make sense and the results headers are changed correctly (i.e., as requested). 
One thing I noticed is that the output files have different number of lines as compared to the previous results - which is not expected.
image
I am guessing you used a new histologies file? (with the cancer group updated?) I then checked the number for gene table and the changes are indeed from those cancer group changes. 
```
> combined %>% filter(is.na(old_Freq) | is.na(new_Freq) | old_Freq != new_Freq) 
                                          . old_Freq new_Freq
1 Metastatic secondary tumors;Neuroblastoma     1057       NA
2                             Neuroblastoma    37244    38394
```
Similarly, for the variant table, the numbers checked out as well:
```
> combined2 %>% filter(is.na(old_Freq) | is.na(new_Freq) | old_Freq != new_Freq) 
                                          . old_Freq new_Freq
1 Metastatic secondary tumors;Neuroblastoma     1131       NA
2                             Neuroblastoma   202873   205123
```

**Comment by runjin326** [comment]
@ewafula, I approved this before but as I am thinking about this more - the number changes are actually a bit unexpected. Let's say none of the variants in `Metastatic secondary tumors;Neuroblastoma` are present in the original `Neuroblastoma`, then the maximum addition of entries will be 1057 or 1131 respectively - but now we are seeing more, which puzzles me. 
Can you look into where those discrepancies come about? Are there any other new files that you used? Thanks!

**Comment by ewafula** [comment]
@runjin326, then it seems I must have run the the previous frequencies table before the updates in cancer_groups. That is the v10 histologies file I have in my local repo of OpenPedCan.

**Comment by runjin326** [comment]
> @runjin326, then it seems I must have run the the previous frequencies table before the updates in cancer_groups. That is the v10 histologies file I have in my local repo of OpenPedCan.

If you ran with the old histologies file, then there should still be `Metastatic secondary tumors;Neuroblastoma` right? But that is not present in the current table - so you should've ran with histologies with cancer group changed. Additionally, there are more entries in the table too - could you please do a `setoff` (or similar function) to see where the discrepancies come from? Thanks!

**Comment by ewafula** [comment]
> > @runjin326, then it seems I must have run the the previous frequencies table before the updates in cancer_groups. That is the v10 histologies file I have in my local repo of OpenPedCan.
> 
> If you ran with the old histologies file, then there should still be `Metastatic secondary tumors;Neuroblastoma` right? But that is not present in the current table - so you should've ran with histologies with cancer group changed. Additionally, there are more entries in the table too - could you please do a `setoff` (or similar function) to see where the discrepancies come from? Thanks!

@runjin326,  all these additional records are stemming from the update in the histologies file changing `cancer_group` from `Metastatic secondary tumors;Neuroblastoma` to `Neuroblastoma` for PBTA cohort. As a result, there are additional Neuroblastoma variants records for `All cohort` (combinations between/among PBTA, GMKF, and TARGET ) in both CNV and SNV frequencies tables. PBTA cohort itself does not have the `Neuroblastoma` entries in frequencies tables because samples are not > 3.

**Review by runjin326 — APPROVED** [review]
@ewafula, thanks for looking into that - yes, it then all makes sense. Approving now.

**Comment by runjin326** [comment]
@ewafula, could you please do another dev merge for this branch as well? Will merge right after that.

**Comment by ewafula** [comment]
@runjin326,  done dev merging.

**Pull request merged**
