### PR TITLE
[Update annotator for v7 Part 3] Add GTEx tissue UBERON annotation columns

### PR DESCRIPTION
**Pull request by logstar**
### Purpose/implementation Section

Update `long-format-table-utils/annotator` submodule for [v7 data release](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/pull/61).

Add the following input column -> annotation column mappings using v7 `uberon-map-gtex-group.tsv` and `uberon-map-gtex-subgroup.tsv`:

- `GTEx_tissue_group` -> `GTEx_tissue_group_UBERON`
- `GTEx_tissue_subgroup` -> `GTEx_tissue_subgroup_UBERON`

#### What was your approach?

Changed the `annotate_long_format_table` function in `long-format-table-utils/annotator/annotator-api.R`, so the function can add `GTEx_tissue_group_UBERON` and `GTEx_tissue_subgroup_UBERON` annotation columns, based on input `GTEx_tissue_group` and `GTEx_tissue_subgroup` columns respectively . The default `columns_to_add` parameter value is **not** changed, in order to be backward compatible.

Changed the help message of `-c`/`--columns-to-add` option `long-format-table-utils/annotator/annotator-cli.R` to include `GTEx_tissue_group_UBERON` and `GTEx_tissue_subgroup_UBERON` as available annotation columns.

Added descriptions in `README.md` for the `GTEx_tissue_group_UBERON` and `GTEx_tissue_subgroup_UBERON` annotation columns.

Added tests for the `GTEx_tissue_group_UBERON` and `GTEx_tissue_subgroup_UBERON` annotation columns.

#### What GitHub issue does your pull request address?

<https://github.com/PediatricOpenTargets/ticket-tracker/issues/132>

#### Which areas should receive a particularly close look?

Do the changes in `analyses/long-format-table-utils/annotator/annotator-api.R` make sense?

Are the annotations in `analyses/long-format-table-utils/annotator/tests/test_data/v7_inspected_annotated_test_long_format_table.tsv` correct? All additional tests in this PR rely on the correctness of the annotations.

#### Is there anything that you want to discuss further?

No

#### Is the analysis in a mature enough form that the resulting figure(s) and/or table(s) are ready for review?

Yes

#### What types of results are included (e.g., table, figure)?

No result

#### What is your summary of the results?

NA

#### Reproducibility Checklist

- [x] The dependencies required to run the code in this pull request have been added to the project Dockerfile.
- [NA] This analysis has been added to continuous integration.

#### Documentation Checklist

- [x] This analysis module has a `README` and it is up to date.
- [x] This analysis is recorded in the table in `analyses/README.md` and the entry is up to date.
- [x] The analytical code is documented and contains comments.

### CODE REVIEW

**Comment by logstar** [comment]
@jharenza @NHJohnson In the last commit <https://github.com/PediatricOpenTargets/OpenPedCan-analysis/pull/71/commits/58b2550c48581b0ea096898df247ce77650be95d>, I changed the remaining `ensg-hugo-rmtl-v1-mapping.tsv` filenames to `ensg-hugo-rmtl-mapping.tsv` in `annotator/download-annotation-data.R`, `long-format-table-utils/README.md`, and `analyses/README.md`. Sorry that I missed these files in PR <https://github.com/PediatricOpenTargets/OpenPedCan-analysis/pull/66>. Meanwhile, in `analyses/README.md`, I also added `data/uberon-map-gtex-group.tsv` and `data/uberon-map-gtex-subgroup.tsv` as input files for `long-format-table-utils` module.

The `analyses/long-format-table-utils/run-update-long-format-table-utils.sh` now runs well in the Docker image/container, and the `annotator/annotation-data/ensg-gene-full-name-refseq-protein.tsv` file is reproduced identically.

```text
$ bash analyses/long-format-table-utils/run-update-long-format-table-utils.sh
Update annotator data...
Retrieve Gene_full_name and Protein_RefSeq_ID from mygene.info...
Querying chunk 1
Querying chunk 2
...
Querying chunk 57
Querying chunk 58
Querying chunk 59
Finished
Done running download-annotation-data.R
Done running run-download-annotation-data.sh
Done running update-long-format-table-utils.sh
```

**Review by NHJohnson — APPROVED** [review]
Thanks for this update!

Added code and comments look good. 

All tests pass within container.

`run-update-long-format-table-utils.sh` runs within container. `ensg-gene-full-name-refseq-protein.tsv` looks reasonable. Input annotations in `v7_inspected_annotated_test_long_format_table.tsv` also appear reasonable but not deeply investigated.

**Comment by logstar** [comment]
Thank you for reviewing and test-running this PR @NHJohnson !

**Comment by logstar** [comment]
I have just merged the latest dev branch to this PR. All tests passed. `run-update-long-format-table-utils.sh` reproduced `analyses/long-format-table-utils/annotator/annotation-data/ensg-gene-full-name-refseq-protein.tsv` identically.

I will merge this PR shortly.

**Pull request merged**
