### PR TITLE
Update 01-cnv-frequencies.py

### PR DESCRIPTION
**Pull request by adilahiri**
Made changes to independent specimen file names. Used WGS.

#### What scientific question is your analysis addressing?
Update the independent specimen filenames to match those in the V11 data.

#### What was your approach?
Changed the files names in lines 33 to 36 of the `01-cnv-frequencies.py` file. . The file names were derived from this [page](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/tree/dev/analyses/independent-samples).
I searched for matching file names as in the V10 data and replaced the names with closest matching WGS files. 

#### What GitHub issue does your pull request address?
[Issue #363](https://github.com/PediatricOpenTargets/ticket-tracker/issues/363)

### Directions for reviewers. Tell potential reviewers what kind of feedback you are soliciting.
The changes are reflected in lines 33 to 36 of the `01-cnv-frequencies.py` file.  Please note I have used WGS files , if WXS files need to be used please let me know. 

#### Which areas should receive a particularly close look?
 Lines 33 to 36 of the `01-cnv-frequencies.py` file. 

#### Is there anything that you want to discuss further?
Is there a file to file mapping between the data releases ?

#### Is the analysis in a mature enough form that the resulting figure(s) and/or table(s) are ready for review?
The analysis could not be run on my personal computer, so it needs to be rerun on the server. 

#### What types of results are included (e.g., table, figure)?
Tables

#### What is your summary of the results?
The results (tables) files are unchanged as the analysis could not be run. 

#### Reproducibility Checklist

- [ ] The dependencies required to run the code in this pull request have been added to the project Dockerfile.
- [ ] This analysis has been added to continuous integration.

#### Documentation Checklist

- [ ] This analysis module has a `README` and it is up to date.
- [ ] This analysis is recorded in the table in `analyses/README.md` and the entry is up to date.
- [ ] The analytical code is documented and contains comments.

### CODE REVIEW

**Comment by ewafula** [comment]
@adilahiri, I am not sure what is happing here. I checked out your PR branch listed (git branch -r) as `origin/v11-cnv-tables`. Have successfully pushed the updates back, but they don't appear here. Is the listed branch different from this one?  When I checkout the `v11-cnv-tables`  branch on another local repo, am getting the code with my updates.  Any idea what is happening?

**Comment by ewafula** [comment]
@adilahiri, you seem to have submitted two different PRs. The one listed that can be checked out and I have updated is different from this one.  Not sure why it does not appear under the PR tab

https://github.com/PediatricOpenTargets/OpenPedCan-analysis/tree/v11-cnv-tables/analyses/cnv-frequencies

**Comment by ewafula** [comment]
@jharenza, the v11 `cnv-frequencies` module  results are on S3 Bucket in that `mtp-tables` folder run by the code in the branch:
https://github.com/PediatricOpenTargets/OpenPedCan-analysis/tree/v11-cnv-tables/analyses/cnv-frequencies

**Comment by adilahiri** [comment]
@ewafula I think I know what the issue is here. I submitted this PR using the branch created from my forked repo (adilahiri/Openpedcan-analysis).   The branch you worked belongs to PediatricOpenTargets/OpenPedCan-analysis.  The commits you made are reflected there.  

I named the branches the same on both my repo and the official repo. However, the changes I made were same in both. I was having issues with permissions while submitting a PR from the branch belonging to PediatricOpenTargets/OpenPedCan-analysis, so I decided to submit this PR from the forked repo. I hope this makes sense. 

Please note the commit are visible to me on the official repo.

**Comment by ewafula** [comment]
Thank you, @adilahiri for working on this. I wasn't sure if you could pull the changes I made to your local branch. You might need to if more updates are need on the module after review. Otherwise module looks to me and works well with the v10 data release.

**Pull request closed without merging**
