### PR TITLE
add uwot to Dockerfile

### PR DESCRIPTION
**Pull request by kgaonkar6**
#### What scientific question is your analysis addressing?
Adding uwot to dockerfile since it is required for RNAseq batch correction module
Also to test if GHA can test build docker image

### CODE REVIEW

**Comment by komalsrathi** [comment]
Looks ok to me, unless there is another package that can be used for umap plots? We have been using uwot for PNOC008.

**Review by komalsrathi — APPROVED** [review]

**Comment by jharenza** [comment]
> Looks ok to me, unless there is another package that can be used for umap plots? We have been using uwot for PNOC008.

Ah, looks like we've been using Rtsne for tsne and umap for umap. Maybe we should add those instead and source these functions?

https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/master/analyses/transcriptomic-dimension-reduction/util/dimension-reduction-functions.R

**Comment by komalsrathi** [comment]
@jharenza sure, I can make that change to be consistent with OpenPBTA analysis - the batch correction PR is still a draft so I can make that change once I start finalizing the module? I am not sure why I picked `uwot` over `umap` - we needed some nearest neighbor analysis done for 008 so that might be the case. 

Is there anything else you need from my side to close this?

**Comment by jharenza** [comment]
Ok, let's close this and you can add with the batch correction module. Thanks!

**Comment by kgaonkar6** [comment]
Just wanted to drop in here to say that any Dockerfile update should go in before the module that needs the update. So when you are ready to put in the batch correction PR  (and still need uwot package) you will do the following:
1) put in a Dockerfile update PR -> merge to dev ( where the dockerfile will be built and pushed to docker hub)
2) pull the updated docker image -> run the module

**Pull request closed without merging**
