### PR TITLE
refactor independent samples modules

### PR DESCRIPTION
**Pull request by komalsrathi**
### Purpose/implementation Section

Update and simplify the independent sample selection

#### What scientific question is your analysis addressing?

Generate WGS-only, WGS-preferred and WXS-preferred lists.

#### What was your approach?

The idea implemented here is simple:

After randomizing the histology file, subset to tumor samples:

```
tumor_samples <- histology_df %>%
  dplyr::filter(sample_type == "Tumor", 
                composition == "Solid Tissue" | composition == "Bone Marrow", 
                experimental_strategy %in% c("WGS", "WXS", "Targeted Sequencing"))
```

For `WGS-preferred` lists: we first subset the **tumor samples** to `WGS` samples only, pass the subsetted samples to the `independent-samples.R` function to generate a `WGS-specific` list. This list only contains a single occurence of `Kids_First_Participant_ID` associated to the `experimental_strategy = WGS`. Next, we subset the **tumor samples** to `WXS and Targeted Sequencing` samples only, pass the subsetted samples to the `independent-samples.R` function to generate a `WXS/Panel specific` list. This list only contains a single occurence of `Kids_First_Participant_ID` associated to either `experimental_strategy = WXS` or `experimental_strategy = Targeted Sequencing`. Then we merge the two lists generated above i.e. 1. `WGS-specific list` and 2. `WXS/Panel specific list` keeping `WGS` list first and `WXS/Panel` as second and take a `dplyr::distinct` to only get the first occurence of `Kids_First_Participant_ID`. 
Because we keep the `WGS-specific list` first when calling `dplyr::distinct`, the `WGS` associated biospecimens will be preferred over other biospecimens for multiple occurrences of `Kids_First_Participant_ID`.

**For each cohort:** post-merge `dplyr::distinct` is called using `Kids_First_Participant_ID + cohort`
**For all cohorts**: post-merge `dplyr::distinct` is called using only `Kids_First_Participant_ID` 

For `WXS-preferred` lists: Same approach as above.

Using this approach we will be sure to not miss any bio-specimens associated with a participant id.

**Screenshot of numbers from `03-qc-independent-samples.nb.html`:** Here it tells you that for the `all-cohort` files the `total_number_of_rows` == `number_of_unique_Kids_First_Participant_ID` which shows there is no duplication.

Screen Shot 2021-09-24 at 9 41 38 AM
Screen Shot 2021-09-24 at 9 41 31 AM
Screen Shot 2021-09-24 at 9 41 23 AM

#### What GitHub issue does your pull request address?

https://github.com/PediatricOpenTargets/ticket-tracker/issues/193

#### Which areas should receive a particularly close look?

- [x] Feasibility of the approach
- [x] I have split the single script into three: WGS-only, WGS-preferred and WXS-preferred because it was getting long and messy.
- [ ] I have also added `cohort`, `cancer_group`,	 `experimental_strategy`, and `tumor_descriptor` columns to the output `.tsv` files in addition to `Kids_First_Participant_ID` and `Kids_First_Biospecimen_ID` because it is easier for quickly looking up and debugging.
- [x] The `03-qc-independent-samples.nb.html` now contains total rows and number of unique `Kids_First_Participant_ID` in each file for each of the analysis type i.e. WGS-only, WGS-preferred and WXS-preferred for easy lookup and comparisons.
- [ ] Wasn't sure if we needed to refactor the RNA-seq lists.

#### Is there anything that you want to discuss further?

N/A

#### Is the analysis in a mature enough form that the resulting figure(s) and/or table(s) are ready for review?

Yes

#### What types of results are included (e.g., table, figure)?

Tables of each-cohort and all-cohorts for each of the analysis type mentioned above 

#### What is your summary of the results?

TBD

#### Reproducibility Checklist

- [x] The dependencies required to run the code in this pull request have been added to the project Dockerfile.
- [x] This analysis has been added to continuous integration.

#### Documentation Checklist

- [x] This analysis module has a `README` and it is up to date.
- [x] This analysis is recorded in the table in `analyses/README.md` and the entry is up to date.
- [x] The analytical code is documented and contains comments.

### CODE REVIEW

**Comment by komalsrathi** [comment]
@logstar @runjin326 I opened this new PR because so as to not make the other PR long and messy. The approach I took is discussed in the PR but I am open to having a quick call to discuss the feasibility of this approach. If this does not look like what we wanted, we can close this.

**Comment by runjin326** [comment]
> @logstar @runjin326 I opened this new PR because so as to not make the other PR long and messy. The approach I took is discussed in the PR but I am open to having a quick call to discuss the feasibility of this approach. If this does not look like what we wanted, we can close this.

Hey @komalsrathi, thanks so much for opening this! I agree, a clean new PR is better. I am looking at your approach of filtering based on `experimental_strategy` and I think this might cause an issue of duplicated samples. For example, 
```
WGS  Participant1 Biospecimen1 PBTA
WXS Participant1 Biospecimen2 PBTA
``` 
will be called twice - which is not what we want. The idea of preferring WGS is to select WGS when both WGS and WXS are present but only choose one. 

But I think it is actually a great idea to separate baes off experimental strategy and generate two lists. What we can do then is separate them the same, but keep `cohort` column as well. 

From the combined list, we can do some cleanup from there to generate what we want: 
1) for each cohort method, for each participant, we compare the `cohort` of WXS+Panel to the `cohort` of WGS - if (all_of(WXS+Panel$cohort %in% WGS$cohort)), we remove all WXS+Panel biospecimens; if not the same, the sample with different cohort will be remained
2) for all cohort method, for each participant, we remove all  WXS+Panel biospecimen that have a chosen WGS already
3) remove the cohort column after this to make the 

I actually think your method should have taken cared of the tumor descriptor issue we had before (since independent is called based on experimental strategy and this solves the issue when different experimental strategy is different tumor descriptor) so maybe do a re-run after implementing the above and I think we should be set!

**Comment by komalsrathi** [comment]
> ```
> WGS  Participant1 Biospecimen1 PBTA
> WXS Participant1 Biospecimen2 PBTA
> ```

**For WGS-preferred**: I am taking a distinct on `Kids_First_Participant_ID` for all-cohorts and a distinct on `Kids_First_Participant_ID` + `cohort` for each-cohort after combining the WGS-specific list + WXS/Panel-specific list. 

Example:
Each-cohort: https://github.com/PediatricOpenTargets/OpenPedCan-analysis/blob/ind-samples-update/analyses/independent-samples/01-generate-independent-specimens-wgs-preferred.R#L58-L65

All-cohorts: https://github.com/PediatricOpenTargets/OpenPedCan-analysis/blob/ind-samples-update/analyses/independent-samples/01-generate-independent-specimens-wgs-preferred.R#L84-L91

**For WXS-preferred**: I am taking a distinct on `Kids_First_Participant_ID` for all-cohorts and a distinct on `Kids_First_Participant_ID` + `cohort` for each-cohort after combining the WXS-specific list + WGS/Panel-specific list. 

Example:
Each-cohort: https://github.com/PediatricOpenTargets/OpenPedCan-analysis/blob/ind-samples-update/analyses/independent-samples/01-generate-independent-specimens-wxs-preferred.R#L58-L65

All-cohorts: https://github.com/PediatricOpenTargets/OpenPedCan-analysis/blob/ind-samples-update/analyses/independent-samples/01-generate-independent-specimens-wxs-preferred.R#L84-L91

Can you also look at the `03-qc-independent-samples.nb.html` file? It tells you that for the `all-cohort` files the `total_number_of_rows == number_of_unique_Kids_First_Participant_ID` which makes sense. (P.S. I added the screenshots of the tables in the PR description)

**Review by runjin326 — APPROVED** [review]
@komalsrathi, oh I see! Another `distinct` was called after combing the two lists! That makes sense - and the code now is so much cleaner! Sorry I missed that part!
And yes, 03 is super helpful - and it seems like all our concerns were resolved. Thank you so much for preparing this!

**Review by logstar — APPROVED** [review]
@komalsrathi Thank you for refactoring the independent samples module.

The new independent sample selection procedures look good to me. Regarding the issues we discussed previously, they are both addressed in this PR. Independent biospecimens of different `experimental_strategies` and `tumor_descriptors` are selected separately, so no patient is missed. The selected biospecimens are combined, and biospecimens with the same patient IDs are further selected to keep only one for one patient ID or one (patient ID, cohort) for all-cohorts and each-cohort respectively, so that all-cohorts lists will only have one biospecimen for one patient ID, and each-cohort lists will have only one biospecimen for one (patient ID, cohort).

I also reproduced the result TSV files identically.

**Comment by runjin326** [comment]
@komalsrathi, not sure if you have done that already, but if not, could you please pull the most up-to-date `dev`, do a merge to the branch so that we can merge? thanks!

**Comment by komalsrathi** [comment]
@runjin326 I think the latest changes are all in this branch:

```
➜  independent-samples git:(ind-samples-update) git checkout dev
Switched to branch 'dev'
Your branch is up to date with 'origin/dev'.
➜  independent-samples git:(dev) git pull origin dev
From github.com:PediatricOpenTargets/OpenPedCan-analysis
 * branch            dev        -> FETCH_HEAD
Already up to date.
➜  independent-samples git:(dev) git checkout ind-samples-update 
Switched to branch 'ind-samples-update'
➜  independent-samples git:(ind-samples-update) git merge origin/dev
Already up to date.
```

**Comment by runjin326** [comment]
> @runjin326 I think the latest changes are all in this branch:
> 
> ```
> ➜  independent-samples git:(ind-samples-update) git checkout dev
> Switched to branch 'dev'
> Your branch is up to date with 'origin/dev'.
> ➜  independent-samples git:(dev) git pull origin dev
> From github.com:PediatricOpenTargets/OpenPedCan-analysis
>  * branch            dev        -> FETCH_HEAD
> Already up to date.
> ➜  independent-samples git:(dev) git checkout ind-samples-update 
> Switched to branch 'ind-samples-update'
> ➜  independent-samples git:(ind-samples-update) git merge origin/dev
> Already up to date.
> ```

Cool! Merging now!

**Pull request merged**
