### PR TITLE
Add script to download methyl files

### PR DESCRIPTION
**Pull request by zzgeng**
#### What scientific question is your analysis addressing?
Add script to download v13 methylation-related files from AWS

#### What was your approach?
add `download_methyl.sh` in script folder. 

#### Which areas should receive a particularly close look?
script/download_methyl.sh

#### Is there anything that you want to discuss further?
No

#### What types of results are included (e.g., table, figure)?
bash script

#### Reproducibility Checklist

- [x] The dependencies required to run the code in this pull request have been added to the project Dockerfile.
- [x] This analysis has been added to continuous integration.

#### Documentation Checklist

- [x] This analysis module has a `README` and it is up to date.
- [x] This analysis is recorded in the table in `analyses/README.md` and the entry is up to date.
- [x] The analytical code is documented and contains comments.

### CODE REVIEW

**Review by jharenza — CHANGES_REQUESTED** [review]
Few notes:
1. If directory does not exist, this will fail. Can you add a chunk to check?
2. Can you make the script name `download-methyl.sh` with hyphen to conform to other script names?
3. Can you add a bit in the readme about this new script, what it is, how to download?

**Comment by jharenza** [comment]
@rjcorb I made some updates, can you test this on your end, esp since you do not have v13 on your computer currently?

**Comment by rjcorb** [comment]
@zzgeng @jharenza this runs fine when run within the `scripts` directory. But there are inconsistencies in which directories different `scripts/` bash files need to be run from. For example, `download-testing-files.sh` needs to be run from root and not `scripts/`. I think following the code in `scripts/generate-analysis-files.sh` would allow this to be run from any directory: 

```
# Set the working directory to the directory of this file
cd "$(dirname "${BASH_SOURCE[0]}")"

# If RUN_LOCAL is used, the time-intensive steps are skipped because they cannot
# be run on a local computer -- the idea is that setting RUN_LOCAL=1 will allow for
# local testing running/testing of all other steps
RUN_LOCAL=${RUN_LOCAL:-0}

# Get base directory of project
cd ..
BASEDIR="$(pwd)"
cd -
```

**Comment by zzgeng** [comment]
> @zzgeng @jharenza this runs fine when run within the `scripts` directory. But there are inconsistencies in which directories different `scripts/` bash files need to be run from. For example, `download-testing-files.sh` needs to be run from root and not `scripts/`. I think following the code in `scripts/generate-analysis-files.sh` would allow this to be run from any directory:
> 
> ```
> # Set the working directory to the directory of this file
> cd "$(dirname "${BASH_SOURCE[0]}")"
> 
> # If RUN_LOCAL is used, the time-intensive steps are skipped because they cannot
> # be run on a local computer -- the idea is that setting RUN_LOCAL=1 will allow for
> # local testing running/testing of all other steps
> RUN_LOCAL=${RUN_LOCAL:-0}
> 
> # Get base directory of project
> cd ..
> BASEDIR="$(pwd)"
> cd -
> ```

That's a very good suggestion! I've made changes accordingly. Thank you!

**Review by rjcorb — APPROVED** [review]

**Comment by jharenza** [comment]
Agree- Thanks @rjcorb

**Pull request merged**
