### PR TITLE
Update Repository README - docker, GA, tables, DGD

### PR DESCRIPTION
**Pull request by jharenza**
#### What scientific question is your analysis addressing?

NA

#### What was your approach?
This PR updates the analysis repo README. Several things were out of date:
- DGD was missing
- Additional PBTA mention was missing
- Tables were v10

- I removed all CI-related wording and updated to GA where necessary.
- I updated docker commands and include information on using EC2 for development, as well as running RStudio from EC2.

#### What GitHub issue does your pull request address?

NA

#### Which areas should receive a particularly close look?
- note to self: make sure table of contents renders
- make sure everything looks good

#### Is there anything that you want to discuss further?
no

#### Is the analysis in a mature enough form that the resulting figure(s) and/or table(s) are ready for review?
yes

#### Reproducibility Checklist

- [ ] The dependencies required to run the code in this pull request have been added to the project Dockerfile.
- [ ] This analysis has been added to continuous integration.

#### Documentation Checklist

- [ ] This analysis module has a `README` and it is up to date.
- [ ] This analysis is recorded in the table in `analyses/README.md` and the entry is up to date.
- [ ] The analytical code is documented and contains comments.

### CODE REVIEW

**Review by adilahiri — COMMENTED** [review]
@jharenza: the changes look good, thank you for making them. 
1. DGD CHOP P30 Panel has been included in the `readme`. 
2. Additional PBTA mentioned within the `readme`.
3. Tables are rendering and website links work. 
4.  v10 Mentions changed to v11.  
**Potential change** : Do we need  to update Line 35 with respect to V11 data ?
"OpenPedCan project includes 10414 TCGA RNA-Seq samples (716 normal and 9698 tumor) from 33 cancer types in the v10 release.”
5. CI wording: **Potential change** : Line 41: Continous integration may need to be changed to GA ? “The maintainers have set up continuous integration software to confirm the reproducibility of analyses within the project’s Docker container.”
6. EC2 instructions are fine.

**Comment by jharenza** [comment]
Thanks @adilahiri - updated 4 and 5 with the latest commit.

**Review by adilahiri — APPROVED** [review]
Looks good :)

**Comment by jharenza** [comment]
Thanks - merging without checks, documentation update only.

**Pull request merged**
