### PR TITLE
update MB SHH abridged output

### PR DESCRIPTION
**Pull request by rjcorb**
#### What scientific question is your analysis addressing?

This PR updates the `molecular-subtyping-MB` analysis module to remove non-relevant columns from abridged output generated by `05-subtype-mb-shh.R`. 

#### What was your approach?

Removed `SHH_subtype` column from `mb_shh_molecular_subtypes.tsv`, since `molecular_subtype` column contains complete information on SHH subtype classification. 

#### What GitHub issue does your pull request address?

#599 

#### Reproducibility Checklist

- [x] The dependencies required to run the code in this pull request have been added to the project Dockerfile.
- [ ] This analysis has been added to continuous integration.

#### Documentation Checklist

- [x] This analysis module has a `README` and it is up to date.
- [x] This analysis is recorded in the table in `analyses/README.md` and the entry is up to date.
- [x] The analytical code is documented and contains comments.

### CODE REVIEW

**Review by jharenza — COMMENTED** [review]
hi @rjcorb are the mutation calls being removed expected here?

**Comment by rjcorb** [comment]
@jharenza I reran the script and am still getting those changes to `mb_shh_subtypes_w_molecular_data.tsv`. For those biospecimen IDs that went from non-NA csq to `NA`, I don't see those IDs in either maf file. So I'm not sure how non-NA csqs were ever reported in those cases...

**Review by jharenza — COMMENTED** [review]
I am not sure what is happening, but when I run this, I get the former result, with the non-NA results.

Line 109 for example:
Screenshot 2024-08-15 at 6 20 30 PM

**Comment by jharenza** [comment]
checks should all pass now, but can you double check re: my comments above - is your data linked to v15, not testing or something odd by chance?

**Review by jharenza — APPROVED** [review]
@rjcorb I just reran the full module and committed results so we are all set on this now

**Comment by jharenza** [comment]
module of interest passed checks

**Pull request merged**
