### PR TITLE
[Update annotator for v7 Part 2] Only require columns that need to be joined by

### PR DESCRIPTION
**Pull request by logstar**
### Purpose/implementation Section

Update `long-format-table-utils/annotator` submodule for [v7 data release](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/pull/61).

- Only require columns that need to be joined by the input table and annotation table. This would handle GTEx->Uberon mapping and Disease/cancer_group->EFO/MONDO mapping without providing both GTEx and Disease columns, so it would be convenient for the developers of analysis modules that only have Disease column or GTEx column.

#### What was your approach?

Changed `long-format-table-utils/annotator/annotator-api.R`, so the `annotate_long_format_table` function only checks that the input `long_format_table` contains the character columns that need to be joined by to add specified `columns_to_add` parameter.

Updated descriptions and examples in README.md for only requiring columns that need to be joined by in annotator API and CLI.

Added tests for only requiring columns that need to be joined by.

#### What GitHub issue does your pull request address?

<https://github.com/PediatricOpenTargets/ticket-tracker/issues/132>

#### Which areas should receive a particularly close look?

Do the changes in `analyses/long-format-table-utils/annotator/annotator-api.R` make sense?

#### Is there anything that you want to discuss further?

No

#### Is the analysis in a mature enough form that the resulting figure(s) and/or table(s) are ready for review?

Yes

#### What types of results are included (e.g., table, figure)?

No result

#### What is your summary of the results?

NA

#### Reproducibility Checklist

- [x] The dependencies required to run the code in this pull request have been added to the project Dockerfile.
- [NA] This analysis has been added to continuous integration.

#### Documentation Checklist

- [x] This analysis module has a `README` and it is up to date.
- [x] This analysis is recorded in the table in `analyses/README.md` and the entry is up to date.
- [x] The analytical code is documented and contains comments.

### CODE REVIEW

**Review by NHJohnson — COMMENTED** [review]
Thanks for these updates! I am getting some errors running the tests in the Docker container. Some examples are:
```
test_annotate_long_format_table.R:62: failure: (unknown)
annotate_long_format_table(long_format_tibble) not equal to `inspected_annotated_long_format_tibble`.
Rows in x but not y: 6, 5, 4, 3, 2. Rows in y but not x: 6, 5, 4, 3, 2. 

test_annotate_long_format_table.R:70: failure: (unknown)
annotate_long_format_table(long_format_tibble_nac) not equal to `inspected_annotated_long_format_tibble_nac`.
Rows in x but not y: 6, 5, 4, 3, 2. Rows in y but not x: 6, 5, 4, 3, 2. 

test_annotate_long_format_table.R:112: failure: (unknown)
annotate_long_format_table(...) not equal to ...[].
Rows in x but not y: 6, 5, 4, 3, 2. Rows in y but not x: 6, 5, 4, 3, 2. 

test_annotate_long_format_table.R:263: failure: (unknown)
annotate_long_format_table(...) not equal to dplyr::select(...).
Rows in x but not y: 6, 5, 4, 3, 2. Rows in y but not x: 6, 5, 4, 3, 2. 
```

Are you able to provide any insight?

**Comment by logstar** [comment]
> Thanks for these updates! I am getting some errors running the tests in the Docker container. Some examples are:
> 
> ```
> test_annotate_long_format_table.R:62: failure: (unknown)
> annotate_long_format_table(long_format_tibble) not equal to `inspected_annotated_long_format_tibble`.
> Rows in x but not y: 6, 5, 4, 3, 2. Rows in y but not x: 6, 5, 4, 3, 2. 
> 
> test_annotate_long_format_table.R:70: failure: (unknown)
> annotate_long_format_table(long_format_tibble_nac) not equal to `inspected_annotated_long_format_tibble_nac`.
> Rows in x but not y: 6, 5, 4, 3, 2. Rows in y but not x: 6, 5, 4, 3, 2. 
> 
> test_annotate_long_format_table.R:112: failure: (unknown)
> annotate_long_format_table(...) not equal to ...[].
> Rows in x but not y: 6, 5, 4, 3, 2. Rows in y but not x: 6, 5, 4, 3, 2. 
> 
> test_annotate_long_format_table.R:263: failure: (unknown)
> annotate_long_format_table(...) not equal to dplyr::select(...).
> Rows in x but not y: 6, 5, 4, 3, 2. Rows in y but not x: 6, 5, 4, 3, 2. 
> ```
> 
> Are you able to provide any insight?

Thank you for running the tests @NHJohnson . I wonder if you have used the v7 data, which could be updated by running the `download-data.sh` script.

**Comment by logstar** [comment]
@NHJohnson To clarify the `download-data.sh`, it is under the root directory rather than this module. There is also a `run-download-annotation-data.sh` in this module, but it does not need to be run.

**Comment by logstar** [comment]
@NHJohnson Also, have you checked out the latest PR? The latest PR reads `ensg-hugo-rmtl-mapping.tsv`, which is only available in v7 data.

**Comment by logstar** [comment]
@NHJohnson I rerun the tests in the Docker image/container with v7 data and latest PR. All tests passed.

```text
rstudio@365c906e0007:~/OpenPedCan-analysis$ ls data/
cnv-cnvkit.seg.gz                               intersect_cds_lancet_strelka_mutect_WGS.bed
cnv-controlfreec.tsv.gz                         intersect_strelka_mutect_WGS.bed
consensus_wgs_plus_cnvkit_wxs_autosomes.tsv.gz  release-notes.md
consensus_wgs_plus_cnvkit_wxs_x_and_y.tsv.gz    snv-consensus-plus-hotspots.maf.tsv.gz
data-files-description.md                       sv-manta.tsv.gz
efo-mondo-map.tsv                               uberon-map-gtex-group.tsv
ensg-hugo-rmtl-mapping.tsv                      uberon-map-gtex-subgroup.tsv
fusion-arriba.tsv.gz                            v5
fusion-putative-oncogenic.tsv                   v6
fusion-starfusion.tsv.gz                        v7
gencode.v27.primary_assembly.annotation.gtf.gz  WGS.hg38.lancet.300bp_padded.bed
gene-counts-rsem-expected_count-collapsed.rds   WGS.hg38.lancet.unpadded.bed
gene-expression-rsem-tpm-collapsed.rds          WGS.hg38.mutect2.vardict.unpadded.bed
GRCh38.primary_assembly.genome.fa.gz            WGS.hg38.strelka2.unpadded.bed
histologies.tsv                                 WGS.hg38.vardict.100bp_padded.bed
rstudio@365c906e0007:~/OpenPedCan-analysis$ bash analyses/long-format-table-utils/annotator/run-tests.sh
✔ |  OK F W S | Context
✔ |  55       | tests/test_annotate_long_format_table.R [21.6 s]
✔ |  45       | tests/test_annotator_cli.R [47.6 s]
✔ |   8       | tests/test_collapse_name_vec.R
✔ |   7       | tests/test_collapse_rp_lists.R
✔ |  21       | tests/test_helper_import_function.R

══ Results ═════════════════════════════════════════════════════════════════════════════════════════════════════
Duration: 69.3 s

OK:       136
Failed:   0
Warnings: 0
Skipped:  0
Done running run-tests.sh
```

**Review by NHJohnson — APPROVED** [review]
Ok thanks, the need to re-download the files was indeed the problem. Test pass now.

**Comment by logstar** [comment]
@NHJohnson You're welcome. Thank you for reviewing and test-running!

**Comment by logstar** [comment]
@jharenza I have merged the latest dev branch in this PR, and I will merge this PR shortly.

**Pull request merged**
