### PR TITLE
Rerun tp53 hgg

### PR DESCRIPTION
**Pull request by adilahiri**
#### What scientific question is your analysis addressing?
To rerun the modules `tp53-nf1-score ` and  `molecular-subtyping-HGG` with using the new CNV files from [207](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/pull/207) + [235](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/pull/235):
```

consensus_seg_with_status.tsv
consensus_wgs_plus_cnvkit_wxs.tsv.gz
consensus_wgs_plus_cnvkit_wxs_autosomes.tsv.gz
consensus_wgs_plus_cnvkit_wxs_x_and_y.tsv.gz
```

#### What was your approach?
Created a branch from the updates ([commit#89733a](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/pull/250/commits/89733a1413c2176a6167041c359a6e804fefc69a
)) in [PR#250](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/pull/250#issuecomment-1253077876)  to first run `tp53-nf1-score `  and then `molecular-subtyping-HGG`. 

For the `tp53-nf1-score `  the data file `consensus_seg_with_status.tsv" `is being used in line 53 of script `03-tp53-cnv-loss-domain.Rmd `.

For the `molecular-subtyping-HGG` the data file `consensus_wgs_plus_cnvkit_wxs.tsv.gz `is being used in line 159 of script `02-HGG-molecular-subtyping-subset-files.R `.

#### What GitHub issue does your pull request address?
[Issue#401
](https://github.com/PediatricOpenTargets/ticket-tracker/issues/401#event-7274209695)

#### Which areas should receive a particularly close look?
Please verify the results files and the input files used. I will discuss any changes in the comments below. 

#### Is there anything that you want to discuss further?

No

#### Is the analysis in a mature enough form that the resulting figure(s) and/or table(s) are ready for review?
Yes

#### What types of results are included (e.g., table, figure)?
Table and figure

#### Reproducibility Checklist

- [ ] The dependencies required to run the code in this pull request have been added to the project Dockerfile.
- [ ] This analysis has been added to continuous integration.

#### Documentation Checklist

- [ ] This analysis module has a `README` and it is up to date.
- [ ] This analysis is recorded in the table in `analyses/README.md` and the entry is up to date.
- [ ] The analytical code is documented and contains comments.

### CODE REVIEW

**Comment by adilahiri** [comment]
For the module` molecular-subtyping-HGG` the `HGG_cleaned_cnv_dev.tsv `and `HGG_molecular_subtype_dev.tsv `changed. 

Upon checking the difference between the PR and Dev versions of  `HGG_cleaned_cnv_dev.tsv ` , it seems that some of the feature names have changed, however, the overall content of the files didn't change. But it seems the rows are ordered a bit differently.  Attached is the R code indicating this:

```
> all_equal(HGG_cleaned_dev,HGG_cleaned_pr,ignore_row_order = FALSE)
New names:
• `1p` -> `..1p`
• `19q` -> `..19q`
• `7p` -> `..7p`
• `7q` -> `..7q`
• `10p` -> `..10p`
• `10q` -> `..10q`
New names:
• `1p` -> `..1p`
• `19q` -> `..19q`
• `7p` -> `..7p`
• `7q` -> `..7q`
• `10p` -> `..10p`
• `10q` -> `..10q`
[1] "Same row values, but different order"
```

The molecular subtypes did increase across each category in the PR file:
Subtype Plot

**Comment by adilahiri** [comment]
For `TP53-NF1-Score` module changes were made to the result and plots directories of the modules. In the results directory new files were added and some of the existing file were updated. Following is the list of files that changed files with a brief description of the changes:
1. **fusion_bk_tp53_loss.tsv** : The entries in the column sample_id were changed from 01A (dev) to 01 (PR).
```
> fusion_bk_tp53_loss_dev_df<-fusion_bk_tp53_loss_dev_df[,-c(7)] # Delete column 7 which is sample_id
> fusion_bk_tp53_loss_pr_df<-fusion_bk_tp53_loss_pr_df[,-c(7)]  # Delete column 7 which is sample_id
> all_equal(fusion_bk_tp53_loss_dev_df,fusion_bk_tp53_loss_pr_df)
[1] TRUE
```

2. **loss_overlap_domains_tp53.tsv**: The new PR version of this file has the following extra columns:
`Kids_First_Participant_ID , composition` ,`tumor_descriptor`,` tp53_shuffle`
The PR file also has 118 observations (data points/rows) compared to the dev file which has 62 observation. The `copy_number` was 1 across biospecimen in both version of the files. The ploidy was 2,3,4 across the biospecimen in each of the files. The `domain` was "P53_tetramer, P53, P53_TAD" in both versions of the file.

```
> colnames(loss_overlap_tp53_dev_df)
[1] "biospecimen_id" "copy_number"    "ploidy"         "domain"         "sample_id"     
> colnames(loss_overlap_tp53_pr_df)
[1] "biospecimen_id"            "copy_number"               "ploidy"                    "domain"                    "Kids_First_Participant_ID"
[6] "sample_id"                 "composition"               "tumor_descriptor"          "tp53_shuffle"             
> unique(loss_overlap_tp53_pr_df$copy_number)
[1] 1
> unique(loss_overlap_tp53_dev_df$copy_number)
[1] 1
> unique(loss_overlap_tp53_dev_df$ploidy)
[1] 2 3 4
> unique(loss_overlap_tp53_pr_df$ploidy)
[1] 2 3 4
> unique(loss_overlap_tp53_pr_df$domain)
[1] "P53_tetramer, P53, P53_TAD"
> unique(loss_overlap_tp53_dev_df$domain)
[1] "P53_tetramer, P53, P53_TAD"

```

3. **sv_overlap_tp53.tsv**: The PR version of the file has 40 extra rows (data points/samples) compared to the dev version of the file. The `sv_type` across each file is compared in the figure below.
svtype



4. **tp53_altered_status.tsv**: The PR version of the file contained more observations (data points / rows) compared to the dev version. The unique `cancer_predisposition` were the same in both the versions of the files. However, in the PR file the observations across each `cancer_predisposition` category increased.

```
> table(tp53_altered_status_dev_df$cancer_predispositions)  ##dev file

                          Li-Fraumeni syndrome                      Li-Fraumeni syndrome,NF-1                                           NF-1 
                                            34                                              7                                            130 
           NF-1,Other inherited conditions NOS                                           NF-2                           NF-2,Schwannomatosis 
                                             6                                             18                                             26 
                               None documented                 Other inherited conditions NOS Other inherited conditions NOS,Schwannomatosis 
                                          3658                                            113                                              4 
                               Schwannomatosis                             Tuberous Sclerosis 
                                            10                                             28 
> table(tp53_altered_status_pr_df$cancer_predispositions) ### PR file

                          Li-Fraumeni syndrome                      Li-Fraumeni syndrome,NF-1                                           NF-1 
                                            54                                              7                                            210 
           NF-1,Other inherited conditions NOS                                           NF-2                           NF-2,Schwannomatosis 
                                            12                                             26                                             46 
                               None documented                 Other inherited conditions NOS Other inherited conditions NOS,Schwannomatosis 
                                          5301                                            183                                              6 
                               Schwannomatosis                             Tuberous Sclerosis 
                                            19                                             54  
```
`SNV_indel_counts `ranged from 0 to 5 across both the file versions.
`CNV_loss_counts` were either 0 or 1 in both the file versions.
`SV_Counts` ranged from 0 to 2 in both the file versions.
`Fusion_counts` were 0,1 or 59 in each version of the file.

```
> unique(tp53_altered_status_dev_df$SNV_indel_counts)
[1] 0 1 2 4 5 3
> unique(tp53_altered_status_pr_df$SNV_indel_counts)
[1] 0 1 2 4 5 3
> unique(tp53_altered_status_dev_df$CNV_loss_counts)
[1] 0 1
> unique(tp53_altered_status_pr_df$CNV_loss_counts)
[1] 0 1
> unique(tp53_altered_status_dev_df$SV_counts)
[1] 0 2 1
> unique(tp53_altered_status_pr_df$SV_counts)
[1] 0 1 2
> unique(tp53_altered_status_dev_df$Fusion_counts)
[1]  0 59  1
> unique(tp53_altered_status_pr_df$Fusion_counts)
[1] 59  0  1
> table(tp53_altered_status_pr_df$Fusion_counts)
```

`HGP_Short` was filled with NA values across each file version. Across both the PR and Dev versions of this file majority of the observations for `CNV_loss_evidence` were filled with NA values, while a minority of the observations were flagged as 1. For `SV_type` the PR version of the file had a few extra categories, this is shown in the code below:

```
> table(tp53_altered_status_dev_df$SV_type)

DEL, INV      INV       NA 
       1        1     6718 
> table(tp53_altered_status_pr_df$SV_type)

     DEL DEL, INV      INV INV, BND       NA 
       1        3        4        1     9060 
       
       
```
The number of distinct categories of `Fusion_Evidence` remained unchanged across both the file version. Both the `hotspots` and `activating` observations increased in the PR file.

```
> table(tp53_altered_status_dev_df$hotspot)

   0    1 
6521  199 
> table(tp53_altered_status_pr_df$hotspot)

   0    1 
8775  294 
> table(tp53_altered_status_dev_df$activating)

   0    1 
6673   47 
> table(tp53_altered_status_pr_df$activating)

   0    1 
8998   71 
```
For `tp53_altered`, we had more observation for each category in the PR file compared to the dev file.

```
> table(tp53_altered_status_dev_df$tp53_altered)

activated      loss     Other 
       47       243      6430 
> table(tp53_altered_status_pr_df$tp53_altered)

activated      loss     Other 
       71       419      8579 
```
5. **TP53_NF1_snv_alteration.tsv:** The PR version of the file had more observations than the Dev version of the same file.The number of observation in each of the main category (listed below in code) of `Variant_Classification` remained the same. What changed in the PR is the number of observation in the NA category of the `Variant_Classification`.
```
> table(TP53_NF1_snv_alteration_dev_df$Variant_Classification)

                 5'UTR        Frame_Shift_Del        Frame_Shift_Ins           In_Frame_Del           In_Frame_Ins                   loss 
                     1                     49                     28                      8                      4                    932 
     Missense_Mutation      Nonsense_Mutation          Splice_Region            Splice_Site Translation_Start_Site 
                   268                     73                      2                     34                      2 
> table(TP53_NF1_snv_alteration_pr_df$Variant_Classification)

                 5'UTR        Frame_Shift_Del        Frame_Shift_Ins           In_Frame_Del           In_Frame_Ins                   loss 
                     1                     49                     28                      8                      4                    932 
     Missense_Mutation      Nonsense_Mutation          Splice_Region            Splice_Site Translation_Start_Site 
                   268                     73                      2                     34                      2 



```

**Comment by jharenza** [comment]
Hi @adilahiri! Thanks for all of the great work on this. Can you create a table of BS_id from the dev HGG mol subtype table and add the dev subtype and the PR subtype? I'm wondering what is causing the large increase in calls - were there more samples in the PR? Are those the methylation samples, if not, what are they? Thanks.

**Comment by adilahiri** [comment]
Thank you @jharenza !! It seems that some of the Biospecimen ID repeat in the PR compared to the Dev version of the subtype table.  I created the table [HGG_Subtype_Review.csv](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/files/9636513/HGG_Subtype_Review.csv)  as per your instructions and noticed that there were duplicate records in this table.  When I left join the smaller DEV file with the PR file, I get more records in the joined table than the DEV file, as some entries of the DEV file have multiple matching records in the PR file. The code for generating the table is as follows:

```
library(dplyr)
library(data.table)
library(ggplot2)

#Load the subtype files from DEV and PR
subtype_dev<- as.data.frame(fread("HGG_molecular_subtype_dev.tsv")) # contains 317 rows and 18 columns
subtype_pr<-as.data.frame(fread("HGG_molecular_subtype_PR.tsv")) # contains 507 rows and 18 columns

#Select columns of biospecimen and molecular subtype in DEV file
df_table_dev <- subtype_dev %>% select(3:5) # contains 317 rows and 3 columns
colnames(df_table_dev)<- c("Kids_First_Biospecimen_ID_DNA_DEV","Kids_First_Biospecimen_ID_RNA_DEV","molecular_subtype_DEV")

#Select columns of biospecimen and molecular subtype in PR file
df_table_pr<- subtype_pr%>%select(3:5) # contains 507 rows and 3 columns
colnames(df_table_pr)<- c("Kids_First_Biospecimen_ID_DNA_PR","Kids_First_Biospecimen_ID_RNA_PR","molecular_subtype_PR")  


# Left join the DEV table with PR table 
test_df<-left_join(df_table_dev, df_table_pr, by=c('Kids_First_Biospecimen_ID_DNA_DEV'='Kids_First_Biospecimen_ID_DNA_PR', 'Kids_First_Biospecimen_ID_RNA_DEV'='Kids_First_Biospecimen_ID_RNA_PR'))

# Test_df attached below has 507 rows and 4 columns, some of the records were repeated in the PR file, due to which the left join of a the smaller (row =317) returns
# more rows

```


In code below we can see that the actual number of unique Biospecimen ID are the same in both the versions of the file:

```
> length(unique(subtype_dev$Kids_First_Biospecimen_ID_DNA))
[1] 262
> length(unique(subtype_pr$Kids_First_Biospecimen_ID_DNA))
[1] 262
> length(unique(subtype_dev$Kids_First_Biospecimen_ID_RNA))
[1] 243
> length(unique(subtype_pr$Kids_First_Biospecimen_ID_RNA))
[1] 243

```

**Comment by jharenza** [comment]
Thank you! One more request please- can you remove the RNA column and unique this table: ([HGG_Subtype_Review.csv](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/files/9636513/HGG_Subtype_Review.csv))? We can remove the RNA samples since the DNA is what is determining these subtypes anyway.

**Comment by adilahiri** [comment]
Here is the filtered file. [Unique_HGG_Review.csv](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/files/9636793/Unique_HGG_Review.csv). Thanks :)

**Comment by jharenza** [comment]
So it looks like `BS_853PNV7P` is the only sample which has non-matched subtypes. Can you dig into the CN changes in this one? TP53 loss was not called in this sample.

**Comment by adilahiri** [comment]
Yes @jharenza  I will look into this.

**Comment by adilahiri** [comment]
@jharenza : Took an initial look. It seems when I matched the `subtype_table` in DEV to PR based on the `Kids_First_Biospecimen_ID_DNA`   the DEV record matched with two records in the PR. I am wondering if I need to have more strict criteria for matching records between DEV and PR. 

Following the record in question from the DEV `subtype_table`  file. 
Dev record:
```

> which(subtype_dev$Kids_First_Biospecimen_ID_DNA=="BS_853PNV7P")
[1] 312
> print(subtype_dev[312,])
    Kids_First_Participant_ID sample_id Kids_First_Biospecimen_ID_DNA Kids_First_Biospecimen_ID_RNA      molecular_subtype cancer_predispositions tp53_score
312               PT_Z4PJA6KT 7316-1763                   BS_853PNV7P                   BS_DRY58DTF DMG, H3 K28, TP53 loss        None documented  0.5179495
    tp53_SNV_indel_counts tp53_CNV_loss_counts SV_counts Fusion_counts tp53_HGVSp_Short tp53_CNV_loss_evidence SV_type Fusion_evidence tp53_hotspot
312                     1                    0         0             0          p.R213*                     NA    <NA>              NA            0
    tp53_activating tp53_altered
312               0         loss
```
The above DEV record matched with the following PR records: 


PR Record#1:  This PR record does not match with the DEV record

```
> which(subtype_pr$Kids_First_Biospecimen_ID_DNA=="BS_853PNV7P")
[1] 497 498
> print(subtype_pr[497,])
    Kids_First_Participant_ID sample_id Kids_First_Biospecimen_ID_DNA Kids_First_Biospecimen_ID_RNA molecular_subtype cancer_predispositions tp53_score
497               PT_Z4PJA6KT 7316-1763                   BS_853PNV7P                   BS_DRY58DTF       DMG, H3 K28        None documented  0.4717424
    tp53_SNV_indel_counts tp53_CNV_loss_counts SV_counts Fusion_counts tp53_HGVSp_Short tp53_CNV_loss_evidence SV_type Fusion_evidence tp53_hotspot
497                     1                    0         0             0          p.R213*                     NA    <NA>              NA            0
    tp53_activating tp53_altered
497               0        Other
```
PR Record#2: This PR record matches with the DEV record.
```
> print(subtype_pr[498,])
    Kids_First_Participant_ID sample_id Kids_First_Biospecimen_ID_DNA Kids_First_Biospecimen_ID_RNA      molecular_subtype cancer_predispositions tp53_score
498               PT_Z4PJA6KT 7316-1763                   BS_853PNV7P                   BS_DRY58DTF DMG, H3 K28, TP53 loss        None documented  0.5179495
    tp53_SNV_indel_counts tp53_CNV_loss_counts SV_counts Fusion_counts tp53_HGVSp_Short tp53_CNV_loss_evidence SV_type Fusion_evidence tp53_hotspot
498                     1                    0         0             0          p.R213*                     NA    <NA>              NA            0
    tp53_activating tp53_altered
498               0         loss 
```
The major difference between the DEV record and the unmatched PR record (Record#1) is the difference in `tp53_score`.  The `tp53_score` was lower in the PR version. Also in the PR `tp53_altered` was in the state of`Other` whereas in the DEV version the state was `loss`. Will look more into this.

**Comment by adilahiri** [comment]
@jharenza For the sample BS_DRY58DTF  (and all other samples) it seems the `molecular_subtype` may in the  lines 56-58 of the script `10-HGG-TP53-annotation.Rmd  ` (molecular-subtyping-HGG module).  The lines code checks if the `tp53_altered` status is "activated" or "loss", depending on the case for the sample in question, the code adds TP53 activated or TP53 loss to the `molecular_subtype` respectively.  

Since `tp53_altered` status is "other" in PR Record#1 and and "loss" in PR Record#2, that is why we see the difference in the final `molecular_subtype`.

**Comment by adilahiri** [comment]
`tp53_altered` is assigned using the script` 05-tp53-altered-annotation.Rmd` of the ` tp53-nf1-score` module.  
`tp53_altered` is determined using the features `activating` ,  `hotspot`, `SNV_indel_counts`, `SV_counts`, `CNV_loss_counts`, and `tp53_score`. 

For the Biospecimen: BS_853PNV7P  there are two records and the only difference between them is based on their tp53 score, the script ` 05-tp53-altered-annotation.Rmd` thresholds `tp53_score` at 0.5.  Since one record lies below this threshold that is why we see the difference in molecular_subtype classification.

**Comment by jharenza** [comment]
I think we can close this since the issue with `BS_853PNV7P` is not copy number related and all other CN updates with GATK CNV gave concordant results with Manta SV consensus.

**Pull request closed without merging**
