### PR TITLE
Update cnv frequencies module

### PR DESCRIPTION
**Pull request by ewafula**
#### What scientific question is your analysis addressing?
- Rename CNV frequencies table headers 

#### What GitHub issue does your pull request address?
- https://github.com/PediatricOpenTargets/ticket-tracker/issues/252

#### Which areas should receive a particularly close look?
Confirm that the result tables now have the required header names

#### Is there anything that you want to discuss further?
No

#### Is the analysis in a mature enough form that the resulting figure(s) and/or table(s) are ready for review?
Yes

#### What types of results are included (e.g., table, figure)?
TSV and JSONL tables

#### What is your summary of the results?
- results/gene-level-cnv-consensus-annotated-mut-freq.tsv.gz
- results/gene-level-cnv-consensus-annotated-mut-freq.jsonl.gz

#### Reproducibility Checklist

- [x] The dependencies required to run the code in this pull request have been added to the project Dockerfile.
- [ ] This analysis has been added to continuous integration.

#### Documentation Checklist

- [x] This analysis module has a `README` and it is up to date.
- [ ] This analysis is recorded in the table in `analyses/README.md` and the entry is up to date.
- [x] The analytical code is documented and contains comments.

### CODE REVIEW

**Review by runjin326 — COMMENTED** [review]
@ewafula , thanks for preparing this! The changes make sense and the result file has the expected heading but as I was going through the new vs. old files, looks like we have more entries in NBL 
```
> combined3 %>% filter(is.na(old_Freq) | is.na(new_Freq) | old_Freq != new_Freq) 
              . old_Freq new_Freq
1 Neuroblastoma   490010   490452
```
Since `Metastatic secondary tumors;Neuroblastoma` was not present in the previous table, so this change is unlikely due to the changes from cancer group update. 
Could you please look into this and figure out where those changes are from and whether they are expected? Thanks!

**Comment by runjin326** [comment]
@ewafula , could you please address the question that I mentioned above? Thanks!

**Comment by ewafula** [comment]
> @ewafula , could you please address the question that I mentioned above? Thanks!

@runjin326, I have already addressed the question in the [SNV update PR](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/pull/156). Same reason as CNV:

```
@runjin326, all these additional records are stemming from the update in the histologies file changing cancer_group from Metastatic secondary tumors;Neuroblastoma to Neuroblastoma for PBTA cohort. As a result, there are additional Neuroblastoma variants records for All cohort (combinations between/among PBTA, GMKF, and TARGET ) in both CNV and SNV frequencies tables. PBTA cohort itself does not have the Neuroblastoma entries in frequencies tables because samples are not > 3.
```

**Comment by runjin326** [comment]
@ewafula, I guess my question is different here - for SNV, it makes more sense to me since `Metastatic secondary tumors;Neuroblastoma` was already in the previous table and the `cancer_group` changes can change the final output. However, for CNV, the cancer group is not present in the original table - so it is hard to imagine why the total number changed. So you meant: `Metastatic secondary tumors;Neuroblastoma` has <3 samples with CNV, and with the change to `Neuroblastoma`, it has >= 3 `Neuroblastoma` samples with CNV frequencies? Could you output the numbers for n samples just to explain this a bit more?

**Comment by ewafula** [comment]
> @ewafula, I guess my question is different here - for SNV, it makes more sense to me since `Metastatic secondary tumors;Neuroblastoma` was already in the previous table and the `cancer_group` changes can change the final output. However, for CNV, the cancer group is not present in the original table - so it is hard to imagine why the total number changed. So you meant: `Metastatic secondary tumors;Neuroblastoma` has <3 samples with CNV, and with the change to `Neuroblastoma`, it has >= 3 `Neuroblastoma` samples with CNV frequencies? Could you output the numbers for n samples just to explain this a bit more?

@runjin326,  it is the same logic. `Metastatic secondary tumors;Neuroblastoma` cancer_group was not in the previous CNV frequencies table for the `PBTA` cohort because there are < 3 samples present. It also did not count towards `All Cohorts` frequencies because the cancer_group was unique to the PBTA cohort. Once it was renamed to `Neuroblastoma`,  it now contributes to `All Cohorts` because it now has > 3 samples when considering `TARGET` and `GMKF` samples. But still has no frequency reported for the `PBTA` cohort (< 3 samples). Therefore, the variant types for the genes shown below must be specific to the PBTA samples contributing to the `Neuroblastoma All Cohorts`.  If additional validation is still needed, we can find out what `Metastatic secondary tumors; Neuroblastoma` PBTA samples are, and confirm if the variant types listed below were called in the consensus CNV file. 
```
> latest_df <- read_tsv("~/Downloads/gene-level-cnv-consensus-annotated-mut-freq_latest.tsv") %>%
+   select(Gene_symbol, targetFromSourceId, Variant_type, Variant_category,Dataset, Disease)
> previous_df <- read_tsv("~/Downloads/gene-level-cnv-consensus-annotated-mut-freq_previous.tsv") %>% 
+   select(Gene_symbol, targetFromSourceId, Variant_type, Variant_category,Dataset, Disease)
> in_latest_not_previous <-  setdiff(latest_df, previous_df)
> in_latest_not_previous
# A tibble: 442 × 6
   Gene_symbol targetFromSourceId Variant_type  Variant_category Dataset     Disease      
   <chr>       <chr>              <chr>         <lgl>            <chr>       <chr>        
 1 MAP3K9      ENSG00000006432    deep deletion NA               All Cohorts Neuroblastoma
 2 POMT2       ENSG00000009830    deep deletion NA               All Cohorts Neuroblastoma
 3 MAP4K5      ENSG00000012983    deep deletion NA               All Cohorts Neuroblastoma
 4 ANGEL1      ENSG00000013523    deep deletion NA               All Cohorts Neuroblastoma
 5 MNAT1       ENSG00000020426    deep deletion NA               All Cohorts Neuroblastoma
 6 SAMD4A      ENSG00000020577    deep deletion NA               All Cohorts Neuroblastoma
 7 NRXN3       ENSG00000021645    deep deletion NA               All Cohorts Neuroblastoma
 8 SNAPC1      ENSG00000023608    deep deletion NA               All Cohorts Neuroblastoma
 9 PRKCH       ENSG00000027075    deep deletion NA               All Cohorts Neuroblastoma
10 SLC39A9     ENSG00000029364    deep deletion NA               All Cohorts Neuroblastoma
# … with 432 more rows
> in_latest_not_previous %>% distinct(Dataset, Disease)
# A tibble: 1 × 2
  Dataset     Disease      
  <chr>       <chr>        
1 All Cohorts Neuroblastoma
> 
> in_previous_not_latest <- setdiff(previous_df, latest_df)
> in_previous_not_latest
# A tibble: 0 × 6
# … with 6 variables: Gene_symbol <chr>, targetFromSourceId <chr>, Variant_type <chr>,
#   Variant_category <lgl>, Dataset <chr>, Disease <chr>
> 
```

**Review by runjin326 — APPROVED** [review]
@ewafula, thanks so much for the explanation - it all makes sense now - approving now.
The dev branch has some update since you last merge, if you can merge the most up-to-date dev to this branch, I will merge right after. Thanks!

**Comment by ewafula** [comment]
@runjin326, Thanks for reviewing! I have updated the PR with the most up-to-date dev to this branch

**Pull request merged**
