### PR TITLE
EFO MONDO map file update

### PR DESCRIPTION
**Pull request by runjin326**
#### What scientific question is your analysis addressing?
Update `efo-mondo-map.tsv` file to include all cancer groups in the histologies file. 

#### What was your approach?
Manual curation of newly added cancer groups.

#### What GitHub issue does your pull request address?
https://github.com/PediatricOpenTargets/ticket-tracker/issues/237

#### Which areas should receive a particularly close look?
Please check all new terms are added correctly.

#### Is there anything that you want to discuss further?
Additionally, these terms do not have exact match so the following procedures were done:
- `Atypical choroid plexus papilloma`- no exact match and used the term for `choroid plexus papilloma`- this term does not have MONDO term
- `Desmoplastic infantile astrocytoma and ganglioglioma` - no match so used the term that showed up when searching for `Desmoplastic infantile astrocytoma and ganglioglioma`
- `Neurocytoma` - used the parent term for `central neurocytoma`

#### Is the analysis in a mature enough form that the resulting figure(s) and/or table(s) are ready for review?
Yes

#### What types of results are included (e.g., table, figure)?
`efo-mondo-map.tsv`

#### What is your summary of the results?
QC file confirmed that all the cancer groups with >=3 occurrence are present in `efo-mondo-map.tsv` file.

#### Reproducibility Checklist

- [x] The dependencies required to run the code in this pull request have been added to the project Dockerfile.
- [ ] This analysis has been added to continuous integration.

#### Documentation Checklist

- [x] This analysis module has a `README` and it is up to date.
- [ ] This analysis is recorded in the table in `analyses/README.md` and the entry is up to date.
- [x] The analytical code is documented and contains comments.

### CODE REVIEW

**Comment by afarrel** [comment]
Should the EFO for **Neurocytoma** be **EFO_1000856** given that Neurocytoma is listed as a synonym on [OLS: EFO_1000856](https://www.ebi.ac.uk/ols/ontologies/efo/terms?iri=http%3A%2F%2Fwww.ebi.ac.uk%2Fefo%2FEFO_1000856)

**Comment by jharenza** [comment]
> Should the EFO for **Neurocytoma** be **EFO_1000856** given that Neurocytoma is listed as a synonym on [OLS: EFO_1000856](https://www.ebi.ac.uk/ols/ontologies/efo/terms?iri=http%3A%2F%2Fwww.ebi.ac.uk%2Fefo%2FEFO_1000856)
> 
> 
> 
> 

No- there are two types of neurocytoma. We discussed this somewhere already, not sure if GitHub or slack. Cancer group is broad, contains both central and extra-ventricular. Once we go down to those levels, we can use central for central and create EFO for extra-ventricular.

**Comment by afarrel** [comment]
> > Should the EFO for **Neurocytoma** be **EFO_1000856** given that Neurocytoma is listed as a synonym on [OLS: EFO_1000856](https://www.ebi.ac.uk/ols/ontologies/efo/terms?iri=http%3A%2F%2Fwww.ebi.ac.uk%2Fefo%2FEFO_1000856)
> 
> No- there are two types of neurocytoma. We discussed this somewhere already, not sure if GitHub or slack. Cancer group is broad, contains both central and extra-ventricular. Once we go down to those levels, we can use central for central and create EFO for extra-ventricular.

Ok Thanks.

**Comment by runjin326** [comment]
@afarrel, thanks for reviewing this! I will merge soon.

**Pull request merged**
