### PR TITLE
Generate an Excel spreadsheet for PedOT website table display orders and names

### PR DESCRIPTION
**Pull request by logstar**
### Purpose/implementation Section

The `pedot-table-column-display-order-name` analysis module generates an Excel spreadsheet for Pediatric Open Targets (PedOT) website table display orders and names. The Excel spreadsheet will be used to coordinate table column order and name changes on PedOT website table views.

#### What was your approach?

Generate the Excel spreadsheet using the TSV result files in the following modules.

- `cnv-frequencies`
- `fusion-frequencies`
- `rna-seq-expression-summary-stats`
- `snv-frequencies`

#### What GitHub issue does your pull request address?

<https://github.com/PediatricOpenTargets/ticket-tracker/issues/157>

#### Which areas should receive a particularly close look?

Does the `results/pedot-table-column-display-order-name.xlsx` make sense? I have tested that the xlsx file can be opened using Mac Excel version 16 and box web app.

Does the code in `.py` files make sense?

#### Is there anything that you want to discuss further?

The `pedot-table-column-display-order-name` analysis module is implemented slightly different from the issue <https://github.com/PediatricOpenTargets/ticket-tracker/issues/157> description.

- The first row in `results/pedot-table-column-display-order-name.xlsx` lists the column display names.
- The last row in  `results/pedot-table-column-display-order-name.xlsx` lists the JSONL/TSV column/field names. This may prevent the JSONL/TSV column/field names from being changed mistakenly. The JSONL/TSV column/field names may be used for PedOT programming and validations.
- The first two columns of  `results/pedot-table-column-display-order-name.xlsx` are user guide and row annotations, which will not be displayed on the PedOT website.
- 60 TSV rows are sample to provide a more comprehensive preview. This may also prevent the last row, i.e. JSONL/TSV column/field names, from being changed mistakenly.
- The sheet names in `results/pedot-table-column-display-order-name.xlsx` are table short names rather than JSONL file names, because Excel only allows sheet names to have <= 31 characters.
- In the `SNV variant-level` sheet of `results/pedot-table-column-display-order-name.xlsx`, `Variant_ID_hg38` and `Protein_change` columns are moved after the `Gene_symbol` column, according to the suggestion by John Maris.
- In all sheets of `results/pedot-table-column-display-order-name.xlsx`, use `PMTL` as the default column display name for the `RMTL` JSONL/TSV column/field name, according to Slack message <https://opentargetspediatrics.slack.com/archives/C021ZLY33S7/p1627998314004300>.

The `pedot-table-column-display-order-name` analysis module will be updated to add procedures for validating a reviewed and modified Excel spreadsheet, but the specific validation procedures need to be determined by considering the following things.

- Feedback from clinicians on the `results/pedot-table-column-display-order-name.xlsx`.
- Specific implementations of the PedOT front-end column setting configuration file described in the coordination plan.

#### Is the analysis in a mature enough form that the resulting figure(s) and/or table(s) are ready for review?

Yes.

#### What types of results are included (e.g., table, figure)?

Table.

#### What is your summary of the results?

```text
$ ls -lh results/
total 72K
-rw-r--r-- 1 ubuntu ubuntu 69K Aug 13 21:34 pedot-table-column-display-order-name.xlsx
```

Each sheet in the Excel spreadsheet has a name corresponding to a JSONL filename.

| Excel sheet name                | JSONL filename                                            |
| ------------------------------- | --------------------------------------------------------- |
| `SNV gene-level`                | `gene-level-snv-consensus-annotated-mut-freq.jsonl.gz`    |
| `SNV variant-level`             | `variant-level-snv-consensus-annotated-mut-freq.jsonl.gz` |
| `CNV gene-level`                | `gene-level-cnv-consensus-annotated-mut-freq.jsonl.gz`    |
| `Fusion gene-level`             | `putative-oncogene-fused-gene-freq.jsonl.gz`              |
| `Fusion fusion-level`           | `putative-oncogene-fusion-freq.jsonl.gz`                  |
| `TPM stats gene-wise z-scores`  | `long_n_tpm_mean_sd_quantile_gene_wise_zscore.jsonl.gz`   |
| `TPM stats group-wise z-scores` | `long_n_tpm_mean_sd_quantile_group_wise_zscore.jsonl.gz`  |

Each sheet contains the following rows.

- Column names for PedOT table view display.
- 60 sample rows of table values.
- Column names in the JSONL/TSV files.

The first two columns of each sheet are "User guide" and "Row annotation", which will not be displayed on the PedOT website.

#### Reproducibility Checklist

- [x] The dependencies required to run the code in this pull request have been added to the project Dockerfile.
- [NA] This analysis has been added to continuous integration.

#### Documentation Checklist

- [x] This analysis module has a `README` and it is up to date.
- [x] This analysis is recorded in the table in `analyses/README.md` and the entry is up to date.
- [x] The analytical code is documented and contains comments.

### CODE REVIEW

**Review by ewafula — APPROVED** [review]
@logstar, Thank you for developing the module! The wrapper bash script, `run-pedot-table-column-display-order-name.sh`  runs ok and reproduces results consistent with the submitted PR results. The code in the primary python script `01-generate-pedot-column-display-order-name-xlsx.py` and python class and function implementations in the `package utils/ ` are correctly executed. The resulting excel workbook s viewable on excel for Mac, Box, google docs, and office 365.  I did not try on excel for Windows.

**Comment by logstar** [comment]
> @logstar, Thank you for developing the module! The wrapper bash script, `run-pedot-table-column-display-order-name.sh` runs ok and reproduces results consistent with the submitted PR results. The code in the primary python script `01-generate-pedot-column-display-order-name-xlsx.py` and python class and function implementations in the `package utils/ ` are correctly executed. The resulting excel workbook s viewable on excel for Mac, Box, google docs, and office 365. I did not try on excel for Windows.

Thank you very much for test-running this PR and reviewing the code and results @ewafula !

**Review by afarrel — APPROVED** [review]
Hi @logstar. Thanks for your hard work with this
I looked at the code and it looks good but I did not test it. I trust @ewafula's assessment. However I looked at the column orders in the xlsx file carefully and confirmed with Drs Tasian and Maris that they are all okay and ready to be delivered to FNL. Great work!

**Comment by logstar** [comment]
@ewafula @afarrel - Thank you for the reviews!

I will upload the xlsx file to box and share it in slack. If there is any change that need to be made at a later point, feel free to submit a ticket, and I will reorder columns or change column names accordingly.

I will merge this PR soon. I will not merge the latest dev branch to this PR, as this PR does not need latest data/results, and this PR does not change any data/results.

cc @jharenza @taylordm @chinwallaa

**Pull request merged**
