### PR TITLE
mutation freq tables qc and summary checks 

### PR DESCRIPTION
**Pull request by ewafula**
#### What scientific question is your analysis addressing?
Generate QC and summary checks for the CNV, SNV, and Fusion, comparing current and previous mutation frequencies tables. 

#### What was your approach?
Compared v11 and v10 mutation frequencies tables

#### What GitHub issue does your pull request address?
- https://github.com/PediatricOpenTargets/ticket-tracker/issues/388

#### Which areas should receive a particularly close look?
Review  results

#### Is there anything that you want to discuss further?
Other suggestions 

#### Is the analysis in a mature enough form that the resulting figure(s) and/or table(s) are ready for review?
Yes

#### What types of results are included (e.g., table, figure)?
tables and notebooks

#### What is your summary of the results?
- `gene-level-cnv-consensus-annotated-mut-freq-checks.nb.html`
- `results/gene-level-cnv-consensus-annotated-mut-freq.xlsx`
- `gene-level-snv-consensus-annotated-mut-freq-checks.nb.html`
- `results/gene-level-snv-consensus-annotated-mut-freq.xlsx`
- `gene-variant-snv-consensus-annotated-mut-freq-checks.nb.html`
- `results/variant-level-snv-consensus-annotated-mut-freq.xlsx`
- `putative-oncogene-fused-gene-freq-checks.nb.html`
- `results/putative-oncogene-fused-gene-freq.xlsx`
- `putative-oncogene-fusion-freq-checks.nb.html`
- `results/putative-oncogene-fusion-freq.xlsx`

#### Reproducibility Checklist

- [x ] The dependencies required to run the code in this pull request have been added to the project Dockerfile.
- [x ] This analysis has been added to continuous integration.

#### Documentation Checklist

- [x] This analysis module has a `README` and it is up to date.
- [ ] This analysis is recorded in the table in `analyses/README.md` and the entry is up to date.
- [x ] The analytical code is documented and contains comments.

### CODE REVIEW

**Review by adilahiri — COMMENTED** [review]
Hello @ewafula , thank you for your work here. The analysis successfully returns the objectives stated in the readme and the PR.  Following are some of my comments.

**_1. Number of patients in each cohort_**
The logic for getting patients numbers is as follows (please correct if required):

-  Firstly, remove `all cohorts` from the `Dataset` column, 
-  Extract the number of patient for cases from the column: `Total_alterations_over_subjects_in_dataset`

- Retain only unique records as `diseases` keep repeating, 
- Remove the `diseases` column, 
- Group by the column `Dataset` and add the number of patients for each dataset


The logic for number of samples in each cohort is similar, instead of `Total_alterations_over_subjects_in_dataset`, `Total_primary_tumors_mutated_over_primary_tumors_in_dataset` is used. 

@ewafula : I believe in line 81 there is typo in the comment ,it should be samples instead of patients. 

**_2. Cancer groups present in each cohort_**
This is clear and looks good, as we get a file for each of the tables containing `cancer groups` in `All Cohort`

**_3. Subset of sorted top 50 records from a static cancer group (Neuroblastoma)  that should not change_**
Indeed two results are printed here, however, I am not sure as to what shouldn't change ? For example in the results file `putative-oncogene-fused-gene-freq.xlsx` there is the gene BRAF is the previous_static_cancer_group but not in current_static_cancer_group . Does this qualify a change ?


**_4. Changes in common columns among mutation frequencies tables with non dynamic values_**
Looks good, the logic of the code as I understand (correct me if needed)
  * Finds elements of a column that are unique in one column .
  * Then finds elements  unique in the column being compared to.
  *  Full join is performed which shows the unique elements of each columns and also the elements common between the both.

**Comment by sangeetashukla** [comment]
@ewafula Thank for your working on this module. The work is very comprehensive, kudos!

I have few comments as below:

1) Since the module requires an update to the OPC repo [Dockerfile here](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/blob/2d306aea322cfa418118f596c1fa9655ed4d265c/Dockerfile#L450), we want to use separate PRs for the Docker file first and then the module as described [here](https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/master/CONTRIBUTING.md#creating-stacked-pull-requests)

2) I think it would make sense to include more details in the module README to describe the sources of the input files (current and previous versions of files compared), eg. release version and clarify the format/method in the results files used to capture the quality. May be that will also answer @adilahiri's comment 3 above. 

3) Please also include in the README the reason/explanation why only a select static cancer_group+cohort combination is used for spot checks ( it has the largest number is samples, perhaps ? )

4) Please include brief introduction about the various tabs in the result xlsx files in the README 

5) Other than that, the module looks good and the results are generated correctly.

**Comment by ewafula** [comment]
> Thanks @adilahiri for reviewing. I have updated the typo you identied. I am going the rerun the module with the final MTP mutation frequencies tables. Results in the PR were generated with preliminary files. The module aims to identify any differences/changes between the current and previous tables to help us determine if the changes are valid. We do expect changes except for the static cancer groups, which might have minimal changes due to changes in annotation files utilized in modules.

**Comment by adilahiri** [comment]
@ewafula Appreciate the clarification, thank you !!

**Comment by ewafula** [comment]
Thank you, @sangeetashukla, for reviewing!

> @ewafula Thank for your working on this module. The work is very comprehensive, kudos!
> 
> I have few comments as below:
> 
> 1. Since the module requires an update to the OPC repo [Dockerfile here](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/blob/2d306aea322cfa418118f596c1fa9655ed4d265c/Dockerfile#L450), we want to use separate PRs for the Docker file first and then the module as described [here](https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/master/CONTRIBUTING.md#creating-stacked-pull-requests)

Since this module does not require any changes except for minor README updates and a rerun using final v11 MPT mutation frequencies tables. I see no deed creating another separate PR for the `Dockerfile` R package update. Should be ready to merge following the minor updates.  I'll make sure to keep this in mind next when working on a module that requires `Dockerfile` update. 

> 2. I think it would make sense to include more details in the module `README` to describe the sources of the input files (current and previous versions of files compared), eg. release version and clarify the format/method in the results files used to capture the quality. May be that will also answer @adilahiri's comment 3 above.

The source of input files are described in the introductory paragraph of the `README`, including link to the source modules

> 3. Please also include in the README the reason/explanation why only a select static cancer_group+cohort combination is used for spot checks ( it has the largest number is samples, perhaps ? )

Results for the module are in notebooks to help readers easily look through the results. I'll ensure to include a sentence in the Rmd under the need to display a few records for a static cancer_group  from both current and previous tables.  Technically there should be no changes in mutation frequencies. Other fields change if annotations are updated.  

> 4. Please include a brief introduction about the various tabs in the result xlsx files in the `README`

Excel tables tabs are descriptive and are an addition of the same results displayed in notebooks stored in tables. I'll make that clarification in the `README` under the `Results` subtitle.

> 5. Other than that, the module looks good and the results are generated correctly.

Thank you!

**Comment by ewafula** [comment]
@adilahiri, @sangeetashukla, made the updates you suggested following my previous comments to your reviews above.  It should be ready to approve.  Also, I rerun the module with the final v11 MTP mutation frequencies tables.

**Review by adilahiri — APPROVED** [review]
Looks good @ewafula , thank you for the updates.

**Review by sangeetashukla — APPROVED** [review]
Thank you @ewafula for clarifying thoughts around my comments. Approving this PR with the latest results.

**Pull request merged**
