### PR TITLE
Adding updated codes for EFO and MONDO,with comments

### PR DESCRIPTION
**Pull request by sangeetashukla**
### Purpose/implementation Section
After recent discussion, it was deduced that some EFO codes may be incorrect in the current efo-mondo-mapping.tsv.
I review the existing codes in v8, and created two new columns for codes that needed review. Another column for comments is also added. This file only contains codes that need review/discussion.

#### What GitHub issue does your pull request address?
[issue](https://github.com/PediatricOpenTargets/ticket-tracker/issues/182)

#### Reproducibility Checklist

- [ ] The dependencies required to run the code in this pull request have been added to the project Dockerfile.
- [ ] This analysis has been added to continuous integration.

#### Documentation Checklist

- [ ] This analysis module has a `README` and it is up to date.
- [ ] This analysis is recorded in the table in `analyses/README.md` and the entry is up to date.
- [ ] The analytical code is documented and contains comments.

### CODE REVIEW

**Comment by jharenza** [comment]
Hi @afarrel and @sangeetashukla - I am going to bring the comments from [this ticket](https://github.com/PediatricOpenTargets/ticket-tracker/issues/182#issuecomment-908872055) over here:

>For "Germinoma;Teratoma" Germinoma is EFO_0000514, Teratoma is MONDO_0002601. There is only one patient with this 'combination/histology' - which means they will be excluded from the analysis modules the require n >= 5.

Since both diagnoses were added for this patient, we can go up a level to "germ cell tumor" and use that EFO code, `EFO:0000514`?

>For "Choroid plexus cyst" - Are we including cysts even though it's not a tumor? Also, N = 1 patient with 1 NGS and 1 RNAseq which means they will be excluded from the analysis modules the require n >= 5.

For this, I would use the `choroid plexus neoplasm` since it can be benign or malignant - EFO ID is `MONDO:0016717`

>Confirm CNS Embryonal tumor:MONDO_0018843 (Actual Description is: embryonal carcinoma of the central nervous system)

This is not necessarily the same, and I found  `EFO:0005784`, which is an embryonal neoplasm which is: "A usually malignant neoplasm composed of primitive (immature) tissues that resemble fetal tissues. Medulloblastoma, Ependymoblastoma, Pineoblastoma, and Wilms tumor are representative embryonal neoplasms" - this is more like it

>"CNS neuroblastoma" - will have the same EFO code as neuroblastoma. - The EFO code covers Neuroblastoma and "Central Neuroblastoma" as well as other subtypes of neuroblastoma? Would we need to get subtype EFO/MONDO codes for NBL too?

yes, I think we will have to get all of these in the future

>"Diffuse midline glioma" - (DMG) has no code. Currently using DIPG code. DMG with H3 K27M-Mutant does have NCIT codes: NCIT_C129309; DOID_0080684

We could go up a level to `MONDO:0003869` for childhood brainstem glioma

>"Dysplasia/Gliosis;Glial-neuronal tumor NOS" - Should there be separates histologies? Gliosis is HP_0002171 and mixed neuronal-glial tumor is MONDO_0016729.

This sample has actually since been revised - it is only now Dysplasia/Gliosis, so I would take this out of our mapping file.

>"Epilepsy" - Should we include this: Epilepsy isn’t a tumor; N = 2 1 WGS and 1 RNAseq - same patient

I looked into this one as well, and it looks like the other diagnosis is `GLIOTIC ENCEPHALOPATHY`, which is a type of gliosis, so I would remove epilepsy from the mapping file.

>"Extraventricular Neurocytoma" - 1 patient with 1 WGS and 1 RNAseq - The old EFO code (EFO_0007201) needs to be reviewed.

I think this is correct (though general)- this is one level up from central neurocytoma.

>"High-grade glioma/astrocytoma" - high-grade glioma: MONDO_0100342; astrocytoma: EFO_0000272 (synonym - astrocytic tumor); high grade astrocytic tumor: MONDO_0016680 - Which is most appropriate?

We can use `MONDO_0016680` 

>"Low-grade glioma/astrocytoma" - Low Grade Glioma:MONDO_0021637 ; Low grade astrocytoma: MONDO_0016685

We can use MONDO_0016685 for now, even though there will be some lower grade gliomas in this group - mostly astrocytic cell derived, though.

>"Melanocytic tumor" - Confirm we can use the EFO code for 'CNS melanocytic tumor'

Do you mean `MONDO:0003222`? This one is `central nervous system melanocytic neoplasm` and works.

>"Myxoid spindle cell tumor" - myxoid isn't specified - maybe need to request subtype in future?

I would just use `EFO:0000705` for now

**Comment by afarrel** [comment]
[efo-mondo-map.txt](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/files/7087349/efo-mondo-map.txt)

@sangeetashukla and @jharenza - This should be the final table for review with all changes and suggestions

**Comment by afarrel** [comment]
[efo-mondo-map.txt](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/files/7087406/efo-mondo-map.txt)

Here is an updated table with 2 minor changes

**Comment by jharenza** [comment]
Actually `Dysplasia/Gliosis` is not in `cancer_group`, so will remove.

**Comment by jharenza** [comment]
@afarrel updated the `Choroid plexus cyst` to have MONDO in both EFO and MONDO groups, and pushed the TSV file. This module does not yet have a README, but I think we can add a ticket for @sangeetashukla to add this later, meanwhile we can get this merged and released.

**Review by afarrel — APPROVED** [review]
Looks Good. Thanks for the work and efforts to get this out.

**Pull request merged**
