### PR TITLE
v9 release

### PR DESCRIPTION
**Pull request by runjin326**
#### What scientific question is your analysis addressing?
V9 release 

#### What was your approach?
Updated release note.
Update download link.
Uploaded the following files to S3 bucket:
- efo-mondo-map.tsv
- release-notes.md
- md5sum.txt
Also tested the download script and it worked. 

#### What GitHub issue does your pull request address?
https://github.com/PediatricOpenTargets/ticket-tracker/issues/183

#### Which areas should receive a particularly close look?
Please check to see the release note makes sense and the download works as well.

#### Is there anything that you want to discuss further?
No.

#### Is the analysis in a mature enough form that the resulting figure(s) and/or table(s) are ready for review?
Yes.

### Data Release Checklist
- [x] Is the table in doc/data-file-descriptions.md up to date?
- [x] Is doc/data-format.md up to date?
- [x] Is doc/release-notes.md up to date?
- [x] Is download-data.sh up to date?
- [x] Was download-data.sh tested and did it complete without error?

### CODE REVIEW

**Comment by jharenza** [comment]
Tagging @logstar and @afarrel for review for this :)

**Review by jharenza — APPROVED** [review]
looks good, download checks out

**Review by logstar — COMMENTED** [review]
@runjin326 Thank you for the updates.

I got one md5sum mismatch when downloading with the following URL and version. It seems that this URL <https://s3.amazonaws.com/d3b-openaccess-us-east-1-prd-pbta/open-targets/v9/data-files-description.md> is currently not available.

```bash

set -e
set -o pipefail

# Use the OpenPBTA bucket as the default.
URL=${OPENPBTA_URL:-https://s3.amazonaws.com/d3b-openaccess-us-east-1-prd-pbta/open-targets}
RELEASE=${OPENPBTA_RELEASE:-v9}
PREVIOUS=${OPENPBTA_RELEASE:-v8}

# Remove old symlinks in data
```

```text
Checking MD5 hashes...
histologies.tsv: OK
...
data-files-description.md: FAILED
...
md5sum: WARNING: 1 computed checksum did NOT match
```

**Comment by runjin326** [comment]
> @runjin326 Thank you for the updates.
> 
> I got one md5sum mismatch when downloading with the following URL and version. It seems that this URL https://s3.amazonaws.com/d3b-openaccess-us-east-1-prd-pbta/open-targets/v9/data-files-description.md is currently not available.
@logstar, thanks for checking! I must have missed it when copying files - updated now!

**Comment by logstar** [comment]
> > @runjin326 Thank you for the updates.
> > I got one md5sum mismatch when downloading with the following URL and version. It seems that this URL https://s3.amazonaws.com/d3b-openaccess-us-east-1-prd-pbta/open-targets/v9/data-files-description.md is currently not available.
> > @logstar, thanks for checking! I must have missed it when copying files - updated now!

@runjin326 Thank you for the quick update. All files passed md5sum checks.

```text
Checking MD5 hashes...
histologies.tsv: OK
cnv-cnvkit.seg.gz: OK
cnv-controlfreec.tsv.gz: OK
consensus_wgs_plus_cnvkit_wxs.tsv.gz: OK
snv-consensus-plus-hotspots.maf.tsv.gz: OK
data-files-description.md: OK
efo-mondo-map.tsv: OK
ensg-hugo-rmtl-mapping.tsv: OK
fusion-arriba.tsv.gz: OK
fusion-putative-oncogenic.tsv: OK
fusion-starfusion.tsv.gz: OK
gene-counts-rsem-expected_count-collapsed.rds: OK
gene-expression-rsem-tpm-collapsed.rds: OK
intersect_cds_lancet_strelka_mutect_WGS.bed: OK
intersect_strelka_mutect_WGS.bed: OK
release-notes.md: OK
sv-manta.tsv.gz: OK
uberon-map-gtex-group.tsv: OK
uberon-map-gtex-subgroup.tsv: OK
WGS.hg38.lancet.300bp_padded.bed: OK
WGS.hg38.lancet.unpadded.bed: OK
WGS.hg38.mutect2.vardict.unpadded.bed: OK
WGS.hg38.strelka2.unpadded.bed: OK
WGS.hg38.vardict.100bp_padded.bed: OK
independent-specimens.rnaseq.primary.eachcohort.tsv: OK
independent-specimens.rnaseq.relapse.eachcohort.tsv: OK
independent-specimens.wgswxspanel.primary.eachcohort.tsv: OK
independent-specimens.wgswxspanel.relapse.eachcohort.tsv: OK
independent-specimens.rnaseq.primary.tsv: OK
independent-specimens.rnaseq.relapse.tsv: OK
independent-specimens.wgswxspanel.primary.tsv: OK
independent-specimens.wgswxspanel.relapse.tsv: OK
```

**Comment by logstar** [comment]
The 11th line of `efo-mondo-map.tsv` has an extra tab in the end.

```text
  10 Choroid plexus carcinoma^IMONDO_0016718^IMONDO_0016718$
  11 Choroid plexus cyst^IMONDO_0016717^IMONDO_0016717^I$
  12 Choroid plexus papilloma^IEFO_1000177^IMONDO_0009837$
```

This would cause a warning when reading.

```text
> edf <- read_tsv('data/efo-mondo-map.tsv')                                                                                                                  

── Column specification ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
cols(
  cancer_group = col_character(),
  efo_code = col_character(),
  mondo_code = col_character()
)

Warning: 1 parsing failure.
row col  expected    actual                     file
 10  -- 3 columns 4 columns 'data/efo-mondo-map.tsv'
```

**Comment by runjin326** [comment]
@logstar, thanks for checking. I removed the tab, checked the reading (which was good) and uploaded S3:
```
> test <- readr::read_tsv("~/Desktop/efo-mondo-map.tsv")
Rows: 55 Columns: 3                                                                                                                   
 0s── Column specification ────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Delimiter: "\t"
chr (3): cancer_group, efo_code, mondo_code

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
```

**Comment by logstar** [comment]
> @logstar, thanks for checking. I removed the tab, checked the reading (which was good) and uploaded S3:
> 
> ```
> > test <- readr::read_tsv("~/Desktop/efo-mondo-map.tsv")
> Rows: 55 Columns: 3                                                                                                                   
>  0s── Column specification ────────────────────────────────────────────────────────────────────────────────────────────────────────────────
> Delimiter: "\t"
> chr (3): cancer_group, efo_code, mondo_code
> 
> ℹ Use `spec()` to retrieve the full column specification for this data.
> ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
> ```

Thank you for the update. <https://s3.amazonaws.com/d3b-openaccess-us-east-1-prd-pbta/open-targets/v9/efo-mondo-map.tsv> currently still has the tab. Maybe s3 needs some time to update. I will check back later.

**Comment by runjin326** [comment]
> Thank you for the update. https://s3.amazonaws.com/d3b-openaccess-us-east-1-prd-pbta/open-targets/v9/efo-mondo-map.tsv currently still has the tab. Maybe s3 needs some time to update. I will check back later.

Hmm weird. 
image
This should be the most up to date one

**Review by jharenza — APPROVED** [review]
thanks for the updates! the download works and there is no tab issue

```
> efo <- read_tsv("~/Documents/GitHub/ped-ot/OpenPedCan-analysis/analyses/efo-mondo-mapping/results/efo-mondo-map.tsv")

── Column specification ──────────────────────────────────────────────
cols(
  cancer_group = col_character(),
  efo_code = col_character(),
  mondo_code = col_character()
)
```

**Comment by logstar** [comment]
@jharenza @runjin326 - Thank you for the updates.

All md5sum checks passed. The extra tab is removed.

```text
Checking MD5 hashes...
histologies.tsv: OK
cnv-cnvkit.seg.gz: OK
cnv-controlfreec.tsv.gz: OK
consensus_wgs_plus_cnvkit_wxs.tsv.gz: OK
snv-consensus-plus-hotspots.maf.tsv.gz: OK
data-files-description.md: OK
efo-mondo-map.tsv: OK
ensg-hugo-rmtl-mapping.tsv: OK
fusion-arriba.tsv.gz: OK
fusion-putative-oncogenic.tsv: OK
fusion-starfusion.tsv.gz: OK
gene-counts-rsem-expected_count-collapsed.rds: OK
gene-expression-rsem-tpm-collapsed.rds: OK
intersect_cds_lancet_strelka_mutect_WGS.bed: OK
intersect_strelka_mutect_WGS.bed: OK
release-notes.md: OK
sv-manta.tsv.gz: OK
uberon-map-gtex-group.tsv: OK
uberon-map-gtex-subgroup.tsv: OK
WGS.hg38.lancet.300bp_padded.bed: OK
WGS.hg38.lancet.unpadded.bed: OK
WGS.hg38.mutect2.vardict.unpadded.bed: OK
WGS.hg38.strelka2.unpadded.bed: OK
WGS.hg38.vardict.100bp_padded.bed: OK
independent-specimens.rnaseq.primary.eachcohort.tsv: OK
independent-specimens.rnaseq.relapse.eachcohort.tsv: OK
independent-specimens.wgswxspanel.primary.eachcohort.tsv: OK
independent-specimens.wgswxspanel.relapse.eachcohort.tsv: OK
independent-specimens.rnaseq.primary.tsv: OK
independent-specimens.rnaseq.relapse.tsv: OK
independent-specimens.wgswxspanel.primary.tsv: OK
independent-specimens.wgswxspanel.relapse.tsv: OK

> edf <- readr::read_tsv('data/efo-mondo-map.tsv')

── Column specification ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
cols(
  cancer_group = col_character(),
  efo_code = col_character(),
  mondo_code = col_character()
)
```

```text
$ head download-data.sh 

set -e
set -o pipefail

# Use the OpenPBTA bucket as the default.
URL=${OPENPBTA_URL:-https://s3.amazonaws.com/d3b-openaccess-us-east-1-prd-pbta/open-targets}
RELEASE=${OPENPBTA_RELEASE:-v9}
PREVIOUS=${OPENPBTA_RELEASE:-v8}

# Remove old symlinks in data
```

**Pull request merged**
