### PR TITLE
Test RUVSeq for identifying and removing features of unwanted variation 

### PR DESCRIPTION
**Pull request by komalsrathi**
#### What scientific question is your analysis addressing?

Evaluate RUVSeq to remove unwanted variation from RNASeq data

#### What was your approach?

**General Approach:**

RUVg is easy to incorporate with DESeq2 but RUVr method requires an edgeR output as input. So I will be testing RUVr with edgeR only and RUVg with both DESeq2 and edgeR.

1. RUVg: Estimating the factors of unwanted variation using control genes. RUVg was tested with both DESeq2 as well as edgeR. Three sets of control genes were evaluated:
a. Housekeeping genes identified in Normal tissues by the HRT protocol
b. Housekeeping genes identified collectively in Tumors + Normal tissues using the HRT protocol
c. Empirical control genes from the first-pass DGE analysis. These are “in-silico empirical” negative controls, e.g., least significantly DE genes (`p-adjust > 0.05`) based on a first-pass DE analysis performed prior to RUVg normalization.
d. Housekeeping genes identified in Normal tissues by the HRT protocol (so the ones used in point a) that are differentially expressed with `p-adjust < 0.05` from the first-pass DGE analysis.

2. RUVr: use the residuals from a DGE analysis (without batch correction) as a source of unwanted variation to correct for in a second pass DGE. RUVr was tested only using edgeR.

**Criterion for Matched samples:**

For the test data, we want to look at individual cohort + cancer group with matched samples in order to avoid identifying differences due to biology. I have identified 4 cohort + cancer_group categories that have matched samples with multiple library prep methods.

1. 24 Acute Lymphoblastic Leukemia samples (TARGET)
2. 10 High-grade glioma/astrocytoma (PBTA)
3. 4 CNS Embryonal tumor (PBTA)
4. 4 Diffuse midline glioma (PBTA)

Based on the sample size, I will be testing `24 ALL samples from TARGET` and `10 HGG samples from PBTA`.

**Experiment Design:**

My goal is to perform a `paired analysis` using an experimental design that takes the `Kids_First_Participant_ID` of match samples and `RNA_library` into account. The idea behind this is to find differences ONLY due to RNA_library.

**Other methods:**

I have also added `ComBat` and `ComBat_seq` from the `sva` package as a comparison to the `RUVseq` package.

#### What GitHub issue does your pull request address?

https://github.com/PediatricOpenTargets/ticket-tracker/issues/279

#### Which areas should receive a particularly close look?

1. Model design for DEG analysis
2. Criterion to identify negative control gene lists
3. PCA/UMAP corresponding to RUVSeq analysis
4. PCA/UMAP for ComBat and ComBat_seq analysis

#### Is there anything that you want to discuss further?

What do the reviewers think about using `ComBat` or `ComBat_seq` over `RUVseq`? 

#### Is the analysis in a mature enough form that the resulting figure(s) and/or table(s) are ready for review?

Yes

#### What types of results are included (e.g., table, figure)?

Figures in PDF format. Please see README. 

#### What is your summary of the results?

Out of all the methods, it seems to me that `ComBat` performs pretty well at correcting batch effects due to `RNA_library`.

#### Reproducibility Checklist

- [x] The dependencies required to run the code in this pull request have been added to the project Dockerfile.
- [ ] This analysis has been added to continuous integration.

#### Documentation Checklist

- [x] This analysis module has a `README` and it is up to date.
- [ ] This analysis is recorded in the table in `analyses/README.md` and the entry is up to date.
- [x] The analytical code is documented and contains comments.

### CODE REVIEW

**Comment by aadamk** [comment]
Thanks for these analyses @komalsrathi 

Key takeaways for me using UMAP embeddings as a reference: 
1. Empirically defined negative control gene and HK normal genes are the more effective batch correction methods.  
2. UQ normalization is insufficient to correct for batch
3. Combat-seq did not perform as well for TARGET relative to RUVg-based approaches from (1)
4. In TARGET, RUVg approaches from (1) clearly outperformed latent factor (RUVr method). 

Just to confirm, the UMAP plots at varying k's correspond to the RUV-normalized counts, right? 

A couple of minor changes: 
1. Can you replace the chisq test with ks.test for uniformity? It seems the former is not resulting in a rejection of the null for distributions that are clearly not uniform (didn't see any issues with the parameters you specified). 
2. Can you compare this [output](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/blob/rnaseq-batch-correct/analyses/rnaseq-batch-correct/output/match_target_all/deseq2_analysis/stranded_vs_polya_dge_deseq2_histogram.pdf) with the output one gets for a differential expression analysis using RUVg at k=5? E.g. for the last plot [here](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/blob/rnaseq-batch-correct/analyses/rnaseq-batch-correct/output/match_target_all/deseq2_analysis/hk_genes_normals_stranded_vs_polya_dge_ruvg_deseq2_histogram.pdf), can you show the results of the full transcriptome (e.g. number of significant genes, etc) when using W_5 as a covariate in the model?

The reason I ask for (2) is that I would have expected that a more uniform distribution of p-values among HK normal genes would correspond to the optimal result in UMAP space, but it appears to be the opposite (at k=5, batch effects seem to be taken care of and not so for k=1 for the TARGET results [here](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/blob/rnaseq-batch-correct/analyses/rnaseq-batch-correct/output/match_target_all/deseq2_analysis/hk_genes_normals_stranded_vs_polya_dge_ruvg_deseq2_clustering.pdf) and [here](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/blob/rnaseq-batch-correct/analyses/rnaseq-batch-correct/output/match_target_all/deseq2_analysis/hk_genes_normals_stranded_vs_polya_dge_ruvg_deseq2_histogram.pdf), for instance).

**Comment by aadamk** [comment]
I also wonder - should we be including `RNA_library` as a covariate in the regression model [here](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/blob/bbd849c9e9ca6e8df4b0add42b2bbc6792e265fa/analyses/rnaseq-batch-correct/util/ruvg_test.R#L50) if we think RUVg is taking care of batch using negative control genes [here](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/blob/bbd849c9e9ca6e8df4b0add42b2bbc6792e265fa/analyses/rnaseq-batch-correct/util/ruvg_test.R#L39)? e.g. shouldn''t the formula in line 50 just be: 

`design <- model.matrix(as.formula(paste0('~0 + W_', i, '+ patient_id')), data = pData(ruvg_set))` for DGE analysis after running RUVg, then do all of the histogram evaluations (UMAP results should be unaffected since those are just normalized counts from the `ruvg` step)? 

With `RNA_library` in the formula, it would resemble combat/combat-seq, where one uses the full transcriptome to regress out batch effects. Whereas using only `W_k`, we're saying that negative control genes capture batch effects with more specificity than the full transcriptome and should be sufficient to correct for that artifact.

**Comment by komalsrathi** [comment]
> Just to confirm, the UMAP plots at varying k's correspond to the RUV-normalized counts, right?

Yes, correct. According to the [plotting function](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/blob/rnaseq-batch-correct/analyses/rnaseq-batch-correct/util/edaseq_plot.R#L15-L21) that I adapted from the `EDASeq` package, it will use the normalized counts if present in the expression set - this is true when RUVg or RUVr is applied. So all the PCA/UMAP plots post RUVg/RUVr are using normalized counts.

> Can you replace the chisq test with ks.test for uniformity? It seems the former is not resulting in a rejection of the null for distributions that are clearly not uniform (didn't see any issues with the parameters you specified).

I have added ks test for uniformity along with chisq test. Added equivalent files with the suffix: `_ks_pvalues.tsv`.

> I also wonder - should we be including `RNA_library` as a covariate in the regression model [here](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/blob/bbd849c9e9ca6e8df4b0add42b2bbc6792e265fa/analyses/rnaseq-batch-correct/util/ruvg_test.R#L50) if we think RUVg is taking care of batch using negative control genes [here](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/blob/bbd849c9e9ca6e8df4b0add42b2bbc6792e265fa/analyses/rnaseq-batch-correct/util/ruvg_test.R#L39)? e.g. shouldn''t the formula in line 50 just be:
`design <- model.matrix(as.formula(paste0('~0 + W_', i, '+ patient_id')), data = pData(ruvg_set))` for DGE analysis after running RUVg, then do all of the histogram evaluations (UMAP results should be unaffected since those are just normalized counts from the `ruvg` step)?
With `RNA_library` in the formula, it would resemble combat/combat-seq, where one uses the full transcriptome to regress out batch effects. Whereas using only `W_k`, we're saying that negative control genes capture batch effects with more specificity than the full transcriptome and should be sufficient to correct for that artifact.

I think you are right and this design makes more sense. Should I remove `RNA_library` from the first pass as well - wondering if it would be biasing our results if RUVseq is working under the assumption that the user has no idea about what is causing the unwanted variation or batch effect ? 

So what I am thinking is 1) only keeping the `RNA_library` for expression filter [here](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/blob/rnaseq-batch-correct/analyses/rnaseq-batch-correct/code/03-test_ruvseq.R#L76) 2) removing it from the design of first pass DGE [here](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/blob/rnaseq-batch-correct/analyses/rnaseq-batch-correct/code/03-test_ruvseq.R#L74) because that is being used by [DESeq2 first pass](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/blob/rnaseq-batch-correct/analyses/rnaseq-batch-correct/code/03-test_ruvseq.R#L127) and [edgeR first pass](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/blob/rnaseq-batch-correct/analyses/rnaseq-batch-correct/code/03-test_ruvseq.R#L186-L196) differential expression results. Not sure if I am overthinking...

**Comment by komalsrathi** [comment]
> Can you compare this [output](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/blob/rnaseq-batch-correct/analyses/rnaseq-batch-correct/output/match_target_all/deseq2_analysis/stranded_vs_polya_dge_deseq2_histogram.pdf) with the output one gets for a differential expression analysis using RUVg at k=5? E.g. for the last plot [here](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/blob/rnaseq-batch-correct/analyses/rnaseq-batch-correct/output/match_target_all/deseq2_analysis/hk_genes_normals_stranded_vs_polya_dge_ruvg_deseq2_histogram.pdf), can you show the results of the full transcriptome (e.g. number of significant genes, etc) when using W_5 as a covariate in the model?

I have made the change in RUVg script [here](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/blob/rnaseq-batch-correct/analyses/rnaseq-batch-correct/util/ruvg_test.R#L82-L85) and RUVr script [here](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/blob/rnaseq-batch-correct/analyses/rnaseq-batch-correct/util/ruvr_test.R#L56-L60) such that the full transcriptome is used for creating the p-value histogram after second pass DGE. I am still using only the negative control genes after second pass DGE analysis for the test of uniformity per [this](https://github.com/PediatricOpenTargets/ticket-tracker/issues/279#issuecomment-1092173873) comment.

**Comment by aadamk** [comment]
> > Can you compare this [output](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/blob/rnaseq-batch-correct/analyses/rnaseq-batch-correct/output/match_target_all/deseq2_analysis/stranded_vs_polya_dge_deseq2_histogram.pdf) with the output one gets for a differential expression analysis using RUVg at k=5? E.g. for the last plot [here](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/blob/rnaseq-batch-correct/analyses/rnaseq-batch-correct/output/match_target_all/deseq2_analysis/hk_genes_normals_stranded_vs_polya_dge_ruvg_deseq2_histogram.pdf), can you show the results of the full transcriptome (e.g. number of significant genes, etc) when using W_5 as a covariate in the model?
> 
> I have made the change in RUVg script [here](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/blob/rnaseq-batch-correct/analyses/rnaseq-batch-correct/util/ruvg_test.R#L82-L85) and RUVr script [here](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/blob/rnaseq-batch-correct/analyses/rnaseq-batch-correct/util/ruvr_test.R#L56-L60) such that the full transcriptome is used for creating the p-value histogram after second pass DGE. I am still using only the negative control genes after second pass DGE analysis for the test of uniformity per [this](https://github.com/PediatricOpenTargets/ticket-tracker/issues/279#issuecomment-1092173873) comment.

Thanks, though can you still include the p-val histograms for only the negative control genes that you originally had? those will likely be helpful for deciding optimal k and the full transcriptome plots are helpful for seeing the effect of the correction on numbers of DEGs, etc. 

To answer your question above regarding removing rna_library from first-pass DGE, I'll specify for each of the comparisons below: 
1. DGE empirical genes - negative control gene set p>0.05 from first pass DGE: _I would remove rna_library from here because including would identify changes that are least altered by polya vs stranded in a matched sample analysis._ 
2. DGE empirical hk genes - p<0.05 intersecting with HRT: _I would not remove rna_library here because this would help to identify changes in hk genes that are dependent on polyA vs stranded._ 
3. Hk genes normals - full HK gene set as negative control gene set. _this wouldn't depend on first pass, so not relevant._ 
4. Hk gene tumor normal - 25 gene set for T/N stably expressed genes. _this wouldn't depend on first pass, so not relevant._

**Comment by aadamk** [comment]
Updating after slack conversation: 
We'll prioritize the Hk genes normals only analysis going forward given the favorable UMAP results and its potential generalizability for many use cases. 
So the only action item is to remove `RNA_library` from the `Hk genes normals only` design and retain the factor of unwanted variation (e.g. `W_k`) in the design for DGE analysis. 
Key outputs: p-value histograms (for all k's) of HRT atlas genes only, p-value histograms (for all k's) with number of DEGs for full transcriptome).

**Comment by komalsrathi** [comment]
Hi @aadamk I have made these changes in the last there commits. The results after RUVg/RUvr are looking quite weird to me - with almost all genes as differentially expressed. Also my old code combining `geom_histogram` and `geom_density` is not working anymore (especially the numbers on the y-axis seem extremely large for some reason) so I am not using it and just generating a basic histogram. When you get a chance, can you take a look at just the last three commits and determine if those changes make sense - especially the design within RUVg/RUVr functions in the util directory?

**Comment by aadamk** [comment]
> Hi @aadamk I have made these changes in the last there commits. The results after RUVg/RUvr are looking quite weird to me - with almost all genes as differentially expressed. Also my old code combining `geom_histogram` and `geom_density` is not working anymore (especially the numbers on the y-axis seem extremely large for some reason) so I am not using it and just generating a basic histogram. When you get a chance, can you take a look at just the last three commits and determine if those changes make sense - especially the design within RUVg/RUVr functions in the util directory?

Thanks. 
The design you specified was what I had in mind, but I agree, the outputs are not interpretable since `patient_id` is the only 'biological' covariate (which is just one multi-level categorical variable). I keep having to remind myself that this is not a typical DGE analysis with two distinct groups, but rather technical replicates - the p-value distributions that we saw in this context when including `rna_library` may differ substantially from a real use case. For that reason, maybe we can retain only the UMAP results for proof of principle and leave these histograms behind. We can use the p-value histogram approach when evaluating a DGE use case (E.g. Neuroblastoma myc-N amplified vs non-amplified) for full transcriptome, negative control genes, and positive control genes (e.g. myc-n related gene set).

 I'm unsure whether anything should be merged at this point (likely we will need to prove the method works in tumor only and T/N comparisons first, then write up generalizable scripts for running batch correction). 

Next steps for me would be: 
1. Evaluate the hk genes normals and dge empirical HK gene approach (1st and 2nd pass DGE) in a neuroblastoma comparison.  
2. Identify a suitable tumor-normal comparison for evaluation of the above two approaches.

**Comment by komalsrathi** [comment]
@aadamk Right now this PR has been tested for the samples that are from same participant but associated with multiple library types, so [this design](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/blob/rnaseq-batch-correct/analyses/rnaseq-batch-correct/code/03-test_ruvseq.R#L74) for first-pass works and [this design](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/blob/rnaseq-batch-correct/analyses/rnaseq-batch-correct/util/ruvg_test.R#L52) for second pass woks i.e.:

```
# first pass
design <- model.matrix(~ 0 + patient_id + rna_library)

# second pass
design <- model.matrix(as.formula(paste0('~0 + W_', i, '+ patient_id')), data = pData(ruvg_set))
```

For real use cases, the designs will change:

1)  MYCN amplified and non-amplified comparison:

```
# OT histologies and filter to NBL
dat <- read_tsv('~/Projects/PediatricOpenTargets/OpenPedCan-analysis/data/histologies.tsv')
dat <- dat %>% filter(experimental_strategy == "RNA-Seq", cancer_group == "Neuroblastoma")

# breakdown by molecular subtype
plyr::count(dat$molecular_subtype)
             x freq
1     MYCN amp   55
2 MYCN non-amp  309
3      Unknown    1
4         <NA>    3

# breakdown by RNA library
plyr::count(dat$RNA_library)
         x freq
1   poly-A  157
2 stranded  210
3     <NA>    1

# breakdown by molecular subtype and RNA library
> plyr::count(dat,c("molecular_subtype", "RNA_library"))
  molecular_subtype RNA_library freq
1          MYCN amp      poly-A   32
2          MYCN amp    stranded   23
3      MYCN non-amp      poly-A  124
4      MYCN non-amp    stranded  184
5      MYCN non-amp        <NA>    1
6           Unknown    stranded    1
7              <NA>      poly-A    1
8              <NA>    stranded    2
```

Are these the design changes you had in mind for the MYCN amp vs non-amp analysis?:

```
# first pass
design <- model.matrix(~ 0 + molecular_subtype)

# second pass
design <- model.matrix(as.formula(paste0('~0 + W_', i, '+ molecular_subtype')), data = pData(ruvg_set))
```

2) For tumor vs normal, we could make one harmonized `group` that has `cancer_group` for tumors and `gtex_group` for normal tissues and use it instead of `molecular_subtype`

Please let me know if there are suggestions to the proposed design changes.

**Comment by komalsrathi** [comment]
Based on our 1:1 today, I will do the NBL comparison and once the results look acceptable, @sangeetashukla can proceed with the actual Tumor vs Normal comparisons.

**Comment by jharenza** [comment]
> Based on our 1:1 today, I will do the NBL comparison and once the results look acceptable, @sangeetashukla can proceed with the actual Tumor vs Normal comparisons.

Thanks for continuing this @komalsrathi! Will you please create a new ticket describing exactly what will need to be done by @sangeetashukla once this PR is merged? If I am thinning about this correctly, we will merge this batch correction workflow, then apply to cohorts of interest and assess whether the results look promising enough to apply this globally? Cc @aadamk @afarrel 

Would rather get the method merged since the PR has become very long, rather than stagger more branches on top of this for comparisons. We can always update the method later if something looks amiss.

**Comment by komalsrathi** [comment]
We have a call today so I will walk @sangeetashukla through my code and PR + next steps. Once I have finished the NBL comparison and @aadamk has reviewed we will open a new ticket.

**Comment by komalsrathi** [comment]
@aadamk there is something weird going on - I cannot figure out where because the design looks ok to me. It looks like all expressed genes are differentially expressed between the two molecular subtypes with many pvalues 0 i.e < 2.225074e-308. 

Reproducible code snippet:

```
# OpenPedCan-analysis repo as working directory
setwd('~/Projects/OpenPedCan-analysis/')
library(tidyverse)
library(DESeq2)
library(DEGreport)

# modified degCheckFactors function to color and facet by subtype
degCheckFactors <- function(counts, metadata){
  counts <- as.data.frame(counts)
  geoMeanNZ <- function(x) {
    if (all(x == 0)) {
      0
    }
    else {
      exp(sum(log(x[x > 0]))/length(x))
    }
  }
  geoMeans <- apply(counts, 1, geoMeanNZ)
  loggeomeans <- log(geoMeans)
  df <- lapply(colnames(counts), function(s) {
    cnts <- counts[[s]]
    r <- (log(cnts) - loggeomeans)[is.finite(loggeomeans) & 
                                     cnts > 0]
    data.frame(ratios = r, sample = s, stringsAsFactors = FALSE)
  }) %>% bind_rows()
  df <- df %>%
    inner_join(metadata, by = c("sample" = "bs_id"))
  p <- ggplot(df, aes(ratios, group = sample, color = molecular_subtype)) + geom_density() + 
    theme_bw() + xlim(-4, 4)
  p <- p + facet_wrap(~molecular_subtype, scales = "free") + guides(color = "none")
  p
}

# read histology
htl_df <- readr::read_tsv('data/histologies.tsv')

# read expected counts
cnt_df <- readRDS('data/gene-counts-rsem-expected_count-collapsed.rds')

# dimensions
dim(cnt_df) # 36718 19995

# filter histology
selected_htl_df <- htl_df %>%
  filter(experimental_strategy == "RNA-Seq",
         sample_type == "Tumor",
         cohort %in% 'TARGET',
         cancer_group %in% 'Neuroblastoma',
         !is.na(molecular_subtype)) 

# filter expression (zero counts)
cnt_df <- cnt_df %>%
  dplyr::select(selected_htl_df$Kids_First_Biospecimen_ID)
cnt_df <- cnt_df[rowSums(cnt_df) > 0,]

# dimensions
dim(cnt_df) # 31331   156

# create design
colnames(cnt_df) <- gsub('TARGET-[0-9]{2}-', '', colnames(cnt_df)) # shorten bs ids for TARGET samples
bs_id <- gsub('TARGET-[0-9]{2}-', '', selected_htl_df$Kids_First_Biospecimen_ID) # shorten bs ids for TARGET samples
molecular_subtype <- factor(as.character(selected_htl_df$molecular_subtype))
design <- model.matrix(~ 0 + molecular_subtype)
colnames(design) <- levels(molecular_subtype)

table(as.data.frame(design))

        MYCN non-amp
MYCN amp   0   1
       0   0 124
       1  32   0

# filter by expression and convert to DGElist
counts_object <- edgeR::DGEList(counts = cnt_df, group = molecular_subtype)
counts_object_filtered <- edgeR::filterByExpr(counts_object, group = molecular_subtype)
counts_object <- counts_object[counts_object_filtered, , keep.lib.sizes = FALSE]

# dimensions
dim(counts_object$counts) # 19866   156

# differentially expressed genes between amp vs non-amp subtypes
dds <- DESeq2::DESeqDataSetFromMatrix(countData = round(counts_object$counts), 
                                      colData =  data.frame(molecular_subtype), 
                                      design = design)
dds <- DESeq2::DESeq(dds)

# QC
# 1. distribution of gene ratios using normalized counts
counts_norm <- DESeq2::counts(dds, normalized = TRUE)
degCheckFactors(counts = counts_norm, metadata = data.frame(bs_id, molecular_subtype))

# 2. heatmap of the top 100 most variable genes
counts_dat <- DESeq2::counts(dds) # raw counts
counts_log <- log2(counts_dat + 0.5) # log2 counts
var_genes <- apply(counts_log, 1, var) # variable genes
select_var <- names(sort(var_genes, decreasing=TRUE))[1:100] # get top 100
highly_variable_dat <- counts_log[select_var,] # matrix of top 100 most variable genes
print(dim(highly_variable_dat)) # 100 x 156
pheatmap::pheatmap(highly_variable_dat, 
                   show_colnames = FALSE, 
                   fontsize_row = 5,
                   scale = "row",
                   main = "Top 100 most variable genes",
                   annotation_colors = list(molecular_subtype = 
                                              c("MYCN amp" = "#F8766D", "MYCN non-amp" = "#00BFC4")),
                   annotation_col = as.data.frame(SummarizedExperiment::colData(dds))["molecular_subtype"])

# dge output
dge_output <- DESeq2::results(dds, cooksCutoff = FALSE, pAdjustMethod = 'BH')
DESeq2::plotMA(dge_output) # MA plot
dge_output <- dge_output %>% 
  as.data.frame() %>% 
  rownames_to_column('gene') %>%
  arrange(padj) 

# all genes are differentially expressed
> summary(dge_output$pvalue)
     Min.   1st Qu.    Median      Mean   3rd Qu.      Max. 
0.000e+00 0.000e+00 0.000e+00 7.910e-10 0.000e+00 9.995e-06 

> summary(dge_output$padj)
     Min.   1st Qu.    Median      Mean   3rd Qu.      Max. 
0.000e+00 0.000e+00 0.000e+00 7.910e-10 0.000e+00 9.995e-06 
```

**Comment by komalsrathi** [comment]
@aadamk as suggested in our 1:1 yesterday, I have updated the dimensions of the count data at various points above.

**Comment by aadamk** [comment]
Ok, so no major concern with the dimensionality of the dataset. 

the bioc package `DEGreport` offers a few handy utilities for QC. 
Can you run the following functions using a DESeq2 object as input? 

1. Given a DESeq2 object `dds`, get histograms of the counts with `counts <- counts(dds, normalized = TRUE)` and `degCheckFactors(counts)`. If you can color by molecular subtype, that would help distinguish what will likely be a busy plot. 
2. An MA plot showing log2 fold change as a function of mean expression - `degMA` function
3. A heatmap of the top 100 most variable genes - `pheatmap(log2(counts(dds) + 0.5)[1:100,], 
         annotation_col = as.data.frame(colData(dds))[,1:4],
         annotation_colors = degColors(colData(dds)[1:4],
                                       con_values = c("white",
                                                      "red")
                                       )
         )`

where colData contains lib size, norm factors, and size factors from the DESeq object.

**Comment by komalsrathi** [comment]
Updated the code in [above comment](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/pull/168#issuecomment-1123808276) to include code for the following plots:

1. Distribution of gene ratios using normalized counts

image

2. Heatmap of the top 100 most variable genes

image

3. MA plot 

image

**Comment by aadamk** [comment]
The gene ratios plot doesn’t seem consistent with the results of the ma plot. The ma plot is unusual as you would expect most log fold change values to hover around 0.
@sangeetashukla - can you dig into this use case? We’re looking to run a simple DGE of mycn amplified vs non-amplified TARGET neuroblasomas (then later test batch correction). Can you run on expected count data and see if you reproduce the same issue as above from Komal.

**Comment by sangeetashukla** [comment]
> The gene ratios plot doesn’t seem consistent with the results of the ma plot. The ma plot is unusual as you would expect most log fold change values to hover around 0. @sangeetashukla - can you dig into this use case? We’re looking to run a simple DGE of mycn amplified vs non-amplified TARGET neuroblasomas (then later test batch correction). Can you run on expected count data and see if you reproduce the same issue as above from Komal.

@aadamk Sure, I will look into this.

**Comment by komalsrathi** [comment]
@sangeetashukla for reference, this is the reproducible code to get the above DEG results/plots: https://github.com/PediatricOpenTargets/OpenPedCan-analysis/pull/168#issuecomment-1123808276 - let me know if you have questions. Thank you!!

**Comment by aadamk** [comment]
hi @sangeetashukla 
to follow up from our 1:1, we can pivot over to HGG/DMG PBTA samples as our use case. 

The genes for which we can track p-values can be: 
1. negative control genes: HRT gene atlas hk genes
2. positive control genes: from https://doi.org/10.1186/s12915-022-01324-0, [Additional file 4: Table S2.](https://static-content.springer.com/esm/art%3A10.1186%2Fs12915-022-01324-0/MediaObjects/12915_2022_1324_MOESM4_ESM.xlsx). Under `Merged_differential_expression` tab, select genes whose adj p-value across K27M  vs WT day5 < 0.05 (so filtering on column Q). These are stemness genes that are differentially expressed in h3k28m vs WT tumors. 

can you run the following? 
1. standard DESeq2 DGE analysis on `High-grade glioma/astrocytoma, H3 wildtype` harmonized diagnosis vs `Diffuse midline glioma, H3 K28-mutant` harmonized diagnosis, where `tumor_descriptor == 'Initial CNS Tumor'`
2. create table of p-values of negative control genes and positive control genes from (1). 
3. run deseq2 with ruv-seq at multiple `k's` (from 1 to 5) using hrt atlas hk genes (>2000 genes) as negative control genes, comparing the two harmonized diagnoses from (1) as the biological factor in the design and W_k as the technical/batch factor in the design. 
4. create table of p-values from (3) for negative and positive control genes. 
5. create a histogram of p-values of negative control genes from the analysis in (3). 
6. UMAP plot for RUVg normalized and separate UMAP plot for non-normalized counts, coloring by the harmonized diagnoses and varying data point shapes by RNA_library. 

i can touch base on slack if needed as well.

**Comment by aadamk** [comment]
closing this PR to open a revised one as I have re-factored the scripts, added features, and generated tumor-normal and tumor-only utilities + run scripts. 
Note: I receive the following git-lfs error regarding data quota when attempting to push even small (10-100 kB) input files to the repo

`batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.
error: failed to push some refs to 'https://github.com/PediatricOpenTargets/OpenPedCan-analysis.git'`

**Pull request closed without merging**
