### PR TITLE
Rerun all of the modules with the new docker image

### PR DESCRIPTION
**Pull request by ewafula**
#### What scientific question is your analysis addressing?

Rerun all of the modules with the new docker image.

#### What was your approach?
- Rerun the entire module and update any module that fails or has warnings as a result of deprecated R or Python functions as a result of newer packages/modules
-  Update Dockerfile if  any dependency is missing

#### What GitHub issue does your pull request address?
- https://github.com/PediatricOpenTargets/ticket-tracker/issues/556

#### Which areas should receive a particularly close look?
Provide suggestions if any other module apart from those listed below Utilized in OPC need  to be included and checked for updates:
[**Dockerfile**]
- [x] install ubuntu libncurses5 library required for GISTIC runs

[**Rerun data pre-release analysis modules**]
- [x] independent-samples 
- [x] fusion_filtering
- [x] run-gistic
- [x] focal-cn-file-preparation
- [x] fusion-summary
- [x] tmb-calculation
- [x] tp53_nf1_score
- [x] data-pre-release-qc

[**Rerun molecular subtyping and addition data pre-release module**]
- [x] molecular-subtyping-ATRT
- [x] molecular-subtyping-chordoma
- [x] molecular-subtyping-CRANIO
- [x] molecular-subtyping-embryonal
- [x] molecular-subtyping-EPN
- [x] molecular-subtyping-EWS
- [x] molecular-subtyping-HGG 
- [x] molecular-subtyping-LGAT
- [x] molecular-subtyping-MB
- [x] molecular-subtyping-neurocytoma
- [x] molecular-subtyping-pathology
- [x] molecular-subtyping-integrate
- [x] independent-samples
- [x] create-subset-files

[**Rerun data post-release modules**]
- [x] gene_match
- [x] efo-mondo-mapping
- [x] mtp-annotations
- [x] long-format-table-utils
- [x] fusion-frequencies
- [x] cnv-frequencies
- [x] snv-frequencies
- [x] rna-seq-expression-summary-stats
- [x] filter-mtp-tables
- [x] mtp-tables-qc-checks
- [x] rnaseq-batch-correct

#### Is there anything that you want to discuss further?
NA

#### Is the analysis in a mature enough form that the resulting figure(s) and/or table(s) are ready for review?
YES

#### What types of results are included (e.g., table, figure)?
Module results that can be uploaded to GitHub with PR 

#### What is your summary of the results?
Successful module runs with new docker image

#### Reproducibility Checklist

- [x] The dependencies required to run the code in this pull request have been added to the project Dockerfile.
- [x] This analysis has been added to continuous integration.

#### Documentation Checklist

- [x] This analysis module has a `README` and it is up to date.
- [x] This analysis is recorded in the table in `analyses/README.md` and the entry is up to date.
- [x] The analytical code is documented and contains comments.

### CODE REVIEW

**Comment by jharenza** [comment]
@ewafula is this done/complete? Also noticed cnv consensus wasn't in here, was that bc of the known issue or just forgotten - in any case, you did test it, so yay!

**Comment by ewafula** [comment]
Yes, this one is done. I intentionally left our the cnv consensus module because I was focused on debugging the the snakemake workflow. Turns out it was docker issue associated Debian Stretch limitations. Can be merged. 

I also left out the cnv consensus module from the repo README update for the data release process because you had suggested that it needs to wrapped in CWL and run on CAVATICA with as pre-release workflows.

**Comment by jharenza** [comment]
Ok thanks- can you put into the release readme for now then since fixed

**Review by jharenza — APPROVED** [review]
I think the TP53 changes are happening because we don't have a seed set for this, and we should, though it does not affect the overall call for these samples. I will create a ticket for this.

**Pull request merged**
