### PR TITLE
Fusion Putative Oncogenic rerun with v10

### PR DESCRIPTION
**Pull request by runjin326**
#### What scientific question is your analysis addressing?
Re-generate `fusion-putative-oncogenic.tsv` with v10 release data.

#### What was your approach?
Download v10 data and re-generate the files. 

#### What GitHub issue does your pull request address?
https://github.com/PediatricOpenTargets/ticket-tracker/issues/188

#### Which areas should receive a particularly close look?
1) Please merge the most up-to-date dev for new independent sample list before running 
2) Please review the attached QC file in results section of this PR for QC.

#### Is there anything that you want to discuss further?
Just note that we need to revisit [this ticket ](https://github.com/PediatricOpenTargets/ticket-tracker/issues/129) to find a good filtering parameter for present in >n `broad_histology`.

#### Is the analysis in a mature enough form that the resulting figure(s) and/or table(s) are ready for review?
Yes.

#### What types of results are included (e.g., table, figure)?
```
FilteredFusion.tsv
fusion-putative-oncogenic.tsv
fusion-recurrent-fusion-bycancergroup.tsv
fusion-recurrent-fusion-bysample.tsv
fusion-recurrently-fused-genes-bycancergroup.tsv
fusion-recurrently-fused-genes-bysample.tsv
```
And only `fusion-putative-oncogenic.tsv` would be in data release.

#### What is your summary of the results?
1) All loss of fusion calls were expected ( either due to filter `present in >4 broad_histology` or lack of oncogenic gene annotation
2) All gains were from new samples added in ( for this release, only 40 PNOC RNA samples were added)

Please see the attached pdf for detailed QC for the results: 
[QC_fusion_filtering_v10.pdf](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/files/7312337/QC_fusion_filtering_v10.pdf)

3) Also note that changes in the following files were due to changes in independent sample lists or update of `cancer_group`. 
- These changes should all be expected since we separated QC'd histology file for `cancer_group` change and independent sample lists. 

```
fusion-recurrent-fusion-bycancergroup.tsv
fusion-recurrent-fusion-bysample.tsv
fusion-recurrently-fused-genes-bycancergroup.tsv
fusion-recurrently-fused-genes-bysample.tsv
```

#### Reproducibility Checklist

- [x] The dependencies required to run the code in this pull request have been added to the project Dockerfile.
- [ ] This analysis has been added to continuous integration.

#### Documentation Checklist

- [x] This analysis module has a `README` and it is up to date.
- [ ] This analysis is recorded in the table in `analyses/README.md` and the entry is up to date.
- [x] The analytical code is documented and contains comments.

### CODE REVIEW

**Comment by runjin326** [comment]
@logstar, I will do a re-run of this module once the independent samples are in. I will ping you when that is ready. You can hold off reviewing this for now. Thanks!

**Comment by logstar** [comment]
@runjin326 I re-ran `./run_fusion_merged.sh` with v10 data, but the `results/fusion-recurrent-fusion-bysample.tsv` is different from the latest PR.

```text
$ ls -lh ../../data/
total 881M
-rw-rw-r-- 1 ubuntu ubuntu 842M Sep 24 11:48 GRCh38.primary_assembly.genome.fa.gz
lrwxrwxrwx 1 ubuntu ubuntu   36 Oct  8 11:46 WGS.hg38.lancet.300bp_padded.bed -> v10/WGS.hg38.lancet.300bp_padded.bed
lrwxrwxrwx 1 ubuntu ubuntu   32 Oct  8 11:46 WGS.hg38.lancet.unpadded.bed -> v10/WGS.hg38.lancet.unpadded.bed
lrwxrwxrwx 1 ubuntu ubuntu   41 Oct  8 11:46 WGS.hg38.mutect2.vardict.unpadded.bed -> v10/WGS.hg38.mutect2.vardict.unpadded.bed
lrwxrwxrwx 1 ubuntu ubuntu   34 Oct  8 11:46 WGS.hg38.strelka2.unpadded.bed -> v10/WGS.hg38.strelka2.unpadded.bed
lrwxrwxrwx 1 ubuntu ubuntu   37 Oct  8 11:46 WGS.hg38.vardict.100bp_padded.bed -> v10/WGS.hg38.vardict.100bp_padded.bed
lrwxrwxrwx 1 ubuntu ubuntu   21 Oct  8 11:46 cnv-cnvkit.seg.gz -> v10/cnv-cnvkit.seg.gz
lrwxrwxrwx 1 ubuntu ubuntu   28 Oct  8 11:46 cnv-consensus-gistic.zip -> v10/cnv-consensus-gistic.zip
lrwxrwxrwx 1 ubuntu ubuntu   24 Oct  8 11:46 cnv-consensus.seg.gz -> v10/cnv-consensus.seg.gz
lrwxrwxrwx 1 ubuntu ubuntu   27 Oct  8 11:46 cnv-controlfreec.tsv.gz -> v10/cnv-controlfreec.tsv.gz
lrwxrwxrwx 1 ubuntu ubuntu   40 Oct  8 11:46 consensus_wgs_plus_cnvkit_wxs.tsv.gz -> v10/consensus_wgs_plus_cnvkit_wxs.tsv.gz
lrwxrwxrwx 1 ubuntu ubuntu   50 Oct  8 11:46 consensus_wgs_plus_cnvkit_wxs_autosomes.tsv.gz -> v10/consensus_wgs_plus_cnvkit_wxs_autosomes.tsv.gz
lrwxrwxrwx 1 ubuntu ubuntu   48 Oct  8 11:46 consensus_wgs_plus_cnvkit_wxs_x_and_y.tsv.gz -> v10/consensus_wgs_plus_cnvkit_wxs_x_and_y.tsv.gz
lrwxrwxrwx 1 ubuntu ubuntu   29 Oct  8 11:46 data-files-description.md -> v10/data-files-description.md
lrwxrwxrwx 1 ubuntu ubuntu   21 Oct  8 11:46 efo-mondo-map.tsv -> v10/efo-mondo-map.tsv
lrwxrwxrwx 1 ubuntu ubuntu   30 Oct  8 11:46 ensg-hugo-pmtl-mapping.tsv -> v10/ensg-hugo-pmtl-mapping.tsv
lrwxrwxrwx 1 ubuntu ubuntu   24 Oct  8 11:46 fusion-arriba.tsv.gz -> v10/fusion-arriba.tsv.gz
lrwxrwxrwx 1 ubuntu ubuntu   33 Oct  8 11:46 fusion-putative-oncogenic.tsv -> v10/fusion-putative-oncogenic.tsv
lrwxrwxrwx 1 ubuntu ubuntu   28 Oct  8 11:46 fusion-starfusion.tsv.gz -> v10/fusion-starfusion.tsv.gz
-rw-rw-r-- 1 ubuntu ubuntu  40M Sep 24 11:47 gencode.v27.primary_assembly.annotation.gtf.gz
lrwxrwxrwx 1 ubuntu ubuntu   49 Oct  8 11:46 gene-counts-rsem-expected_count-collapsed.rds -> v10/gene-counts-rsem-expected_count-collapsed.rds
lrwxrwxrwx 1 ubuntu ubuntu   42 Oct  8 11:46 gene-expression-rsem-tpm-collapsed.rds -> v10/gene-expression-rsem-tpm-collapsed.rds
lrwxrwxrwx 1 ubuntu ubuntu   19 Oct  8 11:46 histologies.tsv -> v10/histologies.tsv
lrwxrwxrwx 1 ubuntu ubuntu   55 Oct  8 11:46 independent-specimens.rnaseq.primary.eachcohort.tsv -> v10/independent-specimens.rnaseq.primary.eachcohort.tsv
lrwxrwxrwx 1 ubuntu ubuntu   44 Oct  8 11:46 independent-specimens.rnaseq.primary.tsv -> v10/independent-specimens.rnaseq.primary.tsv
lrwxrwxrwx 1 ubuntu ubuntu   55 Oct  8 11:46 independent-specimens.rnaseq.relapse.eachcohort.tsv -> v10/independent-specimens.rnaseq.relapse.eachcohort.tsv
lrwxrwxrwx 1 ubuntu ubuntu   44 Oct  8 11:46 independent-specimens.rnaseq.relapse.tsv -> v10/independent-specimens.rnaseq.relapse.tsv
lrwxrwxrwx 1 ubuntu ubuntu   71 Oct  8 11:46 independent-specimens.wgswxspanel.primary.eachcohort.prefer.wxs.tsv -> v10/independent-specimens.wgswxspanel.primary.eachcohort.prefer.wxs.tsv
lrwxrwxrwx 1 ubuntu ubuntu   60 Oct  8 11:46 independent-specimens.wgswxspanel.primary.eachcohort.tsv -> v10/independent-specimens.wgswxspanel.primary.eachcohort.tsv
lrwxrwxrwx 1 ubuntu ubuntu   60 Oct  8 11:46 independent-specimens.wgswxspanel.primary.prefer.wxs.tsv -> v10/independent-specimens.wgswxspanel.primary.prefer.wxs.tsv
lrwxrwxrwx 1 ubuntu ubuntu   49 Oct  8 11:46 independent-specimens.wgswxspanel.primary.tsv -> v10/independent-specimens.wgswxspanel.primary.tsv
lrwxrwxrwx 1 ubuntu ubuntu   71 Oct  8 11:46 independent-specimens.wgswxspanel.relapse.eachcohort.prefer.wxs.tsv -> v10/independent-specimens.wgswxspanel.relapse.eachcohort.prefer.wxs.tsv
lrwxrwxrwx 1 ubuntu ubuntu   60 Oct  8 11:46 independent-specimens.wgswxspanel.relapse.eachcohort.tsv -> v10/independent-specimens.wgswxspanel.relapse.eachcohort.tsv
lrwxrwxrwx 1 ubuntu ubuntu   60 Oct  8 11:46 independent-specimens.wgswxspanel.relapse.prefer.wxs.tsv -> v10/independent-specimens.wgswxspanel.relapse.prefer.wxs.tsv
lrwxrwxrwx 1 ubuntu ubuntu   49 Oct  8 11:46 independent-specimens.wgswxspanel.relapse.tsv -> v10/independent-specimens.wgswxspanel.relapse.tsv
lrwxrwxrwx 1 ubuntu ubuntu   47 Oct  8 11:46 intersect_cds_lancet_strelka_mutect_WGS.bed -> v10/intersect_cds_lancet_strelka_mutect_WGS.bed
lrwxrwxrwx 1 ubuntu ubuntu   36 Oct  8 11:46 intersect_strelka_mutect_WGS.bed -> v10/intersect_strelka_mutect_WGS.bed
lrwxrwxrwx 1 ubuntu ubuntu   20 Oct  8 11:46 release-notes.md -> v10/release-notes.md
lrwxrwxrwx 1 ubuntu ubuntu   42 Oct  8 11:46 snv-consensus-plus-hotspots.maf.tsv.gz -> v10/snv-consensus-plus-hotspots.maf.tsv.gz
lrwxrwxrwx 1 ubuntu ubuntu   19 Oct  8 11:46 sv-manta.tsv.gz -> v10/sv-manta.tsv.gz
lrwxrwxrwx 1 ubuntu ubuntu   54 Oct  8 11:46 tcga-gene-counts-rsem-expected_count-collapsed.rds -> v10/tcga-gene-counts-rsem-expected_count-collapsed.rds
lrwxrwxrwx 1 ubuntu ubuntu   47 Oct  8 11:46 tcga-gene-expression-rsem-tpm-collapsed.rds -> v10/tcga-gene-expression-rsem-tpm-collapsed.rds
lrwxrwxrwx 1 ubuntu ubuntu   29 Oct  8 11:46 uberon-map-gtex-group.tsv -> v10/uberon-map-gtex-group.tsv
lrwxrwxrwx 1 ubuntu ubuntu   32 Oct  8 11:46 uberon-map-gtex-subgroup.tsv -> v10/uberon-map-gtex-subgroup.tsv
drwxr-x--- 2 ubuntu ubuntu 4.0K Oct  8 11:45 v10
drwxr-x--- 2 ubuntu ubuntu 4.0K Oct  6 12:09 v9
$ git st
On branch fusion-filt-rerun
Your branch is up to date with 'upstream/fusion-filt-rerun'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
        modified:   results/fusion-recurrent-fusion-bysample.tsv
        modified:   ../../download-data.sh

no changes added to commit (use "git add" and/or "git commit -a")
$ git diff --stat results/fusion-recurrent-fusion-bysample.tsv
 analyses/fusion_filtering/results/fusion-recurrent-fusion-bysample.tsv | 24303 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++---------------------------------------------------------------
 1 file changed, 11388 insertions(+), 12915 deletions(-)

$ head results/fusion-recurrent-fusion-bysample.tsv
Sample  ABL1--BCR       AC005258.1--DAZAP1      AC008878.3--INSR        AC244472.3--TRBC2       ACTR1A--PPRC1   AFF1--KMT2A     ANKRD11--CBFA2T3        ANP32E--PLEKHO1 BANP--SLC7A5    BCR--ABL1      BRD3--RALGDS     BRF1--MTA1      C11orf95--RELA  C7orf50--MAD1L1 CBFA2T3--ACSF3  CBFA2T3--GSE1   CBFA2T3--SLC7A5 CBFA2T3--ZFPM1  CBFB--MYH11     CD81--PTMA      COL1A1--LRP1    CRTC1--COPE     CSNK1D--FOXK2   CXCR4--PTMA     DOT1L--MKNK2    EIF4A1--KLF2    EIF4A1--PTMA    EIF4A1--RBM38   ELL--COPE       EP300--ZNF384   ETV6--RUNX1     EWSR1--FLI1     FAM19A5--BRD1   FAM20C--COX19   FAM20C--PDGFA  FBRSL1--NCOR2    FOSB--UBC       GAK--MAEA       GPSM1--NOTCH1   GPSM1--RALGDS   GRK2--EEF1D     GSE1--CBFA2T3   GSE1--SLC7A5    H3F3B--HIST1H3J KDM4B--ZBTB7A   KIAA1549--BRAF  KMT2A--AFDN     KMT2A--AFF1     KMT2A--MLLT1    KMT2A--MLLT10   KMT2A--MLLT3    LDLRAD4--TGIF1  LFNG--MAD1L1    LMNB2--DOT1L    MAD1L1--TTYH3   MAFK--MAD1L1    METRNL--FOXK2   MKNK2--DOT1L    MKNK2--RNF126   MLLT10--PICALM NBAS--FAM49A     NCOR2--BCL7A    NCOR2--CDK2AP1  NCOR2--FBRSL1   NFATC1--PQLC1   No_rec_fusion   NOL4L--ASXL1    NSD1--NUP98     NUP214--ABL1    NUP98--KDM5A    NUP98--NSD1     PAX5--ETV6      PAX5--NOL4L     PER1--EIF5A     PHACTR3--RBM38  PICALM--MLLT10  PIM3--BRD1      PIM3--PLXNB2    PIM3--SBF1      PQLC1--NFATC1   PRDM16--SKI     PTBP1--EIF4A1   PTBP1--RNF126   RASA3--ING1     RBM38--NR4A1   RBM38--PMEPA1    RBM38--SEPT9    RBM38--TAF4     REV3L--FYN      RNF168--TFRC    RUNX1--ETV6     RUNX1--RUNX1T1  RUNX1T1--RUNX1  SENP3-EIF4A1--RBM38     SLC12A7--IRX2   SLC19A1--SUMO3  SLC7A5--BANP   SLC7A5--CBFA2T3  SLC7A5--GSE1    SLC7A5--ZFPM1   STK32C--INPP5A  TBCD--FOXK2     TCF25--FUS      TCF3--MKNK2     TCF3--PBX1      TCF3--ZNF384    TRDV2--TRAC     TTYH3--MAD1L1   TTYH3--MRM2     ULK1--FBRSL1    ZFPM1--CBFA2T3  ZFPM1--SLC7A5   ZNF292--PNRC1   ZNF292--SYNCRIP
BS_00FD2KMP     0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0      00       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0      00       0       0       0       0       0       0       0       0       0       0       0       0       0       0       1       0       0       0       0       0       0       0       0       0      00       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0      00       0       0       0       0       0       0       0       0       0       0       0
BS_014EVM2D     0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0      00       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0      00       0       0       0       0       0       0       0       0       0       0       0       0       0       0       1       0       0       0       0       0       0       0       0       0      00       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0      00       0       0       0       0       0       0       0       0       0       0       0
BS_02NZT8CE     0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0      00       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0      00       0       0       0       0       0       0       0       0       0       0       0       0       0       0       1       0       0       0       0       0       0       0       0       0      00       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0      00       0       0       0       0       0       0       0       0       0       0       0
BS_02X4QTNE     0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0      00       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0      00       0       0       0       0       0       0       0       0       0       0       0       0       0       0       1       0       0       0       0       0       0       0       0       0      00       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0      00       0       0       0       0       0       0       0       0       0       0       0
BS_03FT4S8B     0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0      00       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0      00       0       0       0       0       0       0       0       0       0       0       0       0       0       0       1       0       0       0       0       0       0       0       0       0      00       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0      00       0       0       0       0       0       0       0       0       0       0       0
BS_0448A413     0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0      00       0       0       0       0       0       0       1       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0      00       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0      00       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0      00       0       0       0       0       0       0       0       0       0       0       0
BS_044XZ8ST     0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0      00       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0      00       0       0       0       0       0       0       0       0       0       0       0       0       0       0       1       0       0       0       0       0       0       0       0       0      00       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0      00       0       0       0       0       0       0       0       0       0       0       0
BS_052PZFMK     0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0      00       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0      00       0       0       0       0       0       0       0       0       0       0       0       0       0       0       1       0       0       0       0       0       0       0       0       0      00       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0      00       0       0       0       0       0       0       0       0       0       0       0
BS_063ERW0R     0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0      00       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       1       0       0       0      00       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0      00       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0      00       0       0       0       0       0       0       0       0       0       0       0
```

There are also some warnings when running. I am not sure if these warnings are expected. Following is the terminal output:

```text
$ rm results/* && ./run_fusion_merged.sh
── Attaching packages ──────────────────────────────────────────────────────────────────────────────────────── tidyverse 1.2.1 ──
✔ ggplot2 3.2.0     ✔ purrr   0.3.2
✔ tibble  2.1.3     ✔ dplyr   0.8.3
✔ tidyr   0.8.3     ✔ stringr 1.4.0
✔ readr   1.3.1     ✔ forcats 0.4.0
── Conflicts ─────────────────────────────────────────────────────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()

Attaching package: ‘qdapRegex’

The following object is masked from ‘package:dplyr’:

    explain

The following object is masked from ‘package:ggplot2’:

    %+%

Parsed with column specification:
cols(
  LeftBreakpoint = col_character(),
  RightBreakpoint = col_character(),
  FusionName = col_character(),
  Sample = col_character(),
  Caller = col_character(),
  Fusion_Type = col_character(),
  JunctionReadCount = col_double(),
  SpanningFragCount = col_double(),
  Confidence = col_logical(),
  annots = col_character()
)
Parsed with column specification:
cols(
  LeftBreakpoint = col_character(),
  RightBreakpoint = col_character(),
  FusionName = col_character(),
  Sample = col_character(),
  Caller = col_character(),
  Fusion_Type = col_character(),
  JunctionReadCount = col_double(),
  SpanningFragCount = col_double(),
  Confidence = col_character(),
  annots = col_character()
)
Warning messages:
1: Expected 2 pieces. Additional pieces discarded in 28 rows [38263, 38828, 45566, 65255, 68563, 76583, 125578, 152849, 155441, 158126, 158262, 158779, 159112, 161215, 161673, 161881, 162955, 163527, 164033, 164624, ...].
2: Expected 2 pieces. Missing pieces filled with `NA` in 163108 rows [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18,19, 20, ...].
3: Expected 2 pieces. Additional pieces discarded in 24 rows [22675, 27494, 29082, 32555, 41172, 48238, 50834, 61456, 67278, 72264, 76534, 77625, 80441, 137706, 140126, 148693, 149862, 151050, 152623, 154263, ...].
4: Expected 2 pieces. Missing pieces filled with `NA` in 162165 rows [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18,19, 20, ...].
Warning message:
In fusion_filtering_QC(standardFusioncalls = standardFusioncalls,  :
  No fusion calls with annotation: GTEx_Recurrent
Using GeneSymbol as id variables
Warning message:
Column `Sample` joining character vector and factor, coercing into character vector


processing file: 04-project-specific-filtering.Rmd
  |...                                                              |   5%
  ordinary text without R code

  |......                                                           |   9%
label: unnamed-chunk-1
  |.........                                                        |  14%
  ordinary text without R code

  |............                                                     |  18%
label: unnamed-chunk-2
  |...............                                                  |  23%
  ordinary text without R code

  |..................                                               |  27%
label: unnamed-chunk-3
  |.....................                                            |  32%
  ordinary text without R code

  |........................                                         |  36%
label: unnamed-chunk-4
  |...........................                                      |  41%
  ordinary text without R code

  |..............................                                   |  45%
label: unnamed-chunk-5
  |................................                                 |  50%
  ordinary text without R code

  |...................................                              |  55%
label: unnamed-chunk-6
  |......................................                           |  59%
  ordinary text without R code

  |.........................................                        |  64%
label: unnamed-chunk-7
  |............................................                     |  68%
  ordinary text without R code

  |...............................................                  |  73%
label: unnamed-chunk-8
  |..................................................               |  77%
  ordinary text without R code

  |.....................................................            |  82%
label: unnamed-chunk-9
  |........................................................         |  86%
  ordinary text without R code

  |...........................................................      |  91%
label: unnamed-chunk-10
  |..............................................................   |  95%
  ordinary text without R code

  |.................................................................| 100%
label: unnamed-chunk-11

output file: 04-project-specific-filtering.knit.md

/usr/lib/rstudio-server/bin/pandoc/pandoc +RTS -K512m -RTS 04-project-specific-filtering.utf8.md --to html4 --from markdown+autolink_bare_uris+ascii_identifiers+tex_math_single_backslash+smart --output 04-project-specific-filtering.html --email-obfuscation none --self-contained --standalone --section-divs --template /usr/local/lib/R/site-library/rmarkdown/rmd/h/default.html --no-highlight --variable highlightjs=1 --variable 'theme:bootstrap' --include-in-header /tmp/RtmpRPwRRc/rmarkdown-strc5541ecb46c.html --mathjax --variable 'mathjax-url:https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML' --variable code_folding=show --variable source_embed=04-project-specific-filtering.Rmd --include-after-body /tmp/RtmpRPwRRc/filec554317cc11.html --variable code_menu=1 --variable kable-scroll=1

Output created: 04-project-specific-filtering.nb.html


processing file: 05-QC_putative_onco_fusion_distribution.Rmd
  |....                                                             |   6%
  ordinary text without R code

  |........                                                         |  12%
label: load params
  |............                                                     |  19%
  ordinary text without R code

  |................                                                 |  25%
label: get subset of fusion calls to review
  |....................                                             |  31%
  ordinary text without R code

  |........................                                         |  38%
label: function to plot FusionName to N number of cancer groups
  |............................                                     |  44%
  ordinary text without R code

  |................................                                 |  50%
label: other reading-frame fusion
  |.....................................                            |  56%
  ordinary text without R code

  |.........................................                        |  62%
label: local rearrangements fusions
  |.............................................                    |  69%
  ordinary text without R code

  |.................................................                |  75%
label: All putative oncogene fusion
  |.....................................................            |  81%
  ordinary text without R code

  |.........................................................        |  88%
label: get fusions that are found in more than 4 cancer groups
  |.............................................................    |  94%
  ordinary text without R code

  |.................................................................| 100%
label: final filtering

output file: 05-QC_putative_onco_fusion_distribution.knit.md

/usr/lib/rstudio-server/bin/pandoc/pandoc +RTS -K512m -RTS 05-QC_putative_onco_fusion_distribution.utf8.md --to html4 --from markdown+autolink_bare_uris+ascii_identifiers+tex_math_single_backslash+smart --output 05-QC_putative_onco_fusion_distribution.html --email-obfuscation none --self-contained --standalone --section-divs --template /usr/local/lib/R/site-library/rmarkdown/rmd/h/default.html --no-highlight --variable highlightjs=1 --variable 'theme:bootstrap' --include-in-header /tmp/RtmpQhF9yB/rmarkdown-strc847ba60d51.html--mathjax --variable 'mathjax-url:https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML' --variable code_folding=show --variable source_embed=05-QC_putative_onco_fusion_distribution.Rmd --include-after-body /tmp/RtmpQhF9yB/filec845add1225.html --variable code_menu=1 --variable kable-scroll=1

Output created: 05-QC_putative_onco_fusion_distribution.nb.html
Parsed with column specification:
cols(
  .default = col_character(),
  caller.count = col_double(),
  reciprocal_exists = col_logical()
)
See spec(...) for full column specifications.
Parsed with column specification:
cols(
  Kids_First_Participant_ID = col_character(),
  Kids_First_Biospecimen_ID = col_character()
)
Parsed with column specification:
cols(
  Kids_First_Participant_ID = col_character(),
  Kids_First_Biospecimen_ID = col_character()
)
```

**Comment by runjin326** [comment]
@logstar , could you please do another comparison now? I re-ran and committed the results again - you are right the fused gene by sample is different. Not sure what the issue was but I double checked and made sure all the independent samples that I uploaded are the ones currently in dev. Thanks!

**Comment by runjin326** [comment]
@afarrel, thanks so much for reviewing this! Merging soon!

**Pull request merged**
