### PR TITLE
Analysis update: Add methylation in LGAT workflow

### PR DESCRIPTION
**Pull request by zzgeng**
#### What scientific question is your analysis addressing?
Add methylation in LGAT workflow

#### What was your approach?
Add methylation in LGAT workflow

#### What GitHub issue does your pull request address?
https://github.com/d3b-center/OpenPedCan-analysis/issues/533

#### Which areas should receive a particularly close look?
molecular subtype lgg module, workflow 

#### What types of results are included (e.g., table, figure)?
Figure

#### Reproducibility Checklist

- [ ] The dependencies required to run the code in this pull request have been added to the project Dockerfile.
- [ ] This analysis has been added to continuous integration.

#### Documentation Checklist

- [ ] This analysis module has a `README` and it is up to date.
- [ ] This analysis is recorded in the table in `analyses/README.md` and the entry is up to date.
- [ ] The analytical code is documented and contains comments.

### CODE REVIEW

**Comment by jharenza** [comment]
Thanks @zzgeng for putting this together. Are we missing some methyl subtypes?

https://github.com/d3b-center/OpenPedCan-analysis/blob/dfe6d9f0ec8ea390f7bd102e8218642971e9299c/analyses/molecular-subtyping-LGAT/01-subset-files-for-LGAT.Rmd#L348-L360

**Comment by zzgeng** [comment]
> Thanks @zzgeng for putting this together. Are we missing some methyl subtypes?
> 
> https://github.com/d3b-center/OpenPedCan-analysis/blob/dfe6d9f0ec8ea390f7bd102e8218642971e9299c/analyses/molecular-subtyping-LGAT/01-subset-files-for-LGAT.Rmd#L348-L360

I checked the results and find out I missed one subtype (SEGA, to be classified). I just updated the workflow

**Comment by jharenza** [comment]
I meant that we need to include all of the above methyl subtypes in the flow - if they were not subtyped by something else, they are via methyl per 

https://github.com/d3b-center/OpenPedCan-analysis/blob/dfe6d9f0ec8ea390f7bd102e8218642971e9299c/analyses/molecular-subtyping-LGAT/04-LGAT-compile-subtypes.Rmd#L380-L383

**Review by jharenza — APPROVED** [review]
👍

**Comment by jharenza** [comment]
docs only

**Pull request merged**
