### PR TITLE
Add workflow to LGG README

### PR DESCRIPTION
**Pull request by zzgeng**
#### What scientific question is your analysis addressing?
Add workflow to illustrate the molecular subtyping of LGG

#### Which areas should receive a particularly close look?
Workflow plot

#### Reproducibility Checklist

- [x] The dependencies required to run the code in this pull request have been added to the project Dockerfile.
- [x] This analysis has been added to continuous integration.

#### Documentation Checklist

- [x] This analysis module has a `README` and it is up to date.
- [x] This analysis is recorded in the table in `analyses/README.md` and the entry is up to date.
- [x] The analytical code is documented and contains comments.

### CODE REVIEW

**Review by AntoniaChroni — COMMENTED** [review]
Here fusion is colored blue like in the DNA methylation and has its own name. This is not consistent with the rest of the flow charts. Also, what is the difference between: `**or`  vs `**or**`? See below some more comments:

- **LGG, NF1**
  - Maybe it's worth mentioning that this variation can be somatic or germline?

- **LGG, BRAF V600E**
  - contains `BRAF V600E or V599 SNV or non-canonical _BRAF_ alterations such as p.V600ins or p.D594N within the kiinase (PK_Tyr_Ser-Thr) domain`. In the flow chart only `p. V600E mutation in BRAF` is mentioned.

- **LGG, other MAPK**
  - `_RAF1_ and BRAF SNV or indel` are missing . 
  -   In the `README` file is not mentioned if these fusions, alterations etc are conditional, i.e., `or` is not stated.

- **LGG, FGFR**
  - First box should be yellow instead of blue based on this: `harbors _FGFR1_ p.N546K, p.K656E, p.N577, or p. K687 hotspot mutations`

- **LGG, MYB/MYBL1**
  - How come these are not in the same blue box and are separated? Aren't these fusions in the same gene?

- **LGG, CDKN2A/B** 
  - I am not sure what the following means and how it could be included in the flow chart, like secondary to what? It seems important to clarify and add in the flow chart `This is a secondary co-occurring alteration with prognostic significance. `

**Review by naqvia — APPROVED** [review]
This is great! I know LGGs are super complex and the flowchart did a really good job in breaking it down for us. Super easy to follow. Some minor edits to the readme. What does "*" mean after the or in some instances?

**Comment by jharenza** [comment]
Hi @AntoniaChroni can you review this when you get a chance? Thanks!

**Review by AntoniaChroni — APPROVED** [review]
@zzgeng This looks great! My suggestions have been addressed. My only comment is to keep yellow boxes first with the blue to follow for the sake of continuity. This is specifically for `LGG, other MAPK` and `LGG, RTK`. But I don't need to see this again, so I am approving.

**Review by jharenza — CHANGES_REQUESTED** [review]
@zzgeng can you update the NF1 germline box to say "Cancer predisposition == Neurofibromatosis, Type 1" and make it red, since this is _solely_ based on the clinical file right now

**Review by jharenza — APPROVED** [review]

**Pull request merged**
