### PR TITLE
V10 release documentation updates

### PR DESCRIPTION
**Pull request by runjin326**
#### What scientific question is your analysis addressing?
Update the following documentation for v10 release:
`data-files-description.md`
`data-formats.md`
`release-notes.md`
Additionally, the link for data download was modified to use v10.

#### What was your approach?
All the changes with v10 release are included in the documentation file.
Additionally, the link for data download was modified to use v10.

#### What GitHub issue does your pull request address?
https://github.com/PediatricOpenTargets/ticket-tracker/issues/188

#### Which areas should receive a particularly close look?
Please check to see whether the release note is clear enough. 

#### Is there anything that you want to discuss further?
No.

#### Is the analysis in a mature enough form that the resulting figure(s) and/or table(s) are ready for review?
Yes.

### CODE REVIEW

**Comment by runjin326** [comment]
@logstar, @ewafula, the fusion file is now uploaded to S3 so the v10 release is ready now - could you both please try running the download script and make sure everything is fine? 
Once this PR is approved and merged, v10 should be officially alive and @logstar can use this to build the database and @ewafula can start generating tables for FNL. Thanks so much - sorry the data release is taking longer than expected!

**Comment by logstar** [comment]
@runjin326 - Thank you so much for preparing this release!

I have tested downloading v10 data. All downloaded files passed md5sum checks:

```text
Checking MD5 hashes...
gene-expression-rsem-tpm-collapsed.rds: OK
gene-counts-rsem-expected_count-collapsed.rds: OK
fusion-arriba.tsv.gz: OK
fusion-starfusion.tsv.gz: OK
cnv-consensus.seg.gz: OK
cnv-cnvkit.seg.gz: OK
cnv-controlfreec.tsv.gz: OK
cnv-consensus-gistic.zip: OK
consensus_wgs_plus_cnvkit_wxs.tsv.gz: OK
consensus_wgs_plus_cnvkit_wxs_autosomes.tsv.gz: OK
consensus_wgs_plus_cnvkit_wxs_x_and_y.tsv.gz: OK
snv-consensus-plus-hotspots.maf.tsv.gz: OK
sv-manta.tsv.gz: OK
histologies.tsv: OK
data-files-description.md: OK
efo-mondo-map.tsv: OK
ensg-hugo-pmtl-mapping.tsv: OK
fusion-putative-oncogenic.tsv: OK
intersect_cds_lancet_strelka_mutect_WGS.bed: OK
intersect_strelka_mutect_WGS.bed: OK
release-notes.md: OK
uberon-map-gtex-group.tsv: OK
uberon-map-gtex-subgroup.tsv: OK
WGS.hg38.lancet.300bp_padded.bed: OK
WGS.hg38.lancet.unpadded.bed: OK
WGS.hg38.mutect2.vardict.unpadded.bed: OK
WGS.hg38.strelka2.unpadded.bed: OK
WGS.hg38.vardict.100bp_padded.bed: OK
independent-specimens.rnaseq.primary.eachcohort.tsv: OK
independent-specimens.rnaseq.primary.tsv: OK
independent-specimens.rnaseq.relapse.eachcohort.tsv: OK
independent-specimens.rnaseq.relapse.tsv: OK
independent-specimens.wgswxspanel.primary.eachcohort.prefer.wxs.tsv: OK
independent-specimens.wgswxspanel.primary.eachcohort.tsv: OK
independent-specimens.wgswxspanel.primary.prefer.wxs.tsv: OK
independent-specimens.wgswxspanel.primary.tsv: OK
independent-specimens.wgswxspanel.relapse.eachcohort.prefer.wxs.tsv: OK
independent-specimens.wgswxspanel.relapse.eachcohort.tsv: OK
independent-specimens.wgswxspanel.relapse.prefer.wxs.tsv: OK
independent-specimens.wgswxspanel.relapse.tsv: OK
tcga-gene-counts-rsem-expected_count-collapsed.rds: OK
tcga-gene-expression-rsem-tpm-collapsed.rds: OK
```

**Comment by runjin326** [comment]
@logstar, thanks for reviewing it! I think I would probably merge after Eric reviews and approves it as well. Do you have all you need to build the database for now? Or do you need to have it merged by tonight?

**Comment by logstar** [comment]
> @logstar, thanks for reviewing it! I think I would probably merge after Eric reviews and approves it as well. Do you have all you need to build the database for now? Or do you need to have it merged by tonight?

I have all files required for building database:

- `efo-mondo-map.tsv`
- `ensg-hugo-pmtl-mapping.tsv`
- `gene-expression-rsem-tpm-collapsed.rds`
- `histologies.tsv`
- `independent-specimens.rnaseq.primary.eachcohort.tsv`
- `independent-specimens.rnaseq.primary.tsv`
- `uberon-map-gtex-group.tsv`
- `uberon-map-gtex-subgroup.tsv`

I would need this to be merged by tonight, because the v10 commit hash will be used in OpenPedCan-api database building for reproducibility.

**Comment by runjin326** [comment]
@logstar, thanks so much! I tried the download link again and since both of us are able to download with no issue, I will just go ahead and merge the branch.

**Pull request merged**
