### PR TITLE
Rerun snv freq with V11 data and updated PedcBio case ids

### PR DESCRIPTION
**Pull request by kelseykeith**
#### What scientific question is your analysis addressing?

Needed to rerun the `snv-frequencies` module in order to re-generate the results tables after the OpenPedCan v11 data release. Additionally, it was decided at this time that CHOP DGD panel data should be excluded

#### What was your approach?

Updated the `get_cs_cg_tbl()` function to allow specifying the cohorts that should be included in the all cohorts calculation so DGD data would be excluded. 

#### What GitHub issue does your pull request address?

Updated analysis: update snv-frequencies for v11 data release [Ticket #361](https://github.com/PediatricOpenTargets/ticket-tracker/issues/361)

#### Which areas should receive a particularly close look?

- Check that `get_cs_cg_tbl()` behaves as expected since it was modified.
- The codes executes correctly.
- Check outputs for consistency.

#### Is there anything that you want to discuss further?

Updated PedcBio URLs are included in the PR but instructions on how to fetch them from PedcBio Portal are included in the module [README](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/tree/dev/analyses/snv-frequencies#add-annotations).

#### Is the analysis in a mature enough form that the resulting figure(s) and/or table(s) are ready for review?

Yes

#### What types of results are included (e.g., table, figure)?

TSV and JSON tables

#### What is your summary of the results?

- `gene-level-snv-consensus-annotated-mut-freq.jsonl.gz`
- `gene-level-snv-consensus-annotated-mut-freq.tsv.gz`
- `variant-level-snv-consensus-annotated-mut-freq.jsonl.gz`
- `variant-level-snv-consensus-annotated-mut-freq.tsv.gz`

#### Reproducibility Checklist

- [x] The dependencies required to run the code in this pull request have been added to the project Dockerfile.
- [x] This analysis has been added to continuous integration.

#### Documentation Checklist

- [x] This analysis module has a `README` and it is up to date.
- [x] This analysis is recorded in the table in `analyses/README.md` and the entry is up to date.
- [x] The analytical code is documented and contains comments.

### CODE REVIEW

**Comment by jharenza** [comment]
@kelseykeith seeing the same error here with the data dir - can you update please:

```
Error: '../../data/v11/snv-consensus-plus-hotspots.maf.tsv.gz' does not exist in current working directory ('/github/workspace/analyses/snv-frequencies').
```

**Comment by kelseykeith** [comment]
Sorry should be fixed now

**Comment by jharenza** [comment]
No worries, this is why we are using GA now :)

**Comment by kelseykeith** [comment]
This PR was re-submitted as part of [PR #243](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/pull/243), which is a PR of a branch of the OpenPedCan-analysis repository instead of my fork to fix the login issues with GitHub Actions

**Comment by jharenza** [comment]
closing in favor of #243

**Pull request closed without merging**
