### PR TITLE
Update analysis modules README

### PR DESCRIPTION
**Pull request by sangeetashukla**
### Purpose/implementation Section
Review and update information in the analysis/README for each module

#### What was your approach?
Followed directions from [Issue 372](https://github.com/PediatricOpenTargets/ticket-tracker/issues/372)

#### What GitHub issue does your pull request address?
[Issue 372](https://github.com/PediatricOpenTargets/ticket-tracker/issues/372)

### Directions for reviewers. Tell potential reviewers what kind of feedback you are soliciting.
Review the below changes:

- description is updated to reflect "OpenPedCan" and describe the contents of each column
- all 63 of `analysis` modules are tracked in the `README` and related information about each module are up to date.
- Added a Yes/No column "Produces files for data release?"
- renamed "In Use" to "Adapted for OPC?" with the definition of "Adapted for OPC" being that we have updated the modules to consume the OPC release files (opposed to OpenPBTA release files)
- For "Run Platform", only the `tumor-normal-differential-expression` module has added CAVATICA compatibility but the user is expected to create a new app in their personal project, so there is no public link to the app that can be linked here. Additionally, the module needs to be run on HPC, and directions are included in the module readme
- All module links are now redirected to [OpenPedCan](https://github.com/AlexsLemonade/OpenPBTA-analysis/tree/master/analyses) repo instead of the OpenPBTA repo earlier.

#### Is there anything that you want to discuss further?
- Removed the "Modules Consume Outputs" column - Let me know if there is a need to reinstate this column

#### Is the analysis in a mature enough form that the resulting figure(s) and/or table(s) are ready for review?
Yes

### Results
The Analysis/README is updated to include all modules and their input and result files for v11

#### Reproducibility Checklist

- [ ] The dependencies required to run the code in this pull request have been added to the project Dockerfile.
- [ ] This analysis has been added to continuous integration.

#### Documentation Checklist

- [ ] This analysis module has a `README` and it is up to date.
- [ ] This analysis is recorded in the table in `analyses/README.md` and the entry is up to date.
- [ ] The analytical code is documented and contains comments.

### CODE REVIEW

**Review by jharenza — CHANGES_REQUESTED** [review]
Hi @sangeetashukla! Thanks for working on this. The README files we have in the repo are written in markdown, and it looks like you are converting to HTML on this PR. 

This [website](https://www.tablesgenerator.com/markdown_tables) is handy for generating markdown tables and [this one](https://tableconvert.com/markdown-to-markdown) is handy for editing markdown tables if needed.

My suggestion would be to either add to the current table in a text editor using markdown table symbols or to copy the table out of markdown, updating it online such as above, and then putting it back in the README. 

Please let me know if you have any questions.

**Comment by sangeetashukla** [comment]
> Hi @sangeetashukla! Thanks for working on this. The README files we have in the repo are written in markdown, and it looks like you are converting to HTML on this PR.
> 
> This [website](https://www.tablesgenerator.com/markdown_tables) is handy for generating markdown tables and [this one](https://tableconvert.com/markdown-to-markdown) is handy for editing markdown tables if needed.
> 
> My suggestion would be to either add to the current table in a text editor using markdown table symbols or to copy the table out of markdown, updating it online such as above, and then putting it back in the README.
> 
> Please let me know if you have any questions.

Hi @jharenza, I use the website you linked to convert the table back to markdown. I had used RStudio to edit the file earlier, and I missed the format of it there while reviewing it in preview which seemed to look good. 
Please review the PR when you get a chance and let me know if it looks good now.

**Review by jharenza — CHANGES_REQUESTED** [review]
Thanks @sangeetashukla - it looks like the table displays OK now, but all of the module links are missing and the files are not backticked anymore. When you are pasting into the website, you can retain the formatting by opening up the MD file in some text editor, like sublime or other. If you paste from the GUI/table, you may lose the formatting (ie links and backticks which highlight the filenames. Can you please update?

**Comment by sangeetashukla** [comment]
> Thanks @sangeetashukla - it looks like the table displays OK now, but all of the module links are missing and the files are not backticked anymore. When you are pasting into the website, you can retain the formatting by opening up the MD file in some text editor, like sublime or other. If you paste from the GUI/table, you may lose the formatting (ie links and backticks which highlight the filenames. Can you please update?

@jharenza I fixed the hyperlinks to now point to OPC and it works now, and also ensured all file names are wrapped in backticks to transform into code.

**Comment by adilahiri** [comment]
@sangeetashukla: can you please check if the following modules are included in your update of the anaylses/readme ? Thank you. 

1. fusion-frequencies
2. fusion-summary
3. gene-set-enrichment-analysis
4. gene_match
5. hotspot-detection
6. methylation-preprocessing

**Comment by sangeetashukla** [comment]
> @sangeetashukla: can you please check if the following modules are included in your update of the anaylses/readme ? Thank you.
> 
> 1. fusion-frequencies
> 2. fusion-summary
> 3. gene-set-enrichment-analysis
> 4. gene_match
> 5. hotspot-detection
> 6. methylation-preprocessing

@adilahiri  I reviewed the document and have updated it to include any missing modules. The modules you listed above are now present in the README along with the relevant details.

**Comment by adilahiri** [comment]
@sangeetashukla: It's almost there, can you please change `hotspots-detection` to `hotspot-detection` ? 
Sorry to nitpick,  the name might be a concern if the directory is being referenced somewhere else.I will approve it as soon as you can edit it. Thanks !!

**Comment by sangeetashukla** [comment]
> @sangeetashukla: It's almost there, can you please change `hotspots-detection` to `hotspot-detection` ? Sorry to nitpick, the name might be a concern if the directory is being referenced somewhere else.I will approve it as soon as you can edit it. Thanks !!

@adilahiri I reviewed the existing module names and confirmed this module is in fact [`hotspots-detection`](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/tree/dev/analyses/hotspots-detection). This module is meant to evaluate snv and indels variant data for overlaps within hotspots.

**Comment by adilahiri** [comment]
@sangeetashukla  perfect, thank you for the clarification. I will approve it :)

**Review by adilahiri — APPROVED** [review]
Looks good, the remaining module names have been added.

**Review by jharenza — APPROVED** [review]
thank you @sangeetashukla !

**Comment by jharenza** [comment]
merging without checks since this is a documentation change only

**Pull request merged**
