### PR TITLE
add v11 MB subtyping (8/N)

### PR DESCRIPTION
**Pull request by jharenza**
#### What scientific question is your analysis addressing?
MB Molecular subtyping for v11 release

#### What was your approach?
Rerun module with slight modifications

#### What GitHub issue does your pull request address?
https://github.com/PediatricOpenTargets/ticket-tracker/issues/303

#### Is there anything that you want to discuss further?
- I had to change from `histologies.tsv` to `histologies-base.tsv` and from `cancer_group` to `short_histology` for this to run pre-release, as now intended.
- Note, this also added many DGD samples as To be classified.

#### Is the analysis in a mature enough form that the resulting figure(s) and/or table(s) are ready for review?
Yes

#### What types of results are included (e.g., table, figure)?
Table of MB subtypes

#### What is your summary of the results?
The few samples which look deleted might have been previously duplicated because they are still in the dataframe.

#### Reproducibility Checklist

- [x] The dependencies required to run the code in this pull request have been added to the project Dockerfile.
- [x] This analysis has been added to continuous integration.

#### Documentation Checklist

- [ ] This analysis module has a `README` and it is up to date.
- [ ] This analysis is recorded in the table in `analyses/README.md` and the entry is up to date.
- [x] The analytical code is documented and contains comments.

### CODE REVIEW

**Review by kelseykeith — CHANGES_REQUESTED** [review]
What's working:

- Code runs successfully
- DGD samples successfully incorporated into `MB_molecular_subtype.tsv`
- RDS file `mb-classified.rds` is identical to previous RDS. I think expected behavior because classifier only works with RNA-seq and all new samples are DGD targeted sequencing? But wanted to confirm with @jharenze

<br>

Two issues, one that needs to be fixed, one that may or may not be a problem:

**Issue 1:** `MB_molecular_subtype.tsv` has separate rows for DNA and RNA biospecimen IDs for DGD samples with both DNA and RNA targeted sequencing ex: sample 7316-8117

| Kids\_First\_Participant\_ID | sample_id | Kids\_First\_Biospecimen\_ID\_DNA | Kids\_First\_Biospecimen\_ID\_RNA |
| --- | --- | --- | --- |
| PT\_1TQA3ZS2 | 7316-8117	| NA |	BS\_J7160EQ5 |
| PT\_1TQA3ZS2 | 7316-8117	| BS\_W1KD76HS | NA |

This can be fixed by changing lines 29-33 of `04-classify-no-RNA-samples.R` from this

```r
samples_ids_no_rnaseq <- samples_ids_no_rnaseq %>%
  dplyr::mutate(Kids_First_Biospecimen_ID_DNA = ifelse(is.na(RNA_library), Kids_First_Biospecimen_ID, NA),
                Kids_First_Biospecimen_ID_RNA = ifelse(RNA_library == "exome_capture", Kids_First_Biospecimen_ID, NA),
                molecular_subtype = "MB, To be classified") %>%
  dplyr::select(Kids_First_Participant_ID, sample_id, Kids_First_Biospecimen_ID_DNA, Kids_First_Biospecimen_ID_RNA, molecular_subtype)
```	
to this

```r
samples_ids_no_rnaseq <- samples_ids_no_rnaseq %>%
  filter(!sample_id %in% sample_ids_with_rnaseq$sample_id) %>% 
  dplyr::mutate(temp = ifelse(is.na(RNA_library), 
                              'Kids_First_Biospecimen_ID_DNA',
                              'Kids_First_Biospecimen_ID_RNA'),
                molecular_subtype = "MB, To be classified") %>%
  dplyr::select(Kids_First_Participant_ID, sample_id, temp, Kids_First_Biospecimen_ID,
                molecular_subtype) %>%
  tidyr::pivot_wider(names_from = temp, values_from = Kids_First_Biospecimen_ID) %>%
  unnest(c(Kids_First_Biospecimen_ID_DNA, Kids_First_Biospecimen_ID_RNA))
```

**Issue 2:** Participant `PT_CXT81GRM` has two different subtypes assigned; one through subtyping its RNA-seq and also gets assigned "To be classified" because it has a second sample with no RNA. I assumed, but wasn't sure, that we would want to go with the RNA-seq subtyping, so the filtering for samples without RNA-seq in `04-classify-no-RNA-samples.R` would also need to include filtering by `Kids_First_Participant_ID`


| Kids\_First\_Participant\_ID | sample_id | Kids\_First\_Biospecimen\_ID\_DNA | Kids\_First\_Biospecimen\_ID\_RNA | molecular\_subtype | 
| --- | --- | --- | --- | --- |
| PT\_CXT81GRM | 7316-1772 | BS\_3CG2N4PD | BS\_GS1KR5PK | MB, SHH |
| PT_CXT81GRM | 7316-883 | BS_9SVG5Q6R | NA | MB, To be classified |
| PT_CXT81GRM | 7316-883 | BS_HZNKSQ17 | NA | MB, To be classified |

**Comment by jharenza** [comment]
Thanks for reviewing @kelseykeith !!

> I think expected behavior because classifier only works with RNA-seq and all new samples are DGD targeted sequencing?

This is correct- the DGD samples are RNA fusion panel only, so excluded from classification here.

>Issue 1: MB_molecular_subtype.tsv has separate rows for DNA and RNA biospecimen IDs for DGD samples with both DNA and RNA targeted sequencing ex: sample 7316-8117

Good catch on this - will fix!

>Issue 2: Participant PT_CXT81GRM has two different subtypes assigned; one through subtyping its RNA-seq and also gets assigned "To be classified" because it has a second sample with no RNA. I assumed, but wasn't sure, that we would want to go with the RNA-seq subtyping, so the filtering for samples without RNA-seq in 04-classify-no-RNA-samples.R would also need to include filtering by Kids_First_Participant_ID

This example is actually OK because we want to subtype by `sample_id` (or clinical event). The patient could have had two different tumors, initial and relapse, for example, and they should each be treated separately.

**Comment by runjin326** [comment]
@kelseykeith - this is ready for another look!
@jharenza - could you please merge newest `dev` to v11-release? there are additional changes from my commit since my dev branch is up to date but v11-release is not.

**Comment by jharenza** [comment]
>@jharenza - could you please merge newest dev to v11-release? there are additional changes from my commit since my dev branch is up to date but v11-release is not.

done

**Review by kelseykeith — APPROVED** [review]
Looks good now! Approved!

**Pull request merged**
