### PR TITLE
Generate plot/counts for the manuscript

### PR DESCRIPTION
**Pull request by zzgeng**
#### What scientific question is your analysis addressing?
Generate plot/counts for the manuscript

#### Which areas should receive a particularly close look?
figures/manuscript_OPC/figure/ 
and 
figures/manuscript_OPC/ R markdowns

#### Is there anything that you want to discuss further?
The schematic will be updated.

#### Reproducibility Checklist

- [ ] The dependencies required to run the code in this pull request have been added to the project Dockerfile.
- [ ] This analysis has been added to continuous integration.

#### Documentation Checklist

- [ ] This analysis module has a `README` and it is up to date.
- [ ] This analysis is recorded in the table in `analyses/README.md` and the entry is up to date.
- [ ] The analytical code is documented and contains comments.

### CODE REVIEW

**Review by jharenza — CHANGES_REQUESTED** [review]
hi @zzgeng thanks for getting started on these! I was hoping we could more directly mirror the plots you had on your poster. Can you create the tumor descriptor plot as a piechart and then the experimental strategy by cohort as a stacked barplot, both of these by match_id perhaps (that would be number of unique tumors). Can you also use the figure theme we have in our repos (eg: https://github.com/d3b-center/pbta-splicing/blob/main/figures/theme_for_plots.R, you can pull this over). I like the colors on your poster, so we can stick with those or similar if you recall what was used. For experimental strategy, perhaps we can make a new annotation called labeling the cohorts as "Pediatric" or "Adult", and facet the plot by that thing (age_group?) That would put GTEX and TCGA in a second facet, and won't blow out the cohorts in Pediatric. Does that make sense?

**Comment by zzgeng** [comment]
> hi @zzgeng thanks for getting started on these! I was hoping we could more directly mirror the plots you had on your poster. Can you create the tumor descriptor plot as a piechart and then the experimental strategy by cohort as a stacked barplot, both of these by match_id perhaps (that would be number of unique tumors). Can you also use the figure theme we have in our repos (eg: https://github.com/d3b-center/pbta-splicing/blob/main/figures/theme_for_plots.R, you can pull this over). I like the colors on your poster, so we can stick with those or similar if you recall what was used. For experimental strategy, perhaps we can make a new annotation called labeling the cohorts as "Pediatric" or "Adult", and facet the plot by that thing (age_group?) That would put GTEX and TCGA in a second facet, and won't blow out the cohorts in Pediatric. Does that make sense?

Thank you for the advice! I have made changes based on the comments. However, I cannot find Gtex in cohort or subcohort column. I wonder if I was looking at the wrong column?

**Comment by jharenza** [comment]
> > hi @zzgeng thanks for getting started on these! I was hoping we could more directly mirror the plots you had on your poster. Can you create the tumor descriptor plot as a piechart and then the experimental strategy by cohort as a stacked barplot, both of these by match_id perhaps (that would be number of unique tumors). Can you also use the figure theme we have in our repos (eg: https://github.com/d3b-center/pbta-splicing/blob/main/figures/theme_for_plots.R, you can pull this over). I like the colors on your poster, so we can stick with those or similar if you recall what was used. For experimental strategy, perhaps we can make a new annotation called labeling the cohorts as "Pediatric" or "Adult", and facet the plot by that thing (age_group?) That would put GTEX and TCGA in a second facet, and won't blow out the cohorts in Pediatric. Does that make sense?
> 
> 
> 
> Thank you for the advice! I have made changes based on the comments. However, I cannot find Gtex in cohort or subcohort column. I wonder if I was looking at the wrong column?

It got filtered out, but I updated the code. I also ended up splitting the plots so there wasn't so much white space and created a paneled figure 1 with biorender, also committed here. I'll work on updates to the workflow today. Thanks so much!

**Review by jharenza — APPROVED** [review]

**Comment by jharenza** [comment]
does not use GHA

**Pull request merged**
