### PR TITLE
Modify methyl independent specimens to match with indep RNA samples

### PR DESCRIPTION
**Pull request by sangeetashukla**
### Purpose/implementation Section

- Currently, the module creates only methylation all_cohorts independent sample lists independent-specimens.methyl.primary.tsv and independent-specimens.methyl.relapse.tsv. 
- Create additional methylation each_cohorts independent sample lists independent-specimens.methyl.primary.eachcohort.tsv and independent-specimens.methyl.relapse.eachcohort.tsv.
- Create a new match_id to account for the non-unique sample_id in the other cohorts with similar sample_id.

#### What scientific question is your analysis addressing?
Determine methylation samples that have a matching RNA-seq sample to prioritize for selection into independent sample lists.

#### What was your approach?
1) Modify `05-generate-independent-specimens-methyl.R` to generate `each cohort` independent sample lists for methylation samples.
2) Create a new function `util/independent-methyl-samples.R` to be sourced by `05-generate-independent-specimens-methyl.R`similar to `util/independent-rna-samples.R`

#### What GitHub issue does your pull request address?
[Issue 412](https://github.com/PediatricOpenTargets/ticket-tracker/issues/412)

### Directions for reviewers. Tell potential reviewers what kind of feedback you are soliciting.
Please review the newly added function for data integrity while processing methylation samples.

#### Which areas should receive a particularly close look?
Please review the results to see if the cohort-specific data needs to be prioritized further.

#### Is there anything that you want to discuss further?
No.

#### Is the analysis in a mature enough form that the resulting figure(s) and/or table(s) are ready for review?
Yes.

#### What types of results are included (e.g., table, figure)?
Tables in below files under `results/`
`independent-specimens.methyl.primary.tsv`
`independent-specimens.methyl.relapse.tsv`
`independent-specimens.methyl.primary-plus.tsv`
`independent-specimens.methyl.primary.eachcohort.tsv`
`independent-specimens.methyl.relapse.eachcohort.tsv`
`independent-specimens.methyl.primary-plus.eachcohort.tsv`

#### Reproducibility Checklist

- [x] The dependencies required to run the code in this pull request have been added to the project Dockerfile.
- [x] This analysis has been added to continuous integration.

#### Documentation Checklist

- [x] This analysis module has a `README` and it is up to date.
- [ ] This analysis is recorded in the table in `analyses/README.md` and the entry is up to date.
- [ ] The analytical code is documented and contains comments.

### CODE REVIEW

**Comment by chinwallaa** [comment]
@ewafula this should be reviewed 10/6

**Review by ewafula — APPROVED** [review]
@sangeetashukla, thank you so much for updating this module.  I reviewed, made some changes to fix inconsistencies, and then updated the PR.  I was able to reproduce the results for all other independent samples, including the methylation independent samples as expected.  

Approving PR and is ready to merge!

**Review by jharenza — COMMENTED** [review]
I just had a question - why are we removing the indep specimen pre-release files here? I think they should stay?

**Comment by ewafula** [comment]
@jharenza, do you foresee an instance where we are going to need using pre-release independent samples for methylation we do for rnaseqpanel that are used generate fusions pre-release data files?

**Comment by jharenza** [comment]
> @jharenza, do you foresee an instance where we are going to need using pre-release independent samples for methylation we do for rnaseqpanel that are used generate fusions pre-release data files? 

I think only rnaseq/panel since those are required for fusion filtering, but I am reading that those were the ones deleted but maybe I'm missing something.

**Comment by ewafula** [comment]
> > @jharenza, do you foresee an instance where we are going to need using pre-release independent samples for methylation we do for rnaseqpanel that are used generate fusions pre-release data files?
> 
> I think only rnaseq/panel since those are required for fusion filtering, but I am reading that those were the ones deleted but maybe I'm missing something.

@jharenza, I now get your point. If you recall, for v11 rnaseq/panel pre-release data, you generated the files using the older pre-release code from OpenPBTA which is no longer in the modules.  Currently, the `02-generate-independent-rnaseq.R` script  does not have a functional call to the `util/independent-rna-samples.R`  ( with `match_type == "none" & independent_level == "all-cohorts-pre-release"`) to  generate rnaseq/panel pre-release independent samples. I'll bring pre-release files back into the module `results/` directory.

**Comment by jharenza** [comment]
The pre-release files will be generated with [script 04](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/blob/dev/analyses/independent-samples/04-generate-independent-specimens-rnaseq-pre-release.R) with the base subtyping option. My only question now is should these say `rnaseq` or `rnaseqpanel`? I think that the dev version of these might be out of date with the code we have been using for fusion filtering, but can you just double check that everything is as expected for the release as well? That would really be out of scope here but be a new ticket.

**Comment by ewafula** [comment]
> The pre-release files will be generated with [script 04](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/blob/dev/analyses/independent-samples/04-generate-independent-specimens-rnaseq-pre-release.R) with the base subtyping option. My only question now is should these say `rnaseq` or `rnaseqpanel`? I think that the dev version of these might be out of date with the code we have been using for fusion filtering, but can you just double check that everything is as expected for the release as well? That would really be out of scope here but be a new ticket.

@jharenza, the pre-release files on both on `dev` and `s3 data release` are out of date. I have regenerated new pre-release files with the base subtyping option set to run `04-generate-independent-specimens-rnaseq-pre-release.R` and updated the PR.  And yes, the pre-release files are no longer named `rnaseqpanel` but `rnaseq` as they don't include panel samples.  Hopefully, I understood well and addressed the last part of your question!

**Review by jharenza — APPROVED** [review]
@ewafula we can merge this one next, after checks pass!

**Pull request merged**
