### PR TITLE
V12 mol subtype integrate/create histologies (14/N)

### PR DESCRIPTION
**Pull request by jharenza**
#### What scientific question is your analysis addressing?
This PR is an initial run of molecular subtype integrate.

#### What was your approach?
Rerun module, added an export of duplicates to check file. This file has bs_ids which have different values in subtypes or broad/short histologies and need to be checked.

#### What GitHub issue does your pull request address?
v12 release

#### Which areas should receive a particularly close look?
Duplicates need to be checked here. @ewafula many are LGG, so can you dig into these? Either happening via lgg module or pathology module with LGG free text subtyping.

There are some issues with "Other" coming up as cancer group - this is mainly JXGs and 1 astroblastoma, but I can't track it down. They are not "other" harm dx in their path free text subtype file. There are also only 3 in that output file, but 6 in the integrate "Other" category. This may all change with a new histologies base, but just wanted to note.

#### Is there anything that you want to discuss further?
see above

#### Is the analysis in a mature enough form that the resulting figure(s) and/or table(s) are ready for review?
QC needed first

#### Reproducibility Checklist

- [x] The dependencies required to run the code in this pull request have been added to the project Dockerfile.
- [x] This analysis has been added to continuous integration.

#### Documentation Checklist

- [x] This analysis module has a `README` and it is up to date.
- [x] This analysis is recorded in the table in `analyses/README.md` and the entry is up to date.
- [x] The analytical code is documented and contains comments.

### CODE REVIEW

**Comment by jharenza** [comment]
@ewafula for this, we also need a copy of `efo-mondo-map.tsv` in order to generate the pre-fill file. It is not in v12 currently. Thinking maybe we can have `efo-mondo-map-previous-release.tsv` which would essentially be the v11 (previous release) copy, just renamed. I added this and updated md5sum, but can you update the generate analysis files script to add this file?

**Comment by ewafula** [comment]
> @ewafula for this, we also need a copy of `efo-mondo-map.tsv` in order to generate the pre-fill file. It is not in v12 currently. Thinking maybe we can have `efo-mondo-map-previous-release.tsv` which would essentially be the v11 (previous release) copy, just renamed. I added this and updated md5sum, but can you update the generate analysis files script to add this file?

@jharenza,  we might need to update generate analysis files script afterward to include  `efo-mondo-mapping` module. @sangeetashukla is making it a priority to complete updating the module tomorrow and then we can upload `efo-mondo-map.tsv` to s3 bucket.  The alternative would be to update directly on the `Update v12 pre-release files (1/N)` PR  branch.

**Comment by jharenza** [comment]
Yup I meant directly on 1/n, just copy over from v11 and name it as I have (already did it manually)

**Comment by ewafula** [comment]
@jharenza, I have done a deep dive to figure out why we have duplicate samples in the QC file [discrepancies_to_check.tsv](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/blob/v12-integrate/analyses/molecular-subtyping-integrate/results/discrepancies_to_check.tsv).  Details are summarized below. 

In order to continue with the downstream analyses to create preliminary MTP tables, @chinwallaa and I agreed to keep records in the final histologies file with 1) cancer_groups that match pathology_ diagnosis and filter out others for duplicates in  `No. 1 - 5` and 2) set molecular_subtype for RNA-Seq/methylation samples to `NA` and make distinct in  `No.  6 - 7`. This should temporarily address the issue of duplicate samples in the final histologies files until when you return from vacation and help resolve this issue. 

1). ################################  

The following 3 duplicate samples have been subtyped in both molecular-subtyping-embryonal and molecular-subtyping-EWS modules. They all coded as `central nervous system BCOR‐ITD (CNS_BCOR‐ITD) tumors` by methylation classification, which includes them in the embryonal subtyping module, and coded as `Ewing's Sarcoma` in the pathology_diagnosis, which includes them EWS subtyping module.

```
> read_tsv("discrepancies_to_check.tsv") %>% filter(Kids_First_Biospecimen_ID %in% c("BS_21KG9DWJ", "BS_P9G0E57D", "BS_XQNMWJ4H")) %>% group_by(Kids_First_Biospecimen_ID) %>% summarise(short_histologies = toString(unique(short_histology))) %>% ungroup() %>% arrange(short_histologies)
# A tibble: 3 x 2
  Kids_First_Biospecimen_ID short_histologies   
  <chr>                     <chr>               
1 BS_21KG9DWJ               Embryonal tumor, EWS
2 BS_P9G0E57D               Embryonal tumor, EWS
3 BS_XQNMWJ4H               Embryonal tumor, EWS

> read_tsv("../../../data/histologies-base.tsv") %>% filter(Kids_First_Biospecimen_ID %in% c("BS_21KG9DWJ", "BS_P9G0E57D", "BS_XQNMWJ4H")) %>% select(Kids_First_Biospecimen_ID, experimental_strategy, dkfz_v12_methylation_subclass, pathology_diagnosis)
# A tibble: 3 x 4
  Kids_First_Biospecimen_ID experimental_strategy dkfz_v12_methylation~1 patho~2
  <chr>                     <chr>                 <chr>                  <chr>  
1 BS_21KG9DWJ               Methylation           CNS_BCOR_ITD           Ewings~
2 BS_P9G0E57D               Methylation           CNS_BCOR_ITD           Ewings~
3 BS_XQNMWJ4H               Methylation           CNS_BCOR_ITD           Ewings~
```

2). ################################

The following 4 duplicate samples have been subtyped in both molecular-subtyping-embryonal and molecular-subtyping-LGAT modules. They all coded as `Low-grade glioma/astrocytoma (WHO grade I/II)` in the pathology_diagnosis. Based on code logic. they are included in the embryonal subtyping because they are low-grade glioma tumors with the `_MN1_` fusion in the fusion summary file.

```
> read_tsv("discrepancies_to_check.tsv") %>% filter(Kids_First_Biospecimen_ID %in% c("BS_CVGFNCBJ", "BS_SD28E0SC", "BS_WSFB4SA2", "BS_YCREDZTJ")) %>% group_by(Kids_First_Biospecimen_ID) %>% summarise(short_histologies = toString(unique(short_histology))) %>% ungroup() %>% arrange(short_histologies)
# A tibble: 4 x 2
  Kids_First_Biospecimen_ID short_histologies    
  <chr>                     <chr>                
1 BS_CVGFNCBJ               Embryonal tumor, LGAT
2 BS_SD28E0SC               Embryonal tumor, LGAT
3 BS_WSFB4SA2               Embryonal tumor, LGAT
4 BS_YCREDZTJ               Embryonal tumor, LGAT

> read_tsv("../../../data/histologies-base.tsv") %>% filter(Kids_First_Biospecimen_ID %in% c("BS_CVGFNCBJ", "BS_SD28E0SC", "BS_WSFB4SA2", "BS_YCREDZTJ")) %>% select(Kids_First_Biospecimen_ID, experimental_strategy, pathology_diagnosis)
# A tibble: 4 x 3
  Kids_First_Biospecimen_ID experimental_strategy pathology_diagnosis           
  <chr>                     <chr>                 <chr>                         
1 BS_CVGFNCBJ               RNA-Seq               Low-grade glioma/astrocytoma ~
2 BS_SD28E0SC               WGS                   Low-grade glioma/astrocytoma ~
3 BS_WSFB4SA2               WGS                   Low-grade glioma/astrocytoma ~
4 BS_YCREDZTJ               RNA-Seq               Low-grade glioma/astrocytoma ~
```

3). ################################

The following duplicate sample has been subtyped in both molecular-subtyping-embryonal and molecular-subtyping-pathology modules. It is coded as `ETMR_C19MC` by methylation classification, which includes it in the embryonal subtyping module, and coded as `Meningioma` via OpenPBTA subtyping from pathology_free_text_diagnosis, which includes it in the pathology subtyping module.

```
> read_tsv("discrepancies_to_check.tsv") %>% filter(Kids_First_Biospecimen_ID == "BS_Z62B53CW") %>% group_by(Kids_First_Biospecimen_ID) %>% summarise(short_histologies = toString(unique(short_histology))) %>% ungroup() %>% arrange(short_histologies)
# A tibble: 1 x 2
  Kids_First_Biospecimen_ID short_histologies
  <chr>                     <chr>            
1 BS_Z62B53CW               ETMR, Meningioma

> read_tsv("../../../data/histologies-base.tsv") %>% filter(Kids_First_Biospecimen_ID == "BS_Z62B53CW" ) %>% select(Kids_First_Biospecimen_ID, experimental_strategy, pathology_diagnosis)
# A tibble: 1 x 3
  Kids_First_Biospecimen_ID experimental_strategy pathology_diagnosis
  <chr>                     <chr>                 <chr>              
1 BS_Z62B53CW               Methylation           Meningioma   
```

4). ################################

The following duplicate sample has been subtyped in both the molecular-subtyping-EWS and molecular-subtyping-CRANIO modules. It is coded as `EWS` by methylation classification, which includes it in EWS subtyping module, and coded as `Craniopharyngioma` in pathology_diagnosis, which includes it in the CRANIO subtyping module.

```
> read_tsv("discrepancies_to_check.tsv") %>% filter(Kids_First_Biospecimen_ID == "BS_SRW0DH5G") %>% group_by(Kids_First_Biospecimen_ID) %>% summarise(short_histologies = toString(unique(short_histology))) %>% ungroup() %>% arrange(short_histologies)
# A tibble: 1 x 2
  Kids_First_Biospecimen_ID short_histologies     
  <chr>                     <chr>                 
1 BS_SRW0DH5G               EWS, Craniopharyngioma

> read_tsv("../../../data/histologies-base.tsv") %>% filter(Kids_First_Biospecimen_ID == "BS_SRW0DH5G") %>% select(Kids_First_Biospecimen_ID, experimental_strategy, dkfz_v12_methylation_subclass, pathology_diagnosis)
# A tibble: 1 x 4
  Kids_First_Biospecimen_ID experimental_strategy dkfz_v12_methylation~1 patho~2
  <chr>                     <chr>                 <chr>                  <chr>  
1 BS_SRW0DH5G               Methylation           EWS                    Cranio~
```

5). ################################

The following duplicate sample has been subtyped in both molecular-subtyping-EWS and molecular-subtyping-MB modules. It is coded as `EWS` by methylation classification, which includes it in EWS subtyping module, and coded as `Medulloblastoma` in pathology_diagnosis, which includes it in the MB subtyping module.

```
> read_tsv("discrepancies_to_check.tsv") %>% filter(Kids_First_Biospecimen_ID == "BS_ER9RMSVG") %>% group_by(Kids_First_Biospecimen_ID) %>% summarise(short_histologies = toString(unique(short_histology))) %>% ungroup() %>% arrange(short_histologies)
# A tibble: 1 x 2
  Kids_First_Biospecimen_ID short_histologies   
  <chr>                     <chr>               
1 BS_ER9RMSVG               EWS, Medulloblastoma

> read_tsv("../../../data/histologies-base.tsv") %>% filter(Kids_First_Biospecimen_ID == "BS_ER9RMSVG") %>% select(Kids_First_Biospecimen_ID, experimental_strategy, dkfz_v12_methylation_subclass, pathology_diagnosis)
# A tibble: 1 x 4
  Kids_First_Biospecimen_ID experimental_strategy dkfz_v12_methylation~1 patho~2
  <chr>                     <chr>                 <chr>                  <chr>  
1 BS_ER9RMSVG               Methylation           EWS                    Medull~
```

6). ################################
Each of the following 23 HGG RNA-Seq/methylation duplicated samples matches multiple DNA samples (same patient and same sample_id) that have different molecular subtypes. See the example shown below with `BS_7APCGCVF`. This created 2 duplicate records for `BS_7APCGCVF` for DNA molecular_subtype. 


```
> read_tsv("discrepancies_to_check.tsv") %>% filter(Kids_First_Biospecimen_ID %in% c("BS_0YPKW34G", "BS_3V1YK5XG", "BS_4J9RWYRN", "BS_56PCCAVM", "BS_5GPYXH4B", "BS_7APCGCVF", "BS_8RJSR61H", "BS_AF828R76", "BS_BYZBK75T", "BS_C334HDVS", "BS_E7HGJS7W", "BS_GJ1AJVVV", "BS_GNY82SA4", "BS_JVZ7AQPV", "BS_M0XGZ53Z", "BS_N6EPKXEX", "BS_P370P5S7", "BS_QQEAVBCP", "BS_RREMNJJB", "BS_TQ1QY3QH", "BS_TVPQ40TM", "BS_TVZQJP7B", "BS_WDD8VE0Z")) %>% group_by(Kids_First_Biospecimen_ID) %>% summarise(short_histologies = toString(unique(short_histology))) %>% ungroup() %>% arrange(short_histologies)  %>% print(n=23)
# A tibble: 23 x 2
   Kids_First_Biospecimen_ID short_histologies
   <chr>                     <chr>            
 1 BS_0YPKW34G               HGAT             
 2 BS_3V1YK5XG               HGAT             
 3 BS_4J9RWYRN               HGAT             
 4 BS_56PCCAVM               HGAT             
 5 BS_5GPYXH4B               HGAT             
 6 BS_7APCGCVF               HGAT             
 7 BS_8RJSR61H               HGAT             
 8 BS_AF828R76               HGAT             
 9 BS_BYZBK75T               HGAT             
10 BS_C334HDVS               HGAT             
11 BS_E7HGJS7W               HGAT             
12 BS_GJ1AJVVV               HGAT             
13 BS_GNY82SA4               HGAT             
14 BS_JVZ7AQPV               HGAT             
15 BS_M0XGZ53Z               HGAT             
16 BS_N6EPKXEX               HGAT             
17 BS_P370P5S7               HGAT             
18 BS_QQEAVBCP               HGAT             
19 BS_RREMNJJB               HGAT             
20 BS_TQ1QY3QH               HGAT             
21 BS_TVPQ40TM               HGAT             
22 BS_TVZQJP7B               HGAT             
23 BS_WDD8VE0Z               HGAT  

> read_tsv("../../../data/histologies-base.tsv") %>% filter(Kids_First_Biospecimen_ID %in% c("BS_0YPKW34G", "BS_3V1YK5XG", "BS_4J9RWYRN", "BS_56PCCAVM", "BS_5GPYXH4B", "BS_7APCGCVF", "BS_8RJSR61H", "BS_AF828R76", "BS_BYZBK75T", "BS_C334HDVS", "BS_E7HGJS7W", "BS_GJ1AJVVV", "BS_GNY82SA4", "BS_JVZ7AQPV", "BS_M0XGZ53Z", "BS_N6EPKXEX", "BS_P370P5S7", "BS_QQEAVBCP", "BS_RREMNJJB", "BS_TQ1QY3QH", "BS_TVPQ40TM", "BS_TVZQJP7B", "BS_WDD8VE0Z")) %>% select(Kids_First_Biospecimen_ID, experimental_strategy, pathology_diagnosis)  %>% print(n=23)
# A tibble: 23 x 3
   Kids_First_Biospecimen_ID experimental_strategy pathology_diagnosis          
   <chr>                     <chr>                 <chr>                        
 1 BS_0YPKW34G               Methylation           High-grade glioma/astrocytom~
 2 BS_3V1YK5XG               Methylation           High-grade glioma/astrocytom~
 3 BS_56PCCAVM               Methylation           High-grade glioma/astrocytom~
 4 BS_5GPYXH4B               Methylation           High-grade glioma/astrocytom~
 5 BS_C334HDVS               Methylation           High-grade glioma/astrocytom~
 6 BS_N6EPKXEX               Methylation           High-grade glioma/astrocytom~
 7 BS_P370P5S7               Methylation           High-grade glioma/astrocytom~
 8 BS_RREMNJJB               Methylation           High-grade glioma/astrocytom~
 9 BS_TQ1QY3QH               Methylation           High-grade glioma/astrocytom~
10 BS_TVPQ40TM               Methylation           High-grade glioma/astrocytom~
11 BS_TVZQJP7B               Methylation           High-grade glioma/astrocytom~
12 BS_4J9RWYRN               RNA-Seq               High-grade glioma/astrocytom~
13 BS_7APCGCVF               RNA-Seq               High-grade glioma/astrocytom~
14 BS_8RJSR61H               RNA-Seq               High-grade glioma/astrocytom~
15 BS_AF828R76               RNA-Seq               High-grade glioma/astrocytom~
16 BS_BYZBK75T               RNA-Seq               High-grade glioma/astrocytom~
17 BS_E7HGJS7W               RNA-Seq               High-grade glioma/astrocytom~
18 BS_GJ1AJVVV               RNA-Seq               High-grade glioma/astrocytom~
19 BS_GNY82SA4               RNA-Seq               High-grade glioma/astrocytom~
20 BS_JVZ7AQPV               RNA-Seq               High-grade glioma/astrocytom~
21 BS_M0XGZ53Z               RNA-Seq               High-grade glioma/astrocytom~
22 BS_QQEAVBCP               RNA-Seq               High-grade glioma/astrocytom~
23 BS_WDD8VE0Z               RNA-Seq               High-grade glioma/astrocytom~

> read_tsv("HGG_molecular_subtype_tp53.tsv") %>% filter(Kids_First_Biospecimen_ID_RNA == "BS_7APCGCVF") %>% select(Kids_First_Biospecimen_ID_DNA, Kids_First_Biospecimen_ID_RNA, molecular_subtype) %>% distinct()
# A tibble: 8 x 3
  Kids_First_Biospecimen_ID_DNA Kids_First_Biospecimen_ID_RNA molecular_subtype 
  <chr>                         <chr>                         <chr>             
1 BS_3A7YMV93                   BS_7APCGCVF                   DMG, H3 K28, TP53~
2 BS_5PR4KXE1                   BS_7APCGCVF                   DMG, H3 K28       
3 BS_D3BH8D4Y                   BS_7APCGCVF                   DMG, H3 K28, TP53~
4 BS_EV071CE1                   BS_7APCGCVF                   DMG, H3 K28, TP53~
5 BS_FQBVBTCY                   BS_7APCGCVF                   DMG, H3 K28, TP53~
6 BS_M4KR9DSE                   BS_7APCGCVF                   DMG, H3 K28, TP53~
7 BS_T3WNX1E2                   BS_7APCGCVF                   DMG, H3 K28, TP53~
8 BS_Z7806Z75                   BS_7APCGCVF                   DMG, H3 K28, TP53~

> read_tsv("HGG_molecular_subtype_tp53.tsv") %>% filter(Kids_First_Biospecimen_ID_RNA == "BS_7APCGCVF") %>% select(Kids_First_Biospecimen_ID_DNA, Kids_First_Biospecimen_ID_RNA, molecular_subtype, molecular_subtype_methyl) %>% pull(molecular_subtype) %>% unique
[1] "DMG, H3 K28, TP53 activated" "DMG, H3 K28" 

```

7). ################################
Each of the following 6 LGG RNA-Seq duplicated samples matches multiple DNA samples (same patient and same sample_id) that have different molecular subtypes. See the example shown below with `BS_40HCP3HB`. This created 4 duplicate records for `BS_40HCP3HB` for DNA molecular_subtype. 


```
> read_tsv("discrepancies_to_check.tsv") %>% filter(Kids_First_Biospecimen_ID %in% c("BS_40HCP3HB", "BS_MKGTXW8A", "BS_MMEVDXGV", "BS_P412CPXJ", "BS_X5A5TNG1", "BS_YV1E1G58")) %>% group_by(Kids_First_Biospecimen_ID) %>% summarise(short_histologies = toString(unique(short_histology))) %>% ungroup() %>% arrange(short_histologies)
# A tibble: 6 x 2
  Kids_First_Biospecimen_ID short_histologies
  <chr>                     <chr>            
1 BS_40HCP3HB               LGAT             
2 BS_MKGTXW8A               LGAT             
3 BS_MMEVDXGV               LGAT             
4 BS_P412CPXJ               LGAT             
5 BS_X5A5TNG1               LGAT             
6 BS_YV1E1G58               LGAT

> read_tsv("../../../data/histologies-base.tsv") %>% filter(Kids_First_Biospecimen_ID %in% c("BS_40HCP3HB", "BS_MKGTXW8A", "BS_MMEVDXGV", "BS_P412CPXJ", "BS_X5A5TNG1", "BS_YV1E1G58")) %>% select(Kids_First_Biospecimen_ID, experimental_strategy, pathology_diagnosis)
# A tibble: 6 x 3
  Kids_First_Biospecimen_ID experimental_strategy pathology_diagnosis           
  <chr>                     <chr>                 <chr>                         
1 BS_40HCP3HB               RNA-Seq               Low-grade glioma/astrocytoma ~
2 BS_MKGTXW8A               RNA-Seq               Low-grade glioma/astrocytoma ~
3 BS_MMEVDXGV               RNA-Seq               Low-grade glioma/astrocytoma ~
4 BS_P412CPXJ               RNA-Seq               Low-grade glioma/astrocytoma ~
5 BS_X5A5TNG1               RNA-Seq               Low-grade glioma/astrocytoma ~
6 BS_YV1E1G58               RNA-Seq               Low-grade glioma/astrocytoma ~


> read_tsv("lgat_subtyping.tsv") %>% filter(Kids_First_Biospecimen_ID_RNA == "BS_40HCP3HB") %>% select(Kids_First_Biospecimen_ID_DNA, Kids_First_Biospecimen_ID_RNA, molecular_subtype, molecular_subtype_methyl)
# A tibble: 9 x 4
  Kids_First_Biospecimen_ID_DNA Kids_First_Biospecimen_ID_RNA molecula~1 molec~2
  <chr>                         <chr>                         <chr>      <chr>  
1 BS_0GVJJYWV                   BS_40HCP3HB                   LGG, wild~ NA     
2 BS_0MCY93CV                   BS_40HCP3HB                   LGG, FGFR  NA     
3 BS_0NNV9QAF                   BS_40HCP3HB                   LGG, NF1-~ NA     
4 BS_1C5Y79HZ                   BS_40HCP3HB                   LGG, wild~ NA     
5 BS_BYMV4DS7                   BS_40HCP3HB                   LGG, NF1-~ NA     
6 BS_STETBQHK                   BS_40HCP3HB                   LGG, NF1-~ NA     
7 BS_W8QVVDEJ                   BS_40HCP3HB                   LGG, FGFR  NA     
8 BS_X6NW8R6K                   BS_40HCP3HB                   LGG, wild~ NA     
9 BS_YAE6B9W7                   BS_40HCP3HB                   LGG, FGFR  NA 
> read_tsv("lgat_subtyping.tsv") %>% filter(Kids_First_Biospecimen_ID_RNA == "BS_40HCP3HB") %>% select(Kids_First_Biospecimen_ID_DNA, Kids_First_Biospecimen_ID_RNA, molecular_subtype, molecular_subtype_methyl) %>% pull(molecular_subtype) %>% unique
[1] "LGG, wildtype"          "LGG, FGFR"              "LGG, NF1-somatic, FGFR"
[4] "LGG, NF1-somatic"
```

**Comment by jharenza** [comment]
Update on this. 

1. should be resolved with new logic in the embryonal script by pulling in only BCOR methylation if path dx is an embryonal or PNET tumor
2. fixed with logic implemented from ticket https://github.com/PediatricOpenTargets/ticket-tracker/issues/531
3. For now, we should do the same as we did with 1. @ewafula can you update the embryonal module once more for this?
4. This sample needs to be excluded for previous mis-identification ca. 12/2020 and will fix this issue. Worked with @youngnm and we hid these, I re-pulled/created histologies file so this should be fixed with a rerun.
5. We should also exclude this from EWS subtyping - make sure here the path dx is EWS. @zzgeng can you update this module?
6 and 7. This is tricky since we have multiple samples and some can show TP53 alteration and some not. I am wondering if we make the TP53 annot just "TP53" to not annot loss/activation, and/or even keep TP53 status separated and in the TP53 module. For LGG, I need to look at this code - I will check on these two @ewafula

**Pull request merged**
