### PR TITLE
Analysis Update: Add neurocytoma workflow to README

### PR DESCRIPTION
**Pull request by zzgeng**
#### What scientific question is your analysis addressing?
Add neurocytoma workflow to README

#### What was your approach?
Add neurocytoma workflow to README

#### Which areas should receive a particularly close look?
Neurocytoma workflow

#### Reproducibility Checklist

- [ ] The dependencies required to run the code in this pull request have been added to the project Dockerfile.
- [ ] This analysis has been added to continuous integration.

#### Documentation Checklist

- [ ] This analysis module has a `README` and it is up to date.
- [ ] This analysis is recorded in the table in `analyses/README.md` and the entry is up to date.
- [ ] The analytical code is documented and contains comments.

### CODE REVIEW

**Review by naqvia — APPROVED** [review]
The code looks good to me. I would maybe add a portion on the methylation subtyping in the readme (rationale, cut-off used, etc).

**Review by jharenza — COMMENTED** [review]
I think you have a typo in the figure (EVN) not EWN

**Review by JosephDybas — APPROVED** [review]
This is straightforward and clear. It looks good to me. No notes! Thanks.

**Review by jharenza — APPROVED** [review]
👍

**Comment by jharenza** [comment]
docs only, no need for CI

**Pull request merged**
