### PR TITLE
Update PedOT column display order module

### PR DESCRIPTION
**Pull request by ewafula**
#### What scientific question is your analysis addressing?
Delete EFO and MONDO columns in `pedot-table-column-display-order-name.xlsx` using corresponding TSV files for v9  OpenPedCan data release JSONL files

#### What GitHub issue does your pull request address?
- https://github.com/PediatricOpenTargets/ticket-tracker/issues/189
- https://github.com/PediatricOpenTargets/ticket-tracker/issues/190

#### Which areas should receive a particularly close look?
Created the global variable list similar `COLUMNS_TO_DROP` to columns to be dropped similar to a global variable dictionary `TSV_FN_XLSX_SN_LUT` analyses table excel sheet names. Then  dropped the listed columns in the `_get_col_disp_order_name_df`  method of the  `TSVSheet` class

`Lines: 29 - 30`
```
# A list of names to drop from the PedOT column display
COLUMNS_TO_DROP = ["EFO", "MONDO"]
```

`Lines: 193 - 194`
```
# drop columns that are not required in PedOT column display
if len(COLUMNS_TO_DROP) != 0:
    sample_df.drop(columns=COLUMNS_TO_DROP, inplace=True)
```

#### Is there anything that you want to discuss further?
Updated `pedot-table-column-display-order-name.xlsx` file uploaded to OT Box folder

#### Is the analysis in a mature enough form that the resulting figure(s) and/or table(s) are ready for review?
YES

#### What types of results are included (e.g., table, figure)?
- `results/pedot-table-column-display-order-name.xlsx`

#### Reproducibility Checklist

- [x] The dependencies required to run the code in this pull request have been added to the project Dockerfile.
- [ ] This analysis has been added to continuous integration.

#### Documentation Checklist

- [x] This analysis module has a `README` and it is up to date.
- [ ] This analysis is recorded in the table in `analyses/README.md` and the entry is up to date.
- [x] The analytical code is documented and contains comments.

### CODE REVIEW

**Review by logstar — APPROVED** [review]
@ewafula - Thank you for updating the module!

The code and documentation changes look good to me. I have also reproduced the result Excel workbook `results/pedot-table-column-display-order-name.xlsx` identically by rerunning the updated module.

The result Excel workbook is also expected. The `EFO` and `MONDO` columns are removed from all Excel sheets. The "Fusion gene-level" sheet is consistent to the v9 `../fusion-frequencies/results/putative-oncogene-fused-gene-freq.jsonl.gz`.

@ewafula - After merging this PR, could you upload it to <https://nih.box.com/s/vja2gg7s4y5h6sgrdw88iwdkd0p1xvff> and send notification to the `#ot-portal-content` slack channel?

**Comment by jharenza** [comment]
@logstar @ewafula - is this ready to merge? (one more dev merge into this first?)

**Comment by ewafula** [comment]
@logstar approved, and FNL already have the updated column order excel file
posted in Box. I would say for v9 data release yes. But we may need to
update in the future to align with the additional columns that FNL proposed
for the all mutation files.

**Comment by jharenza** [comment]
ok sounds good @ewafula - can you check whether there are more updates from dev to pull into this? then we can merge.

**Comment by logstar** [comment]
@jharenza Thank you for checking.

I agree with @ewafula . This PR can be merged.

I think this module also needs to be updated to incorporate changes in <https://github.com/PediatricOpenTargets/ticket-tracker/issues/197>.

**Comment by ewafula** [comment]
@jharenza, I have pulled in updates from upstream/dev. Should be good to merge now.

**Pull request merged**
