### PR TITLE
Update gene_match module to add a new column in results mapping table

### PR DESCRIPTION
**Pull request by sangeetashukla**
### Purpose/implementation Section
- Update the module results table (ensg-hugo-pmtl-mapping.tsv) to include an additional mapping column (i.e., lastest_gene_symbol) for the gene symbols in the GENCODE version (v39) currently being utilized in the OpenPedCan.
- Update module README with appropriate description of module, files, and scripts.

#### What scientific question is your analysis addressing?
- Some discrepancies were found between the PMTL gene symbols and the result table in the module, since they were updated with newer Gencode versions. This module is now updated to include a new column `latest_gene_symbol` to display gene_symbols as found in Gencode v39 for corresponding ENSG IDs in the final `results\ensg-hugo-pmtl-mapping.tsv`

#### What was your approach?
Include a column to track the Gencode version source in the merged file, and use that as a reference to to extract the v39 gene_symbol in the `latest_gene_symbol` column in the final `results\ensg-hugo-pmtl-mapping.tsv` table.

#### What GitHub issue does your pull request address?
[Issue 472](https://github.com/PediatricOpenTargets/ticket-tracker/issues/472)

### Directions for reviewers. Tell potential reviewers what kind of feedback you are soliciting.
Review if discrepancies between gene symbols between the PMTL table and the final table can be appropriately resolved with the newly added column in `results\ensg-hugo-pmtl-mapping.tsv`

#### Which areas should receive a particularly close look?
No

#### Is there anything that you want to discuss further?
No

#### Is the analysis in a mature enough form that the resulting figure(s) and/or table(s) are ready for review?
Yes

### Results
`results\ensg-hugo-pmtl-mapping.tsv`

#### What types of results are included (e.g., table, figure)?
Table

#### Reproducibility Checklist

- [ ] The dependencies required to run the code in this pull request have been added to the project Dockerfile.
- [ ] This analysis has been added to continuous integration.

#### Documentation Checklist

- [ ] This analysis module has a `README` and it is up to date.
- [ ] This analysis is recorded in the table in `analyses/README.md` and the entry is up to date.
- [ ] The analytical code is documented and contains comments.

### CODE REVIEW

**Comment by ewafula** [comment]
@sangeetashukla, can you resolve the conflicts on this branch?

**Comment by sangeetashukla** [comment]
> @sangeetashukla, can you resolve the conflicts on this branch?

@ewafula it looks like I do not have write access and can not resolve the conflicts. And locally, my branch is clean.
Screen Shot 2023-01-10 at 8 42 37 AM

**Comment by ewafula** [comment]
> > @sangeetashukla, can you resolve the conflicts on this branch?
> 
> @ewafula it looks like I do not have write access and can not resolve the conflicts. And locally, my branch is clean. Screen Shot 2023-01-10 at 8 42 37 AM



> > @sangeetashukla, can you resolve the conflicts on this branch?
> 
> @ewafula it looks like I do not have write access and can not resolve the conflicts. And locally, my branch is clean. Screen Shot 2023-01-10 at 8 42 37 AM



> > @sangeetashukla, can you resolve the conflicts on this branch?
> 
> @ewafula it looks like I do not have write access and can not resolve the conflicts. And locally, my branch is clean. Screen Shot 2023-01-10 at 8 42 37 AM

**Comment by ewafula** [comment]
> > @sangeetashukla, can you resolve the conflicts on this branch?
> 
> @ewafula it looks like I do not have write access and can not resolve the conflicts. And locally, my branch is clean. Screen Shot 2023-01-10 at 8 42 37 AM

@sangeetashukla, you don't have write access to push? You can push after resolving conflicts, as you did before. The write access here have to do with merging the PR.  You need to merge dev into the PR's local branch before pushing to origin.  This branch is behind dev.

**Comment by sangeetashukla** [comment]
> > > @sangeetashukla, can you resolve the conflicts on this branch?
> > 
> > 
> > @ewafula it looks like I do not have write access and can not resolve the conflicts. And locally, my branch is clean. Screen Shot 2023-01-10 at 8 42 37 AM
> 
> @sangeetashukla, you don't have write access to push? You can push after resolving conflicts, as you did before. The write access here have to do with merging the PR. You need to merge dev into the PR's local branch before pushing to origin. This branch is behind dev.

@ewafula Everything looks good now, and all checks have passed.

**Comment by ewafula** [comment]
Thanks, @sangeetashukla, for solving the conflicts. I am not going to review this PR until after the v12 data release. But looking at the results file you did not address what was described in the ticket. I don't see values in the additional column with the latest gene symbols (v39) mapping back to the Gencode v27 Ensembl ID and gene symbols on which PMTL genes are based. `NAs` all through. 

In a previous discussion with @jharenza, we also need to add the corresponding latest  Ensemble ID column.  Found out that those also can change between Ensemble versions as observed  with the histone gene below:
```
v39  <- v29
H3C2 (ENSG00000286522)  <- HIST1H3B("ENSG00000274267)
H3C3 (ENSG00000287080) <- HIST1H3C (ENSG00000278272)
```

**Comment by sangeetashukla** [comment]
> Thanks, @sangeetashukla, for solving the conflicts. I am not going to review this PR until after the v12 data release. But looking at the results file you did not address what was described in the ticket. I don't see values in the additional column with the latest gene symbols (v39) mapping back to the Gencode v27 Ensembl ID and gene symbols on which PMTL genes are based. `NAs` all through.
> 
> In a previous discussion with @jharenza, we also need to add the corresponding latest Ensemble ID column. Found out that those also can change between Ensemble versions as observed with the histone gene below:
> 
> ```
> v39  <- v27
> H3C2 (ENSG00000286522)  <- HIST1H3B("ENSG00000274267)
> H3C3 (ENSG00000287080) <- HIST1H3C (ENSG00000278272)
> ```



@ewafula  I am testing the mapping table, and I see below results:
```
ensg_hugo_mapping <- readr::read_tsv("results/ensg-hugo-pmtl-mapping.tsv")
> length(unique(ensg_hugo_mapping$latest_gene_symbol))
[1] 60287

> ensg_hugo_mapping[which(ensg_hugo_mapping$latest_gene_symbol == "GMEB1"),]
# A tibble: 1 × 5
  ensg_id         gene_symbol pmtl  version latest_gene_symbol
  <chr>           <chr>       <chr> <chr>   <chr>             
1 ENSG00000162419 GMEB1       NA    v39     GMEB1 
```

But I will test the file for some more IDs and post the findings here.

**Comment by ewafula** [comment]
> > Thanks, @sangeetashukla, for solving the conflicts. I am not going to review this PR until after the v12 data release. But looking at the results file you did not address what was described in the ticket. I don't see values in the additional column with the latest gene symbols (v39) mapping back to the Gencode v27 Ensembl ID and gene symbols on which PMTL genes are based. `NAs` all through.
> > In a previous discussion with @jharenza, we also need to add the corresponding latest Ensemble ID column. Found out that those also can change between Ensemble versions as observed with the histone gene below:
> > ```
> > v39  <- v27
> > H3C2 (ENSG00000286522)  <- HIST1H3B("ENSG00000274267)
> > H3C3 (ENSG00000287080) <- HIST1H3C (ENSG00000278272)
> > ```
> 
> @ewafula I am testing the mapping table, and I see below results:
> 
> ```
> ensg_hugo_mapping <- readr::read_tsv("results/ensg-hugo-pmtl-mapping.tsv")
> > length(unique(ensg_hugo_mapping$latest_gene_symbol))
> [1] 60287
> 
> > ensg_hugo_mapping[which(ensg_hugo_mapping$latest_gene_symbol == "GMEB1"),]
> # A tibble: 1 × 5
>   ensg_id         gene_symbol pmtl  version latest_gene_symbol
>   <chr>           <chr>       <chr> <chr>   <chr>             
> 1 ENSG00000162419 GMEB1       NA    v39     GMEB1 
> ```
> 
> But I will test the file for some more IDs and post the findings here.

@sangeetashukla, these two subsets from the results suggest the majority of gene symbols and/or Ensemble IDs in v27 are not in  v39.  `61,487` vs. `235,966` rows for `Symbols` vs. `NAs,` respectively.
```
> read_tsv("results/ensg-hugo-pmtl-mapping.tsv") %>% filter(!is.na(latest_gene_symbol))                                          
# A tibble: 61,487 x 5
   ensg_id         gene_symbol     pmtl  version latest_gene_symbol
   <chr>           <chr>           <chr> <chr>   <chr>             
 1 ENSG00000223972 DDX11L1         NA    v39     DDX11L1           
 2 ENSG00000227232 WASH7P          NA    v39     WASH7P            
 3 ENSG00000278267 MIR6859-1       NA    v39     MIR6859-1         
 4 ENSG00000243485 MIR1302-2HG     NA    v39     MIR1302-2HG       
 5 ENSG00000284332 MIR1302-2       NA    v39     MIR1302-2         
 6 ENSG00000237613 FAM138A         NA    v39     FAM138A           
 7 ENSG00000268020 OR4G4P          NA    v39     OR4G4P            
 8 ENSG00000240361 OR4G11P         NA    v39     OR4G11P           
 9 ENSG00000186092 OR4F5           NA    v39     OR4F5             
10 ENSG00000238009 ENSG00000238009 NA    v39     ENSG00000238009   

> read_tsv("results/ensg-hugo-pmtl-mapping.tsv") %>% filter(is.na(latest_gene_symbol))                                          
# A tibble: 235,966 x 5
   ensg_id         gene_symbol pmtl  version latest_gene_symbol
   <chr>           <chr>       <chr> <chr>   <chr>             
 1 ENSG00000223972 DDX11L1     NA    v27     NA                
 2 ENSG00000227232 WASH7P      NA    v27     NA                
 3 ENSG00000278267 MIR6859-1   NA    v27     NA                
 4 ENSG00000243485 MIR1302-2HG NA    v27     NA                
 5 ENSG00000284332 MIR1302-2   NA    v27     NA                
 6 ENSG00000237613 FAM138A     NA    v27     NA                
 7 ENSG00000268020 AL627309.6  NA    v27     NA                
 8 ENSG00000240361 OR4G11P     NA    v27     NA                
 9 ENSG00000186092 OR4F5       NA    v27     NA                
10 ENSG00000238009 AL627309.1  NA    v27     NA                
> 
```

**Comment by sangeetashukla** [comment]
@ewafula I have tested the latest version of the results table for all the `ensg_id` you listed above and a few more, and the file looks good to me. This version of the final table shows a unique `latest_gene_symbol` for each `ensg_id`. Note that, the value in `latest_gene_symbol` is not included in `gene_symbol` column thus reducing redundancy. Of course, all `gene_symbol` for each `ensg_id` are tracked, each of which is mapped to a unique `latest_gene_symbol`.

**Comment by chinwallaa** [comment]
@sangeetashukla Can you confirm that this matches the targets mapping file in the MTP annotation module.

**Comment by sangeetashukla** [comment]
> @sangeetashukla Can you confirm that this matches the targets mapping file in the MTP annotation module.

@chinwallaa I can confirm after I have completed my review of the results from [PR 319](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/pull/319). I will work on it this week.

**Pull request closed without merging**
