### PR TITLE
Part 1 v6 release: update copy consensus

### PR DESCRIPTION
**Pull request by kgaonkar6**
#### What scientific question is your analysis addressing?
Update `copy_number_consensus_call` module and annotating calls in `focal-cn-prepration-files` to run for OT. 

#### What was your approach?
- update `pbta-histologies.tsv` to `histologies.tsv` 
- use `guess=100000` because without it `tumor_ploidy` is read incorreectly as `NA`
- update cnvkit and  controlfreec filename

#### What GitHub issue does your pull request address?
https://github.com/PediatricOpenTargets/ticket-tracker/issues/60

#### Which areas should receive a particularly close look?
NA this module only updates the filenames so no major code changes.

#### Is the analysis in a mature enough form that the resulting figure(s) and/or table(s) are ready for review?
yes

#### What types of results are included (e.g., table, figure)?
table

#### What is your summary of the results?
```
histology %>% filter(Kids_First_Biospecimen_ID %in% consensus_seg$ID) %>% pull(cohort) %>% table()
.
GMKF PBTA 
 261  915 
```
261 out of 336 GMKF and 915 out of 940 PBTA WGS samples are retained in the consensus cnv calls.  

#### Reproducibility Checklist

- [x] The dependencies required to run the code in this pull request have been added to the project Dockerfile.
- [x] This analysis has been added to continuous integration.

#### Documentation Checklist

- [x] This analysis module has a `README` and it is up to date.
- [x] This analysis is recorded in the table in `analyses/README.md` and the entry is up to date.
- [x] The analytical code is documented and contains comments.

### CODE REVIEW

**Review by runjin326 — APPROVED** [review]
Looks good to me!

**Review by runjin326 — APPROVED** [review]
Looks good to me!

**Review by jharenza — APPROVED** [review]
looks good to me!

**Comment by kgaonkar6** [comment]
Thanks for the review @jharenza @runjin326 🙌

**Pull request merged**
