### PR TITLE
Fusion Frequency Table Update

### PR DESCRIPTION
**Pull request by runjin326**
#### What scientific question is your analysis addressing?
Now that `independent-samples.*.tsv` and  `independent-samples.*.eachcohort.tsv` were modified to use same `Kids_First_Biospecimen_ID` if possible (specified in [this ticket](https://github.com/PediatricOpenTargets/ticket-tracker/issues/135)), `fusion-frequencies` module is updated to use all-cohorts independent sample lists (ISLs) for computing all-cohorts fusion frequencies and use each-cohort ISLs for computing each-cohort fusion frequencies. 

#### What was your approach?
When annotating the fusion frequency, depending on whether multiple cohorts were listed in the intermediate table `nf_cancer_group_cohort_summary_df` (column `cohort`), different independent sample lists were used:
```
 if(str_detect(cgcs_row$cohort, '&')){
      # Call function for all cohorts that have the cancer_group
      res_df <- get_cg_ch_mut_freq_tbl(
        fusion_df, td_htl_dfs$overall_htl_df, td_htl_dfs$primary_htl_all_df,
        td_htl_dfs$relapse_htl_all_df, c_cancer_group, c_cohorts) 
    }else{
      # Call function for each cohort and cancer_group
      res_df <- get_cg_ch_mut_freq_tbl(
        fusion_df, td_htl_dfs$overall_htl_df, td_htl_dfs$primary_htl_each_df,
        td_htl_dfs$relapse_htl_each_df, c_cancer_group, c_cohorts) 
    }
```

#### What GitHub issue does your pull request address?
https://github.com/PediatricOpenTargets/ticket-tracker/issues/140

#### Which areas should receive a particularly close look?
Please check to see whether my modification was what is wanted 

#### Is there anything that you want to discuss further?
Currently, with v8 `ensg-hugo-rmtl-mapping.tsv`, we are getting [an error in this line](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/blob/174a028183fdaec84a780b3bcf516b1e3ceabd40/analyses/fusion-frequencies/01-fusion-frequencies.R#L106-L107). I had to comment it out for the code to run properly. Do we need an update with `ensg-hugo-rmtl-mapping.tsv` or is it fine to leave it like this?

#### Is the analysis in a mature enough form that the resulting figure(s) and/or table(s) are ready for review?
Yes.

#### What types of results are included (e.g., table, figure)?
```
putative-oncogene-fused-gene-freq.jsonl.gz
putative-oncogene-fused-gene-freq.tsv.gz
putative-oncogene-fusion-freq.jsonl.gz
putative-oncogene-fusion-freq.tsv.gz
```

#### Reproducibility Checklist

- [x] The dependencies required to run the code in this pull request have been added to the project Dockerfile.
- [ ] This analysis has been added to continuous integration.

#### Documentation Checklist

- [x] This analysis module has a `README` and it is up to date.
- [ ] This analysis is recorded in the table in `analyses/README.md` and the entry is up to date.
- [x] The analytical code is documented and contains comments.

### CODE REVIEW

**Comment by logstar** [comment]
@ewafula Thank you for the review.

> I think the error with `v8 ensg-hugo-rmtl-mapping.tsv` is expected if not commented off. 

This is correct.

> In the latest update of the `long-format-table-utils` annotator by @logstar, ESNG ID may be assigned to multiple gene symbols.

ENSG IDs are assigned to multiple gene symbols in <https://github.com/d3b-center/D3b-codes/pull/48>. The annotator does not map ENSG ID to gene symbols.

> Therefore, the ENSG IDs might not be unique in the results.

This is correct.

@runjin326 Before v8, one ENSG ID only maps to one gene symbol. In v8, one ENSG ID may map to more than one gene symbols. If the assumption that one ENSG ID only maps to one gene symbol is used in any computation procedure, the computation procedure needs to be revised to handle cases where one ENSG ID maps to multiple gene symbols.

Generally, the `stopifnot(...)` asserts certain assumption is true when running the script. An error indicates that the assumption does not hold, which may or may not affect the whole computation procedure and results. In order to determine whether the whole computation procedure or results are affected or not, the maintainer needs to reason through the whole computation procedure.

**Comment by runjin326** [comment]
> I regenerated identical results to @runjin326 PR update. The logic for `all cohorts` and `each cohort` variant frequencies calculation utilizing different independent samples is implemented correctly on lines 240 - 250 of the `01-fusion-frequencies.R` script. I think the error with `v8 ensg-hugo-rmtl-mapping.tsv` is expected if not commented off. In the latest update of the `long-format-table-utils` annotator by @logstar, ESNG ID may be assigned to multiple gene symbols. Therefore, the ENSG IDs might not be unique in the results. But @logstar can confirm.

@ewafula, thanks so much for reviewing!

**Comment by runjin326** [comment]
> @runjin326 Before v8, one ENSG ID only maps to one gene symbol. In v8, one ENSG ID may map to more than one gene symbols. If the assumption that one ENSG ID only maps to one gene symbol is used in any computation procedure, the computation procedure needs to be revised to handle cases where one ENSG ID maps to multiple gene symbols.
> 
> Generally, the `stopifnot(...)` asserts certain assumption is true when running the script. An error indicates that the assumption does not hold, which may or may not affect the whole computation procedure and results. In order to determine whether the whole computation procedure or results are affected or not, the maintainer needs to reason through the whole computation procedure.

@logstar, thanks so much for the clarification! Looks like the uniqueness of the mapping is not absolutely necessary for the correct annotation so I think it should be fine to leave commented like this.

**Comment by runjin326** [comment]
@runjin326, change cancer_group N>=3 [in this step](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/blob/73d7a4d4ca8cbe564b8ae8c4d0401448372cb091/analyses/fusion-frequencies/01-fusion-frequencies.R#L198-L199).

**Comment by runjin326** [comment]
@jharenza, this is re-run with new `efo-mondo-map.txt` file and cancer group n>=3 and I implemented the changes to take different independent samples - however, I haven't merge PR (https://github.com/PediatricOpenTargets/OpenPedCan-analysis/pull/101) so the jsonl change is not reflected. Will re-run this once you reviewed 101 and merged.

**Comment by runjin326** [comment]
@ewafula, I know you have approved this before (thank you!) but I have now added a couple changes:
1) used cancer group N>=3
2) Used v9 mondo file 
3) Implemented changes in this PR (https://github.com/PediatricOpenTargets/OpenPedCan-analysis/pull/101) - basically writing out the correct fields for JSONL file 
Could you please re-run the code and see everything still runs for you and the results are as expected? 

Thanks so much!

**Comment by ewafula** [comment]
Sure, I’ll rerun the code.

**Comment by ewafula** [comment]
> @ewafula, I know you have approved this before (thank you!) but I have now added a couple changes:
> 
> 1. used cancer group N>=3
> 2. Used v9 mondo file
> 3. Implemented changes in this PR ([Fusion frequencies jsonl update #101](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/pull/101)) - basically writing out the correct fields for JSONL file
>    Could you please re-run the code and see everything still runs for you and the results are as expected?
> 
> Thanks so much!

@runjin326,  rerun the fusion frequencies module produces the results as those in your PR. There are no errors or warnings messages during the execution, and the key-values in the JSONL files are identical to column names and records in TSV files for random subsets. 
Is there anything specific that you like me to validate in the results? 
Otherwise,  looks good to me!

**Comment by runjin326** [comment]
> @runjin326, rerun the fusion frequencies module produces the results as those in your PR. There are no errors or warnings messages during the execution, and the key-values in the JSONL files are identical to column names and records in TSV files for random subsets.
> Is there anything specific that you like me to validate in the results?
> Otherwise, looks good to me!
Thanks so much! That is all I need - just want to confirm everything still works by you!

**Pull request merged**
