### PR TITLE
update independent samples  README

### PR DESCRIPTION
**Pull request by ewafula**
#### What scientific question is your analysis addressing?
Update README

#### What was your approach?
Add correct descriptions and files names for independent specimen results

#### What GitHub issue does your pull request address?
https://github.com/PediatricOpenTargets/ticket-tracker/issues/443

#### Which areas should receive a particularly close look?
The correct descriptions and files nammes of independent specimen results 

#### Is there anything that you want to discuss further?
No

#### Is the analysis in a mature enough form that the resulting figure(s) and/or table(s) are ready for review?
Yes

#### What types of results are included (e.g., table, figure)?
Markdown

#### What is your summary of the results?
Update README

#### Reproducibility Checklist

- [x] The dependencies required to run the code in this pull request have been added to the project Dockerfile.
- [x ] This analysis has been added to continuous integration.

#### Documentation Checklist

- [x] This analysis module has a `README` and it is up to date.
- [x] This analysis is recorded in the table in `analyses/README.md` and the entry is up to date.
- [x] The analytical code is documented and contains comments.

### CODE REVIEW

**Review by sangeetashukla — COMMENTED** [review]
Now that the `long-format-table-utils` module has been removed from CI per [this PR](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/pull/284#pullrequestreview-1163931719), I can approve this once it passes all checks.

**Comment by sangeetashukla** [comment]
@ewafula  Will wait for another round of checks since [this](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/pull/284) was merged, and then approve.

**Comment by ewafula** [comment]
> @ewafula Will wait for another round of checks since [this](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/pull/284) was merged, and then approve.

Thank you!

**Review by sangeetashukla — APPROVED** [review]
@ewafula Approving since all checks have passed. 
Thanks for updating the README.

**Pull request merged**
