### PR TITLE
TP53 module modified to add fusion columns

### PR DESCRIPTION
**Pull request by runjin326**
#### What scientific question is your analysis addressing?
OpenPBTA has updated to add `Fusion_evidence` and `Fusion_counts` columns and we can bring in those changes. 

#### What was your approach?
Modified `04-tp53-sv-loss.Rmd` to include fusion filtering calls.

#### What GitHub issue does your pull request address?
https://github.com/PediatricOpenTargets/ticket-tracker/issues/222

#### Which areas should receive a particularly close look?
Please review after [PR134](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/pull/134) is merged and v10 release is out to use the most up-to-date files. 

#### Is there anything that you want to discuss further?
No.

#### Is the analysis in a mature enough form that the resulting figure(s) and/or table(s) are ready for review?
Not yet - need a re-run after v10 release.

#### What types of results are included (e.g., table, figure)?
```
TP53_NF1_snv_alteration.tsv
exome_capture_TP53.png
fusion_bk_tp53_loss.tsv
gene-expression-rsem-tpm-collapsed_classifier_scores.tsv
loss_overlap_domains_tp53.tsv
poly-A_TP53.png
stranded_TP53.png
sv_overlap_tp53.tsv
tp53_altered_status.tsv
```

#### What is your summary of the results?
Not yet ready - will summarize once re-ran with v10 files.

#### Reproducibility Checklist

- [x] The dependencies required to run the code in this pull request have been added to the project Dockerfile.
- [ ] This analysis has been added to continuous integration.

#### Documentation Checklist

- [ ] This analysis module has a `README` and it is up to date.
- [ ] This analysis is recorded in the table in `analyses/README.md` and the entry is up to date.
- [x] The analytical code is documented and contains comments.

### CODE REVIEW

**Comment by ewafula** [comment]
@runjin326,  I have been looking through the module, and the R update code in `04-tp53-sv-loss.Rmd` to include fusion results, and seem okay to me. Was the purpose of the update just to list the fusion breakpoints within TP53.  Were they also be associated in some way with their effect on TP53 functionality?  

Am not able to run the module successfully using the OpenPedCan Docker container starting with the initial script of the analysis, `00-tp53-nf1-alterations.R`.  
- The bash wrapper script, `run_classifier.sh` needs to the correct, on line 15 to `if [[ ${RUN_FOR_SUBTYPING} == "0" ]]`. Otherwise, it selects the `histologies-base.tsv` rather `histologies.tsv` which we don't OpenPedCan v10 data release.  
```
Error: '../../data/histologies-base.tsv' does not exist in current working directory ('/home/OpenPedCan-analysis/analyses/tp53_nf1_score').
Execution halted
```
- There is a contradiction as coded in the bash wrapper script, `run_classifier.sh` where it should be executed as opposed to what is written in the README.md

- The initial analysis script, `00-tp53-nf1-alterations.R` needs to write the output file into a module's `results` directory. There is nowhere in the script where the `results` directory is created, including the preceding caller bash script, `run_classifier.sh`. 
```
In open.connection(path, "wb") :
  cannot open file '/home/OpenPedCan-analysis/analyses/tp53_nf1_score/results/TP53_NF1_snv_alteration.tsv': No such file or directory
Execution halted
``` 
- The module is missing the input file `cnvkit_with_status.tsv` causing the notebook  `03-tp53-cnv-loss-domain.Rmd` rendering to terminate prematurely. 
```
processing file: 03-tp53-cnv-loss-domain.Rmd
  |....                                                             |   7%
  ordinary text without R code

  |.........                                                        |  13%
label: unnamed-chunk-1
  |.............                                                    |  20%
  ordinary text without R code

  |.................                                                |  27%
label: unnamed-chunk-2
Quitting from lines 57-76 (03-tp53-cnv-loss-domain.Rmd) 
Error: '/home/OpenPedCan-analysis/analyses/tp53_nf1_score/input/cnvkit_with_status.tsv' does not exist.
```
- Do you have an updated Dockerfile that you used to reproduce the PR results? Might solve the following R and Python warnings if I can rebuild the Docker image: 
```
Registered S3 method overwritten by 'R.oo':
  method        from       
  throw.default R.methodsS3
```

```
Warning messages:
1: In bind_rows_(x, .id) :
  binding character and factor vector, coercing into character vector
2: In bind_rows_(x, .id) :
  binding character and factor vector, coercing into character vector
/usr/local/lib/python3.5/dist-packages/rpy2/rinterface/__init__.py:145: RRuntimeWarning: Error: package or namespace load failed for ‘stats’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/usr/local/lib/R/library/stats/libs/stats.so':
  libRlapack.so: cannot open shared object file: No such file or directory

  warnings.warn(x, RRuntimeWarning)
/usr/local/lib/python3.5/dist-packages/rpy2/rinterface/__init__.py:145: RRuntimeWarning: During startup - 
  warnings.warn(x, RRuntimeWarning)
/usr/local/lib/python3.5/dist-packages/rpy2/rinterface/__init__.py:145: RRuntimeWarning: Warning message:

  warnings.warn(x, RRuntimeWarning)
/usr/local/lib/python3.5/dist-packages/rpy2/rinterface/__init__.py:145: RRuntimeWarning: package ‘stats’ in options("defaultPackages") was not found 

  warnings.warn(x, RRuntimeWarning)
/usr/local/lib/python3.5/dist-packages/rpy2/robjects/pandas2ri.py:190: FutureWarning: from_items is deprecated. Please use DataFrame.from_dict(dict(items), ...) instead. DataFrame.from_dict(OrderedDict(items)) may be used to preserve the key order.
  res = PandasDataFrame.from_items(items)
```

**Comment by runjin326** [comment]
@ewafula, thanks for reviewing this PR and these are all good questions!
1) To answer the question about `if [[ ${RUN_FOR_SUBTYPING} == "0" ]]` - background information is this module is by default to be run before subtyping - therefore, it assumes that we are using `histologies-base.tsv` instead of `histologies.tsv`. 
- To run the module using the `histologies.tsv`, please use `RUN_ORIGINAL=1 bash run_classifier.sh` to run the module

2) For missing `cnvkit_with_status.tsv` file - it stated i[n this part of the script](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/blob/c7a01f547c5f7acc5f5e416729456b1fce59cc40/analyses/tp53_nf1_score/03-tp53-cnv-loss-domain.Rmd#L41-L53) that it needs two Rmd from focal cn preparation module to be ran first. Once you have the files ready, you should be able to run

3) For `results` folder missing - this is pretty interesting since I never noticed it - when I clone the repo, it already cloned the results folder with all the files in there. But I added lines to create the results folder in 00 script so you should be good to go.

4) For docker file, there is not an updated docker file and I have seen those warning messages as well - seems like these messages did not stop the module to be ran so I would probably leave it as is for now.

**Comment by runjin326** [comment]
@ewafula, oh for 2 - once you ran the 2 Rmd files, you would also need to copy those files from `scratch` folder in the base directory to the `input` folder of this repo to get the module running. 
This file was not pushed since it exceeds 100Mb.

**Comment by ewafula** [comment]
@runjin326, Thank you!  Makes sense now. I follow the steps you outlined to try and reproduce results.

**Comment by runjin326** [comment]
@ewafula, oh well I messed up the branch when I was resolving conflicts and merging dev - I will close this PR and open a new one with most up-to-date dev without all the issues. Could you please review that PR instead? Thanks so much and sorry about that.

**Pull request closed without merging**
