### PR TITLE
Tp53 nf1 update p2

### PR DESCRIPTION
**Pull request by runjin326**
#### What scientific question is your analysis addressing?
Modify the tp53-nf1-score module to be compatible with OpenPedCan datasets.

#### What was your approach?

- For 03 script - since we implement two different workflows for WGS and WXS CNV calling - two separate CNV files for WGS and WXS are used.
- For 04 script - the combined RNA expression matrix is used (instead of poly-A and stranded separately)
- For 05 script - only one classifier score and one combined RNA expression matrix is used - however, for the visualization, they are broken down based on the `RNA_library` type since that is how the scores were previously calculated s well
- For 06 script - again, combined file was read in but they are subset based on `RNA_library` type for the visualization.

#### What GitHub issue does your pull request address?
https://github.com/PediatricOpenTargets/ticket-tracker/issues/97

#### Which areas should receive a particularly close look?
Please see whether subsetting them based on RNA-library type makes sense.

#### Is there anything that you want to discuss further?
Some of the violin plots are super crowded (over-plotting probably). Do we want different visuals?

#### Is the analysis in a mature enough form that the resulting figure(s) and/or table(s) are ready for review?
Yes.

#### What types of results are included (e.g., table, figure)?

- `loss_overlap_domains_tp53.tsv `(from 03)
- `sv_overlap_tp53.tsv` (from 04) 
- `loss_overlap_domains_tp53.tsv` (from 05)
- Figures from 06:
  - `poly-A_TP53.png`
  - `stranded_TP53.png`
  - `poly-A_stranded_TP53.png`

#### What is your summary of the results?
Based on the results, looks like for the stranded samples, classifier score give good estimate about functionality.

#### Reproducibility Checklist

- [x] The dependencies required to run the code in this pull request have been added to the project Dockerfile.
- [ ] This analysis has been added to continuous integration.

#### Documentation Checklist

- [x] This analysis module has a `README` and it is up to date.
- [ ] This analysis is recorded in the table in `analyses/README.md` and the entry is up to date.
- [x] The analytical code is documented and contains comments.

### CODE REVIEW

**Review by jharenza — COMMENTED** [review]
yikes - those polya and polya stranded ROC curves are not looking so hot. polya is surprising to me since we now have a lot of TARGET samples in here and should have some signal and not sure why this is happening. I also checked - the `TARGET-40-*` samples, which are osteosarcomas driven by TP53 inactivation/loss are almost all annotated as loss, but they don't all have high TP53 scores (see below). I would expect these to almost all be high (>0.7 based on previous work [here](https://www.cell.com/cell-reports/pdfExtended/S2211-1247(19)31268-9)). Although, maybe the OS RNA-Seq samples might have some QC issues - cc @apexamodi for input.

Also @zhangb1 @bmennis @yuankunzhu - for TARGET etc new data we process, are we utilizing our QC filters (eg need to have at least 60% of reads mapped to human?)

image

**Comment by jharenza** [comment]
@runjin326 can you just subset this to only run for PBTA for now since we know it works well and most are stranded, and then add a ticket to investigate the other datasets later? We can't reliably use those results with a ROC with no sensitivity or specificity. Thanks!

**Comment by runjin326** [comment]
> @runjin326 can you just subset this to only run for PBTA for now since we know it works well and most are stranded, and then add a ticket to investigate the other datasets later? We can't reliably use those results with a ROC with no sensitivity or specificity. Thanks!

I realized that for 06 when running the ROC scores, it did not subset to contain our cohorts of interest (i.e., TCGA and GTEx were not subsetted). The results now actually does not have signals for all of them - very weird. 

So should I hard coded to filter cohort PBTA for now for this PR? @jharenza

**Comment by jharenza** [comment]
> So should I hard coded to filter cohort PBTA for now for this PR? 

Yes. Also, I see a _polya_ and _Poly-A_ curve - we may need a histology file update on RNA_library - can you file that issue for whichever sample(s) that is?

**Comment by runjin326** [comment]
> > So should I hard coded to filter cohort PBTA for now for this PR?
> 
> Yes. Also, I see a _polya_ and _Poly-A_ curve - we may need a histology file update on RNA_library - can you file that issue for whichever sample(s) that is?

I believe the polya that you saw was previous results that we had and that was deleted and we actually only have poly-A now - I used the name as is now but before they rename `poly-A` to `polya` for file name. 

I will subset to PBTA now and submit a ticket for the issue we see.

**Comment by runjin326** [comment]
@jharenza, I subset to PBTA and all scripts were re-run now. All files were updated now and contains only PBTA samples, Luckily the signals for both poly-A and stranded are back. 
ROC scores are as followed:
- poly-A - before, read:shuffle = 0.71:0.34; now, read:shuffle = 0.81:0.45
- stranded- before, read:shuffle = 0.92:0.59; now, read:shuffle = 0.83:0.51
Looks like the absolute values are different, the diffs are the same. 

I will open a ticket to investigate TARGET and GMKF.

**Review by jharenza — APPROVED** [review]

**Pull request merged**
