### PR TITLE
Tp53 score rerun

### PR DESCRIPTION
**Pull request by runjin326**
#### What scientific question is your analysis addressing?
After the 2 PNOC datasets (24 WGS from PNOC dataset1 and 40 WXS from PNOC dataset2) were added for v10 release, this module needs a re-run with all those file added. 

#### What was your approach?
- I ran the module with `histologies-base.tsv` which contained the additional samples (the newly added ones do not have molecular subtype yet) as well as all samples that were already added. 
- This is an intermediate file that would not be included in the data release - just used for subtyping related modules to get subtypes for new additional samples.

#### What GitHub issue does your pull request address?
https://github.com/PediatricOpenTargets/ticket-tracker/issues/209

#### Which areas should receive a particularly close look?
- Since this is a re-run, we do not need to worry about code review - just do a result review will be sufficient.
- `results/tp53_altered_status.tsv` is the file that would be used in the subtyping module and is the file that we need to QC
- Since the classifier ran based on z-scored gene expression and the addition of samples changes the z-score matrix - it is expected that `tp53_score` in `results/tp53_altered_status.tsv` would change with addition of samples. 
     -  However, we would not expected the number to change drastically (e.g., >0.7~0.8 should not change to 0.3~0.4) but a relatively small change <=~0.02~0.03 should be expected
     - Spot check for some samples would be sufficient to QC the scores
- Additionally, the AUROC plots for all RNA library (for now `poly-A_TP53.png`, `stranded_TP53.png` and `exome_capture_TP53.png`) would need to look at 
      - Basically this part is where we see whether the classifier worked - what we want is the score for real curve to  be higher than >0.5 and be higher than the shuffled curve.

#### Is there anything that you want to discuss further?
No.

#### Is the analysis in a mature enough form that the resulting figure(s) and/or table(s) are ready for review?
Yes. 

#### What types of results are included (e.g., table, figure)?
Table and figures in the results folder with the following being most important:
```
tp53_altered_status.tsv
poly-A_TP53.png
stranded_TP53.png
exome_capture_TP53.png	
```

#### What is your summary of the results?
1) In the final output `tp53_altered_status.tsv`, an additional of 64 entries were present which is expected since we added 24 WGS PNOC dataset 1 and 40 WXS PNOC dataset 2
2) All three AUROC plots showed >0.7 scores for real matrix and <0.5 scores for shuffled matrix.

#### Reproducibility Checklist

- [x] The dependencies required to run the code in this pull request have been added to the project Dockerfile.
- [ ] This analysis has been added to continuous integration.

#### Documentation Checklist

- [x] This analysis module has a `README` and it is up to date.
- [ ] This analysis is recorded in the table in `analyses/README.md` and the entry is up to date.
- [x] The analytical code is documented and contains comments.

### CODE REVIEW

**Comment by kgaonkar6** [comment]
Hi @runjin326  I'm wondering which commands creates exome_capture_TP53.png ? The bash script seems to only evaluation commands for  stranded and polya rnaseq?

**Comment by runjin326** [comment]
@kgaonkar6 , yes it is through 06 - https://github.com/PediatricOpenTargets/OpenPedCan-analysis/blob/0dd54a38def54210b746d65d318a79f7bde738f8/analyses/tp53_nf1_score/06-evaluate-classifier.py#L172-L204
Basically I am iterating through each RNA library possible without specifically calling them.

**Comment by kgaonkar6** [comment]
> Basically I am iterating through each RNA library possible without specifically calling them.

Ah ok do you want to update the comments in the bash script then? Other than that I'll approve the changes because it's only a rerun.

**Review by kgaonkar6 — APPROVED** [review]

**Comment by runjin326** [comment]
@kgaonkar6, thanks so much for reviewing! I updated the run script and merged dev back - merging soon.

**Pull request merged**
