### PR TITLE
Modify methyl independent specimens to match with independent RNA samples

### PR DESCRIPTION
**Pull request by sangeetashukla**
### Purpose/implementation Section
Update [independent-samples module](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/tree/dev/analyses/independent-samples) 05-generate-independent-specimens-methyl.R script to create methylation all_cohorts and each_cohorts primary and relapse independent sample lists.

#### What scientific question is your analysis addressing?

- Currently, the module creates only methylation all_cohorts independent sample lists independent-specimens.methyl.primary.tsv and independent-specimens.methyl.relapse.tsv.
- Need to create additional methylation each_cohorts independent sample lists independent-specimens.methyl.primary.eachcohort.tsv and independent-specimens.methyl.relapse.eachcohort.tsv.
- A new match_id needs to be created to account for the non-unique sample_id in the TARGET cohort and future cohorts with similar sample_id. The new match_id is for determining methylation samples with matching RNA-Seq samples that need to be prioritized for selection into the independent sample lists. Please refer to a similar approach implemented for matching RNA-Seq to DNA samples in the util/independent-rna-samples.R

#### What was your approach?
1.  Modify `05-generate-independent-specimens-methyl.R` to add code chunks to create methylation DNA samples for `each_cohort` lists for `primary` and `relapse` samples.
2. Modify `utils/independent-dna-samples.R` to create a new `match_id` to account for non-unique `sample_id` across cohorts and determine matching RNA-Seq samples.

#### What GitHub issue does your pull request address?
[Issue 412](https://github.com/PediatricOpenTargets/ticket-tracker/issues/412)

### Directions for reviewers. Tell potential reviewers what kind of feedback you are soliciting.
- Review the newly added result files for data integrity
`independent-specimens.methyl.primary-plus.eachcohort.tsv`
`independent-specimens.methyl.primary-plus.tsv`
`independent-specimens.methyl.primary.eachcohort.tsv`
`independent-specimens.methyl.primary.tsv`
`independent-specimens.methyl.relapse.eachcohort.tsv`
`independent-specimens.methyl.relapse.tsv`

#### Which areas should receive a particularly close look?
Please review the code changes in util/independent-dna-samples.R to account for non-unique `sample_id` from specified cohort (`TARGET` in this case) with match RNA-seq sample.

#### Is there anything that you want to discuss further?
No

#### Is the analysis in a mature enough form that the resulting figure(s) and/or table(s) are ready for review?
Yes

#### What types of results are included (e.g., table, figure)?
Files listed as above

#### Reproducibility Checklist

- [x] The dependencies required to run the code in this pull request have been added to the project Dockerfile.
- [x] This analysis has been added to continuous integration.

#### Documentation Checklist

- [x] This analysis module has a `README` and it is up to date.
- [x] This analysis is recorded in the table in `analyses/README.md` and the entry is up to date.
- [x] The analytical code is documented and contains comments.

### CODE REVIEW

**Comment by ewafula** [comment]
@sangeetashukla, thanks for working to module the module.  I have a few review comments.  

You don't need to update the code for generating DNA independent (`WGS/WXS/Targeted Sequencing`) samples to include `match_id`  with `RNA-Seq`. The matching DNA-RNA-Seq is not needed for DNA independent samples. Therefore, the following scripts should not be updated:

Instead of updating util/independent-dna-samples.R  function,  she should create a util/independent-methly-samples.R  function similar to util/independent-rna-samples.R function with match_id for RNA-Seq- Methylation experimental_strategy to be sourced by 05-generate-independent-specimens-methyl.R.  Then,  there would be no need of amending all the scripts for creating WGS/WXS/Targeted Sequencing  DNA  independent samples.

**Comment by ewafula** [comment]
@sangeetashukla had a discussion below with @jharenza because I need methylaected. 

tion-independent samples for the working generating downstream table for API plotting.  She agrees that we need to change the logic for generating methylation-independent samples. This approach you used will impact the DNA- independent samples selected. 
```
In my opinion, she did not need to update the code for generating DNA  independent samples to include `match_id  with RNA-Seq (not need to for DNA independent samples).  Instead of updating util/independent-dna-samples.R  function,  she should create a util/independent-methly-samples.R  function similar to util/independent-rna-samples.R function with match_id for RNA-Seq- Methylation experimental_strategy to be sourced by 05-generate-independent-specimens-methyl.R.  Then,  there would be no need to amend all the scripts for creating WGS/WXS/Targeted Sequencing  DNA  independent samples.
```

**Comment by ewafula** [comment]
@sangeetashukla , A quick look at the results, there are no PBTA methyl samples included (majority of the data).  Only TARGET are included and GMKF which does not have methylation samples: [https://github.com/PediatricOpenTargets/OpenPedCan-analysis/blob/update-methyl-ind[…]endent-samples/results/independent-specimens.methyl.primary.tsv](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/blob/update-methyl-indspec/analyses/independent-samples/results/independent-specimens.methyl.primary.tsv)

**Comment by sangeetashukla** [comment]
Closing in favor of [this](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/pull/263)

**Pull request closed without merging**
