### PR TITLE
update methylation summary module

### PR DESCRIPTION
**Pull request by ewafula**
### Purpose/implementation Section
Update [methylation-summary](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/tree/dev/analyses/methylation-summary) modules

#### What scientific question is your analysis addressing?
- utilize independent sample lists
- include gene locus-isforms in methylation summary tables

#### What was your approach?
- updated the  module to utilize RNA-Seq and methyl  independent sample lists 
- updated module to compute gene locus-isoforms in addition to gene locus for beta-tpm correlations 
- created separate gene-level and isoform-level methylation summary tables to reduce the file size
- introduced command line options for all scripts to enable easy implementation in cavatica 
- utilized Rsqlite3 where possible to reduce memory usage. 

#### What GitHub issue does your pull request address?
- https://github.com/PediatricOpenTargets/ticket-tracker/issues/371

#### Which areas should receive a particularly close look?
All scripts have been updated and need to be reviewed

#### Is there anything that you want to discuss further?
NA

#### Is the analysis in a mature enough form that the resulting figure(s) and/or table(s) are ready for review?
YES

#### What types of results are included (e.g., table, figure)?
TSV and JSONL tables

#### What is your summary of the results?
- `results/methyl-probe-annotations.tsv.gz`
- `results/methyl-probe-beta-quantiles.tsv.gz`
- `results/gene-methyl-probe-beta-tpm-correlations.tsv.gz`
- `results/isoform-methyl-probe-beta-tpm-correlations.tsv.gz`
- `results/gene-methyl-beta-values-summary.rds` 
- `results/gene-methyl-beta-values-summary.tsv.gz` 
- `results/gene-methyl-beta-values-summary.jsonl.gz`
- `results/isoform-methyl-beta-values-summary.rds` 
- `results/isoform-methyl-beta-values-summary.tsv.gz` 
- `results/isoform-methyl-beta-values-summary.jsonl.gz`

#### Reproducibility Checklist

- [x] The dependencies required to run the code in this pull request have been added to the project Dockerfile.
- [ ] This analysis has been added to continuous integration.

#### Documentation Checklist

- [x] This analysis module has a `README` and it is up to date.
- [x] This analysis is recorded in the table in `analyses/README.md` and the entry is up to date.
- [x] The analytical code is documented and contains comments.

### CODE REVIEW

**Comment by ewafula** [comment]
@afarrel, results for this module are available on Isilon (`/mnt/isilon/opentargets/wafulae/methylation-summary/results`) to review. These have been generated using the v11 datasets. Either @zhangb1 will rerun the module with v12 data if the D3b bix-dev team can develop a cavatica app time, or I can rerun the OPC module on Isilon. I used the latest Illumina Infinium methylation probe manifest (available in the module `input/` directory), now using Build 37 (GRCh37) instead of  hg19 (equivalent builds except for the use of 0- or 1-based coordinate systems). The latest probes manifest includes associated Ensembl gene transcript IDs (transformed to gencode v39 in the module) and the previous RefSeq gene IDs.

@jharenza to request the bix-dev team to start work cavatica app after @afarrel has reviewed the module. I'll write a ticket.

**Comment by ewafula** [comment]
@afarrel, I regenerated results using `primary-each-cohort` instead of `primary-each-cohort-plus` independent samples list for both methylation and RNA-Seq data.

**Review by afarrel — CHANGES_REQUESTED** [review]
Hi Eric! Great work. I looked at the code and the rest tables and they look great. The only thing I'd add in regards to the transcript summary table is annotating an estimation of the percent of each transcript occurring in the diseases. This will be useful information in the final plot. Given the diversity of the data going into the plot, we would have to weight each sample to calculate a fair percent transcript expression of a gene in a given cancer group. Perhaps the below approach would work:

1) First calculate a Z score for each sample

**Z<sub>s</sub>= S<sub>G_TPM</sub> - µ<sub>G_TPM</sub>/sd<sub>G_TPM</sub>**

Where Z<sub>s</sub> is the Sample gene expression Z Score, S<sub>G_TPM</sub> is the gene expression value of that sample in TPM, µ<sub>G_TPM</sub> is the mean TPM expression of the gene in that cancer group, and sd<sub>G_TPM</sub> is the standard deviation of the TPM expression of the gene in that cancer group.

2) Then Calculate the Weight. The inverse exponential function of the absolute Z-score will give us a weight that decreases the further the sample's gene expression deviates from the mean. This way, weird outliers will not distort the calculation.

**W<sub>s</sub> = 1/e<sup>|Z<sub>s</sub>|</sup>**

Where W<sub>s</sub> is the weight assigned to the sample, and Z<sub>s</sub> is the sample's gene expression Z score calculated in the previous step.

3) Finally, apply the weights to the Transcript expressions and sum them to calculate the percent expression.

**Transcript_Representation = (∑<sub>S_t</sub> W<sub>s</sub>•TPM<sub>S_transcript</sub>)/ (∑ W<sub>s</sub>• TPM<sub>S_Total(All transcripts)</sub>)**

Where W<sub>s</sub> is the weight assigned to the sample calculated in the previous step, TPM<sub>S_transcript</sub> is expression of each Sample's individual transcript in TPM, and TPM<sub>S_Total(All transcripts)</sub> is the total expression in TPM  of transcripts of that gene in that sample.

Hopefully this will give us a fair estimation of the percent of a transcript occurrence in a given cancer group.

Thanks

**Comment by ewafula** [comment]
Thanks, @afarrel. I'll work to integrate the transcript expression representation in the cancer group as you described above.

**Comment by ewafula** [comment]
@afarrel,  I have completed the updates to include the percent transcript representation (implemented in the `04-tpm-transcript-representation.py` script). Results are in `methyl-tpm-transcript-representation.tsv.gz` and also integrated into the `isoform-methyl-beta-values-summary.tsv.gz` summary table. The [REDME](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/tree/update-methyl-summary/analyses/methylation-summary) is updated too.
Result tables are available on Isilon - `/mnt/isilon/opentargets/wafulae/OpenPedCan-analysis/analyses/methylation-summary/results/`

**Comment by afarrel** [comment]
Hi @ewafula I'm going through the code and checking the results files. It seems that 01-create-probe-annotations.R might not be capturing all of the genes located in the vicinity of the probes. These genes are not present in the resulting methyl-probe-annotations.tsv.gz and are subsequently excluded in the summary tables. The following relevant genes from the PMTL list should be present in methyl-probe-annotations.tsv.gz as there are probes in the gene regions: (H3F3A, MYCN, TMEM173, ZNRD1 TWISTNB, TUBB8, CSNK2A3, PSMB3, HDAC5 H3F3B CD3EAP BIRC8 SSTR3 FIGF SEPT6).

**Comment by ewafula** [comment]
Thanks, @afarrel. I'll check the the Illumina probe manifest and the code tomorrow to figure out why those gene are not included in the probe annotation table.

**Comment by ewafula** [comment]
@afarrel,  some the missing genes were excluded in the resulting `methyl-probe-annotations.tsv.gz` because the Ensembl ids Gencode v39 gtf have changed  (deprecated) when compared to Ensembl ids in the Illumina array probe manifest.  

These 8 gene symbols are not in Gencode v39 - see code below:
```
[1] "H3F3A"   "TMEM173" "ZNRD1"   "TWISTNB" "H3F3B"   "CD3EAP"  "FIGF"    "SEPT6"
```
Gene symbol `CSNK2A3` is not in the Illumina array probe manifest.

I'll need to create a mapping file of `deprecated-ensembl_ids_in_arrays` -> `gene_symbol` -> `gencode_v39_ensembl_ids`  in order to bring back some of the missing genes (those present gencode v39) into module `methyl-probe-annotations.tsv.gz` file. 

### load PMTL file
```
> pmtl <- readr::read_tsv("../../data/ensg-hugo-pmtl-mapping.tsv") %>% dplyr::filter(pmtl == "Relevant Molecular Target") %>% dplyr::select(ensg_id, gene_symbol) %>% dplyr::rename("targetFromSourceId" = "ensg_id", "pmtl_gene_symbol" = "gene_symbol")
```

 ### load Gencode v39 and select relevant columns
```
> gencode_v39_gtf <-  "../../data/gencode.v39.primary_assembly.annotation.gtf.gz" 
> gencode_v39 <- rtracklayer::import(con = gencode_v39_gtf) %>% 
+   tibble::as_tibble() %>%
+   dplyr::select(gene_id, transcript_id, gene_name) %>%
+   dplyr::rename(targetFromSourceId = gene_id, 
+                 Gene_symbol = gene_name) %>% 
+   dplyr::mutate(transcript_id = stringr::str_extract(transcript_id, "ENST\\d+"), 
+                 targetFromSourceId = stringr::str_extract(targetFromSourceId, "ENSG\\d+")) %>% 
+   dplyr::distinct()
> gencode_v39
# A tibble: 306,366 × 3
   targetFromSourceId transcript_id   Gene_symbol
   <chr>              <chr>           <chr>      
 1 ENSG00000223972    NA              DDX11L1    
 2 ENSG00000223972    ENST00000456328 DDX11L1    
 3 ENSG00000223972    ENST00000450305 DDX11L1    
 4 ENSG00000227232    NA              WASH7P     
 5 ENSG00000227232    ENST00000488147 WASH7P     
 6 ENSG00000278267    NA              MIR6859-1  
 7 ENSG00000278267    ENST00000619216 MIR6859-1  
 8 ENSG00000243485    NA              MIR1302-2HG
 9 ENSG00000243485    ENST00000473358 MIR1302-2HG
10 ENSG00000243485    ENST00000469289 MIR1302-2HG
# … with 306,356 more rows
# ℹ Use `print(n = ...)` to see more rows
```
### This is the `list of missing PMTL gene symbols` that are `IN` the `array probe manifest` but are `NOT` in `Gencode v39.`
```
> setdiff(c("H3F3A", "MYCN", "TMEM173", "ZNRD1", "TWISTNB", "TUBB8", "CSNK2A3", "PSMB3", "HDAC5", "H3F3B", "CD3EAP", "BIRC8", "SSTR3", "FIGF", "SEPT6"),
 unique(gencode_v39$Gene_symbol))  
[1] "H3F3A"   "TMEM173" "ZNRD1"   "TWISTNB" "H3F3B"   "CD3EAP"  "FIGF"    "SEPT6"
>
```
### These are `Ensembl ids` in the `array probe manifest` corresponding to the `list of missing PMTL gene symbols` that are `NOT` in `Gencode v39.`
```
> setdiff(c("ENST00000366816", "ENST00000426211", "ENST00000509573", "ENST00000425604", "ENST00000222567", "ENST00000482075", "ENST00000225426", "ENST00000393622",  "ENST00000254810", "ENST00000309424", "ENST00000426466", "ENST00000328544",  "ENST00000297904", "ENST00000394616"),
unique(gencode_v39$transcript_id))  
[1] "ENST00000426211" "ENST00000482075" "ENST00000225426" "ENST00000393622" "ENST00000426466"
[6] "ENST00000328544" "ENST00000394616"
>
```
### These are `Ensembl ids` that are in the `array probe manifest` corresponding to the `list of missing PMTL gene symbols` and are in `Gencode v39.` The `OpenPedCan PMTL` list has alternative gene symbols, of which only one is present in the  `Gencode v39`.  Therefore, these genes should not be considered as missing in `methyl-probe-annotations.tsv.gz`. Maybe the PMTL list should be updated with the current Hugo gene symbols in Gencode v39
```
> intersect(c("ENST00000366816", "ENST00000426211", "ENST00000509573", "ENST00000425604", "ENST00000222567", "ENST00000482075", "ENST00000225426", "ENST00000393622", "ENST00000254810", "ENST00000309424", "ENST00000426466", "ENST00000328544", "ENST00000297904", "ENST00000394616"), unique(gencode_v39$transcript_id))  
[1] "ENST00000366816" "ENST00000509573" "ENST00000425604" "ENST00000222567" "ENST00000254810"
[6] "ENST00000309424" "ENST00000297904"
>
> gencode_v39 %>% dplyr::filter(transcript_id %in% c("ENST00000366816", "ENST00000509573", "ENST00000425604", "ENST00000222567", "ENST00000254810", "ENST00000309424", "ENST00000297904")) %>% dplyr::rename("gencode_gene_symbol" = "Gene_symbol") %>% dplyr::left_join(pmtl, by = "targetFromSourceId")
# A tibble: 13 × 4
   targetFromSourceId transcript_id   gencode_gene_symbol pmtl_gene_symbol
   <chr>              <chr>           <chr>               <chr>           
 1 ENSG00000163041    ENST00000366816 H3-3A               H3F3A           
 2 ENSG00000163041    ENST00000366816 H3-3A               H3-3A           
 3 ENSG00000184584    ENST00000509573 STING1              TMEM173         
 4 ENSG00000184584    ENST00000509573 STING1              STING1          
 5 ENSG00000204623    ENST00000425604 ZNRD1ASP            NA              
 6 ENSG00000105849    ENST00000222567 POLR1F              TWISTNB         
 7 ENSG00000105849    ENST00000222567 POLR1F              POLR1F          
 8 ENSG00000132475    ENST00000254810 H3-3B               H3F3B           
 9 ENSG00000132475    ENST00000254810 H3-3B               H3-3B           
10 ENSG00000117877    ENST00000309424 POLR1G              CD3EAP          
11 ENSG00000117877    ENST00000309424 POLR1G              POLR1G          
12 ENSG00000165197    ENST00000297904 VEGFD               FIGF            
13 ENSG00000165197    ENST00000297904 VEGFD               VEGFD           
>
```

@afarrel , any feedback will be helpful

**Comment by afarrel** [comment]
sorry - I forgot to mention, CSNK2A3 is not in EPIC manifest but I saw it in the Illumina 450k manifest from bioconductor.

**Comment by afarrel** [comment]
@ewafula Thanks for looking into this. If the alternate/new gene symbols are present then those genes are fine and there are no issue with those genes. Both old and new symbols are in the PMTL file. Maybe we can include a column in the PMTL file indicating which gencode version/s the gene symbol is associated with. We can discuss this at our next MTP meeting as this decision may impact others. Any luck on figuring out the issue with the other genes? Thanks for working on this.

**Comment by ewafula** [comment]
@afarrel, there are 4 cases that may or may not need to be addressed: 

1. We don't have to do anything about the alternative gene symbols utilized in Gencode v39, as you suggested in your previous comment
2. There are gene symbols in both PMTL and array probe manifest that seem to be deprecated in the recent versions of Gencode. For example, PMTL gene symbol `SEPT6`  is now `SEPTIN6`  in Gencode v39. I think this is ok too, and  methyl-probe-annotations.tsv.gz does not need to be updated.  
3. Probes for PMTL genes like `CSNK2A3` from 450k  arrays were dropped in the EPIC arrays. Illumina is continually updating the probe manifest, including dropping probes that are problematic.  We are currently using the latest array probe manifest, which includes both 450K and EPIC probe sets. I need to figure out how to bring in annotations for a few 450K probes sets that are not in the EPIC arrays. 
4. The last and most challenging is resolving the Ensembl ids in the array probe manifest that are not in Gencode v39.  I plan to create a mapping file of `deprecated-ensembl_ids_in_arrays` -> `gene_symbol`-> `gencode_v39_ensembl_ids`. This might be perfect because a gene symbol can have a `1:many` relationship with Ensembl ids.

**Comment by afarrel** [comment]
Hi @ewafula. There is another issue we need to address. I think the underlying issue is the manifest (infinium-methylationepic-v-1-0-b5-manifest-file.csv) . Right now `01-create-probe-annotations.R` uses the manifest to generate
`methyl-probe-annotations.tsv.gz` . `methyl-probe-annotations.tsv.gz` is then used for downstream analysis to generate correlations, etc. However, in the manifest, all probes that are assigned to a gene are not necessarily assigned to all the transcripts. This creates a `methyl-probe-annotations.tsv.gz` file that does not capture all the transcripts that a probe is close to. 

For example: BPTF

There are 74 unique probes associated with the gene:
```
> Methyl_Annotations = read.delim("/mnt/isilon/opentargets/wafulae/OpenPedCan-analysis/analyses/methylation-summary/results/methyl-probe-annotations.tsv.gz")
> length(unique(Methyl_Annotations$Probe_ID[which(Methyl_Annotations$Gene_symbol=="BPTF")]))
[1] 74
```
But the transcripts present aren't recorded to be associated with each probe. There is only a subset of probes associated with the transcripts.:

```
> BPTF_Probes = unique(Methyl_Annotations$Probe_ID[which(Methyl_Annotations$Gene_symbol == "BPTF")])
> BPTF_transcripts = unique(Methyl_Annotations$transcript_id[which(Methyl_Annotations$Gene_symbol == "BPTF")])
> sapply(BPTF_transcripts, function(X) length(which(Methyl_Annotations$transcript_id[which(Methyl_Annotations$Gene_symbol == "BPTF")] == X)))
ENST00000467104 ENST00000424123 ENST00000306378 ENST00000321892 ENST00000544778 ENST00000342579 
             54              27              11              10               8               6 
ENST00000544491 
              5 
```

This seems to be an issue because the smallest transcript seems to have the most probes associated with it. The larger transcripts only have a small fraction of the probes associated with them in the manifest and the `methyl-probe-annotations.tsv.gz` file:
image

There are so overlaps but we want to have all the probes for the gene associated with all the transcripts. Right now the overlaps/intersections that at least two isoforms are associated with most of the probes `(ENST00000467104 and ) ENST00000424123)` but the others aren't:

image

To correlate the expression of each transcript with methylation at each probe site, and populate that in the summary tables, your code requires it to be in the `methyl-probe-annotations.tsv.gz` file. It seems this occurs because all transcripts aren't present each room representing a probe even though the gene is in the record. One possible solution is extracting all the transcripts for a gene, and create the table associating each gene and transcript with the probe ID instead of only including specific transcripts that are in probe rows in the manifest.

Please let me know if you have any questions or concerns .

**Comment by ewafula** [comment]
@afarrel, I have completed rerunning the module with updated gencode v39 probe annotation mappings and also updated the module code for this PR. Now includes all genes in the latest Illumina Infinium probe manifest  (EPIC + 450K arrays) except for 1) some multi-locus gene symbols (present in v39) with legacy Ensembl IDs that are no longer Gencode v39 and 2) legacy gene symbols + Ensembl IDs that are not Gencode v39. 
```
Updated results: /mnt/isilon/opentargets/wafulae/methylation-summary/results/*
Updated annotation mappings: /mnt/isilon/opentargets/wafulae/methylation-summary/input/infinium-annotation-mapping.tsv
```

**Comment by sickler-alex** [comment]
If this is still being worked on and reviewed, now would be a good time to go through and format the code to make it more readable. I use `black` for python and `Prettier` for R. I also saw when reading through this that there's some modules and variables that aren't being used and can probably be safely deleted. Nothing major so I'm not going to require changes.

**Comment by ewafula** [comment]
No. Has already been reviewed and awaiting the required one approval and then merging.

**Comment by jharenza** [comment]
@afarrel is this ready for final approval?

**Review by afarrel — APPROVED** [review]
Thanks @ewafula for working on this. It looks good. I also uploaded the data on isaac (dbhi machine) and took a closer look at the results and it looks good. Thanks for fixing the previous issues.

**Comment by ewafula** [comment]
> Thanks @ewafula for working on this. It looks good. I also uploaded the data on isaac (dbhi machine) and took a closer look at the results and it looks good. Thanks for fixing the previous issues.

Thank you @afarrel for reviewing!

@sickler-alex,  merging this PR into dev.

**Pull request merged**
