### PR TITLE
Fusion filtering staggered PR5 part2: adding breakpoint location and annots column

### PR DESCRIPTION
**Pull request by kgaonkar6**
🚨 merge after #40 

#### What scientific question is your analysis addressing?
We need to add BreakpointLocation as a column to the output as it is needed in OT portal files.

#### What was your approach?
For BreakpointLocation:
```
mutate(
        BreakpointLocation = case_when(
       # gene1A and gene1B are the same so these are breakpoints within the gene
        Gene1A == Gene1B & !grepl("/", FusionName) ~ "Intragenic",
       # the "/" is an annotation for intergenic fusions called by arriba 
        grepl("/", FusionName) ~ "Intergenic",
        TRUE ~ "Genic"
      )
  ) 
```
For annots
https://github.com/PediatricOpenTargets/OpenPedCan-analysis/blob/37568684013015bbfb506f31ad8869a0cfde3749/analyses/fusion_filtering/05-QC_putative_onco_fusion_distribution.Rmd#L208-L234

#### What GitHub issue does your pull request address?
PediatricOpenTargets/ticket-tracker#70
PediatricOpenTargets/ticket-tracker#72

#### Which areas should receive a particularly close look?
Does the condition for `BreakpointsLocation` look right?

#### Is there anything that you want to discuss further?
NA

#### Is the analysis in a mature enough form that the resulting figure(s) and/or table(s) are ready for review?
Yes

#### What types of results are included (e.g., table, figure)?
table

#### What is your summary of the results?
`BreakpointLocation` with "Genic" and "Intergenic" values added and `annots` column is now aggregated by all columns removing the caller specific cols below since we want to aggregate the caller specific annotation in `annots`
```
c("JunctionReadCount",
                        "SpanningFragCount",
                        "Confidence",
                        "caller","annots")
```

#### Reproducibility Checklist

- [x] The dependencies required to run the code in this pull request have been added to the project Dockerfile.
- [x] This analysis has been added to continuous integration.

#### Documentation Checklist

- [x] This analysis module has a `README` and it is up to date.
- [x] This analysis is recorded in the table in `analyses/README.md` and the entry is up to date.
- [x] The analytical code is documented and contains comments.

### CODE REVIEW

**Comment by kgaonkar6** [comment]
closing for now, will reopen with annots column updated.

**Comment by runjin326** [comment]
@kgaonkar6, the code ran smoothly for me and the annots make sense. Just to clarify, for us, "Intergenic" includes both "genic-intergenic" and "Intergenic-intergenic", right? And "intragenic" is actually a subtype of "genic" (only when the two genes are the same), right?

**Comment by kgaonkar6** [comment]
Thanks for the review, @runjin326 !

> @kgaonkar6, the code ran smoothly for me and the annots make sense. Just to clarify, for us, "Intergenic" includes both "genic-intergenic" and "Intergenic-intergenic", right? And "intragenic" is actually a subtype of "genic" (only when the two genes are the same), right?

That's right!

**Review by runjin326 — APPROVED** [review]
Looks good to me@

**Review by jharenza — APPROVED** [review]
this looks good, thanks @kgaonkar6 !

**Comment by kgaonkar6** [comment]
Sorry reviewers, I just noticed as part of @jharenza review of #49  that Gene2A_anno and Gene2B_anno were all NA so updating code to add `guess_max` for reading filtered fusion file here.

**Pull request merged**
