### PR TITLE
release v7

### PR DESCRIPTION
**Pull request by jharenza**
#### What scientific question is your analysis addressing?
v7 release

#### What was your approach?
# release notes
## current release
- release date: 2021-07-23
- status: available
- changes:
   - Updated EFO/MONDO mapping file per [ticket 88](https://github.com/PediatricOpenTargets/ticket-tracker/issues/88)
   - Added GTEX UBERON mapping files for subgroup and group per [ticket 85](https://github.com/PediatricOpenTargets/ticket-tracker/issues/85)
     - Collapsed `Cerebellum hemisphere` and `Cerebellum` to `Cerebellum` since GTEX has the same UBERON code listed for both per [ticket 106](https://github.com/PediatricOpenTargets/ticket-tracker/issues/106)
     - Renamed `Whole Blood` to `Blood` per John Maris's suggestion to alphabetize and [ticket 106](https://github.com/PediatricOpenTargets/ticket-tracker/issues/106).
       - Note: v8 gtex lists "whole blood" subgroup and "whole blood" group as UBERON_0013756, which is mapped to venous blood and "Whole blood" maps to UBERON_0000178.
       - After inquiry at GTEx, we were told they are equivalent terms as seen in [this link](https://www.ebi.ac.uk/ols/ontologies/uberon/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FUBERON_0013756)
    - Updated `ensg-hugo-rmtl-v1-mapping.tsv` with minor updates according to [ticket 125](https://github.com/PediatricOpenTargets/ticket-tracker/issues/125) and changed filename to `ensg-hugo-rmtl-mapping.tsv`
    - Histology file updates:
      - Collapsed `Cerebellum hemisphere` and `Cerebellum` to `Cerebellum` since GTEX has the same UBERON code listed for both per [ticket 106](https://github.com/PediatricOpenTargets/ticket-tracker/issues/106)
      - Renamed `Whole Blood` to `Blood` per John Maris's suggestion to alphabetize and [ticket 106](https://github.com/PediatricOpenTargets/ticket-tracker/issues/106).
      - Added inferred strandedness to RNA-Seq samples per [ticket 104](https://github.com/PediatricOpenTargets/ticket-tracker/issues/104)
      - Added `broad_tumor_descriptor` to designate grouped `Diagnosis` and `Relapse` samples used in SNV, CNV, Fusion tables as well as for grouping on pedcbio per [ticket 109](https://github.com/PediatricOpenTargets/ticket-tracker/issues/109)
      - Added ploidy information for TARGET AML and NBL WXS samples per [ticket 121](https://github.com/PediatricOpenTargets/ticket-tracker/issues/121)
      - Collapsed TARGET ids containing suffixes to match the BAM file sample IDs from GDC and match the RDS processed files per [comment here](https://github.com/d3b-center/D3b-codes/pull/41#issuecomment-885809293)
    - Added TARGET NBL and AML WXS, PBTA WXS CNV calls to `cnv-cnvkit.seg.gz` and `cnv-controlfreec.tsv.gz` per [ticket 80](https://github.com/PediatricOpenTargets/ticket-tracker/issues/80)
    - Added `consensus_wgs_plus_cnvkit_wxs_x_and_y.tsv.gz` (removed WGS only file `consensus_seg_annotated_cn_autosomes.tsv.gz`) and `consensus_wgs_plus_cnvkit_wxs_autosomes.tsv.gz` (removed WGS only file `consensus_seg_annotated_cn_x_and_y.tsv.gz`) containing consensus WGS and CNVkit WXS data per [ticket 102](https://github.com/PediatricOpenTargets/ticket-tracker/issues/102)
    - Updated RNA-Seq files to include TARGET RNA (N = 1329) samples:
      - fusion-arriba.tsv.gz
      - fusion-starfusion.tsv.gz
      - fusion-putative-oncogenic.tsv
      - gene-counts-rsem-expected_count-collapsed.rds
      - gene-expression-rsem-tpm-collapsed.rds

#### What GitHub issue does your pull request address?
https://github.com/PediatricOpenTargets/ticket-tracker/issues/92

#### Which areas should receive a particularly close look?
NA

#### Is there anything that you want to discuss further?
No

#### Is the analysis in a mature enough form that the resulting figure(s) and/or table(s) are ready for review?
no - awaiting putative oncogenic file

### Data Release Checklist
- [x] Is the table in doc/data-file-descriptions.md up to date?
- [ ] Is doc/data-format.md up to date?
- [x] Is doc/release-notes.md up to date?
- [x] Is download-data.sh up to date?
- [x] Was download-data.sh tested and did it complete without error?

### CODE REVIEW

**Comment by logstar** [comment]
Thank you for preparing the v7 release @jharenza !

I was able to download the v7 data, but I received a warning which might be caused by the following line of code due to the `-z` in the warning message.

<https://github.com/PediatricOpenTargets/OpenPedCan-analysis/blob/4211ce1d3467da3fc8c0eee2a8c33e9cdef1ff4d/download-data.sh#L14>

Following is the complete output when running the updated data downloading script.

```text
$ head download-data.sh 

set -e
set -o pipefail

# Use the OpenPBTA bucket as the default.
URL=${OPENPBTA_URL:-https://s3.amazonaws.com/kf-openaccess-us-east-1-prd-pbta/open-targets}
RELEASE=${OPENPBTA_RELEASE:-v7}
PREVIOUS=${OPENPBTA_RELEASE:-v6}

# Remove old symlinks in data


$ bash download-data.sh 
Warning: Illegal date format for -z, --time-cond (and not a file name). 
Warning: Disabling time condition. See curl_getdate(3) for valid date syntax.
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1601  100  1601    0     0  16435      0 --:--:-- --:--:-- --:--:-- 16505
Checking for unchanged files...
intersect_cds_lancet_strelka_mutect_WGS.bed
Hard linking intersect_cds_lancet_strelka_mutect_WGS.bed
Hard linking intersect_strelka_mutect_WGS.bed
Hard linking sv-manta.tsv.gz
Hard linking WGS.hg38.lancet.300bp_padded.bed
Hard linking WGS.hg38.lancet.unpadded.bed
Hard linking WGS.hg38.mutect2.vardict.unpadded.bed
Hard linking WGS.hg38.strelka2.unpadded.bed
Hard linking WGS.hg38.vardict.100bp_padded.bed
Downloading cnv-cnvkit.seg.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 31.0M  100 31.0M    0     0  33.9M      0 --:--:-- --:--:-- --:--:-- 33.9M
Downloading cnv-controlfreec.tsv.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 38.7M  100 38.7M    0     0  29.5M      0  0:00:01  0:00:01 --:--:-- 29.5M
Downloading consensus_wgs_plus_cnvkit_wxs_autosomes.tsv.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 73.2M  100 73.2M    0     0  41.6M      0  0:00:01  0:00:01 --:--:-- 41.6M
Downloading consensus_wgs_plus_cnvkit_wxs_x_and_y.tsv.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 3665k  100 3665k    0     0  21.5M      0 --:--:-- --:--:-- --:--:-- 21.5M
Downloading data-files-description.md
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 18517  100 18517    0     0   262k      0 --:--:-- --:--:-- --:--:--  265k
Downloading efo-mondo-map.tsv
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  2719  100  2719    0     0  49191      0 --:--:-- --:--:-- --:--:-- 49436
Downloading ensg-hugo-rmtl-mapping.tsv
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 1769k  100 1769k    0     0  14.6M      0 --:--:-- --:--:-- --:--:-- 14.7M
Downloading fusion-arriba.tsv.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 22.1M  100 22.1M    0     0  36.5M      0 --:--:-- --:--:-- --:--:-- 36.5M
Downloading fusion-putative-oncogenic.tsv
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 7096k  100 7096k    0     0  57.7M      0 --:--:-- --:--:-- --:--:-- 58.2M
Downloading fusion-starfusion.tsv.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 4122k  100 4122k    0     0  26.1M      0 --:--:-- --:--:-- --:--:-- 26.3M
Downloading gene-counts-rsem-expected_count-collapsed.rds
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 1023M  100 1023M    0     0  38.3M      0  0:00:26  0:00:26 --:--:-- 43.1M
Downloading gene-expression-rsem-tpm-collapsed.rds
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 1536M  100 1536M    0     0  34.2M      0  0:00:44  0:00:44 --:--:-- 33.1M
Downloading histologies.tsv
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 12.1M  100 12.1M    0     0  28.1M      0 --:--:-- --:--:-- --:--:-- 28.1M
Downloading release-notes.md
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 12509  100 12509    0     0   132k      0 --:--:-- --:--:-- --:--:--  132k
Downloading snv-consensus-plus-hotspots.maf.tsv.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  562M  100  562M    0     0  39.5M      0  0:00:14  0:00:14 --:--:-- 35.5M
Downloading uberon-map-gtex-group.tsv
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   731  100   731    0     0   9269      0 --:--:-- --:--:-- --:--:--  9371
Downloading uberon-map-gtex-subgroup.tsv
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  2855  100  2855    0     0  22634      0 --:--:-- --:--:-- --:--:-- 22658
/home/ubuntu/volume/OpenPedCan-analysis
Checking MD5 hashes...
cnv-cnvkit.seg.gz: OK
cnv-controlfreec.tsv.gz: OK
consensus_wgs_plus_cnvkit_wxs_autosomes.tsv.gz: OK
consensus_wgs_plus_cnvkit_wxs_x_and_y.tsv.gz: OK
data-files-description.md: OK
efo-mondo-map.tsv: OK
ensg-hugo-rmtl-mapping.tsv: OK
fusion-arriba.tsv.gz: OK
fusion-putative-oncogenic.tsv: OK
fusion-starfusion.tsv.gz: OK
gene-counts-rsem-expected_count-collapsed.rds: OK
gene-expression-rsem-tpm-collapsed.rds: OK
histologies.tsv: OK
intersect_cds_lancet_strelka_mutect_WGS.bed: OK
intersect_strelka_mutect_WGS.bed: OK
release-notes.md: OK
snv-consensus-plus-hotspots.maf.tsv.gz: OK
sv-manta.tsv.gz: OK
uberon-map-gtex-group.tsv: OK
uberon-map-gtex-subgroup.tsv: OK
WGS.hg38.lancet.300bp_padded.bed: OK
WGS.hg38.lancet.unpadded.bed: OK
WGS.hg38.mutect2.vardict.unpadded.bed: OK
WGS.hg38.strelka2.unpadded.bed: OK
WGS.hg38.vardict.100bp_padded.bed: OK
```

**Comment by jharenza** [comment]
hmm interesting, when I remove the `-z` and try again, I get:
```
harenzaj@0068ebe4364c OpenPedCan-analysis % bash download-data.sh 
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1601  100  1601    0     0   6205      0 --:--:-- --:--:-- --:--:--  6205
curl: (6) Could not resolve host: data
```

but then get no other errors with it present:
```
harenzaj@0068ebe4364c OpenPedCan-analysis % bash download-data.sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
Checking for unchanged files...
intersect_cds_lancet_strelka_mutect_WGS.bed
Downloading histologies.tsv
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 12.1M  100 12.1M    0     0  10.4M      0  0:00:01  0:00:01 --:--:-- 10.4M
/Users/harenzaj/Documents/GitHub/ped-ot/OpenPedCan-analysis
Checking MD5 hashes...
cnv-cnvkit.seg.gz: OK
cnv-controlfreec.tsv.gz: OK
consensus_wgs_plus_cnvkit_wxs_autosomes.tsv.gz: OK
consensus_wgs_plus_cnvkit_wxs_x_and_y.tsv.gz: OK
data-files-description.md: OK
efo-mondo-map.tsv: OK
ensg-hugo-rmtl-mapping.tsv: OK
fusion-arriba.tsv.gz: OK
fusion-putative-oncogenic.tsv: OK
fusion-starfusion.tsv.gz: OK
gene-counts-rsem-expected_count-collapsed.rds: OK
gene-expression-rsem-tpm-collapsed.rds: OK
histologies.tsv: OK
intersect_cds_lancet_strelka_mutect_WGS.bed: OK
intersect_strelka_mutect_WGS.bed: OK
release-notes.md: OK
snv-consensus-plus-hotspots.maf.tsv.gz: OK
sv-manta.tsv.gz: OK
uberon-map-gtex-group.tsv: OK
uberon-map-gtex-subgroup.tsv: OK
WGS.hg38.lancet.300bp_padded.bed: OK
WGS.hg38.lancet.unpadded.bed: OK
WGS.hg38.mutect2.vardict.unpadded.bed: OK
WGS.hg38.strelka2.unpadded.bed: OK
WGS.hg38.vardict.100bp_padded.bed: OK
```

I wonder if it is a version or OS issue. We can submit a ticket for optimization, but since it works, I won't worry about it for this PR.

**Review by logstar — APPROVED** [review]
I think the warning can be ignored. The warning also exists for v6 data download, which is probably caused be specifying `-z data/$RELEASE/md5sum.txt`, but `data/$RELEASE/md5sum.txt` is not available when the release is downloaded for the first time.

**Comment by logstar** [comment]
> hmm interesting, when I remove the `-z` and try again, I get:
> 
> ```
> harenzaj@0068ebe4364c OpenPedCan-analysis % bash download-data.sh 
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
> 100  1601  100  1601    0     0   6205      0 --:--:-- --:--:-- --:--:--  6205
> curl: (6) Could not resolve host: data
> ```
> 
> but then get no other errors with it present:
> 
> ```
> harenzaj@0068ebe4364c OpenPedCan-analysis % bash download-data.sh
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
>   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
> Checking for unchanged files...
> intersect_cds_lancet_strelka_mutect_WGS.bed
> Downloading histologies.tsv
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
> 100 12.1M  100 12.1M    0     0  10.4M      0  0:00:01  0:00:01 --:--:-- 10.4M
> /Users/harenzaj/Documents/GitHub/ped-ot/OpenPedCan-analysis
> Checking MD5 hashes...
> cnv-cnvkit.seg.gz: OK
> cnv-controlfreec.tsv.gz: OK
> consensus_wgs_plus_cnvkit_wxs_autosomes.tsv.gz: OK
> consensus_wgs_plus_cnvkit_wxs_x_and_y.tsv.gz: OK
> data-files-description.md: OK
> efo-mondo-map.tsv: OK
> ensg-hugo-rmtl-mapping.tsv: OK
> fusion-arriba.tsv.gz: OK
> fusion-putative-oncogenic.tsv: OK
> fusion-starfusion.tsv.gz: OK
> gene-counts-rsem-expected_count-collapsed.rds: OK
> gene-expression-rsem-tpm-collapsed.rds: OK
> histologies.tsv: OK
> intersect_cds_lancet_strelka_mutect_WGS.bed: OK
> intersect_strelka_mutect_WGS.bed: OK
> release-notes.md: OK
> snv-consensus-plus-hotspots.maf.tsv.gz: OK
> sv-manta.tsv.gz: OK
> uberon-map-gtex-group.tsv: OK
> uberon-map-gtex-subgroup.tsv: OK
> WGS.hg38.lancet.300bp_padded.bed: OK
> WGS.hg38.lancet.unpadded.bed: OK
> WGS.hg38.mutect2.vardict.unpadded.bed: OK
> WGS.hg38.strelka2.unpadded.bed: OK
> WGS.hg38.vardict.100bp_padded.bed: OK
> ```
> 
> I wonder if it is a version or OS issue. We can submit a ticket for optimization, but since it works, I won't worry about it for this PR.

Thank you for looking into the warning. I agree that we should deal with the warning outside of this PR if necessary.

**Pull request merged**
