### PR TITLE
update ubuntu version

### PR DESCRIPTION
**Pull request by jharenza**
### Purpose/implementation Section

Update deprecated ubuntu version for running github actions

#### What GitHub issue does your pull request address?
Fixes https://github.com/PediatricOpenTargets/ticket-tracker/issues/394

#### Reproducibility Checklist

- [ ] The dependencies required to run the code in this pull request have been added to the project Dockerfile.
- [ ] This analysis has been added to continuous integration.

#### Documentation Checklist

- [ ] This analysis module has a `README` and it is up to date.
- [ ] This analysis is recorded in the table in `analyses/README.md` and the entry is up to date.
- [ ] The analytical code is documented and contains comments.

### CODE REVIEW

**Comment by jharenza** [comment]
Using [RStudio Package manager](https://packagemanager.rstudio.com/client/#/) worked, but the build and push docker github action failed.

**Review by devbyaccident — APPROVED** [review]
👍 Lgtm

**Comment by jharenza** [comment]
I am going to merge since `build_and_run` https://github.com/PediatricOpenTargets/OpenPedCan-analysis/actions/runs/2841998308/attempts/1 with the first attempt in the latest commit and `build_docker` https://github.com/PediatricOpenTargets/OpenPedCan-analysis/runs/7793460891?check_suite_focus=true here. It looks like a rerun was triggered here, but not needed.

**Comment by ewafula** [comment]
Sure. The build_and_run seems to have succeed in your previous run with the
update Ubuntu version.

**Pull request merged**
