### PR TITLE
Update gencode gene match

### PR DESCRIPTION
**Pull request by sangeetashukla**
### Purpose/implementation Section
Update module to include all GENCODE versions being used as of v12 release forward.

#### What scientific question is your analysis addressing?
Add GTF and matching for GENCODE versions:

v27
v28
v36
v38
v39

Note: previously the module used v28 and v38, and v27, v36, v39 are added with this PR

#### What was your approach?
- Download the new gencode files manually (source provided in the README)
- Update the `merge_gencode_v28_v38_open_ped_can_v7_gene_ensg_symbol_mapping_files.R` script to merge data from all gencode files
- The new result file with merged data is now called `results/ensembl_gene_symbol_gtf_genode_all_open_ped_can_v7_merged.tsv` instead of `results/ensembl_gene_symbol_gtf_genode_v28_v38_open_ped_can_v7_merged.tsv`

#### What GitHub issue does your pull request address?
[Issue 400](https://github.com/PediatricOpenTargets/ticket-tracker/issues/400)

### Directions for reviewers. Tell potential reviewers what kind of feedback you are soliciting.
- Please note the new file name for merged mapping files
- Once the PR is reviewed, I will remove the old merged mapping file `ensembl_gene_symbol_gtf_genode_v28_v38_open_ped_can_v7_merged.tsv` from the branch before PR is merged

#### Which areas should receive a particularly close look?
- Do we want to rename the `merge_gencode_v28_v38_open_ped_can_v7_gene_ensg_symbol_mapping_files.R` script to better reflect that all relevant gencode files are used for mapping, and not just v28 and v38?

#### Is there anything that you want to discuss further?
No

#### Is the analysis in a mature enough form that the resulting figure(s) and/or table(s) are ready for review?
Yes

### Results
```
input/gencode.v27.annotation.gtf.gz
input/gencode.v28.annotation.gtf.gz
input/gencode.v36.annotation.gtf.gz
input/gencode.v38.annotation.gtf.gz
input/gencode.v39.annotation.gtf.gz
results/ensembl_gene_symbol_gtf_genode_v27.tsv
results/ensembl_gene_symbol_gtf_genode_v28.tsv
results/ensembl_gene_symbol_gtf_genode_v36.tsv
results/ensembl_gene_symbol_gtf_genode_v38.tsv
results/ensembl_gene_symbol_gtf_genode_v39.tsv
results/ensembl_gene_symbol_gtf_genode_all_open_ped_can_v7_merged.tsv

```

#### Reproducibility Checklist

- [ ] The dependencies required to run the code in this pull request have been added to the project Dockerfile.
- [ ] This analysis has been added to continuous integration.

#### Documentation Checklist

- [x] This analysis module has a `README` and it is up to date.
- [x] This analysis is recorded in the table in `analyses/README.md` and the entry is up to date.
- [x] The analytical code is documented and contains comments.

### CODE REVIEW

**Comment by jharenza** [comment]
For discussion next week - I think this should be 27, 28, 36, and 39.

**Comment by jharenza** [comment]
MTP is on gencode 39, so we need to remove 38

**Comment by sangeetashukla** [comment]
> MTP is on gencode 39, so we need to remove 38

@jharenza I have removed gencode v38 from the module, and re-run. The module is ready for review.

**Review by ewafula — APPROVED** [review]
Thank you @sangeetashukla  for updating this module. Code updates look ok to address what was required in the ticket.

**Comment by ewafula** [comment]
@sangeetashukla can you fix the following error? GA is failing.
```
Error: 'results/ensembl_gene_symbol_gtf_genode_v38.tsv' does not exist in current working directory ('/github/workspace/analyses/gene_match').
```

**Comment by sangeetashukla** [comment]
@jharenza "All checks have passed". The only thing to consider now is to maybe rename the script `merge_gencode_v28_v38_open_ped_can_v7_gene_ensg_symbol_mapping_files.R` to something like `merge_gencode_open_ped_can_v7_gene_ensg_symbol_mapping_files.R`. Thoughts?

**Comment by jharenza** [comment]
> merge_gencode_open_ped_can_v7_gene_ensg_symbol_mapping_files.R

Thanks, probably something even more concise like `merge_gencode_ensg_symbol_map.R` would be better

**Comment by sangeetashukla** [comment]
> > merge_gencode_open_ped_can_v7_gene_ensg_symbol_mapping_files.R
> 
> Thanks, probably something even more concise like `merge_gencode_ensg_symbol_map.R` would be better

I have changed the R script name and also fixed a typo in a few result files, and re-run module successfully. The CI/Run Analysis is in progress, I expect it to complete smoothly.

**Comment by sangeetashukla** [comment]
@jharenza This one is all set now.

**Review by jharenza — COMMENTED** [review]
Thanks @sangeetashukla - one more quick request. Can you number your R scripts please and update the shell script to match? Then we will be set.

**Comment by sangeetashukla** [comment]
> Thanks @sangeetashukla - one more quick request. Can you number your R scripts please and update the shell script to match? Then we will be set.

@jharenza Re-ran module successfully after renaming files.

**Review by jharenza — APPROVED** [review]

**Pull request merged**
