### PR TITLE
[Update annotator for v7 Part 1] change `ensg-hugo-rmtl-v1-mapping.tsv` to `ensg-hugo-rmtl-mapping.tsv`

### PR DESCRIPTION
**Pull request by logstar**
### Purpose/implementation Section

Update `long-format-table-utils/annotator` submodule for [v7 data release](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/pull/61).

- Change `ensg-hugo-rmtl-v1-mapping.tsv` to `ensg-hugo-rmtl-mapping.tsv`.

#### What was your approach?

Changed `ensg-hugo-rmtl-v1-mapping.tsv` to `ensg-hugo-rmtl-mapping.tsv` in `long-format-table-utils/annotator/annotator-api.R`.

Updated test annotated table `long-format-table-utils/annotator/tests/test_data/inspected_annotated_test_long_format_table.tsv`:

- Changed RMTL `version 1` to `version 1.0`.
- Added EFO code `EFO_0003851` for Meningioma.

#### What GitHub issue does your pull request address?

<https://github.com/PediatricOpenTargets/ticket-tracker/issues/132>

#### Which areas should receive a particularly close look?

Are the changes in `long-format-table-utils/annotator/annotator-api.R` and `long-format-table-utils/annotator/tests/test_data/inspected_annotated_test_long_format_table.tsv` expected?

#### Is there anything that you want to discuss further?

Is it possible to prioritize the review and merging of this PR? The annotator is currently broken, because it still tries to read `ensg-hugo-rmtl-v1-mapping.tsv`. This PR could get the annotator running for other developers.

#### Is the analysis in a mature enough form that the resulting figure(s) and/or table(s) are ready for review?

Yes

#### What types of results are included (e.g., table, figure)?

NA

#### What is your summary of the results?

NA

#### Reproducibility Checklist

- [x] The dependencies required to run the code in this pull request have been added to the project Dockerfile.
- [NA. CI is not available.] This analysis has been added to continuous integration.

#### Documentation Checklist

- [x] This analysis module has a `README` and it is up to date.
- [x] This analysis is recorded in the table in `analyses/README.md` and the entry is up to date.
- [x] The analytical code is documented and contains comments.

### CODE REVIEW

**Comment by jharenza** [comment]
@ewafula do you want to give this PR a review?

**Comment by ewafula** [comment]
> @ewafula do you want to give this PR a review?

Sure, I will.

**Review by ewafula — APPROVED** [review]
Test run works with CNV frequencies module using OpenPedCan `v7` data release and the file chnage  `ensg-hugo-rmtl-v1-mapping.tsv `to `ensg-hugo-rmtl-mapping.tsv`.

**Review by jharenza — APPROVED** [review]

**Comment by jharenza** [comment]
@logstar - you can merge this one after a dev merge into this branch, thanks!

**Comment by logstar** [comment]
@jharenza @ewafula Thank you for reviewing this PR. I have merged with the latest dev branch, and I will merge this PR shortly.

**Pull request merged**
