### PR TITLE
Update module to use appropriate ensg-hugo-mapping.tsv file

### PR DESCRIPTION
**Pull request by sangeetashukla**
### Purpose/implementation Section
- Edit `gene_match` module to remove any PMTL annotation references and change the input and result file names accordingly.
- Edit `create-subset-files` module appropriately to use correct input file as generated by the gene_match module, which eventually is added to the data release.

#### What scientific question is your analysis addressing?
Starting v12, the PMTL annotation references must be removed.
This is done in two PRs, one of which is this. The other is [PR#290](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/pull/290).

#### What was your approach?
1) Delete/rename files with pmtl or rmtl references in the gene_match module, and update the scripts to use the correct files for input and the results.
2) Scan all scripts in the create-subset-files module and update the file names.

#### What GitHub issue does your pull request address?
[Issue 447](https://github.com/PediatricOpenTargets/ticket-tracker/issues/447)

#### Which areas should receive a particularly close look?
Review the renamed files and script file names.

#### Is there anything that you want to discuss further?
No

#### Is the analysis in a mature enough form that the resulting figure(s) and/or table(s) are ready for review?
Yes

#### Reproducibility Checklist

- [x] The dependencies required to run the code in this pull request have been added to the project Dockerfile.
- [ ] This analysis has been added to continuous integration.

#### Documentation Checklist

- [ ] This analysis module has a `README` and it is up to date.
- [ ] This analysis is recorded in the table in `analyses/README.md` and the entry is up to date.
- [x] The analytical code is documented and contains comments.

### CODE REVIEW

**Review by ewafula — APPROVED** [review]
@sangeetashukla, thank you for updating. 

This PR should not be merged until after the v12 data release, inlcuding updated and renamed `ensg-hugo-pmtl-mapping.tsv` to `ensg-hugo-mapping.tsv`

GA checks are failing because of missing CI testing data missing `ensg-hugo-mapping.tsv` file.

**Comment by jharenza** [comment]
> This PR should not be merged until after the v12 data release, inlcuding updated and renamed ensg-hugo-pmtl-mapping.tsv to ensg-hugo-mapping.tsv

Do we need to remove this from the mapping file? I think aditya will need PMTL for the paper so we ought to keep- as long as it's not in the MTP tables (can be dropped from this file in those modules), better to keep?

**Comment by ewafula** [comment]
> > This PR should not be merged until after the v12 data release, inlcuding updated and renamed ensg-hugo-pmtl-mapping.tsv to ensg-hugo-mapping.tsv
> 
> Do we need to remove this from the mapping file? I think aditya will need PMTL for the paper so we ought to keep- as long as it's not in the MTP tables (can be dropped from this file in those modules), better to keep?

Ok, @jharenza. We will reverse the course and only remove PMTL annotations from the MTP tables. This PR is not going to be necessary.

**Comment by sangeetashukla** [comment]
@jharenza @ewafula Closing this PR since we do not want to rename mapping file at this time.

**Pull request closed without merging**
