### PR TITLE
Molecular subtype integrate module update

### PR DESCRIPTION
**Pull request by runjin326**
#### What scientific question is your analysis addressing?
We want to pull OpenPBTA `molecular-subtyping-integrate` module.

#### What was your approach?
Copy and Paste the `molecular-subtyping-integrate` module to OpenPedCan Repo.

#### What GitHub issue does your pull request address?
https://github.com/PediatricOpenTargets/ticket-tracker/issues/98

#### Which areas should receive a particularly close look?
Please cross check with OpenPBTA repo and make sure all the changes are as expected.

#### Is there anything that you want to discuss further?
No.

#### Is the analysis in a mature enough form that the resulting figure(s) and/or table(s) are ready for review?

Yes.

#### Reproducibility Checklist

- [x] The dependencies required to run the code in this pull request have been added to the project Dockerfile.
- [ ] This analysis has been added to continuous integration.

#### Documentation Checklist

- [x] This analysis module has a `README` and it is up to date.
- [ ] This analysis is recorded in the table in `analyses/README.md` and the entry is up to date.
- [x] The analytical code is documented and contains comments.

### CODE REVIEW

**Comment by runjin326** [comment]
@chinwallaa, this PR is only pulling the changes from OpenPBTA now - I did not do any re-run. All the changes that you see should be able to get checked out by checking the [OpenPBTA module](https://github.com/AlexsLemonade/OpenPBTA-analysis/tree/master/analyses/molecular-subtyping-integrate). Do you think you can give this a try?

**Comment by chinwallaa** [comment]
Yes. Thanks for decoupling this PR.  To clarify is this PR for the pulling changes from OpenPBTA or for the file-name change PR  @runjin326

**Comment by runjin326** [comment]
No problem, @chinwallaa ! That was a good suggestion!

**Review by chinwallaa — APPROVED** [review]
Spot check  changes to OpenPBTA are expected. Dry Run not performed as filenames are based on OpenPBTA.

**Pull request merged**
