### PR TITLE
Assert compatibility for SNV frequency tables

### PR DESCRIPTION
**Pull request by kelseykeith**
#### What scientific question is your analysis addressing?

Wanted to update the `snv-frequencies` module needs to assert that histology file is compatible with independent sample lists in `01-snv-frequencies.R`.

#### What was your approach?

The update could not be accomplished as written in the ticket. The code given there checks that all patients present in both the histology and SNV MAF files are present in the independent-specimen lists. However, there are a few intended exceptions where that this is not true because those patients have diseases or missing information that excluded them from independent specimens. These patients are not included in the results and are filtered out because they are not in the independent specimens table.

Instead, I added a check to make sure that the histology and independent sample lists match after they are combined, similar to the existing check between the histology and the MAF files.

#### What GitHub issue does your pull request address?

Updated analysis: assert that histology file is compatible with independent sample lists in snv-frequencies module [Ticket #293](https://github.com/PediatricOpenTargets/ticket-tracker/issues/)

#### Which areas should receive a particularly close look?

The codes executes correctly without any stop exceptions.

#### Is there anything that you want to discuss further?

N/A

#### Is the analysis in a mature enough form that the resulting figure(s) and/or table(s) are ready for review?

Yes

#### What types of results are included (e.g., table, figure)?

TSV and JSON tables

#### What is your summary of the results?

- `gene-level-snv-consensus-annotated-mut-freq.jsonl.gz`
- `gene-level-snv-consensus-annotated-mut-freq.tsv.gz`
- `variant-level-snv-consensus-annotated-mut-freq.jsonl.gz`
- `variant-level-snv-consensus-annotated-mut-freq.tsv.gz`

#### Reproducibility Checklist

- [x] The dependencies required to run the code in this pull request have been added to the project Dockerfile.
- [x] This analysis has been added to continuous integration.

#### Documentation Checklist

- [x] This analysis module has a `README` and it is up to date.
- [x] This analysis is recorded in the table in `analyses/README.md` and the entry is up to date.
- [x] The analytical code is documented and contains comments.

### CODE REVIEW

**Review by adilahiri — COMMENTED** [review]
Ran the code on EC2, it runs without errors.

**Comment by kelseykeith** [comment]
Great! I pulled the PR out of draft form - can you approve please?

**Review by adilahiri — APPROVED** [review]
The script runs on EC2 within docker without errors.

**Comment by adilahiri** [comment]
@kelseykeith: I just did.

**Comment by kelseykeith** [comment]
Thanks!

**Comment by jharenza** [comment]
@kelseykeith can you un comment the SNV frequencies run in the run analysis yaml file and commit to both of your SNV table PRs?

**Comment by kelseykeith** [comment]
Done!

**Comment by jharenza** [comment]
For this one, the error:
```
gzip: results/variant-level-snv-consensus-annotated-mut-freq.jsonl.gz already exists;	not overwritten
```

is because we are asking whether or not to overwrite, but we should update this to force overwrite.

Can you update the shell `gzip` command to `gzip -f`? I think that should do it.

EDIT - this will gzip the gzipped files, so you need to add `rm results/*gz` before you do the gzipping.

**Comment by kelseykeith** [comment]
This PR was re-submitted as part of [PR #243](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/pull/243), which is a PR of a branch of the OpenPedCan-analysis repository instead of my fork to fix the login issues with GitHub Actions

**Comment by jharenza** [comment]
closing in favor of #243

**Pull request closed without merging**
