### PR TITLE
Updated input files for gene_match ran the module

### PR DESCRIPTION
**Pull request by sangeetashukla**
### Purpose/implementation Section
Update the input files for the module to the most recent version

#### What scientific question is your analysis addressing?
The `gene_match` module used two input files, list of genes that are included in the PMTL list, and ENSG ids mapped to the genes.
Recently, there have been updates to the gene symbols (as per GTF v39) and the corresponding ENSG IDs needed to be reviewed. Therefore, the module needed to be updated with the changes.

#### What was your approach?
Edit the relevant scripts to use the newer versions of input files.
Note: Previous versions of files are still in the `input` directory. Please let me know if we want to get rid of those.

#### What GitHub issue does your pull request address?
[Issue 525](https://github.com/PediatricOpenTargets/ticket-tracker/issues/525)

#### Which areas should receive a particularly close look?
The QC script from the module failed, with the error `../../data/snv-consensus-plus-hotspots.maf.tsv.gz` was not found.
It does not impact the results of this module, but this module may need to be re-run when the data files for v12 are ready and available.

#### Is there anything that you want to discuss further?
No.

#### Is the analysis in a mature enough form that the resulting figure(s) and/or table(s) are ready for review?
Yes.

#### What types of results are included (e.g., table, figure)?
`results/ensg-hugo-pmtl-mapping.tsv`
`results/gencode_ensg_symbol_map_merged.tsv`

#### Reproducibility Checklist

- [ ] The dependencies required to run the code in this pull request have been added to the project Dockerfile.
- [ ] This analysis has been added to continuous integration.

#### Documentation Checklist

- [x] This analysis module has a `README` and it is up to date.
- [x] This analysis is recorded in the table in `analyses/README.md` and the entry is up to date.
- [x] The analytical code is documented and contains comments.

### CODE REVIEW

**Comment by ewafula** [comment]
@sangeetashukla, please download the `snv-consensus-plus-hotspots.maf.tsv.gz` file from the s3 bucket and rerun the module to with for your QC script. The v12 datasets are available. Some are still being updated and QCed. But this one is good.  
```
curl -O https://s3.amazonaws.com/d3b-openaccess-us-east-1-prd-pbta/open-targets/v12/snv-consensus-plus-hotspots.maf.tsv.gz
```

**Comment by sangeetashukla** [comment]
> @sangeetashukla, please download the `snv-consensus-plus-hotspots.maf.tsv.gz` file from the s3 bucket and rerun the module to with for your QC script. The v12 datasets are available. Some are still being updated and QCed. But this one is good.
> 
> ```
> curl -O https://s3.amazonaws.com/d3b-openaccess-us-east-1-prd-pbta/open-targets/v12/snv-consensus-plus-hotspots.maf.tsv.gz
> ```

@ewafula Thanks for the file. I had some trouble earlier with memory on my EC2 instance causing delays in testing this module again. All good now. The module has been tested successfully and is ready for re-review.

**Comment by sangeetashukla** [comment]
@ewafula Just letting you know that all checks have passed for this one.

**Comment by ewafula** [comment]
@sangeetashukla, thank you for updating this module. A few comments:

1). Script  `02-merge-gencode-ensg-symbol-map.R`
- Please update the variable `open_ped_can_v7_eh_df` to a generic name (i.e.,  `open_ped_can_eh_df`) instead of having the `v7` substring. Will void changing with every release.  We are now on v12 and using the v12 input file based on `Gencode v39` and` PMTL v3.1`.
- In my opinion, we should only be using the current  Gencode v39 to create `gencode_ensg_symbol_map_merged.tsv` file. Reading in and concatenating all Gencode versions (all the way from v27 to v39)  is the reason for the QC check failures in script `04-qc-ensg-hugo-pmtl-mapping.Rmd` and `03-add-pmtl-ensg-hugo.Rmd` with the v12 data release files.  All the Ensembl IDs and gene symbols from the older Gencode versions are not in the data files.  This should serve as another line QC check, which unfortunately was not applied to all v12 data files except for the gene expression matrices to check if gene symbols/Ensembl IDs are concordant with the latest Gencode v39. We assumed that because reharmonization was performed with v39, therefore, the data files should have correct gene symbols.
https://github.com/PediatricOpenTargets/OpenPedCan-analysis/blob/d8934b1b764241174a04ebfff098a60d85526351/analyses/gene_match/02-merge-gencode-ensg-symbol-map.R#L4-L15

2). Script  `03-add-pmtl-ensg-hugo.Rmd`
- Please change ` PMTL version 1.1` to `PMTL version 3.1`
https://github.com/PediatricOpenTargets/OpenPedCan-analysis/blob/d8934b1b764241174a04ebfff098a60d85526351/analyses/gene_match/03-add-pmtl-ensg-hugo.Rmd#L15

3).  Script `run-gene-mapping.sh`
- same as in # 1 above.  Exclude older versions of Gencode
https://github.com/PediatricOpenTargets/OpenPedCan-analysis/blob/d8934b1b764241174a04ebfff098a60d85526351/analyses/gene_match/run-gene-mapping.sh#L18-L21

**Comment by ewafula** [comment]
@zhangb1,  @jharenza, and @chinwallaa, diffs in gene symbols between `snv consensus maf` and gene `ensg-hugo-pmtl-mapping.tsv` produced by this module (`gene_match`) are mostly regulatory elements. They are represented mostly by their ENSG IDs in Gencode. But in the `snv consensus maf`, these regulatory gene symbols (`Hugo_symbol` column ) are mostly represented by either `ESNT or  ESNR IDs`. For this reason, it seems they are ignored in the downstream modules that utilize the svn consensus maf file.  I wanted to make sure I bring this to your attention in case you want to change course in the future to recode the `Hugo_symbol` column in the `snv consensus maf` using the appropriate Gencode gene symbol representation. 

[04-qc-ensg-hugo-pmtl-mapping.nb.html.zip](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/files/11036564/04-qc-ensg-hugo-pmtl-mapping.nb.html.zip)

**Review by ewafula — APPROVED** [review]
@sangeetashukla, thanks for updating!

**Pull request merged**
