### PR TITLE
Test Docker build on PR

### PR DESCRIPTION
**Pull request by logstar**
### Purpose/implementation Section

Test docker build.

#### What was your approach?

Add a few newlines to Dockerfile.

#### Which areas should receive a particularly close look?

Whether the docker build process is expected?

### CODE REVIEW

**Comment by kgaonkar6** [comment]
Hi @logstar , do you have any questions related to this or else we can close this.

**Comment by logstar** [comment]
Hi @kgaonkar6 . Could we wait for PR <https://github.com/PediatricOpenTargets/OpenPedCan-analysis/pull/29> to be merged? The PR <https://github.com/PediatricOpenTargets/OpenPedCan-analysis/pull/29> will modify the Dockerfile, so it could test whether docker build after merging works.

**Comment by jharenza** [comment]
@logstar I merged #29

**Comment by logstar** [comment]
If this `build-and-push-docker` action <https://github.com/PediatricOpenTargets/OpenPedCan-analysis/actions/runs/1121284568> passes, we could close this PR.

**Comment by logstar** [comment]
Closed with <https://github.com/PediatricOpenTargets/OpenPedCan-analysis/actions/runs/1121284568> passed. The cavatica docker registry is also updated.

**Pull request closed without merging**
