### PR TITLE
Methylation arrays processing module

### PR DESCRIPTION
**Pull request by ewafula**
#### What scientific question is your analysis addressing?
Process probe hybridization intensity values of selected methylated and unmethylated cytosine (CpG) loci into usable methylation measurements for the [Pediatric Open Targets, OPenPedCan-analysis](https://github.com/PediatricOpenTargets/OpenPedCan-analysis) raw DNA methylation array datasets.   

#### What was your approach?
Preprocesses raw Illumina Infinium HumanMethylation BeadArrays (27K, and 450K) intensities using `minfi Bioconductor package` into usable methylation measurements (Beta and M values) for TARGET normal and tumor samples.

#### What GitHub issue does your pull request address?
- https://github.com/PediatricOpenTargets/ticket-tracker/issues/269

#### Which areas should receive a particularly close look?
Review the entire code and test run the module. Also, check the results produced by the module  for consistency 

#### Is there anything that you want to discuss further?
The module cannot be run in the OpenPedCan Docker image because it utilizes R version > 4.1. Please the module README for detailed instructions on how to run the module. 

#### Is the analysis in a mature enough form that the resulting figure(s) and/or table(s) are ready for review?
Yes.

#### What types of results are included (e.g., table, figure)?
TSV Tables and plots

#### What is your summary of the results?
- `results/Normal-beta-values-methylation.tsv.gz`
- `results/Normal-m-values-methylation.tsv.gz`
- `results/NBL-beta-values-methylation.tsv.gz`
- `results/NBL-m-values-methylation.tsv.gz`
- `results/OS-beta-values-methylation.tsv.gz`
- `results/OS-m-values-methylation.tsv.gz`
- `results/CCSK-beta-values-methylation.tsv.gz`
- `results/CCSK-m-values-methylation.tsv.gz`
- `results/WT-beta-values-methylation.tsv.gz`
- `results/WT-m-values-methylation.tsv.gz`
- `results/AML450k-beta-values-methylation.tsv.gz`
- `results/AML450k-m-values-methylation.tsv.gz`
- `results/AML27k-beta-values-methylation.tsv.gz`
- `results/AML27k-m-values-methylation.tsv.gz`
#### Reproducibility Checklist

- [x] The dependencies required to run the code in this pull request have been added to the project Dockerfile.
- [ ] This analysis has been added to continuous integration.

#### Documentation Checklist

- [x] This analysis module has a `README` and it is up to date.
- [ ] This analysis is recorded in the table in `analyses/README.md` and the entry is up to date.
- [x] The analytical code is documented and contains comments.

### CODE REVIEW

**Comment by ewafula** [comment]
@afarrel, I have updated the methylation array analysis module with the code for comparison plots. The plots for `214 genes` from your list of genes that are only expressed in a subset of the tumor types (`metadata/TARGET_Methylation_GeneList.txt`) are included in the `plots folder`. `36 genes` are not in Illumina 450k  methylation arrays probe design.  I didn't upload the corresponding methylation values gene matrices, but have uploaded them on Isilon in the same folder with the plots (`/mnt/isilon/opentargets/wafulae/methylation-analysis/plots/`).

**Review by afarrel — APPROVED** [review]
Hi Eric. Looks good. This allowed me to evaluate the method and compare it to other analyses we have done previously. This is good. I approve but don't close the ticket attached to the PR as we can build off of this analysis to finalize thee module with tables that would be easily adaptable for the R API and PostgreSQL database.

**Comment by jharenza** [comment]
Hi @ewafula and @afarrel - I haven't looked at the code, but the PR said 450k. Will you also add 850k compatibility for incoming arrays? Thanks!

**Comment by ewafula** [comment]
> Hi Eric. Looks good. This allowed me to evaluate the method and compare it to other analyses we have done previously. This is good. I approve but don't close the ticket attached to the PR as we can build off of this analysis to finalize thee module with tables that would be easily adaptable for the R API and PostgreSQL database.

Thanks, @afarrel! We can plan to meet and discussed the required changes for the final output table.

**Comment by ewafula** [comment]
> Hi @ewafula and @afarrel - I haven't looked at the code, but the PR said 450k. Will you also add 850k compatibility for incoming arrays? Thanks!

@jharenza, yes we can add the 850K. A substantial percentage of the CpG loci contained on the 450k array (93.3%, according to Illumina) are also present on the 850k array and measured using the same probes and chemistry. The `minfi R Bioconductor package` has implemented functionality to combine data from both arrays. It can output a data object they call `virtual array` after combining that mimics either the 450k  array or the 850k array.  Alternatively, independently preprocess the 850k arrays with the same methodology as we've done the 450k array.

**Comment by afarrel** [comment]
@ewafula, Can you check how many patients in each histology from TARGET have both methylation data and RNAseq data? Thanks!

**Comment by ewafula** [comment]
@afarrel, here are the patient USI IDs with both methylation and RNA-Seq data

```
suppressPackageStartupMessages(library(tidyverse))
suppressPackageStartupMessages(library(data.table))

# OpenPedCan TARGET patients with RNA-Seq tumor samples (USI IDs)
histologies_file <-  file.path("../../data", "histologies.tsv")
rnaseq_usi <- readr::read_tsv(histologies_file, show_col_types = FALSE) %>% 
  dplyr::filter(sample_type == "Tumor", cohort == "TARGET", 
                experimental_strategy == "RNA-Seq") %>% 
  dplyr::pull(Kids_First_Participant_ID) 
rnaseq_usi <- unique(rnaseq_usi)

# NBL patients with both methylation and RNA-Seq data
meth_table <- file.path("results", "NBL-beta-values-methylation.tsv.gz")
meth_usi <- data.table::fread(meth_table, select = "Sample_Name",
                              showProgress = FALSE) %>% 
  tibble::tibble() %>% dplyr::distinct() %>% 
  dplyr::mutate(
    usi = stringr::str_split(Sample_Name, "-", simplify = TRUE)[,3]
  ) %>% 
  dplyr::filter(usi %in% rnaseq_usi) %>% 
  dplyr::pull(usi)
> unique(meth_usi)
  [1] "PAIFXV" "PAIPGU" "PAISNS" "PAITCI" "PAIVHE" "PAKYZS" "PAKZRH" "PALBFW" "PALCBW" "PALETP" "PALEVG"
 [12] "PALIIN" "PALNVP" "PALXTB" "PALZZV" "PAMMXF" "PAMNLH" "PAMYCE" "PAMZGT" "PAMZMG" "PANBMJ" "PANBSP"
 [23] "PANKFE" "PANLET" "PANNMS" "PANRHJ" "PANRRW" "PANRVJ" "PANUIF" "PANWRR" "PANXJL" "PANYGR" "PANZPV"
 [34] "PANZVU" "PAPBGH" "PAPBJE" "PAPBZI" "PAPCTS" "PAPEFE" "PAPHPE" "PAPICY" "PAPKWN" "PAPKXS" "PAPTAN"
 [45] "PAPTCR" "PAPTDH" "PAPTFZ" "PAPTLV" "PAPUNH" "PAPUWY" "PAPVEB" "PAPVFD" "PAPVRN" "PAPVXS" "PAPZYP"
 [56] "PAPZYZ" "PARACM" "PARACS" "PARAMT" "PARBAJ" "PARBGP" "PARDCK" "PARDIW" "PARFRE" "PARFWB" "PARGKK"
 [67] "PARHAM" "PARJVP" "PARKGJ" "PARNNC" "PARSBI" "PARVLK" "PARYNK" "PARZCJ" "PARZHA" "PARZIP" "PASCFC"
 [78] "PASCTR" "PASEGA" "PASFGG" "PASFIC" "PASGAP" "PASGUT" "PASHFA" "PASJZC" "PASMDM" "PASMJG" "PASMNT"
 [89] "PASNEF" "PASNML" "PASNPG" "PASNZU" "PASPBZ" "PASPER" "PASRFS" "PASSRN" "PASSRS" "PASSWW" "PASTCN"
[100] "PASTKC" "PASUCB" "PASUML" "PASUYG" "PASVRU" "PASWFB" "PASWIJ" "PASWVY" "PASWYR" "PASXGP" "PASXHE"
[111] "PASXIE" "PASXRG" "PASXRJ" "PASYPX" "PASZKE" "PATAYJ" "PATBMM" "PATCFL" "PATDWN" "PATDXC" "PATEPF"
[122] "PATESI" "PATFCY" "PATFXV" "PATGJU" "PATGLU" "PATHKB" "PATHVK" "PATNKP" "PATYIL" "PAUDDK"
> length(unique(meth_usi))
[1] 131

# WT patients with both methylation and RNA-Seq data
meth_table <- file.path("results", "WT-beta-values-methylation.tsv.gz")
meth_usi <- data.table::fread(meth_table, select = "Sample_Name",
                              showProgress = FALSE) %>%
  tibble::tibble() %>% dplyr::distinct() %>%
  dplyr::mutate(
    usi = stringr::str_split(Sample_Name, "-", simplify = TRUE)[,3]
  ) %>%
  dplyr::filter(usi %in% rnaseq_usi) %>%
  dplyr::pull(usi)
> unique(meth_usi)
  [1] "CAAAAB" "CAAAAC" "CAAAAH" "CAAAAJ" "CAAAAL" "CAAAAM" "CAAAAO" "CAAAAP" "CAAAAQ" "CAAAAR" "CAAAAS"
 [12] "PADXAY" "PADZUB" "PAEAFB" "PAEBXA" "PAECJB" "PAJLIP" "PAJLKC" "PAJLKR" "PAJLLF" "PAJLNJ" "PAJLPX"
 [23] "PAJLSP" "PAJLTH" "PAJLTI" "PAJLUJ" "PAJLWT" "PAJMEL" "PAJMEN" "PAJMEP" "PAJMFU" "PAJMFY" "PAJMIZ"
 [34] "PAJMJT" "PAJMKI" "PAJMKJ" "PAJMKN" "PAJMLI" "PAJMLZ" "PAJMMY" "PAJMRL" "PAJMSE" "PAJMUF" "PAJMVC"
 [45] "PAJMVU" "PAJMXF" "PAJNAA" "PAJNAV" "PAJNBN" "PAJNCC" "PAJNCJ" "PAJNCZ" "PAJNDU" "PAJNEC" "PAJNGH"
 [56] "PAJNJJ" "PAJNLT" "PAJNNC" "PAJNNR" "PAJNRH" "PAJNRL" "PAJNSL" "PAJNTJ" "PAJNUP" "PAJNUS" "PAJNVE"
 [67] "PAJNVX" "PAJNYT" "PAJNZI" "PAJNZK" "PAJNZS" "PAJNZU" "PAJPAR" "PAJPAU" "PAJPCM" "PAJPDC" "PAJPDN"
 [78] "PAJPEW" "PAJPGY" "PAJPHA" "PAKECR" "PAKFME" "PAKFYV" "PAKGED" "PAKGZX" "PAKJGM" "PAKKNS" "PAKKSE"
 [89] "PAKMSV" "PAKMUB" "PAKNAL" "PAKNRX" "PAKNTW" "PAKNXS" "PAKPDF" "PAKRVH" "PAKRZW" "PAKSCC" "PAKSDG"
[100] "PAKUIT" "PAKULH" "PAKVET" "PAKWPM" "PAKXWB" "PAKXXF" "PAKYFC" "PAKYLT" "PAKZER" "PAKZFK" "PAKZHF"
[111] "PALDTE" "PALDWP" "PALERC" "PALEZT" "PALFME" "PALFRD" "PALGAZ" "PALGLU" "PALGVY" "PALJIP" "PALKCW"
[122] "PALKRS" "PALLFB"
> length(unique(meth_usi))
[1] 123

# AML patients with both methylation and RNA-Seq data
meth_table <- file.path("results", "AML450k-beta-values-methylation.tsv.gz")
meth_usi <- data.table::fread(meth_table, select = "Sample_Name",
                              showProgress = FALSE) %>% 
  tibble::tibble() %>% dplyr::distinct() %>% 
  dplyr::mutate(
    usi = stringr::str_split(Sample_Name, "-", simplify = TRUE)[,3]
  ) %>% 
  dplyr::filter(usi %in% rnaseq_usi) %>% 
  dplyr::pull(usi)
> unique(meth_usi)
 [1] "PABLDZ" "PADYIR" "PADZCG" "PAECCE" "PAEDKB" "PAEERJ" "PAEFGR" "PAEFGT" "PAEIKD" "PAKERZ" "PAKIWK"
[12] "PAKSMZ" "PAKTCX" "PAKVGI" "PALGKX" "PAMYAS" "PANDER" "PANDIX" "PANGDN" "PANGTF" "PANLIR" "PANLLX"
[23] "PANLXM" "PANNHB" "PANSJB" "PANTNA" "PANYNR" "PAPBEJ" "PAPVZK" "PAPXRJ" "PAPXWI" "PARASV" "PARBIU"
[34] "PARCCH" "PARCUK" "PARDMG" "PARIMT" "PARPDS" "PARSAN" "PARSHM" "PARTAL" "PARUBT" "PARUDL" "PARUWX"
[45] "PARXMP" "PARYVW" "PASBBE" "PASCFW" "PASCGR" "PASCRZ" "PASGMZ" "PASHBI" "PASJGZ" "PASJTM" "PASLSD"
[56] "PASMGW" "PASMHY" "PASPLU" "PASTTW" "PASTUH" "PASVVS" "PASVYA" "PASVYL" "PASWAT" "PASWLN" "PASWPD"
[67] "PASZLJ" "PATDHA" "PATIAK" "PAMYMA" "PANVPB" "PANZLR" "PARLSL" "PARXYR" "PASDKZ" "PASFHK" "PASFJJ"
[78] "PASFLG" "PASNKZ" "PASSLT" "PASTZK" "PASVJS" "PASYEJ" "PASYWA" "PATAIJ" "PATHIU" "PATISD" "PATJMY"
[89] "PATKBK" "PATKKJ" "PATKWH"
> length(unique(meth_usi))
[1] 91

# OS patients with both methylation and RNA-Seq data
meth_table <- file.path("results", "OS-beta-values-methylation.tsv.gz")
meth_usi <- data.table::fread(meth_table, select = "Sample_Name",
                              showProgress = FALSE) %>%
  tibble::tibble() %>% dplyr::distinct() %>%
  dplyr::mutate(
    usi = stringr::str_split(Sample_Name, "-", simplify = TRUE)[,3]
  ) %>%
  dplyr::filter(usi %in% rnaseq_usi) %>%
  dplyr::pull(usi)
> unique(meth_usi)
 [1] "0A4HLD" "0A4HMC" "0A4HX8" "0A4HXS" "0A4HY5" "0A4I0Q" "0A4I0W" "0A4I3S" "0A4I42" "0A4I48" "0A4I4E"
[12] "0A4I4M" "0A4I4O" "0A4I5B" "0A4I65" "0A4I6O" "0A4I8U" "0A4I9K" "PAKFVX" "PAKUZU" "PAKXLD" "PAKZZK"
[23] "PALECC" "PALFYN" "PALHRL" "PALKDP" "PALKGN" "PALWWX" "PALZGU" "PAMEKS" "PAMHYN" "PAMJXS" "PAMLKS"
[34] "PAMRHD" "PAMTCM" "PAMYYJ" "PANGPE" "PANGRW" "PANMIG" "PANPUM" "PANSEN" "PANVJJ" "PANXSC" "PANZHX"
[45] "PANZZJ" "PAPFLB" "PAPIJR" "PAPKWD" "PAPNVD" "PAPWWC" "PAPXGT" "PARDAX" "PARFTG" "PARGTM" "PARJXU"
[56] "PARKAF" "PASEBY" "PASEFS" "PASFCV" "PASKZZ" "PASNZV" "PASRNE" "PASSLM" "PASUUH" "PASYUK" "PATAWV"
[67] "PATEEM" "PATJVI" "PATKSS" "PATMIF" "PATMPU" "PATMXR" "PATPBS" "PATUXZ" "PAUBIT" "PAUTWB" "PAUTYB"
[78] "PAUUML" "PAUVUL" "PAUXPZ" "PAUYTT" "PAVALD" "PAVCLP" "PAVDTY" "PAVECB"
> length(unique(meth_usi))
[1] 85

# CCSK patients with both methylation and RNA-Seq data
meth_table <- file.path("results", "CCSK-beta-values-methylation.tsv.gz")
meth_usi <- data.table::fread(meth_table, select = "Sample_Name",
                              showProgress = FALSE) %>%
  tibble::tibble() %>% dplyr::distinct() %>%
  dplyr::mutate(
    usi = stringr::str_split(Sample_Name, "-", simplify = TRUE)[,3]
  ) %>%
  dplyr::filter(usi %in% rnaseq_usi) %>%
  dplyr::pull(usi)
> unique(meth_usi)
 [1] "PAEALX" "PAJLWU" "PAJMFS" "PAJNCV" "PAJPFB" "PAKWMM" "PALEIR" "PALFEF" "PALFYG" "PALKEI" "PALLXV"
> length(unique(meth_usi))
[1] 11
```

**Comment by afarrel** [comment]
Thanks @ewafula ! This is very useful. We will include correlations of RNA expression (TPM) vs Methylation (beta scores) in one of the final plots and should include the option that if RNA and Methylation data its available for that cancer histology it is calculated. But if no RNAseq expression is available for a cancer histology (We should get methylation data from other institutions in the future that may not have RNAseq data) it still determines the methylation beta values only without causing an error.

**Comment by afarrel** [comment]
Hi @ewafula, For the final PR, we would need to pull data from the **histologies.tsv**, **gene-expression-rsem-tpm-collapsed.rds**, **efo-mondo-map.tsv**, **ensg-hugo-rmtl-v1-mapping.tsv** 

There should be 3 Output tables:
**1) beta value Table**
-  **Columns**: Patient IDs
- **Rows**: Probe IDs

**2) m-Value table**
- **Columns**: Patient IDs
- **Rows**: Probe IDs

**3) Methylation_Data_table for Plots**

The following should be columns for this table:
- **Gene_Symbol**: gene symbol
- **Ensembl_ID**: ensemble ID
- **PMTL**: Is gene on PMTL ("Relevant Molecular Target"/"NA")
- **datatypeId**: illumina methylation array
- **PROBE_ID**: cg########
- **Chromosome**: chromosome eg. chr1
- **Location**: genomic location
- **Cohort**: (from histology file) eg TARGET 
- **Cancer_Group**: (from histology file) eg Neuroblastoma 
- **EFO_ID**: EFO ID of cancer_group from From efo-mondo-map.tsv
- **MONDO_ID**: MONDO_ID of cancer group From efo-mondo-map.tsv
- **RNA_Correlation**: Correlation between beta values and TPM of samples with both methylation data and RNAseq data
- **Beta_Q1**: Calculate quantiles for the beta scores of the patients at each probe in the specific Cancer_Group of the specific Cohort using quantile function and use Q1.
- **Beta_Q2**:Calculate quantiles for the beta scores of the patients at each probe in the specific Cancer_Group of the specific Cohort using quantile function and useQ2.
- **Beta_Median**:Calculate quantiles for the beta scores of the patients at each probe in the specific Cancer_Group of the specific Cohort using quantile function and use Q3.
- **Beta_Q4**:Calculate quantiles for the beta scores of the patients at each probe in the specific Cancer_Group of the specific Cohort using quantile function and use Q4.
- **Beta_Q5**:Calculate quantiles for the beta scores of the patients at each probe in the specific Cancer_Group of the specific Cohort using quantile function and use Q5.

This table will be used to generate two methylation visualizations:

1. **Methylation heat map**: Gene vs All Cancers (Requires Gene_Symbol, Ensembl_ID, PMTL, PROBE_ID, Chromosome, Location, Cancer_Group, EFO_ID, Beta_Median,
2. **Methylation-RNA correlation and beta score range**: 1 Gene vs All 1 Cancer_group (Requires Gene_Symbol, Ensembl_ID, PMTL, PROBE_ID, Chromosome, Location, Cancer_Group, EFO_ID, RNA_Correlation , Beta_Q1, Beta_Q2 ,Beta_Median, Beta_Q4, Beta_Q5)

Let's discuss any questions, concerns, and suggestions.

**Comment by runjin326** [comment]
@ewafula - I think for this one, we mentioned that this was ready for merge? Maybe @afarrel missed approving it?

**Comment by ewafula** [comment]
> @ewafula - I think for this one, we mentioned that this was ready for merge? Maybe @afarrel missed approving it?

@runjin326, just synced with upstream dev and ready to merge when @afarrel approves. He had already reviewed and maybe forgot to approve.

**Comment by afarrel** [comment]
> > @ewafula - I think for this one, we mentioned that this was ready for merge? Maybe @afarrel missed approving it?
> 
> @runjin326, just synced with upstream dev and ready to merge when @afarrel approves. He had already reviewed and maybe forgot to approve.

@ewafula and @runjin326,  I want to review the results again when I review the results for PR #165. Right now I'm locked out of the open targets subfolders on Isilon so I'll try again in the morning. I initially approved this but then dismissed the review when we designed the new output table that should be generated in PR #165. I'll approve this PR once I have completed the first round of review for #165. We will need to discuss adding the 850K data to PR #165.

**Comment by afarrel** [comment]
Hi @ewafula , the CBTN 850K methylation files are here `https://cavatica.sbgenomics.com/u/cavatica/pbta-cbttc/files/#q?path=methylation` and I have transferred some to `/mnt/isilon/opentargets/Methylation/850k_data/` so you can start working on them. I've attached the metadata data here.
[manifest_methylation_CBTN_20220410.csv](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/files/8466630/manifest_methylation_CBTN_20220410.csv)

**Pull request closed without merging**
