### PR TITLE
Focal CN preparation module 

### PR DESCRIPTION
**Pull request by runjin326**
#### What scientific question is your analysis addressing?
Analyze 200 samples per batch for CNV annotation to avoid getting killed due to memory issues. 

#### What was your approach?
Generate a vector with step of 200
```
cnv_df_ids <- cnv_df %>% 
  dplyr::pull(Kids_First_Biospecimen_ID) %>% unique()
# slice to 200 samples each
slice_vector <- seq(1, length(cnv_df_ids), 200) 

# define combined dataframe
autosome_annotated_cn <- data.frame()
for (i in 1:length(slice_vector)){
  start_id <- as.numeric(slice_vector[i])
  if(i<length(slice_vector)){
    end_id <- as.numeric(slice_vector[i+1]-1)
  } else {
    end_id <- as.numeric(length(cnv_df_ids))
  }
  # get the matching BS IDs
  cnv_df_ids_each <- cnv_df_ids[start_id:end_id]
  # get the matching CNV dataframe
  cnv_df_each <- cnv_df %>% 
    dplyr::filter(Kids_First_Biospecimen_ID %in% cnv_df_ids_each)

 # and then run the annotation on either x_and_y or autosome filtered cnv_df_each 
}

```

#### What GitHub issue does your pull request address?
https://github.com/PediatricOpenTargets/ticket-tracker/issues/245

#### Which areas should receive a particularly close look?
1) Please check to make sure the logic for parsing makes sense
2) I ran the analysis on histologies file and `cnvkit_with_status.tsv` Bo sent me and the analysis went well - please also test either in CAVATICA or EC2 instance to make sure that works on your end as well.

#### Is there anything that you want to discuss further?
No.

#### Is the analysis in a mature enough form that the resulting figure(s) and/or table(s) are ready for review?
Yes.

#### What types of results are included (e.g., table, figure)?
`cnvkit_annotated_cn_wxs_x_and_y.tsv.gz`
`cnvkit_annotated_cn_wxs_autosomes.tsv.gz`

#### What is your summary of the results?
Annotation works as expected.

#### Reproducibility Checklist

- [x] The dependencies required to run the code in this pull request have been added to the project Dockerfile.
- [ ] This analysis has been added to continuous integration.

#### Documentation Checklist

- [x] This analysis module has a `README` and it is up to date.
- [ ] This analysis is recorded in the table in `analyses/README.md` and the entry is up to date.
- [x] The analytical code is documented and contains comments.

### CODE REVIEW

**Comment by komalsrathi** [comment]
Hi @runjin326 @zhangb1, I would need the `cnvkit_with_status.tsv` to test it - where can I find it?

**Comment by zhangb1** [comment]
[scratch.tar.gz](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/files/7435319/scratch.tar.gz)

@komalsrathi  you can use this file.

**Comment by komalsrathi** [comment]
Hi all, I tested the code and it worked fine. I am looking into an alternative method to run it more efficiently but don't want to hold this from merging. I'll create another PR if I find a "significant" difference in the runtimes of both methods.

**Comment by komalsrathi** [comment]
@runjin326 just a quick question before this is merged - I was looking at the output file,  do we want to keep rows with `status == NA`? If so, what does that mean?

**Comment by runjin326** [comment]
@komalsrathi , thanks for the question. `status == NA` should only come from WXS samples since during [this step](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/blob/64db9a2040c1ae5b4c9f6a3466ce0b3cd71f5679/analyses/focal-cn-file-preparation/01-add-ploidy-cnvkit.Rmd#L117-L134), based on whether the sample is male or female, we assign status to it. However, not all WXS samples have gender information and for those without the information, we cannot infer status and hence it is NA.

**Comment by jharenza** [comment]
> @komalsrathi , thanks for the question. `status == NA` should only come from WXS samples since during [this step](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/blob/64db9a2040c1ae5b4c9f6a3466ce0b3cd71f5679/analyses/focal-cn-file-preparation/01-add-ploidy-cnvkit.Rmd#L117-L134), based on whether the sample is male or female, we assign status to it. However, not all WXS samples have gender information and for those without the information, we cannot infer status and hence it is NA.

hi @runjin326 I know that @zhangb1 had done this somewhere at some point for PNOC, but for TARGET, if we do not have `germline_sex_estimate` (or if any other WXS samples do not have this), we should go back to the `reported_gender` and use that column instead. For PNOC, we had WXS + WGS, so for WXS, we took WGS `germline_sex_estimate`. Can you make sure we have this implemented? Thanks!

**Comment by runjin326** [comment]
> hi @runjin326 I know that @zhangb1 had done this somewhere at some point for PNOC, but for TARGET, if we do not have `germline_sex_estimate` (or if any other WXS samples do not have this), we should go back to the `reported_gender` and use that column instead. For PNOC, we had WXS + WGS, so for WXS, we took WGS `germline_sex_estimate`. Can you make sure we have this implemented? Thanks!

Yes this is already in the workflow - [see here](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/blob/64db9a2040c1ae5b4c9f6a3466ce0b3cd71f5679/analyses/focal-cn-file-preparation/01-add-ploidy-cnvkit.Rmd#L32-L65). But I can confirm with him to make sure the CWL workflow has this as well.

**Comment by komalsrathi** [comment]
For all rows with `status == NA` in the final output files (n = 547953 in `consensus_wgs_plus_cnvkit_wxs_x_and_y.tsv.gz` and `consensus_wgs_plus_cnvkit_wxs.tsv.gz`) , would it be feasible to add the status using the following criteria (similar to what is being implemented in the clinical reporting pipeline)? 

```
cnvData <- cnvData %>%
      mutate(status = case_when(copy_number == 0 ~ "deep deletion",
                                copy_number < ploidy & copy_number > 0 ~ "loss",
                                copy_number == ploidy ~ "neutral",
                                copy_number > ploidy & copy_number < ploidy + 3 ~ "gain",
                                copy_number >= ploidy + 3 ~ "amplification"))
```

**Comment by jharenza** [comment]
@komalsrathi we have validated some different cutoffs in OpenPBTA and have been using those. I'm not sure offhand how much these overlap or are different, but we can investigate whether or not what we've come up with catches everything for your samples.

**Comment by jharenza** [comment]
> For all rows with `status == NA` in the final output files (n = 547953 in `consensus_wgs_plus_cnvkit_wxs_x_and_y.tsv.gz` and `consensus_wgs_plus_cnvkit_wxs.tsv.gz`) , would it be feasible to add the status using the following criteria (similar to what is being implemented in the clinical reporting pipeline)?
> 
> ```
> cnvData <- cnvData %>%
>       mutate(status = case_when(copy_number == 0 ~ "deep deletion",
>                                 copy_number < ploidy & copy_number > 0 ~ "loss",
>                                 copy_number == ploidy ~ "neutral",
>                                 copy_number > ploidy & copy_number < ploidy + 3 ~ "gain",
>                                 copy_number >= ploidy + 3 ~ "amplification"))
> ```

@komalsrathi I think what you have above is for autosomes only, correct? The `status == NA` here should only apply to sex chromosomes unless there was some uncallable region in an autosome (can you check?). If we don't have the sex or gender, we can't infer status on XY.

Below are the criteria we have been using:

First, everything is marked as gain, neutral, or loss:

https://github.com/PediatricOpenTargets/OpenPedCan-analysis/blob/64db9a2040c1ae5b4c9f6a3466ce0b3cd71f5679/analyses/focal-cn-file-preparation/02-add-ploidy-consensus.Rmd#L93-L125

Next, amplifications and deletions are calculated:

https://github.com/PediatricOpenTargets/OpenPedCan-analysis/blob/64db9a2040c1ae5b4c9f6a3466ce0b3cd71f5679/analyses/focal-cn-file-preparation/04-prepare-cn-file.R#L262-L266


It looks like our deep deletions and neutral calls are the same, amplifications are less stringent on our end, so we will have more amplifications compared to gains than you would have. Will you need to be more stringent for tumor board? Do you look at both gains and amplifications to make sure you are capturing everything or do you focus on amplifications there? It could be beneficial to lower the stringency to capture more.

**Comment by komalsrathi** [comment]
> @komalsrathi I think what you have above is for autosomes only, correct? The `status == NA` here should only apply to sex chromosomes unless there was some uncallable region in an autosome (can you check?). If we don't have the sex or gender, we can't infer status on XY.

Yes correct, autosomes only. I didn't realize the NA's all correspond to sex chroms in consensus_wgs_plus_cnvkit_wxs.tsv.gz - so all good. 

> It looks like our deep deletions and neutral calls are the same, amplifications are less stringent on our end, so we will have more amplifications compared to gains than you would have. Will you need to be more stringent for tumor board? Do you look at both gains and amplifications to make sure you are capturing everything or do you focus on amplifications there?

We look at both gains/amps.

**Comment by runjin326** [comment]
Double checked that the outputs from original script vs. 200 each batch are identical - this is ready for merge.

**Pull request merged**
