### PR TITLE
add mutational signature dependencies to Dockerfile

### PR DESCRIPTION
**Pull request by rjcorb**
#### What scientific question is your analysis addressing?

This PR adds dependencies for [mutational signature analyses](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/tree/dev/analyses/mutational-signatures) to the project Dockerfile

#### What was your approach?

Added new installation commands to Dockerfile for `signature.tools.lib` R package and `libgmp3-dev`

#### What GitHub issue does your pull request address?

[Ticket #464](https://github.com/PediatricOpenTargets/ticket-tracker/issues/464)

#### Which areas should receive a particularly close look?

Confirm dependencies have been installed successfully. 

#### Is there anything that you want to discuss further?

No

#### Is the analysis in a mature enough form that the resulting figure(s) and/or table(s) are ready for review?

NA

#### What types of results are included (e.g., table, figure)?

NA

#### What is your summary of the results?

NA

#### Reproducibility Checklist

- [x] The dependencies required to run the code in this pull request have been added to the project Dockerfile.
- [ ] This analysis has been added to continuous integration.

### CODE REVIEW

**Comment by ewafula** [comment]
@rjcorb GA checks are failing when installing `sigfit` package: 
```
Error: buildx failed with: ERROR: failed to solve: process "/bin/sh -c R -e \"remotes::install_github('kgori/sigfit', ref = '209776ee1d2193ad4b682b2e2472f848bd7c67a6', build_vignettes = TRUE, build_opts = c('--no-resave-data', '--no-manual'), dependencies = TRUE)\"" did not complete successfully: exit code: 1 
```

**Comment by jharenza** [comment]
@ewafula I was looking at this yesterday and it is an api rate limit issue, which was solved in OpenPBTA using a [github PAT token](https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/5301c9873e8b93e33cbf4074f1ddbb3eb45be009/Dockerfile#L172) - cc-ing @devbyaccident to see if we can implement here as well.

**Comment by rjcorb** [comment]
We may also be able to remove sigfit installation, since we no longer use it in the `mutational-signatures` module

**Comment by devbyaccident** [comment]
> @ewafula I was looking at this yesterday and it is an api rate limit issue, which was solved in OpenPBTA using a [github PAT token](https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/5301c9873e8b93e33cbf4074f1ddbb3eb45be009/Dockerfile#L172) - cc-ing @devbyaccident to see if we can implement here as well.

The way it looks like they did that is with a file on their build machine. I can add the PAT as a secret for the repo and expose it to the build action, I just need to generate a token. Shouldn't be a big change, especially if you already have a token I can use, maybe look for a commit with it by EoB today?

**Comment by ewafula** [comment]
@rjcorb,  is this PR still needed? Associate with [ticket #464](https://github.com/PediatricOpenTargets/ticket-tracker/issues/464)

**Comment by rjcorb** [comment]
@ewafula the API rate limit issue hasn't been resolved so PR is still needed

**Comment by jharenza** [comment]
To add to this - @devbyaccident won't be able to complete before the holiday, and it's possible we may not be able to remedy with GA, but can look for a solution in Jan.

**Comment by devbyaccident** [comment]
Ok @jharenza @rjcorb, I added the authentication token as a build arg to the docker buildx action, and once I got the syntax right, it built and ran the job green. 

I'm using the `{{ secrets.GITHUB_TOKEN }}` built into the repo actions context and setting it as the value for `GITHUB_PAT` at build time, so the `install_github()` function will consume it as a value for the `auth_token` parameter [as shown in the docs](https://www.rdocumentation.org/packages/remotes/versions/2.4.2/topics/install_github). 

GitHub Actions should render it as `'***'` in any logs, but just in case, I also [changed the token's scope](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/enabling-features-for-your-repository/managing-github-actions-settings-for-a-repository#setting-the-permissions-of-the-github_token-for-your-repository) to read-only.

Also, I wasn't able to rebase this branch because there's just too many commits I'd need to update from main, and since it's not my code, I wouldn't be comfortable resolving all those conflicts, but I'm happy to go through re-basing commits and cleaning git history with the team at some point. 

In any case, let me know if you have any questions or concerns.

**Comment by jharenza** [comment]
Amazing work @devbyaccident! I'll take care of conflicts

**Comment by jharenza** [comment]
Going to merge this without module checks since it is only a docker image build PR.

**Pull request merged**
