### PR TITLE
Updated efo-mondo module to use v12 prefill 

### PR DESCRIPTION
**Pull request by sangeetashukla**
### Purpose/implementation Section
Update the module to use v12 `efo-mondo-map-prefill.tsv`

#### What scientific question is your analysis addressing?
With v12, a new `efo-mondo-map-prefill.tsv` is generated by `molecular-subtype-integrate` module.
This module uses the file to re-run an automated search for all the `cancer_group`s across EBI OLS, to assist a downstream manual review and ensure all cancer_group have their associated EFO, MONDO, and NCIT codes captured in the final `efo-mondo-map.tsv` file. The file is then ready to be added to the data release.

#### What was your approach?
Copy the provided `efo-mondo-map-prefill.tsv` file into the results directory and run the module. 
Also review the file for any missing codes or typos and debug module as needed.
Update the `efo-mondo-map.tsv` file based on the automatic and manual search findings.

#### What GitHub issue does your pull request address?
[Issue 526](https://github.com/PediatricOpenTargets/ticket-tracker/issues/526)

#### Which areas should receive a particularly close look?
Fixed a typo in the input file from **'witj'** to **'with'**
Added a few NCIT codes that were missing previously in the input file.

#### Is there anything that you want to discuss further?
The manual update of the `results/efo-mondo-map.tsv` is also done. Comments are noted here.

**Below** cancer_group s were **removed** from the final mapping file since they did not exist in the input prefill file:
`CNS Burkitt's lymphoma	EFO_1000157	Orphanet_46135	NCIT_C9189`
`Diffuse fibrillary astrocytoma	Orphanet_251601	MONDO_0016688	NCIT_C4322`
`Gliosarcoma	EFO_1001465	MONDO_0016681	NCIT_C3796`
`Central neurocytoma	EFO_1000856	MONDO_0019134	NCIT_C3791`
`Extraventricular neurocytoma	EFO_1000856	MONDO_0016727	NCIT_C92555`
`Pilocytic astrocytoma	MONDO_0016691	MONDO_0016691	NCIT_C4047`

**Below** cancer_group s were **added**, and it is important to review their codes:
`Diffuse hemispheric glioma	NA	NA	NA` - No codes were found, and need to be added manually.
`Epstein-Barr virus-related tumor	MONDO_0017342	MONDO_0017342	NA` -NCIT code is pending.
`Extraventricular neurocytoma	EFO_1000856	MONDO_0016727	NCIT_C92555` - EFO code needs review.
`High-grade glioma	MONDO_0100342	MONDO_0100342	NCIT_C4822`
`Infant-type hemispheric glioma	EFO_0005543	MONDO_0014695	NCIT_C185471`
`Low-grade glioma	MONDO_0021637	MONDO_0021637	NCIT_C132067`
`Mesenchymal tumor	EFO_1000473	MONDO_0003512	NCIT_C7059` - needs review for description.
`Non-germinomatous germ cell tumor	MONDO_0020580	MONDO_0020580	NCIT_C121619`
`Other	EFO_0030051	GO_0051707	NCIT_C17649` - needs review since this is not specific at all.
`Perineuroma	NA	NA	NA` - was added but is missing all codes, therefore needs review.
`Primary CNS lymphoma	EFO_1000157	MONDO_0002571	NCIT_C9301`

**Note**: 

- `High-grade glioma` and `Low-grade glioma` need additional review since `High-grade glioma/astrocytoma` and `Low-grade glioma/astrocytoma` are also included, although the codes are different.

- `Neuroepithelial neoplasm	MONDO_0021193	MONDO_0021193	NCIT_C3787` was replaced with

`Neuroepithelial neoplasm with EWSR1--PLAG1 fusion	EFO_0005551	MONDO_0021193	NCIT_C101053` and needs review

- `T Acute Lymphoblastic Leukemia/Lymphoma	EFO_0000209	MONDO_0004963	NCIT_C3183	EFO_1001936	MONDO_0003537	NCIT_C8694` The codes need to be re-visited. Alternatives are suggested here.

- `Uterine Corpus Endometrial Carcinoma	EFO_0007532	MONDO_0000553	NCIT_C159413	EFO_1000238	MONDO_0000553	NCIT_C159413` EFO code seems to have changed, needs review.

#### Is the analysis in a mature enough form that the resulting figure(s) and/or table(s) are ready for review?
Yes.

#### What types of results are included (e.g., table, figure)?
`results/efo-mondo-map.tsv`

#### What is your summary of the results?
The final `efo-mondo-map.tsv` file is updated as per list of `cancer_group`s in the input prefill file.

#### Reproducibility Checklist

- [x] The dependencies required to run the code in this pull request have been added to the project Dockerfile.
- [x] This analysis has been added to continuous integration.

#### Documentation Checklist

- [x] This analysis module has a `README` and it is up to date.
- [x] This analysis is recorded in the table in `analyses/README.md` and the entry is up to date.
- [x] The analytical code is documented and contains comments.

### CODE REVIEW

**Comment by ewafula** [comment]
@sangeetashukla,  Thanks for updating this module. 
Above, you listed cancer groups that have been removed in v12. These 2 are both in the  [efo-mondo-map-prefill.tsv](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/blob/v12-integrate/analyses/efo-mondo-mapping/results/efo-mondo-map-prefill.tsv) file and the [histologies.tsv](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/blob/v12-integrate/analyses/molecular-subtyping-integrate/results/histologies.tsv) file. Not removed.
```
> read_tsv("../../efo-mondo-mapping/results/efo-mondo-map-prefill.tsv") %>% filter(cancer_group %in% c("CNS Burkitt's lymphoma", "Diffuse fibrillary astrocytoma", "Gliosarcoma", "Central neurocytoma", "Extraventricular neurocytoma", "Pilocytic astrocytoma")) %>% pull(cancer_group) %>% unique()
[1] "Central neurocytoma"          "Extraventricular neurocytoma"
>
> read_tsv("histologies.tsv") %>%  filter(cancer_group %in% c("CNS Burkitt's lymphoma", "Diffuse fibrillary astrocytoma", "Gliosarcoma", "Central neurocytoma", "Extraventricular neurocytoma", "Pilocytic astrocytoma")) %>% pull(cancer_group) %>% unique()
[1] "Extraventricular neurocytoma" "Central neurocytoma"
```

Would you mind checking?  
Here is the list of all 128 cancer groups currently in preliminary v12 histologies.tsv excluding `Other` and `NAs`
```
> read_tsv("../../efo-mondo-mapping/results/efo-mondo-map-prefill.tsv") %>% filter(cancer_group %in% c("CNS Burkitt's lymphoma", "Diffuse fibrillary astrocytoma", "Gliosarcoma", "Central neurocytoma", "Extraventricular neurocytoma", "Pilocytic astrocytoma")) %>% pull(cancer_group) %>% unique()
[1] "Acute Lymphoblastic Leukemia"                                    
  [2] "Acute Myeloid Leukemia"                                          
  [3] "Adamantinomatous Craniopharyngioma"                              
  [4] "Adenocarcinoma"                                                  
  [5] "Adrenocortical Carcinoma"                                        
  [6] "Anaplastic Large Cell Lymphoma"                                  
  [7] "Angiosarcoma"                                                    
  [8] "Atypical Teratoid Rhabdoid Tumor"                                
  [9] "B Acute Lymphoblastic Leukemia/Lymphoma"                         
 [10] "Bladder Urothelial Carcinoma"                                    
 [11] "Breast Invasive Carcinoma"                                       
 [12] "Burkitt Leukemia/Lymphoma"                                       
 [13] "Cavernoma"                                                       
 [14] "Central neurocytoma"                                             
 [15] "Cervical Squamous Cell Carcinoma and Endocervical Adenocarcinoma"
 [16] "Cholangiocarcinoma"                                              
 [17] "Chondromyxoid fibroma"                                           
 [18] "Chordoma"                                                        
 [19] "Choroid plexus carcinoma"                                        
 [20] "Choroid plexus papilloma"                                        
 [21] "Choroid plexus tumor"                                            
 [22] "Chromophobe renal cell carcinoma"                                
 [23] "Chronic Myelogenous Leukemia"                                    
 [24] "CIC-DUX4 Sarcoma"                                                
 [25] "Clear cell sarcoma of the kidney"                                
 [26] "CNS Embryonal tumor"                                             
 [27] "CNS Melanoma"                                                    
 [28] "CNS neuroblastoma"                                               
 [29] "Colon Adenocarcinoma"                                            
 [30] "Craniopharyngioma"                                               
 [31] "Cutaneous Melanoma"                                              
 [32] "Desmoid-type fibromatosis"                                       
 [33] "Desmoplastic infantile astrocytoma and ganglioglioma"            
 [34] "Diffuse hemispheric glioma"                                      
 [35] "Diffuse intrinsic pontine glioma"                                
 [36] "Diffuse leptomeningeal glioneuronal tumor"                       
 [37] "Diffuse midline glioma"                                          
 [38] "Dysembryoplastic neuroepithelial tumor"                          
 [39] "Dysgerminoma"                                                    
 [40] "Embryonal tumor"                                                 
 [41] "Embryonal Tumor NOS"                                             
 [42] "Embryonal tumor with multilayer rosettes"                        
 [43] "Ependymoma"                                                      
 [44] "Epstein-Barr virus-related tumor"                                
 [45] "Esophageal Carcinoma"                                            
 [46] "Ewing sarcoma"                                                   
 [47] "Extraventricular neurocytoma"                                    
 [48] "Fibromyxoid lesion"                                              
 [49] "Ganglioglioma"                                                   
 [50] "Ganglioneuroblastoma"                                            
 [51] "Ganglioneuroma"                                                  
 [52] "Germ Cell Tumor"                                                 
 [53] "Germinoma"                                                       
 [54] "Glial-neuronal tumor"                                            
 [55] "Glial-neuronal tumor NOS"                                        
 [56] "Glioblastoma Multiforme"                                         
 [57] "Gliomatosis Cerebri"                                             
 [58] "Head and Neck Squamous Cell Carcinoma"                           
 [59] "Hemangioblastoma"                                                
 [60] "Hepatoblastoma"                                                  
 [61] "Hepatocellular Carcinoma"                                        
 [62] "High-grade glioma"                                               
 [63] "High-grade glioma/astrocytoma"                                   
 [64] "Histiocytic tumor"                                               
 [65] "Hodgkin's lymphoma"                                              
 [66] "Infant-type hemispheric glioma"                                  
 [67] "Infantile Fibrosarcoma"                                          
 [68] "Inflammatory Myofibroblastic Tumor"                              
 [69] "Intrahepatic Cholangiocarcinoma"                                 
 [70] "Intraneural perineuroma"                                         
 [71] "Juvenile xanthogranuloma"                                        
 [72] "Langerhans Cell histiocytosis"                                   
 [73] "Low-grade glioma"                                                
 [74] "Low-grade glioma/astrocytoma"                                    
 [75] "Lung Adenocarcinoma"                                             
 [76] "Lung Squamous Cell Carcinoma"                                    
 [77] "Lymphoid Neoplasm Diffuse Large B-cell Lymphoma"                 
 [78] "Malignant peripheral nerve sheath tumor"                         
 [79] "Medulloblastoma"                                                 
 [80] "Melanocytic tumor"                                               
 [81] "Melanoma"                                                        
 [82] "Meningioma"                                                      
 [83] "Mesenchymal tumor"                                               
 [84] "Mesothelioma"                                                    
 [85] "Metastatic secondary tumors"                                     
 [86] "Mixed germ cell tumor"                                           
 [87] "Myeloid Neoplasm"                                                
 [88] "Neuroblastoma"                                                   
 [89] "Neurofibroma/Plexiform"                                          
 [90] "Non-germinomatous germ cell tumor"                               
 [91] "Non-Hodgkin Lymphoma"                                            
 [92] "Oligodendroglioma"                                               
 [93] "Osteosarcoma"                                                    
 [94] "Other"                                                           
 [95] "Ovarian Serous Cystadenocarcinoma"                               
 [96] "Pancreatic Adenocarcinoma"                                       
 [97] "Perineuroma"                                                     
 [98] "Pheochromocytoma and Paraganglioma"                              
 [99] "Pineal tumor"                                                    
[100] "Pineoblastoma"                                                   
[101] "Pineocytoma"                                                     
[102] "Pleomorphic xanthoastrocytoma"                                   
[103] "Primary CNS lymphoma"                                            
[104] "Primary mediastinal large B cell lymphoma"                       
[105] "Prostate Adenocarcinoma"                                         
[106] "Rectum Adenocarcinoma"                                           
[107] "Renal Clear Cell Carcinoma"                                      
[108] "Renal Papillary Cell Carcinoma"                                  
[109] "Retinoblastoma"                                                  
[110] "Rhabdoid tumor of the kidney"                                    
[111] "Rhabdomyosarcoma"                                                
[112] "Rosai-Dorfman disease"                                           
[113] "Rosette-forming glioneuronal tumor"                              
[114] "Sarcoma"                                                         
[115] "Schwannoma"                                                      
[116] "SEGA"                                                            
[117] "Stomach Adenocarcinoma"                                          
[118] "Subependymal Giant Cell Astrocytoma"                             
[119] "T Acute Lymphoblastic Leukemia/Lymphoma"                         
[120] "Teratoma"                                                        
[121] "Testicular Germ Cell Tumor"                                      
[122] "Thymoma"                                                         
[123] "Thyroid Carcinoma"                                               
[124] "Thyroid Gland Follicular Carcinoma"                              
[125] "Thyroid Gland Papillary Carcinoma"                               
[126] "Uterine Carcinosarcoma"                                          
[127] "Uterine Corpus Endometrial Carcinoma"                            
[128] "Uveal Melanoma"                                                  
[129] "Wilms tumor"                               
```

**Comment by ewafula** [comment]
@sangeetashukla,  here differences between your PR's EFO-MONDO results and the v12 histologies. 

```
# This cancer group are in your EFO-MOND results but not in v12 histologies
> setdiff(efo_mondo, hist)
[1] "Neuroepithelial neoplasm with EWSR1--PLAG1 fusion"

# This cancer groups are in v12 histologies but not in your EFO-MONDO results (ignore NA here)
> setdiff(hist, efo_mondo)
[1] NA                     "SEGA"                 "Glial-neuronal tumor"

Note: both "Glial-neuronal tumor NOS" and  "Glial-neuronal tumor", are in the histologies and only the former is in your  EFO-MONDO results.  
```

**Comment by chinwallaa** [comment]
@sangeetashukla waiting for these edits before doing the PR

**Comment by sangeetashukla** [comment]
Hi @ewafula Thanks for catching that.
I might have removed  "SEGA" and "Glial-neuronal tumor" from my branch's prefill list by mistake. I have added them again. 
And I have removed "Neuroepithelial neoplasm with EWSR1--PLAG1 fusion" from all downstream tables since it is not in v12 histologies.

As of now, below are the QC findings, which show no incompatibility. However, please note that for "SEGA" and "Glial-neuronal tumor", I was not able to find any matching codes, and therefore need expert input.


```
> prefill_cg <- readr::read_tsv("results/efo-mondo-map-prefill.tsv") %>%
+   dplyr::select(cancer_group)
> mapped_cg <- readr::read_tsv("results/efo-mondo-map.tsv") %>%
+   dplyr::select(cancer_group)
> length(hist_cg)
[1] 129
> length(prefill_cg$cancer_group)
[1] 129
> length(mapped_cg$cancer_group)
[1] 129
> setdiff(hist_cg, prefill_cg$cancer_group)
character(0)
> setdiff(prefill_cg$cancer_group, hist_cg)
character(0)
> setdiff(hist_cg, mapped_cg$cancer_group)
character(0)
> setdiff(mapped_cg$cancer_group, hist_cg)
character(0)
> setdiff(prefill_cg$cancer_group, mapped_cg$cancer_group)
character(0)
> setdiff(mapped_cg$cancer_group, prefill_cg$cancer_group)
character(0)
> setdiff(prefill_cg$cancer_group, integrate_prefill_cg$cancer_group)
character(0)
> setdiff(integrate_prefill_cg$cancer_group, prefill_cg$cancer_group)
character(0)
```

Note: `hist_cg` is the list of cancer_groups I copied from @ewafula 's comment

**Comment by sangeetashukla** [comment]
> @sangeetashukla waiting for these edits before doing the PR


@chinwallaa Here are the `cancer_group`s that I need help with finding codes:
Here the order for codes is EFO, MONDO, and NCIT. Just fyi, sometimes, EFO codes may start with MONDO prefix and vice versa. I can imagine it can get confusing.
```
Diffuse hemispheric glioma	NA	NA	NA
Epstein-Barr virus-related tumor	MONDO_0017342	MONDO_0017342	NA
Glial-neuronal tumor	NA	NA	NA
Perineuroma	NA	NA	NA
Pheochromocytoma and Paraganglioma	EFO_0020005	MONDO_0035540	NA
SEGA	NA	NA	NA
```

**Review by ewafula — APPROVED** [review]
@sangeetashukla, thank updating and making review changes. LGTM with the exception of a few missing codes for some cancer groups which will be addressed later. 

Approving!

**Comment by sangeetashukla** [comment]
@jharenza @chinwallaa @ewafula 
Final summary of changes that need reviewing before merging into dev:

As of now, the list of cancer_groups in the `results/efo-mondo-map.tsv` in this branch matches the v12 `histologies.tsv`. As per that list, below are the notes. 

`Diffuse hemispheric glioma NA NA NA` - No codes were found, and need to be added manually.

`Epstein-Barr virus-related tumor MONDO_0017342 MONDO_0017342 NA` - NCIT code is pending.

`Extraventricular neurocytoma EFO_1000856 MONDO_0016727 NCIT_C92555` - EFO code needs review.

`Glial-neuronal tumor	NA	NA	NA` - No codes were found, and need to be added manually.

`Mesenchymal tumor EFO_1000473 MONDO_0003512 NCIT_C7059` - needs review because description for each of the codes is not necessarily the same.

`Other EFO_0030051 GO_0051707 NCIT_C17649` - needs review since this is not specific at all.

`Perineuroma NA NA NA` - was added but is missing all codes, therefore needs review.

`Pheochromocytoma and Paraganglioma	EFO_0020005	MONDO_0035540	NA` - NCIT code is pending.

`SEGA	NA	NA	NA` - was added but is missing all codes, therefore needs review.

`High-grade glioma` and `Low-grade glioma` need additional review since `High-grade glioma/astrocytoma` and `Low-grade glioma/astrocytoma` are also included, although the codes are different.

`T Acute Lymphoblastic Leukemia/Lymphoma EFO_0000209 MONDO_0004963 NCIT_C3183 EFO_1001936 MONDO_0003537 NCIT_C8694` The codes need to be re-visited. Alternatives are suggested here based on the automated search results captured in `results/efo-mondo-map-prefill-auto.tsv`

`Uterine Corpus Endometrial Carcinoma EFO_0007532 MONDO_0000553 NCIT_C159413 EFO_1000238 MONDO_0000553 NCIT_C159413` - EFO code seems to have changed, needs review.

**Pull request merged**
