### PR TITLE
Change the output format in molecular-subtyping-HGG module

### PR DESCRIPTION
**Pull request by zzgeng**
#### What scientific question is your analysis addressing?
Change the format of HGG molecular subtype table. 

#### What was your approach?
In the previous version, the molecular subtype table contains three columns for Biospecimen ID, `Kids_First_Biospecimen_ID_RNA`, `Kids_First_Biospecimen_ID_DNA`, and `Kids_First_Biospecimen_ID_Methyl`. In this version, the molecular subtype table only contain one column `Kids_First_Biospecimen_ID`. 

#### Which areas should receive a particularly close look?
07-HGG-molecular-subtyping-combine-table.Rmd
results/HGG_molecular_subtype_tp53.tsv
results/HGG_molecular_subtype.tsv

#### Is there anything that you want to discuss further?
No

#### What types of results are included (e.g., table, figure)?
Table

#### What is your summary of the results?
Change the format of HGG molecular subtype table. 

#### Reproducibility Checklist

- [x] The dependencies required to run the code in this pull request have been added to the project Dockerfile.
- [x] This analysis has been added to continuous integration.

#### Documentation Checklist

- [x] This analysis module has a `README` and it is up to date.
- [x] This analysis is recorded in the table in `analyses/README.md` and the entry is up to date.
- [x] The analytical code is documented and contains comments.

### CODE REVIEW

**Comment by jharenza** [comment]
looks like you are getting an error here: 
```
                           
Quitting from lines 25-39 (10-HGG-TP53-annotation.Rmd) 
Error in `$<-`:
! Assigned data
  `as.character(hgg_subtypes$Kids_First_Biospecimen_ID_RNA)` must be compatible
  with existing data.
✖ Existing data has 1050 rows.
✖ Assigned data has 0 rows.
ℹ Only vectors of size 1 are recycled.
Caused by error in `vectbl_recycle_rhs_rows()`:
! Can't recycle input of size 0 to size 1050.
Backtrace:
 1. base::`$<-`(`*tmp*`, Kids_First_Biospecimen_ID_RNA, value = `<chr>`)
 2. tibble:::`$<-.tbl_df`(...)
 3. tibble:::tbl_subassign(...)
 4. tibble:::vectbl_recycle_rhs_rows(value, fast_nrow(xo), i_arg = NULL, value_arg, call)
  |...................................                 |  67% (unnamed-chunk-2)
```

**Comment by jharenza** [comment]
@zzgeng this will need another rerun since #450 was merged

**Comment by jharenza** [comment]
@zzgeng can you fix merge conflicts here please? Then @rjcorb can you review? Thanks!

**Review by rjcorb — APPROVED** [review]
Looks good to me!

**Pull request merged**
