### PR TITLE
Update ploidy for female Y chr >0 calls

### PR DESCRIPTION
**Pull request by sangeetashukla**
### Purpose/implementation Section
Updating the logic for ploidy when `chrom == "chrY" & germline_sex_estimate == "Female" & copy.num > 0` as discussed in [Issue 318](https://github.com/PediatricOpenTargets/ticket-tracker/issues/318)

#### What scientific question is your analysis addressing?
Refer to the issue linked above

#### What GitHub issue does your pull request address?
[Issue 318](https://github.com/PediatricOpenTargets/ticket-tracker/issues/318)

#### Reproducibility Checklist

- [ ] The dependencies required to run the code in this pull request have been added to the project Dockerfile.
- [ ] This analysis has been added to continuous integration.

#### Documentation Checklist

- [ ] This analysis module has a `README` and it is up to date.
- [ ] This analysis is recorded in the table in `analyses/README.md` and the entry is up to date.
- [ ] The analytical code is documented and contains comments.

### CODE REVIEW

**Review by jharenza — CHANGES_REQUESTED** [review]
@sangeetashukla can you run the entire module please

**Comment by jharenza** [comment]
closing this so it can be staggered on the PR for https://github.com/PediatricOpenTargets/ticket-tracker/issues/320

**Comment by sangeetashukla** [comment]
> @sangeetashukla can you run the entire module please

@jharenza I ran the entire module in the [new PR](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/pull/181) for [Issue 320](https://github.com/PediatricOpenTargets/ticket-tracker/issues/320), and I also created a [separate PR](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/pull/182) instead of this current one for [this issue 318](https://github.com/PediatricOpenTargets/ticket-tracker/issues/318)

**Comment by jharenza** [comment]
closed with https://github.com/PediatricOpenTargets/OpenPedCan-analysis/pull/248

**Pull request closed without merging**
