### PR TITLE
Analysis update: Add workflow for HGG molecular subtyping

### PR DESCRIPTION
**Pull request by zzgeng**
#### What scientific question is your analysis addressing?
Add workflow to illustrate the molecular subtyping of HGG

#### What was your approach?
Add workflow to illustrate the molecular subtyping of HGG

#### Which areas should receive a particularly close look?
Workflow image 

#### What types of results are included (e.g., table, figure)?
figure

#### Reproducibility Checklist

- [ ] The dependencies required to run the code in this pull request have been added to the project Dockerfile.
- [ ] This analysis has been added to continuous integration.

#### Documentation Checklist

- [ ] This analysis module has a `README` and it is up to date.
- [ ] This analysis is recorded in the table in `analyses/README.md` and the entry is up to date.
- [ ] The analytical code is documented and contains comments.

### CODE REVIEW

**Review by jharenza — COMMENTED** [review]
For the red path dx block, is it the case that all IHG are included in the HGG path dx now such that we do not pull them in separately? Possibly, we should add them to the free text block just as a check. Similarly, with PXA, we might want to have all of those come in via free text as well.

For the PXA, can you add the path free text requirement before the molecular alterations, and then for IHG with no fusion, also add the IHG, To be classified?

**Review by AntoniaChroni — APPROVED** [review]
It looks good overall. 

- You should align the first arrow form histologies to the red box, it falls inside the red box.
- Same comment about `IHG` as in the `HOPE png`
- First red box doesn't exist in the `HOPE png`
- Blue boxes are connected differently than in the `HOPE png`
- First red box to fix some syntax/commas:
1. `Brainstem glioma-Diffuse intrinsic pontine glioma`,
2. `Astrocytoma, and`
3. infant type hemispheric glioma (maybe capital first letter in `Infant` unless it doesn't show like that in the pathology diagnosis?) ~ same for the following plus adding `and` before the last histology on the list.
4. `Anaplastic gliomatosis cerebri (who grade 4), and`
5. `Astroblastoma`

**Review by jharenza — CHANGES_REQUESTED** [review]
One minor change request - can you add a `*` to each green box and then in the legend `*scores >= 0.80` and add this to every other workflow which is using methyl?

**Review by jharenza — COMMENTED** [review]
Can you also add here "DMG_EGFR" for methylation. 
I just noticed as well that the methylation subtypes are slightly off from the actual subtypes- can you use the exact subtypes in the methylation subclass column so there is no confusion?

**Review by jharenza — APPROVED** [review]
👍

**Comment by jharenza** [comment]
docs only, no need for GA

**Pull request merged**
