### PR TITLE
Compare RNA-Seq workflows

### PR DESCRIPTION
**Pull request by sangeetashukla**
### Purpose/implementation Section
This module uses gene expression data from different RNA-Seq workflows and compares the workflows by calculating the correlation coefficient, standard error, and probable error of the coefficient.

#### What scientific question is your analysis addressing?
The correlation coefficient and its standard and probable errors throw insight into whether the correlation is significant to allow underlying data to be used for any downstream analysis.

#### What was your approach?
Use `cor` library to calculate correlation coefficent, and then use below formula to calculate standard and probable error at gene level:

standard_error = (1 - (r^2))/number of samples/models per gene
probable_error = 0.6745*((1 - (r^2))/sqrt(number of samples/models per gene)

`0.6745` multiplier implies that the calculated error covers data under 95% of normal distribution

#### What GitHub issue does your pull request address?
[Issue 271](https://github.com/PediatricOpenTargets/ticket-tracker/issues/271)

### Directions for reviewers. Tell potential reviewers what kind of feedback you are soliciting.
Please review the formula for standard and probable errors of correlation coeffient.
This module does not include a result file at this time, since the input files need to be harmonized to ensure the same genes and sample_ids were processed in all workflows.

#### Which areas should receive a particularly close look?
The module currently only includes scripts and functions for comparison of the full gene set. However, once the final data is available, while the script in `utils` does not need to change, a new script to filter data to fit additional requirements described in the issue, will be added.

#### Is there anything that you want to discuss further?
No

#### Is the analysis in a mature enough form that the resulting figure(s) and/or table(s) are ready for review?
No

### Results
This PR is to have the functions in the module reviewed. The results will be added later.

#### What types of results are included (e.g., table, figure)?
None.

#### What is your summary of the results?
NA

#### Reproducibility Checklist

- [ ] The dependencies required to run the code in this pull request have been added to the project Dockerfile.
- [ ] This analysis has been added to continuous integration.

#### Documentation Checklist

- [x] This analysis module has a `README` and it is up to date.
- [ ] This analysis is recorded in the table in `analyses/README.md` and the entry is up to date.
- [x] The analytical code is documented and contains comments.

### CODE REVIEW

**Comment by ewafula** [comment]
@sangeetashukla,  Thank you for working on this module! I am summing this module is not ready for review yet. There are no results submitted with PR (even if preliminary, not too large for GitHub). I also don't see any usage of the `required options` in the script mentioned in the README.
```
Required flags:
  - First argument must be the path to the input expression .Rds file
  - `--scratch ../../scratch` provides path to scratch dir where intermediate files shared between steps can be read and written.
```
There are a few ideas I would like to suggest if possible:
1).  All gene expression matrices in OpenPedCan are normally RDS files and always reside in the data directory of the repo.  Maybe set code to work an OpenPedCan module that is able to access datasets either from data or analyses directory of the repo.  Something like this:
```
# establish base dir
root_dir <- rprojroot::find_root(rprojroot::has_dir(".git"))

# Set path to module and results directories
data_dir <- file.path(root_dir, "data") # for RDS expression matrices
module_dir <- file.path(root_dir, "analyses", "pipeline-comparison")
input_dir <- file.path(module_dir, "input")
results_dir <- file.path(module_dir, "results)

# Create results directory if it doesn't exist
if (!dir.exists(results_dir)) {
  dir.create(results_dir)
}
```
2).  The name `pipeline-comparison`  is ambiguous. Something more informative like `comparison-of_rnaseq-pipelines` or `comparison-of_rnaseq-worflows` 

3). After running the current PR, the results are missing the gene column to associate with the statistics. You could also consider filtering out `NAs` which are normally associated with either one or both variables being compared with the `cor()` function having an `std == 0`. Could also drop corresponding columns in both matrices if they can't be compared before calling `cor()` - `purrr::discard(~ all((is.numeric(.x) & sd(.x) == 0), na.rm = TRUE))` - to avoid `NAs`.   Maybe, it might not be necessary to get rid of `NAs` if the associated gene is also listed? 
```
# A tibble: 56,648 x 3
   coeff_KF_JAX stderr_coef proberr_coef
          <dbl>       <dbl>        <dbl>
 1     NA        NA           NA        
 2     -0.00422   1.00         0.674    
 3      0.898     0.194        0.131    
 4      0.990     0.0190       0.0128   
 5      0.999     0.00167      0.00113  
 6      1.00      0.0000206    0.0000139
 7      1.00      0.0000931    0.0000628
 8      1.00      0.000166     0.000112 
 9      0.999     0.00142      0.000957 
10      1.00      0.000566     0.000382 
# ... with 56,638 more rows
```
4) You are not really computing an all-against-all correlation between the two matrices, only corresponding variables (vectors). Therefoere, dataframes to matrix conversion is no really necessary.  Just as you have used the `sapply()` to compute `stderr_coef` and `proberr_coef`,  why not do the same with `coeff_KF_JAX` instead of the for loop  -  `sapply(1:ncol(matrix1), function(i) cor(matrix1[i,], matrix2[i,]))` - with `rbind()` or `row_bind()` depending on data object class type. 

@logstar can chime in

**Comment by jharenza** [comment]
@sangeetashukla does this one get closed in favor of #194 ?

**Comment by sangeetashukla** [comment]
> #194

Yes, that's the new PR.

**Comment by jharenza** [comment]
Ok then you can close this please

**Comment by sangeetashukla** [comment]
Closing this in favor of PR linked above.

**Pull request closed without merging**
