### PR TITLE
Update PedcBioPortal case set  ID  list

### PR DESCRIPTION
**Pull request by ewafula**
#### What scientific question is your analysis addressing?
Update PedcBioPortal case set  ID  list for `snv-frequencies` module

#### What was your approach?
Pull updated case set IDs in URLs from the PedcBioPortal

#### What GitHub issue does your pull request address?
https://github.com/PediatricOpenTargets/ticket-tracker/issues/230

#### Which areas should receive a particularly close look?
Confirm that the `input/ped_opentargets_2021_pedcbio_case_set_ids.json` `snv-frequencies` module file is updated.

#### Is there anything that you want to discuss further?
No

#### Is the analysis in a mature enough form that the resulting figure(s) and/or table(s) are ready for review?
Yes 

#### What types of results are included (e.g., table, figure)?
JSON

#### What is your summary of the results?
ped_opentargets_2021_pedcbio_case_set_ids.json

### CODE REVIEW

**Review by logstar — APPROVED** [review]
@ewafula - Thank you for preparing this PR.

The updated `input/ped_opentargets_2021_pedcbio_case_set_ids.json` file looks good to me. I downloaded the `case_set_ids` directly from pedcbio portal and got the same JSON file.

@jharenza - I was wondering if the `snv-frequencies` results shoud be updated for v10 data first, and then v11. This way, v10 `snv-frequencies` results with updated pedcbio plot URLs will be available for sharing.

The v10 `snv-frequencies` results update will need manual change of release version in `download-data.sh`, which can be noted in the README.md of v10 `snv-frequencies`.

**Comment by jharenza** [comment]
@logstar i need to confirm but it sounds like we will end up leaving the 404 for v 1.0 since FNL doesn't want to add any new updates before the beta release. Cc @chinwallaa - may have to confirm tomorrow. 

If we end up doing a v10 update on this, their links to our data release / repo will be a bit confusing, and we will have to figure out the best way to document / have them link.

**Comment by chinwallaa** [comment]
@logstar  - Do we have a sense of the fraction of the number of URLs/plots that will have 404 errors due to the missing cancer group wrt to using histology v7 vs v10?

**Comment by logstar** [comment]
> @logstar - Do we have a sense of the fraction of the number of URLs/plots that will have 404 errors due to the missing cancer group wrt to using histology v7 vs v10?

> @logstar i need to confirm but it sounds like we will end up leaving the 404 for v 1.0 since FNL doesn't want to add any new updates before the beta release. Cc @chinwallaa - may have to confirm tomorrow.
> 
> If we end up doing a v10 update on this, their links to our data release / repo will be a bit confusing, and we will have to figure out the best way to document / have them link.

@jharenza @chinwallaa - I do not know the fraction of the number of URLs/plots that will have 404 errors. I can write a ticket and look into that, which will probably take one or two days. Let me know if you think this will be worthwhile to look into.

I agree that the v10 update after v11 release will be confusing. If FNL is not taking new updates, it may not be necessary to update v10 JSONL files, as the links will be fixed in v11 JSONL files.

**Comment by chinwallaa** [comment]
>> can write a ticket and look into that, which will probably take one or two days. Let me know if you think this will be worthwhile to look into.
Since this will be fixed in v11, my vote is not to put to much time into the v10 fixes, as this was released with the expectation as an initial beta release.

**Comment by jharenza** [comment]
For now, will merge this and note we will _not_ rerun for v10.

**Pull request merged**
