### PR TITLE
Methylation arrays preprocessing module

### PR DESCRIPTION
**Pull request by ewafula**
#### What scientific question is your analysis addressing?
Process probe hybridization intensity values of selected methylated and unmethylated cytosine (CpG) loci into usable methylation measurements for the [Pediatric Open Targets, OPenPedCan-analysis](https://github.com/PediatricOpenTargets/OpenPedCan-analysis) raw DNA methylation array datasets.   

#### What was your approach?
Preprocesses raw Illumina Infinium HumanMethylation BeadArrays (27K,  450K, 850k) intensities using `minfi Bioconductor package` into usable methylation measurements (Beta and M values) for TARGET normal and tumor samples.

#### What GitHub issue does your pull request address?
- https://github.com/PediatricOpenTargets/ticket-tracker/issues/269

#### Which areas should receive a particularly close look?
Review the entire code and test run the module. Also, check the results produced by the module  for consistency 

#### Is there anything that you want to discuss further?
The module cannot be run in the OpenPedCan Docker image because it utilizes R version > 4.1. Please the module README for detailed instructions on how to run the module. 

#### Is the analysis in a mature enough form that the resulting figure(s) and/or table(s) are ready for review?
Yes.

#### What types of results are included (e.g., table, figure)?
TSV Tables and plots

#### What is your summary of the results?
- `results/Normal-beta-values-methylation.tsv.gz`
- `results/Normal-m-values-methylation.tsv.gz`
- `results/NBL-beta-values-methylation.tsv.gz`
- `results/NBL-m-values-methylation.tsv.gz`
- `results/OS-beta-values-methylation.tsv.gz`
- `results/OS-m-values-methylation.tsv.gz`
- `results/CCSK-beta-values-methylation.tsv.gz`
- `results/CCSK-m-values-methylation.tsv.gz`
- `results/WT-beta-values-methylation.tsv.gz`
- `results/WT-m-values-methylation.tsv.gz`
- `results/AML450k-beta-values-methylation.tsv.gz`
- `results/AML450k-m-values-methylation.tsv.gz`
- `results/AML27k-beta-values-methylation.tsv.gz`
- `results/AML27k-m-values-methylation.tsv.gz`
#### Reproducibility Checklist

- [x] The dependencies required to run the code in this pull request have been added to the project Dockerfile.
- [ ] This analysis has been added to continuous integration.

#### Documentation Checklist

- [x] This analysis module has a `README` and it is up to date.
- [ ] This analysis is recorded in the table in `analyses/README.md` and the entry is up to date.
- [x] The analytical code is documented and contains comments.

### CODE REVIEW

**Comment by ewafula** [comment]
@dmiller15 and @jharenza, the CAVATICA CWL methylation app code into this methylation-preprocessing PR

**Comment by afarrel** [comment]
Hi @ewafula,  reviewed and everything looks good.  reviewed the code (but did not run) and reviewed the results (including the summary results). They all look good. Just one very minor change. Please change the old isilon path in the readme to the new/current isilon path where the data is stored. Once that's done I will approve. Thanks.

**Comment by ewafula** [comment]
> Hi @ewafula, reviewed and everything looks good. reviewed the code (but did not run) and reviewed the results (including the summary results). They all look good. Just one very minor change. Please change the old isilon path in the readme to the new/current isilon path where the data is stored. Once that's done I will approve. Thanks.

@afarrel, README updated. Thank you for reviewing!

**Review by afarrel — APPROVED** [review]
Hi @ewafula, Thanks for working on this. I reviewed and everything looks good. I reviewed the code (but did not run) and I reviewed the results on isilon (including the summary results). They all look good. Thanks again!

**Pull request merged**
