### PR TITLE
Focal-CN Module: change each sample workflow back to group workflow

### PR DESCRIPTION
**Pull request by runjin326**
#### What scientific question is your analysis addressing?
If we run the code sample by sample, some samples with `ensembl` that doesn't match any key in`AnnotationDbi::mapIds` step will throw an error message.

#### What was your approach?
Instead of running the mapping per sample, run the mapping for all samples.

#### What GitHub issue does your pull request address?
https://github.com/PediatricOpenTargets/ticket-tracker/issues/159#issuecomment-899680644

#### Is there anything that you want to discuss further?
No.

#### Is the analysis in a mature enough form that the resulting figure(s) and/or table(s) are ready for review?
Yes

#### What types of results are included (e.g., table, figure)?
`consensus_seg_annotated_cn_[autosomes|x_any_y].tsv.gz` should be able to be generated.
**NOTE**: this PR is just a code modification and the actual running of the modules and results updates will be made by @zhangb1.

#### Reproducibility Checklist

- [x] The dependencies required to run the code in this pull request have been added to the project Dockerfile.
- [ ] This analysis has been added to continuous integration.

#### Documentation Checklist

- [x] This analysis module has a `README` and it is up to date.
- [ ] This analysis is recorded in the table in `analyses/README.md` and the entry is up to date.
- [x] The analytical code is documented and contains comments.

### CODE REVIEW

**Comment by jharenza** [comment]
I am going to assign @zhangb1 to review so he can run the code off of this branch and make sure it works before we merge it.

**Comment by zhangb1** [comment]
only got some warnings ,consensus results are generated : 

```
Welcome to Bioconductor

    Vignettes contain introductory material; view with
    'browseVignettes()'. To cite Bioconductor, see
    'citation("Biobase")', and for packages 'citation("pkgname")'.


'select()' returned 1:many mapping between keys and columns
'select()' returned 1:many mapping between keys and columns
'select()' returned 1:many mapping between keys and columns
'select()' returned 1:many mapping between keys and columns
```

the results are here, I will approve the PR for now.

[consensus_seg_annotated_cn_autosomes.tsv.gz](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/files/6994457/consensus_seg_annotated_cn_autosomes.tsv.gz)
[consensus_seg_annotated_cn_x_and_y.tsv.gz](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/files/6994461/consensus_seg_annotated_cn_x_and_y.tsv.gz)

**Review by zhangb1 — APPROVED** [review]

**Comment by jharenza** [comment]
ok great, @runjin326 feel free to merge

**Comment by runjin326** [comment]
> ok great, @runjin326 feel free to merge
@jharenza, I don't think I am authorized to merge yet. Could you please authorize me?

**Pull request merged**
