### PR TITLE
Independent Samples Re-Run

### PR DESCRIPTION
**Pull request by runjin326**
#### What scientific question is your analysis addressing?
Re-generate independent sample lists with v10 histologies file for data release.

#### What was your approach?
Re-run module with v10 histologies.

#### What GitHub issue does your pull request address?
https://github.com/PediatricOpenTargets/ticket-tracker/issues/215

#### Which areas should receive a particularly close look?
No. 

#### Is there anything that you want to discuss further?
No.

#### Is the analysis in a mature enough form that the resulting figure(s) and/or table(s) are ready for review?
Yes. 

#### What types of results are included (e.g., table, figure)?
Independent sample lists:
```
   11631 independent-specimens.rnaseq.primary-plus.eachcohort.tsv
   11604 independent-specimens.rnaseq.primary-plus.tsv
   11037 independent-specimens.rnaseq.primary.eachcohort.tsv
   11022 independent-specimens.rnaseq.primary.tsv
     370 independent-specimens.rnaseq.relapse.eachcohort.tsv
     367 independent-specimens.rnaseq.relapse.tsv
    1160 independent-specimens.wgs.primary-plus.eachcohort.tsv
    1152 independent-specimens.wgs.primary-plus.tsv
    1028 independent-specimens.wgs.primary.eachcohort.tsv
    1024 independent-specimens.wgs.primary.tsv
     172 independent-specimens.wgs.relapse.eachcohort.tsv
     168 independent-specimens.wgs.relapse.tsv
    2714 independent-specimens.wgswxspanel.primary-plus.eachcohort.prefer.wxs.tsv
    2714 independent-specimens.wgswxspanel.primary-plus.eachcohort.tsv
    2613 independent-specimens.wgswxspanel.primary-plus.prefer.wxs.tsv
    2613 independent-specimens.wgswxspanel.primary-plus.tsv
    2565 independent-specimens.wgswxspanel.primary.eachcohort.prefer.wxs.tsv
    2565 independent-specimens.wgswxspanel.primary.eachcohort.tsv
    2464 independent-specimens.wgswxspanel.primary.prefer.wxs.tsv
    2464 independent-specimens.wgswxspanel.primary.tsv
     204 independent-specimens.wgswxspanel.relapse.eachcohort.prefer.wxs.tsv
     204 independent-specimens.wgswxspanel.relapse.eachcohort.tsv
     204 independent-specimens.wgswxspanel.relapse.prefer.wxs.tsv
     204 independent-specimens.wgswxspanel.relapse.tsv
```

#### What is your summary of the results?
All the changes are expected:
- Compared to previous results, all lists of relapse DNA sample remained the same 
    - expected since all additional samples are primary
- An additional of 465 DNA samples were added to the primary all panels sample - 42 from PBTA and 423 from TARGET
    1) All 40 new DNA WGS from pnoc_dataset_2 were present in the `independent-specimens.wgswxspanel.primary.tsv` file 
    2) Out of the 24 new DNA WGS from pnoc_dataset_1, 22 of them belong to `Kids_First_Participant_ID` that is already present in the old histology file - hence we only expect 2 more in the new list 
    3) 40 new DNA WGS from pnoc_dataset_2 + 2 from pnoc_dataset_1, an additional of 42 PBTA are present in the new list, which is identical to what we have. 
    4) For 423 TARGET, this number is also expected since out of the 438 additional ALL WXS TARGET, we have 15 of them have `Peripheral Whole Blood` as composition 
- The additional 40 RNA samples from pnoc_dataset_2 were also confirmed to be in the RNA independent list.

#### Reproducibility Checklist

- [x] The dependencies required to run the code in this pull request have been added to the project Dockerfile.
- [ ] This analysis has been added to continuous integration.

#### Documentation Checklist

- [x] This analysis module has a `README` and it is up to date.
- [ ] This analysis is recorded in the table in `analyses/README.md` and the entry is up to date.
- [x] The analytical code is documented and contains comments.

### CODE REVIEW

**Comment by logstar** [comment]
@runjin326 Where could I get v10 histologies.tsv? I am planning to rerun this module with the v10 histologies.tsv.

I found the following two v10 histologies files, but they seem to be the same as v9:

- <http://s3.amazonaws.com/d3b-openaccess-us-east-1-prd-pbta/open-targets/v10/histologies.tsv>
- <https://github.com/ewafula/D3b-codes/blob/7a340cdd8ee4f3eeb4ac84709c2e77d74e7d9f71/v10-OpenPedCan/v10/histologies.tsv>

**Comment by logstar** [comment]
> @runjin326 Where could I get v10 histologies.tsv? I am planning to rerun this module with the v10 histologies.tsv.
> 
> I found the following two v10 histologies files, but they seem to be the same as v9:
> 
> * http://s3.amazonaws.com/d3b-openaccess-us-east-1-prd-pbta/open-targets/v10/histologies.tsv
> * https://github.com/ewafula/D3b-codes/blob/7a340cdd8ee4f3eeb4ac84709c2e77d74e7d9f71/v10-OpenPedCan/v10/histologies.tsv

@runjin326 Sorry. <https://github.com/ewafula/D3b-codes/blob/7a340cdd8ee4f3eeb4ac84709c2e77d74e7d9f71/v10-OpenPedCan/v10/histologies.tsv> is actually different from v9.

I used <https://github.com/ewafula/D3b-codes/blob/7a340cdd8ee4f3eeb4ac84709c2e77d74e7d9f71/v10-OpenPedCan/v10/histologies.tsv> to rerun this module using docker, but the result TSV files are different from the ones in the PR.

**Review by logstar — APPROVED** [review]
The code changes look good to me.

I reran `run-independent-samples.sh` with up-to-date `histologies.tsv` shared by @runjin326 , and all result TSV files are reproduced identically.

**Comment by runjin326** [comment]
@logstar, thanks so much for reviewing this! I will do a dev merge and merge this branch soon!

**Pull request merged**
