### PR TITLE
Update fusion frequencies module

### PR DESCRIPTION
**Pull request by ewafula**
#### What scientific question is your analysis addressing?
- Modify `fusion-frequencies` module to exclude TCGA samples in computing mutation frequencies to avoid including `All Cohort` frequencies in single cohort diseases
- utilized the v10 `histologies.txt` files  updated to replace `Metastatic secondary tumors;Neuroblastoma` in the `cancer_group` column to `Neuroblastoma`
- Rename fusion frequencies table headers 

#### What was your approach?
Filtered out TCGA samples present in the input data files 

#### What GitHub issue does your pull request address?
- https://github.com/PediatricOpenTargets/ticket-tracker/issues/238
- https://github.com/PediatricOpenTargets/ticket-tracker/issues/235
- https://github.com/PediatricOpenTargets/ticket-tracker/issues/252

#### Which areas should receive a particularly close look?
Check to confirm input file tibbles are filtered to exclude TCGA samples before compting mutation frequencies

#### Is there anything that you want to discuss further?
No

#### Is the analysis in a mature enough form that the resulting figure(s) and/or table(s) are ready for review?
Yes

#### What types of results are included (e.g., table, figure)?
TSV and JSONL tables

#### What is your summary of the results?
- results/putative-oncogene-fused-gene-freq.jsonl.gz
- results/putative-oncogene-fused-gene-freq.tsv.gz
- results/putative-oncogene-fusion-freq.jsonl.gz
- results/putative-oncogene-fusion-freq.tsv.gz

#### Reproducibility Checklist

- [x] The dependencies required to run the code in this pull request have been added to the project Dockerfile.
- [ ] This analysis has been added to continuous integration.

#### Documentation Checklist

- [x] This analysis module has a `README` and it is up to date.
- [ ] This analysis is recorded in the table in `analyses/README.md` and the entry is up to date.
- [x] The analytical code is documented and contains comments.

### CODE REVIEW

**Comment by ewafula** [comment]
Sure, @runjin326. Makes sense. Had just filtered out all TCGA sample from
the both the histologies file and the rnaseq independent sample input
files.

Do we not want to keep all other samples and exclude TCGA?  Isn’t your example
doing the opposite?

**Comment by runjin326** [comment]
> Sure, @runjin326. Makes sense. Had just filtered out all TCGA sample from the both the histologies file and the rnaseq independent sample input files. Do we not want to keep all other samples and exclude TCGA? Isn’t your example doing the opposite?
> […](#)

Yes good catch - should be 
```
primary_indp_sdf_all <- primary_indp_sdf_all %>%
filter(!Kids_First_Biospecimen_ID %in% tcga_bs_id)
```

**Comment by ewafula** [comment]
@runjin326 implemented your approach above. But the histologies file still needs to be filtered to exclude TCGA samples as well because there is where `each` and `all cohorts` labels are determined. Otherwise, the `all cohorts for other `cancer_groups` beyond `Neuroblastoma` will still persist in the result tables.
```
# filter TCGA samples out of the histologies df
htl_df <- htl_df %>%  
  filter(!Kids_First_Biospecimen_ID %in% tcga_bs_id)
```

**Review by runjin326 — APPROVED** [review]
@ewafula, thanks so much for making the update! The output contains the table headers that we are expecting - I think we can merge this with the above changes (TCGA samples taken out + header change) and once we have new data release in v11, we re-run and merge again to avoid having too many changes in one PR. 
Can you confirm this branch already have the most up-to-date dev (I did see that you already merged but just want to double check)? If so, I will merge.

**Comment by ewafula** [comment]
> @ewafula, thanks so much for making the update! The output contains the table headers that we are expecting - I think we can merge this with the above changes (TCGA samples taken out + header change) and once we have new data release in v11, we re-run and merge again to avoid having too many changes in one PR. Can you confirm this branch already have the most up-to-date dev (I did see that you already merged but just want to double check)? If so, I will merge.

@runjin326, I have checked.  It is up to date with the dev. The submitted SNV and CNV PRs are also up to date with dev.

**Pull request merged**
