### PR TITLE
Step 1 of DGE analysis of matched polya and stranded samples

### PR DESCRIPTION
**Pull request by logstar**
This is the first one of the four pull requests for creating the PediatricOpenTargets/OpenPBTA-analysis/analysis/rna-seq-protocol-dge analysis module. These four pull requests correspond to the following four analysis steps:

1. Collapse `pbta-gene-counts-rsem-expected_count` matrices of stranded and poly-A libraries using the OpenPBTA-analysis/analyses/collapse-rnaseq analysis module.
2. Generate a HTML report of the collapsed genes using the OpenPBTA-analysis/analyses/collapse-rnaseq analysis module.
3. Run edgeR `exactTest`, `glmLRT`, and `glmQLFTest` comparing stranded and poly-A RNA-seq `rsem-expected_count`s, using an adapted workflow from the [OMPARE project](https://github.com/d3b-center/OMPARE/blob/master/code/patient_level_analyses/utils/rnaseq_edger_normalizations.R#L37-L41).
4. Select genes that are stably expressed in poly-A and stranded RNA-seq libraries.

The overall purposes of the PediatricOpenTargets/OpenPBTA-analysis/analysis/rna-seq-protocol-dge module are:

> - Check if the DGE analysis between polya and stranded data follow a null-p-value distribution.
> - Determine stably expressed transcripts between polyA and stranded samples.

### Purpose

Collapse `pbta-gene-counts-rsem-expected_count` matrices of stranded and poly-A libraries using the OpenPBTA-analysis/analyses/collapse-rnaseq module.

The collapsed `pbta-gene-counts-rsem-expected_count` matrices will be used for the following analysis steps:

> - Check if the DGE analysis between polya and stranded data follow a null-p-value distribution.
> - Determine stably expressed transcripts between polyA and stranded samples.

#### What was your approach?

Use the `OpenPBTA-analysis/analyses/collapse-rnaseq/01-summarize_matrices.R` by changing the input and out filenames in `run-rna-seq-protocol-dge.sh` line 26-30 (pasted below).

```bash
  Rscript --vanilla 01-summarize_matrices.R \
    -i ../../data/pbta-gene-counts-rsem-expected_count.${strategy}.rds \
    -g ../../data/gencode.v27.primary_assembly.annotation.gtf.gz \
    -m results/pbta-gene-counts-rsem-expected_count-collapsed.${strategy}.rds \
    -t results/pbta-gene-counts-rsem-expected_count-collapsed_table.${strategy}.rds
```

#### What GitHub issue does your pull request address?

<https://github.com/PediatricOpenTargets/ticket-tracker/issues/17>

#### Which areas should receive a particularly close look?

Can `01-summarize_matrices.R`, which is copied from the OpenPBTA-analysis/analyses/collapse-rnaseq module, be directly applied to `pbta-gene-counts-rsem-expected_count.polya.rds` and `pbta-gene-counts-rsem-expected_count.stranded.rds` as in the line 22-32 of `run-rna-seq-protocol-dge.sh` (pasted below)?

```bash
# generate collapsed matrices for poly-A and stranded datasets
libraryStrategies=("polya" "stranded")
for strategy in ${libraryStrategies[@]}; do

  Rscript --vanilla 01-summarize_matrices.R \
    -i ../../data/pbta-gene-counts-rsem-expected_count.${strategy}.rds \
    -g ../../data/gencode.v27.primary_assembly.annotation.gtf.gz \
    -m results/pbta-gene-counts-rsem-expected_count-collapsed.${strategy}.rds \
    -t results/pbta-gene-counts-rsem-expected_count-collapsed_table.${strategy}.rds

done
```

#### Is there anything that you want to discuss further?

How to add `pbta-gene-counts-rsem-expected_count.polya.rds` and `pbta-gene-counts-rsem-expected_count.stranded.rds` in future PediatricOpenTargets/OpenPBTA-analysis data releases?

The added results were generated using [AlexsLemonade/OpenPBTA-analysis](https://github.com/AlexsLemonade/OpenPBTA-analysis) release-v19-20210423. The release data were downloaded by changing the `URL`, `RELEASE` and `PREVIOUS` variables in `download-data.sh` to:

```bash
URL=${OPENPBTA_URL:-https://s3.amazonaws.com/kf-openaccess-us-east-1-prd-pbta/data}
RELEASE=${OPENPBTA_RELEASE:-release-v19-20210423}
PREVIOUS=${OPENPBTA_RELEASE:-release-v18-20201123}
```

The [PediatricOpenTargets/OpenPBTA-analysis](https://github.com/PediatricOpenTargets/OpenPBTA-analysis) project has a separate data release, so the `download-data.sh` currently has the following variables:

```bash
URL=${OPENPBTA_URL:-https://s3.amazonaws.com/kf-openaccess-us-east-1-prd-pbta/open-targets}
RELEASE=${OPENPBTA_RELEASE:-v2}
PREVIOUS=${OPENPBTA_RELEASE:-v1}
```

The [PediatricOpenTargets/OpenPBTA-analysis](https://github.com/PediatricOpenTargets/OpenPBTA-analysis) release v2 currently does not have `pbta-gene-counts-rsem-expected_count.polya.rds` or `pbta-gene-counts-rsem-expected_count.stranded.rds`.

#### Is the analysis in a mature enough form that the resulting figure(s) and/or table(s) are ready for review?

Yes.

#### What types of results are included (e.g., table, figure)?

- `results/pbta-gene-counts-rsem-expected_count-collapsed_table.polya.rds`: summary table of the collapsed genes in `../../data/pbta-gene-counts-rsem-expected_count.polya.rds`, generated  by `01-summarize_matrices.R`.
- `results/pbta-gene-counts-rsem-expected_count-collapsed_table.stranded.rds`: summary table of the collapsed genes in `../../data/pbta-gene-counts-rsem-expected_count.stranded.rds`, generated  by `01-summarize_matrices.R`.

#### Documentation Checklist

- [x] This analysis module has a `README` and it is up to date.
- [x] The analytical code is documented and contains comments.

### CODE REVIEW

**Review by jharenza — CHANGES_REQUESTED** [review]
Hi @logstar ! Thanks for this first PR! Before delving into the code, I have a few comments about the data and structuring the folders.

>Can 01-summarize_matrices.R, which is copied from the OpenPBTA-analysis/analyses/collapse-rnaseq module, be directly applied to pbta-gene-counts-rsem-expected_count.polya.rds and pbta-gene-counts-rsem-expected_count.stranded.rds as in the line 22-32 of run-rna-seq-protocol-dge.sh (pasted below)?

Ahh, nice catch/good point - we hadn't used collapsed counts in OpenPBTA, but we should create this collapsed matrix here. Yes, this can be applied. However, will you use this PR to update the code in collapse-rnaseq within the OT/OpenPBTA repo such that your resulting files will end up [here](https://github.com/PediatricOpenTargets/OpenPBTA-analysis/tree/dev/analyses/collapse-rnaseq/results)? instead of within your dge module?

>How to add pbta-gene-counts-rsem-expected_count.polya.rds and pbta-gene-counts-rsem-expected_count.stranded.rds in future PediatricOpenTargets/OpenPBTA-analysis data releases?

We are still trying to determine how best to do this and open to suggestions. That being said, pulling them locally for now may be OK. Another option is to include direct s3 download links in a first script. 

In thinking about this analysis a bit, I also think that perhaps we should merge the polyA and stranded raw counts (as there will be differences that may not be captured if the genes differ in the collapsed files). We may also think about doing this ahead of, and releasing the file this way cc @yuankunzhu and @kgaonkar6 for thoughts on that.

**Comment by logstar** [comment]
@jharenza Thank you for the detailed comment.

I will update the OT/OpenPBTA/analysis/collapse-rnaseq module, so that the resulting files will be located in the collapse-rnaseq module, when we have a working protocol for new data release. I expect that I would need to make the following changes:

1. Update OT/OpenPBTA/analysis/collapse-rnaseq module to collapse `pbta-gene-counts-rsem-expected_count.polya.rds` and `pbta-gene-counts-rsem-expected_count.stranded.rds`.
2. Put the collapsed `pbta-gene-counts-rsem-expected_count.polya.rds` or `pbta-gene-counts-rsem-expected_count.stranded.rds` to the next data release.
3. Remove the collapsing procedure in the dge module.

I put the collapsing procedure within the dge module, mainly because I would be able to complete this analysis module without any data release protocol.

If I understand correctly that we should merge polyA and stranded raw counts, we are expecting to run DGE analysis on the raw counts without collapsing genes. The raw counts are not the RSEM expected counts. I may be confused because I have not looked into how the RNA-seq read count matrices were generated yet, but I will look further into it.

**Comment by jharenza** [comment]
>I put the collapsing procedure within the dge module, mainly because I would be able to complete this analysis module without any data release protocol.

Thanks for this - after discussing with @yuankunzhu, we have decided to add full matrices for the rna-seq data, so we would plan for this to come via release before this would be merged. Sorry!

>If I understand correctly that we should merge polyA and stranded raw counts, we are expecting to run DGE analysis on the raw counts without collapsing genes. 

No, I meant that we would merge polyA and stranded counts prior to collapsing, then use collapsed counts in DGE.

>The raw counts are not the RSEM expected counts.

They are.

**Comment by logstar** [comment]
@jharenza Thank you for the detailed reply.

I will track the OT/OpenPBTA data release status and make the following updates in a timely manner.

- When `pbta-gene-counts-rsem-expected_count.polya.rds` and `pbta-gene-counts-rsem-expected_count.stranded.rds` are available, I will update the OT/OpenPBTA/analysis/collapse-rnaseq module to collapse them, so the collapsed `rsem-expected_count` matrices will end up in the OT/OpenPBTA/analysis/collapse-rnaseq module.
- Then, I will somehow make a request to put the collapsed `rsem-expected_count` matrices into the next release.
- When the collapsed `rsem-expected_count` matrices are available, I will update the dge module to remove the collapsing procedure.
- I will close the [step 1](https://github.com/PediatricOpenTargets/OpenPBTA-analysis/pull/8) and [step 2](https://github.com/PediatricOpenTargets/OpenPBTA-analysis/pull/9) pull requests, as they are opened to add the collapsing procedure.
- I will update the [step 3](https://github.com/PediatricOpenTargets/OpenPBTA-analysis/pull/10) and [step 4](https://github.com/PediatricOpenTargets/OpenPBTA-analysis/pull/11) pull requests to remove the collapsing procedure.

Regarding the merge -> collapse -> DGE analysis, I will follow-up if there is any further updates on the discussion.

**Comment by kgaonkar6** [comment]
> * I will close the [step 1](https://github.com/PediatricOpenTargets/OpenPBTA-analysis/pull/8) and [step 2](https://github.com/PediatricOpenTargets/OpenPBTA-analysis/pull/9) pull requests, as they are opened to add the collapsing procedure.

Just dropping by here to confirm if we need to close this PR and #9 as mentioned in the comment above?

**Comment by logstar** [comment]
@kgaonkar6 Thank you for the follow-up. I will close step 1 and step 2 PRs.

**Pull request closed without merging**
