### PR TITLE
fusion_filtering module changes

### PR DESCRIPTION
**Pull request by runjin326**
#### What scientific question is your analysis addressing?

Re-run the fusion filtering module with the new histologies file to include cohort CBTN, GMKF and PNOC

#### What was your approach?
Modify relevant codes to allow cohort matching + group by cancer_group instead of broad_histology when needed

#### What GitHub issue does your pull request address?
https://github.com/PediatricOpenTargets/ticket-tracker/issues/7

### Directions for reviewers. Tell potential reviewers what kind of feedback you are soliciting.
Please double check all the changes and make sense that it makes sense.

#### Which areas should receive a particularly close look?
1) Please check out 00 - which is a new R code to generate normal expression data based on the new `gene-expression-rsem-tpm-collapsed.rds` we got
2) In code 03 - L150-178 - a new trunk of code to slice data frame is added to solve memory issues

#### Is there anything that you want to discuss further?
1) For now, I am using the older version of `independent-specimens.wgswxs.primary-plus.tsv` so it did not include "Bone Marrow" and it did not have specimens that are released in `histologies.tsv` v5 - we an re-run this later
2) For 06, I already added "Bone Marrow" for the filtering so we don't need to modify that 
3) Since there are many cancer groups, for recurrent fusion per cancer group, we use >3, and that results in only a couple recurrent fusions - most of them have 1-2 fusions.

#### Is the analysis in a mature enough form that the resulting figure(s) and/or table(s) are ready for review?
Yes

### Results
Please see ./results folder 
- files in `../../scratch` will be uploaded later

#### What types of results are included (e.g., table, figure)?
Table

#### Reproducibility Checklist

- [ ] The dependencies required to run the code in this pull request have been added to the project Dockerfile.
- [ ] This analysis has been added to continuous integration.

#### Documentation Checklist

- [x] This analysis module has a `README` and it is up to date.
- [ ] This analysis is recorded in the table in `analyses/README.md` and the entry is up to date.
- [x] The analytical code is documented and contains comments.

### CODE REVIEW

**Comment by jharenza** [comment]
hi @runjin326! I forgot to update this ticket, but can you make CBTN and PNOC into `PBTA` cohort? Thanks!

**Comment by runjin326** [comment]
@jharenza Sure I will do that! I am about to update the analyses using the most up-to-date independent sample list as well

**Review by jharenza — CHANGES_REQUESTED** [review]
hey @runjin326 ! thanks for working on this - can you do me a favor and split this up into multiple staggered PRs, starting with the updates you do to the scripts in order of updates, which will make this easier to review? There are too many changes right now to review easily. I am seeing that results files are missing many cancer groups but I expect the changes here to be additional rows added to the original files, corresponding to Neuroblastoma. PBTA, should for the most part, remain in tact. Thanks!

**Comment by runjin326** [comment]
@jharenza sure! I will work on submitting staggered PRs!

**Comment by kgaonkar6** [comment]
Can we close this since you are putting in staggered PRs now?

**Comment by runjin326** [comment]
Yes closing it now!

**Pull request closed without merging**
