### PR TITLE
Analysis update: Add EPN workflow to README

### PR DESCRIPTION
**Pull request by zzgeng**
#### What scientific question is your analysis addressing?
Add EPN workflow to README

#### What was your approach?
Add EPN workflow to README

#### Which areas should receive a particularly close look?
EPN workflow 

#### Is the analysis in a mature enough form that the resulting figure(s) and/or table(s) are ready for review?
Yes

#### Reproducibility Checklist

- [ ] The dependencies required to run the code in this pull request have been added to the project Dockerfile.
- [ ] This analysis has been added to continuous integration.

#### Documentation Checklist

- [ ] This analysis module has a `README` and it is up to date.
- [ ] This analysis is recorded in the table in `analyses/README.md` and the entry is up to date.
- [ ] The analytical code is documented and contains comments.

### CODE REVIEW

**Review by rjcorb — CHANGES_REQUESTED** [review]
There seem to be a few discrepancies between the flow diagram here and the `03-summary.Rmd` where EPN samples are subtyped. I think they may be issues related to the script rather than the flow diagram. These are as follows:

- The flow diagram describes assignment of EPN samples to subtype `EPN, SP` but there is actually no code for this in `03_summary.Rmd`. There is code for assignment to `EPN, SP-MYCN`, but not `EPN, SP`:

```{r}
EPN_final <- EPN_final %>%
  mutate(molecular_subtype = ifelse(disease_group == "spinal" & grepl("amplification", consensus_focal_CN_MYCN), "EPN, SP-MYCN", molecular_subtype))
sp_mycn_samples_assigned <- EPN_final %>%
  filter(molecular_subtype == "EPN, SP-MYCN") %>%
  pull(id) %>%
  unique()
print(paste("Number of samples assigned for SP-MYCN:", length(sp_mycn_samples_assigned)))
```

so I think this needs to be changed in the script rather than in the diagram. 

- In the `03_summary.Rmd` script, it looks like for samples that do not get assigned a subtype by the strategies in this flow diagram, they are assigned based on methyl subtype. For example, `EPN, MPE` is reported as a molecular subtype in `EPN_molecular_subtypes.tsv`, but this is not included in the flow diagram. I'm not sure if this is something that has to be changed in the script or the flow diagram.

I think the middle section of this flow diagram aligns exactly with the subtyping script strategies, but the spinal and methyl subtype inconsistencies need to be resolved.

**Review by AntoniaChroni — APPROVED** [review]
The summary in this `README` file was a bit confusing when trying to link it to the generated figure. But it looks good to me overall.

- Do you know why `EPN, PF SE (methylation classificaton)` and `EPN, SP-SE (methylation classificaton)` as recorded on the `EPN_all_data.tsv` weren't used for the EPN classification?
- There are some additional gene expression, SNV, and CNV values not used for the figure. I understand that the scope of the figure is only for reporting the use of various data sources and confident data that allow for identification of mol. subtype rather than including other potential, e.g. variants associated with that subtype. I just wanted to point this out as this would be additional information that the user will have to be aware and have to search for.

**Comment by zzgeng** [comment]
Thank you for your advice! @rjcorb @AntoniaChroni 
This module is a little bit complicated. For `EPN, SP`, we used to have code for this subtype and later it was removed.  Now all the samples with EPN, SP are based on the methylation subtype. I created a ticket for this issue and will look into it after release. I updated the figure based on this. Please take a look and let me know if any update is needed.

**Review by jharenza — CHANGES_REQUESTED** [review]
Can you annotated the molecular subtype scores here as well?

For the box that says "samples with high conf methylation" - I think that can be removed and added as a box for each subtype because it is a bit confusing having it both ways

**Review by rjcorb — APPROVED** [review]
This is looking good! See minor comments below. I am approving and don't need to review again. 

- For EPN, SP-MYCN: it's somewhat unclear how these criteria should be grouped here. some might read this as spinal disease group being required, as well as  one of the two other criteria. Is there a way to illustrate this as `Disease group is "spinal" AND MYCN amplification` OR `Methylation classification is "EPN, SP-MYCN"`? 
- There is a typo in the box `Methylation classification is "EPM, SP-SE" *`
- Very minor, but "chr" is capitalized in one box and not in the other

**Review by jharenza — APPROVED** [review]

**Comment by jharenza** [comment]
docs only, no need for GA

**Pull request merged**
