### PR TITLE
v12 snv-frequencies

### PR DESCRIPTION
**Pull request by kelseykeith**
#### What scientific question is your analysis addressing?

Needed to rerun the `snv-frequencies` module with the v12 data and update the variant level tables to include the Human Genome Variation Society genomic variant ids (`HGVSg` column in SNV mafs) and to switch the `datatypeId` colum to `pediatric_cancer`.

#### What was your approach?

Minimal code changes to include an HGVSg column in the variant level results and to address an error (more below) found when rerunning the module.

#### What GitHub issue does your pull request address?

- [Ticket #331](https://github.com/PediatricOpenTargets/ticket-tracker/issues/315) update snv-frequencies tables for v12
- [Ticket #529](https://github.com/PediatricOpenTargets/ticket-tracker/issues/529) Updated analysis: `snv-frequencies` to add HGVS

#### Which areas should receive a particularly close look?

The module assumes that for each gene ensembl ID one ensembl ID will map to one gene name/HUGO symbol, but because of the update to gencode v39, there are some ensembl IDs that map to multiple ensembl transcript IDs in the MAF `Hugo_Symbol` column. This effects only two genes in v12. Both genes are in the `mtp-annotations` module `mtp-targets-mapping.tsv.gz` file so as discussed with @ewafula, I retained the genes rather than removing them. To handle the error for this pre-release table run, I added code to arbitrarily pick the transcript, but we may want to reconsider this handling method in the future, even as soon as the module rerun with the updated v12 PedcBio links. The two affected genes are listed in the table below.

| cohort | cancer_group | Gene | Hugo_Symbol |
| --- | --- | --- | --- |
| Diffuse midline glioma | PBTA | ENSG00000254519 | ENST00000529769 |
| Diffuse midline glioma | PBTA | ENSG00000254519 | ENST00000635559 |
| Medulloblastoma | PBTA | ENSG00000230153 | ENST00000424539 |
| Medulloblastoma | PBTA | ENSG00000230153 | ENST00000437772 |

#### Is there anything that you want to discuss further?

- PedcBio portal has not been updated with the v12 data yet, so the v11 links are still present in the code and results.
- Also, there are some duplicate gene names in the gene level results due to multiple ensembl ids for the same gene name, but from what I can tell this should be resolved later when filtering with the `mtp-annotations` tables.

#### Is the analysis in a mature enough form that the resulting figure(s) and/or table(s) are ready for review?

yes

#### What types of results are included (e.g., table, figure)?

Tab-delimited and JSONL tables

#### What is your summary of the results?

- `results/variant-level-snv-consensus-annotated-mut-freq.jsonl.gz`
- `results/variant-level-snv-consensus-annotated-mut-freq.tsv.gz`
- `results/gene-level-snv-consensus-annotated-mut-freq.jsonl.gz`
- `results/gene-level-snv-consensus-annotated-mut-freq.tsv.gz`

#### Documentation Checklist

- [x] This analysis module has a `README` and it is up to date.
- [x] This analysis is recorded in the table in `analyses/README.md` and the entry is up to date.
- [x] The analytical code is documented and contains comments.

### CODE REVIEW

**Review by zzgeng — APPROVED** [review]
Looking good to me! New column `HGVSg` is added into variant-level results and datatypeID has been changed to `pediatric_cancer`.

**Review by ewafula — APPROVED** [review]
@kelseykeith,  thanks for updating.  Looks good to me as per the update tickets.

**Comment by ewafula** [comment]
@kelseykeith,  these weird IDs (1,224 unique) in the  `gene-level-snv-consensus-annotated-mut-freq.tsv.gz` and `variant-level-snv-consensus-annotated-mut-freq.tsv.gz`  v12 SNV MTP tables (`targetFromSourceId` column)  supposed to Ensembl gene IDs.  I checked a few, and they were not in the MAF files. The MTP filtering module is filtering them out, I am wondering why are they in the commit module tables? Can you investigate?  See attached Ensembl IDs filtered out of the SNV tables for MTP. 

```
> read_tsv("~/Downloads/gene-level-snv-consensus-annotated-mut-freq_dropped_ensg.tsv.gz") |> select(Gene_symbol, Ensembl_ID) |> distinct()
# A tibble: 1,224 x 2
   Gene_symbol Ensembl_ID
   <chr>       <chr>     
 1 DNAH3       55567     
 2 UTRN        7402      
 3 FCGBP       8857      
 4 WDFY4       57705     
 5 MUC19       283463    
 6 HELZ2       85441     
 7 NCOR2       9612      
 8 TENM1       10178     
 9 TENM2       57451     
10 MAST4       375449    
# ... with 1,214 more rows
# i Use `print(n = ...)` to see more rows
```
[variant-level-snv-consensus-annotated-mut-freq_dropped_ensg.tsv.gz](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/files/11092410/variant-level-snv-consensus-annotated-mut-freq_dropped_ensg.tsv.gz)

[gene-level-snv-consensus-annotated-mut-freq_dropped_ensg.tsv.gz](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/files/11092412/gene-level-snv-consensus-annotated-mut-freq_dropped_ensg.tsv.gz)

**Comment by kelseykeith** [comment]
Those ids are coming from the `Gene` column of the MAF, which is used for Ensembl IDs in the `snv-frequencies` code (see example below). Turns out the alternative numbers are actually the entrez IDs (for example see DNAH3 https://www.ncbi.nlm.nih.gov/gene/55567). As a fix for now, I could update the `snv-frequencies` code to only keep ensembl IDs

```
maf %>%
  distinct(Hugo_Symbol, Gene) %>%
  filter(Hugo_Symbol %in% c('DNAH3', 'UTRN', 'FCGBP', 'WDFY4',
                            'MUC19', 'HELZ2', 'NCOR2', 'TENM1', 
                            'MAST4')) %>% 
  distinct() %>%
  arrange(Hugo_Symbol)
```
| Hugo_Symbol | Gene |
| --- | --- |
DNAH3 | ENSG00000158486 |   |   |  
DNAH3 | 55567 |   |   |  
FCGBP | 8857 |   |   |  
FCGBP | ENSG00000275395 |   |   |  
HELZ2 | 85441 |   |   |  
HELZ2 | ENSG00000130589 |   |   |  
MAST4 | ENSG00000069020 |   |   |  
MAST4 | 375449 |   |   |  
MUC19 | 283463 |   |   |  
NCOR2 | ENSG00000196498

**Comment by ewafula** [comment]
> Those ids are coming from the `Gene` column of the MAF, which is used for Ensembl IDs in the `snv-frequencies` code (see example below). Turns out the alternative numbers are actually the entrez IDs (for example see DNAH3 https://www.ncbi.nlm.nih.gov/gene/55567). As a fix for now, I could update the `snv-frequencies` code to only keep ensembl IDs
> 
> ```
> maf %>%
>   distinct(Hugo_Symbol, Gene) %>%
>   filter(Hugo_Symbol %in% c('DNAH3', 'UTRN', 'FCGBP', 'WDFY4',
>                             'MUC19', 'HELZ2', 'NCOR2', 'TENM1', 
>                             'MAST4')) %>% 
>   distinct() %>%
>   arrange(Hugo_Symbol)
> ```
> 
> Hugo_Symbol	Gene
> DNAH3	ENSG00000158486
> DNAH3	55567
> FCGBP	8857
> FCGBP	ENSG00000275395
> HELZ2	85441
> HELZ2	ENSG00000130589
> MAST4	ENSG00000069020
> MAST4	375449
> MUC19	283463
> NCOR2	ENSG00000196498

**Comment by ewafula** [comment]
> 



> entrez IDs



> @kelseykeith, these weird IDs (1,224 unique) in the `gene-level-snv-consensus-annotated-mut-freq.tsv.gz` and `variant-level-snv-consensus-annotated-mut-freq.tsv.gz` v12 SNV MTP tables (`targetFromSourceId` column) supposed to Ensembl gene IDs. I checked a few, and they were not in the MAF files. The MTP filtering module is filtering them out, I am wondering why are they in the commit module tables? Can you investigate? See attached Ensembl IDs filtered out of the SNV tables for MTP.
> 
> ```
> > read_tsv("~/Downloads/gene-level-snv-consensus-annotated-mut-freq_dropped_ensg.tsv.gz") |> select(Gene_symbol, Ensembl_ID) |> distinct()
> # A tibble: 1,224 x 2
>    Gene_symbol Ensembl_ID
>    <chr>       <chr>     
>  1 DNAH3       55567     
>  2 UTRN        7402      
>  3 FCGBP       8857      
>  4 WDFY4       57705     
>  5 MUC19       283463    
>  6 HELZ2       85441     
>  7 NCOR2       9612      
>  8 TENM1       10178     
>  9 TENM2       57451     
> 10 MAST4       375449    
> # ... with 1,214 more rows
> # i Use `print(n = ...)` to see more rows
> ```
> 
> [variant-level-snv-consensus-annotated-mut-freq_dropped_ensg.tsv.gz](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/files/11092410/variant-level-snv-consensus-annotated-mut-freq_dropped_ensg.tsv.gz)
> 
> [gene-level-snv-consensus-annotated-mut-freq_dropped_ensg.tsv.gz](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/files/11092412/gene-level-snv-consensus-annotated-mut-freq_dropped_ensg.tsv.gz)

@kelseykeith, I've retracted my previous comment. Let's keep them in for now. They get filtered out anyway and won't be in the final MTP tables.

**Pull request merged**
