### PR TITLE
Update oncoprint-landscape to use Gencode v39

### PR DESCRIPTION
**Pull request by komalsrathi**
#### What scientific question is your analysis addressing?

1. Update oncoprint-landscape module
2. Create new genelists to be used with Gencode version 39

#### What was your approach?

1. Replace old genes with new (source: GeneCards) and remove existing duplicates.
2. Replace readr::read_tsv with data.table::fread for faster reading of maf file

#### What GitHub issue does your pull request address?

https://github.com/PediatricOpenTargets/ticket-tracker/issues/494

#### Which areas should receive a particularly close look?

N/A

#### Is there anything that you want to discuss further?

Should we remove the `driver-lists` folder as it is not being used?

#### Is the analysis in a mature enough form that the resulting figure(s) and/or table(s) are ready for review?

Yes

#### What types of results are included (e.g., table, figure)?

N/A

#### What is your summary of the results?

N/A

#### Reproducibility Checklist

- [ ] The dependencies required to run the code in this pull request have been added to the project Dockerfile.
- [ ] This analysis has been added to continuous integration.

#### Documentation Checklist

- [ ] This analysis module has a `README` and it is up to date.
- [ ] This analysis is recorded in the table in `analyses/README.md` and the entry is up to date.
- [ ] The analytical code is documented and contains comments.

### CODE REVIEW

**Comment by jharenza** [comment]
Hi @komalsrathi thanks for starting this. I just peeked at the lists and it looks like this module is super out of date- can you pull the lists from OpenPBTA, or even bring that whole module folder over to replace this one? We have not done anything with this in OPC, so I'd be ok with you bringing it all over, updating the lists, then merging.

Basically, we aren't using long or short- we had generated 4 lists (by broad hist oncoplot) so what you'll want to do is update those and combine for your purposes.

**Comment by komalsrathi** [comment]
Yes sure!

**Comment by komalsrathi** [comment]
So I don't see 4 lists and instead only see [these](https://github.com/AlexsLemonade/OpenPBTA-analysis/tree/master/analyses/oncoprint-landscape/driver-lists) gene lists from OpenPBTA which look identical to what we have in OPC. Am I looking at the wrong folder? 

```
➜  OpenPBTA-analysis git:(master) git pull origin master
From github.com:AlexsLemonade/OpenPBTA-analysis
 * branch            master     -> FETCH_HEAD
Already up to date.

# short list comparison between OpenPBTA and OPC (only diff is new line character)
➜  OpenPBTA-analysis git:(master) diff analyses/oncoprint-landscape/driver-lists/brain-goi-list-short.txt ../OpenPedCan-analysis/analyses/oncoprint-landscape/driver-lists/brain-goi-list-short.txt
26c26
< MYC
---
> MYC
\ No newline at end of file

# long list comparison between OpenPBTA and OPC (no difference)
➜  OpenPBTA-analysis git:(master) diff analyses/oncoprint-landscape/driver-lists/brain-goi-list-long.txt ../OpenPedCan-analysis/analyses/oncoprint-landscape/driver-lists/brain-goi-list-long.txt
```

**Comment by jharenza** [comment]
Ah, sorry they are [here](https://github.com/AlexsLemonade/OpenPBTA-analysis/tree/master/analyses/oncoprint-landscape/data)

**Comment by komalsrathi** [comment]
This is ready to review.

**Review by jharenza — APPROVED** [review]
Thanks @komalsrathi

**Comment by jharenza** [comment]
will merge this without CI since we aren't yet running this module

**Pull request merged**
