### PR TITLE
Collapse rnaseq with generic names

### PR DESCRIPTION
**Pull request by kgaonkar6**
#### What scientific question is your analysis addressing?
The rnaseq files are now updated to have generic names so updated the collapse-rnaseq module to create the *collapsed* files for v4

#### What was your approach?
Remove project-acronym and library-strategies from the naming convention.

#### What GitHub issue does your pull request address?
[#24](https://github.com/PediatricOpenTargets/ticket-tracker/issues/24)

#### Which areas should receive a particularly close look?
NA

#### Is there anything that you want to discuss further?
NA

#### Is the analysis in a mature enough form that the resulting figure(s) and/or table(s) are ready for review?
Yes

#### What types of results are included (e.g., table, figure)?
tables

#### What is your summary of the results?
kfnbl+pbta collapsed files

#### Reproducibility Checklist

- [x] The dependencies required to run the code in this pull request have been added to the project Dockerfile.
- [x] This analysis has been added to continuous integration.

#### Documentation Checklist

- [x] This analysis module has a `README` and it is up to date.
- [x] This analysis is recorded in the table in `analyses/README.md` and the entry is up to date.
- [x] The analytical code is documented and contains comments.

### CODE REVIEW

**Comment by logstar** [comment]
@kgaonkar6 Thank you for updating the analysis module for generic RNA-seq matrix names.

All look good, except `02-analyze-drops.Rmd` still has a `strategy` parameter, which is used for 
<https://github.com/PediatricOpenTargets/OpenPedCan-analysis/blob/7b9b705b33813cfd412ad87eb1f726a248834c54/analyses/collapse-rnaseq/02-analyze-drops.Rmd#L86-L101>.

As generic RNA-seq matrix names do not have library preparation strategy, it might be more straightforward to remove the strategy parameter and modify relevant code in `02-analyze-drops.Rmd`.

**Review by logstar — CHANGES_REQUESTED** [review]
@kgaonkar6 Thank you for updating the analysis module for generic RNA-seq matrix names.

All look good, except `02-analyze-drops.Rmd` still has a `strategy` parameter, which is used for 
<https://github.com/PediatricOpenTargets/OpenPedCan-analysis/blob/7b9b705b33813cfd412ad87eb1f726a248834c54/analyses/collapse-rnaseq/02-analyze-drops.Rmd#L86-L101>.

As generic RNA-seq matrix names do not have library preparation strategy, it might be more straightforward to remove the strategy parameter and modify relevant code in `02-analyze-drops.Rmd`.

**Comment by kgaonkar6** [comment]
Thanks for the review @logstar! I've updated the notebook and also removed the old files since those will not be required anymore , the collapsed files will be available via download_script.sh

**Review by logstar — APPROVED** [review]
@kgaonkar6 Thank you for the updates.

**Pull request merged**
