### PR TITLE
[WIP] Update oncoprint-landscape module to generate mutation frequency table

### PR DESCRIPTION
**Pull request by logstar**
#### What scientific question is your analysis addressing?

Update oncoprint-landscape module to output a gene mutation frequency TSV per `cancer_group`/`cancer_group_cohort` for Pediatric Open Targets platform. For this, we will use all genes, not genes of interest.

#### What was your approach?

**(Update 06/28/2021 3pm)** Subset independent samples in `snv-consensus-plus-hotspots.maf.tsv.gz` either with `../independent-samples/results/independent-specimens.wgs.primary.tsv` or `../independent-samples/results/independent-specimens.wgs.primary-plus.tsv`.

If `n_samples >= 5` in a `cancer_group`/`cancer_group_cohort`, use `maftools::getGeneSummary` to get the mutation frequency table for the following non-synonymous variant classifications:

```text
c(
        "Frame_Shift_Del",
        "Frame_Shift_Ins",
        "Splice_Site",
        "Nonsense_Mutation",
        "Nonstop_Mutation",
        "In_Frame_Del",
        "In_Frame_Ins",
        "Missense_Mutation",
        "Fusion",
        "Multi_Hit",
        "Multi_Hit_Fusion",
        "Hom_Deletion",
        "Hem_Deletion",
        "Amp",
        "Del",
        "Translation_Start_Site"
      )
```

Compute `altered_sample_percentage = AlteredSamples / n_samples * 100` for each gene.

#### What GitHub issue does your pull request address?

<https://github.com/PediatricOpenTargets/ticket-tracker/issues/8>

#### Which areas should receive a particularly close look?

Is it appropriate to use `Kids_First_Biospecimen_ID` as `Tumor_Sample_Barcode`? In previous analysis, `sample_id` is used as `Tumor_Sample_Barcode`, but I found `sample_id` has a large number of duplicates in `PediatricOpenTargets/OpenPedCan-analysis` data release. In previous analysis, `sample_id` is also used to find independent RNA-seq samples for filtering fusion data frame, which is described in <https://github.com/PediatricOpenTargets/ticket-tracker/issues/8#issuecomment-867902947>.

Are the mutation frequency tables in the expected format?

```text
head results/primary_only-Neuroblastoma-mutation_frequency.tsv 
Hugo_Symbol	Frame_Shift_Del	Frame_Shift_Ins	In_Frame_Del	In_Frame_Ins	Missense_Mutation	Nonsense_Mutation	Nonstop_Mutation	Splice_Site	Translation_Start_Site	total	MutatedSamples	AlteredSamples	n_samples	altered_sample_percentage
MUC5AC	0	0	0	0	29	0	0	0	0	29	21	21	328	6.402439024390244
ALK	0	0	0	0	20	0	0	0	0	20	20	20	328	6.097560975609756
MUC16	0	0	0	0	18	2	0	1	0	21	17	17	328	5.182926829268292
KL	0	0	0	0	16	1	0	0	0	17	17	17	328	5.182926829268292
MT-ND5	0	0	0	0	13	0	0	0	0	13	12	12	328	3.6585365853658534
TTN	1	0	0	0	18	1	0	0	0	20	11	11	328	3.353658536585366
DNAH11	0	0	0	0	11	0	0	0	0	11	11	11	328	3.353658536585366
SP8	0	0	11	0	0	0	0	0	0	11	11	11	328	3.353658536585366
MT-CYB	0	0	0	0	16	0	0	0	0	16	10	10	328	3.048780487804878
```

#### Is there anything that you want to discuss further?

**(Update 06/28/2021 3pm)** Do we also need to subset independent samples using `independent-specimens.wgs.relapse.tsv`? The relapse samples are mentioned in <https://github.com/PediatricOpenTargets/ticket-tracker/issues/64>.

The `maftools::getGeneSummary` will only include genes that have non-synonymous mutations. Do we need to add all other genes and 0s in the mutation frequency table?

This module is still work in progress:

- The code is very time inefficient, in order to reduce memory usage. The time efficient version of the code uses > 16GB memory, which exceeds the limit of my local computer. I have submitted a request to apply for kf-strides AWS EC2 access.
- As the code is very time inefficient, I have not fully tested result reproducibility using the CI docker image.
- The module only uses `snv-consensus-plus-hotspots.maf.tsv.gz`, and the module is going to include CNV and fusion when the data are available.

I have left many lines of previous code commented rather than deleted for future reference. I will delete them after adding CNV and fusion to this module as well.

#### Is the analysis in a mature enough form that the resulting figure(s) and/or table(s) are ready for review?

The resulting figures and tables are ready for review.

The correctness of the code is ready for review.

The efficiency of the code is not ready for review, which will be further optimized after obtaining access to kf-strides.

#### What types of results are included (e.g., table, figure)?

Tables and figures.

#### What is your summary of the results?
- **Tables:**

```text
wc -l results/*tsv
     295 results/primary-plus-Adamantimomatous-craniopharyngioma-mutation_frequency.tsv
     295 results/primary-plus-Adamantimomatous-craniopharyngioma___CBTN-mutation_frequency.tsv
    1411 results/primary-plus-Atypical-Teratoid-Rhabdoid-Tumor-mutation_frequency.tsv
    1411 results/primary-plus-Atypical-Teratoid-Rhabdoid-Tumor___CBTN-mutation_frequency.tsv
     101 results/primary-plus-Atypical-meningioma-mutation_frequency.tsv
     101 results/primary-plus-Atypical-meningioma___CBTN-mutation_frequency.tsv
     149 results/primary-plus-Benign-tumor-mutation_frequency.tsv
     149 results/primary-plus-Benign-tumor___CBTN-mutation_frequency.tsv
     133 results/primary-plus-CNS-Embryonal-tumor-mutation_frequency.tsv
     133 results/primary-plus-CNS-Embryonal-tumor___CBTN-mutation_frequency.tsv
     111 results/primary-plus-Choroid-plexus-papilloma-mutation_frequency.tsv
     111 results/primary-plus-Choroid-plexus-papilloma___CBTN-mutation_frequency.tsv
     171 results/primary-plus-Craniopharyngioma-mutation_frequency.tsv
     171 results/primary-plus-Craniopharyngioma___CBTN-mutation_frequency.tsv
    1010 results/primary-plus-Diffuse-midline-glioma-mutation_frequency.tsv
     845 results/primary-plus-Diffuse-midline-glioma___CBTN-mutation_frequency.tsv
     196 results/primary-plus-Diffuse-midline-glioma___PNOC-mutation_frequency.tsv
     208 results/primary-plus-Dysembryoplastic-neuroepithelial-tumor-mutation_frequency.tsv
     208 results/primary-plus-Dysembryoplastic-neuroepithelial-tumor___CBTN-mutation_frequency.tsv
      88 results/primary-plus-Dysplasia-Gliosis-mutation_frequency.tsv
      88 results/primary-plus-Dysplasia-Gliosis___CBTN-mutation_frequency.tsv
    2492 results/primary-plus-Ependymoma-mutation_frequency.tsv
    2492 results/primary-plus-Ependymoma___CBTN-mutation_frequency.tsv
      78 results/primary-plus-Ewing-sarcoma-mutation_frequency.tsv
      78 results/primary-plus-Ewing-sarcoma___CBTN-mutation_frequency.tsv
      60 results/primary-plus-Glial-neuronal-tumor-NOS-mutation_frequency.tsv
      60 results/primary-plus-Glial-neuronal-tumor-NOS___CBTN-mutation_frequency.tsv
   13213 results/primary-plus-High-grade-glioma-astrocytoma-mutation_frequency.tsv
   13196 results/primary-plus-High-grade-glioma-astrocytoma___CBTN-mutation_frequency.tsv
    3366 results/primary-plus-Low-grade-glioma-astrocytoma-mutation_frequency.tsv
    3366 results/primary-plus-Low-grade-glioma-astrocytoma___CBTN-mutation_frequency.tsv
    1782 results/primary-plus-Medulloblastoma-mutation_frequency.tsv
    1782 results/primary-plus-Medulloblastoma___CBTN-mutation_frequency.tsv
     175 results/primary-plus-Meningioma-mutation_frequency.tsv
     175 results/primary-plus-Meningioma___CBTN-mutation_frequency.tsv
    5928 results/primary-plus-Neuroblastoma-mutation_frequency.tsv
    5928 results/primary-plus-Neuroblastoma___GMKF-mutation_frequency.tsv
     109 results/primary-plus-Neurofibroma-Plexiform-mutation_frequency.tsv
     109 results/primary-plus-Neurofibroma-Plexiform___CBTN-mutation_frequency.tsv
     152 results/primary-plus-Schwannoma-mutation_frequency.tsv
     152 results/primary-plus-Schwannoma___CBTN-mutation_frequency.tsv
      92 results/primary-plus-Teratoma-mutation_frequency.tsv
      92 results/primary-plus-Teratoma___CBTN-mutation_frequency.tsv
     199 results/primary_only-Adamantimomatous-craniopharyngioma-mutation_frequency.tsv
     199 results/primary_only-Adamantimomatous-craniopharyngioma___CBTN-mutation_frequency.tsv
     425 results/primary_only-Atypical-Teratoid-Rhabdoid-Tumor-mutation_frequency.tsv
     425 results/primary_only-Atypical-Teratoid-Rhabdoid-Tumor___CBTN-mutation_frequency.tsv
     101 results/primary_only-Atypical-meningioma-mutation_frequency.tsv
     101 results/primary_only-Atypical-meningioma___CBTN-mutation_frequency.tsv
      95 results/primary_only-Benign-tumor-mutation_frequency.tsv
      95 results/primary_only-Benign-tumor___CBTN-mutation_frequency.tsv
      98 results/primary_only-CNS-Embryonal-tumor-mutation_frequency.tsv
      98 results/primary_only-CNS-Embryonal-tumor___CBTN-mutation_frequency.tsv
     106 results/primary_only-Choroid-plexus-papilloma-mutation_frequency.tsv
     106 results/primary_only-Choroid-plexus-papilloma___CBTN-mutation_frequency.tsv
      66 results/primary_only-Craniopharyngioma-mutation_frequency.tsv
      66 results/primary_only-Craniopharyngioma___CBTN-mutation_frequency.tsv
     779 results/primary_only-Diffuse-midline-glioma-mutation_frequency.tsv
     608 results/primary_only-Diffuse-midline-glioma___CBTN-mutation_frequency.tsv
     197 results/primary_only-Diffuse-midline-glioma___PNOC-mutation_frequency.tsv
     141 results/primary_only-Dysembryoplastic-neuroepithelial-tumor-mutation_frequency.tsv
     141 results/primary_only-Dysembryoplastic-neuroepithelial-tumor___CBTN-mutation_frequency.tsv
      84 results/primary_only-Dysplasia-Gliosis-mutation_frequency.tsv
      84 results/primary_only-Dysplasia-Gliosis___CBTN-mutation_frequency.tsv
    2331 results/primary_only-Ependymoma-mutation_frequency.tsv
    2331 results/primary_only-Ependymoma___CBTN-mutation_frequency.tsv
      62 results/primary_only-Ewing-sarcoma-mutation_frequency.tsv
      62 results/primary_only-Ewing-sarcoma___CBTN-mutation_frequency.tsv
   10964 results/primary_only-High-grade-glioma-astrocytoma-mutation_frequency.tsv
   10949 results/primary_only-High-grade-glioma-astrocytoma___CBTN-mutation_frequency.tsv
    2345 results/primary_only-Low-grade-glioma-astrocytoma-mutation_frequency.tsv
    2345 results/primary_only-Low-grade-glioma-astrocytoma___CBTN-mutation_frequency.tsv
    1761 results/primary_only-Medulloblastoma-mutation_frequency.tsv
    1761 results/primary_only-Medulloblastoma___CBTN-mutation_frequency.tsv
      89 results/primary_only-Meningioma-mutation_frequency.tsv
      89 results/primary_only-Meningioma___CBTN-mutation_frequency.tsv
    5928 results/primary_only-Neuroblastoma-mutation_frequency.tsv
    5928 results/primary_only-Neuroblastoma___GMKF-mutation_frequency.tsv
      63 results/primary_only-Neurofibroma-Plexiform-mutation_frequency.tsv
      63 results/primary_only-Neurofibroma-Plexiform___CBTN-mutation_frequency.tsv
     150 results/primary_only-Schwannoma-mutation_frequency.tsv
     150 results/primary_only-Schwannoma___CBTN-mutation_frequency.tsv
```

- **Figures:**

```text
ls -1 plots 
primary-plus-Adamantimomatous-craniopharyngioma-goi_oncoprint.png
primary-plus-Adamantimomatous-craniopharyngioma-oncoprint.png
primary-plus-Adamantimomatous-craniopharyngioma___CBTN-goi_oncoprint.png
primary-plus-Adamantimomatous-craniopharyngioma___CBTN-oncoprint.png
primary-plus-Atypical-Teratoid-Rhabdoid-Tumor-goi_oncoprint.png
primary-plus-Atypical-Teratoid-Rhabdoid-Tumor-oncoprint.png
primary-plus-Atypical-Teratoid-Rhabdoid-Tumor___CBTN-goi_oncoprint.png
primary-plus-Atypical-Teratoid-Rhabdoid-Tumor___CBTN-oncoprint.png
primary-plus-Atypical-meningioma-goi_oncoprint.png
primary-plus-Atypical-meningioma-oncoprint.png
primary-plus-Atypical-meningioma___CBTN-goi_oncoprint.png
primary-plus-Atypical-meningioma___CBTN-oncoprint.png
primary-plus-Benign-tumor-goi_oncoprint.png
primary-plus-Benign-tumor-oncoprint.png
primary-plus-Benign-tumor___CBTN-goi_oncoprint.png
primary-plus-Benign-tumor___CBTN-oncoprint.png
primary-plus-CNS-Embryonal-tumor-goi_oncoprint.png
primary-plus-CNS-Embryonal-tumor-oncoprint.png
primary-plus-CNS-Embryonal-tumor___CBTN-goi_oncoprint.png
primary-plus-CNS-Embryonal-tumor___CBTN-oncoprint.png
primary-plus-Choroid-plexus-papilloma-goi_oncoprint.png
primary-plus-Choroid-plexus-papilloma-oncoprint.png
primary-plus-Choroid-plexus-papilloma___CBTN-goi_oncoprint.png
primary-plus-Choroid-plexus-papilloma___CBTN-oncoprint.png
primary-plus-Craniopharyngioma-goi_oncoprint.png
primary-plus-Craniopharyngioma-oncoprint.png
primary-plus-Craniopharyngioma___CBTN-goi_oncoprint.png
primary-plus-Craniopharyngioma___CBTN-oncoprint.png
primary-plus-Diffuse-midline-glioma-goi_oncoprint.png
primary-plus-Diffuse-midline-glioma-oncoprint.png
primary-plus-Diffuse-midline-glioma___CBTN-goi_oncoprint.png
primary-plus-Diffuse-midline-glioma___CBTN-oncoprint.png
primary-plus-Diffuse-midline-glioma___PNOC-goi_oncoprint.png
primary-plus-Diffuse-midline-glioma___PNOC-oncoprint.png
primary-plus-Dysembryoplastic-neuroepithelial-tumor-goi_oncoprint.png
primary-plus-Dysembryoplastic-neuroepithelial-tumor-oncoprint.png
primary-plus-Dysembryoplastic-neuroepithelial-tumor___CBTN-goi_oncoprint.png
primary-plus-Dysembryoplastic-neuroepithelial-tumor___CBTN-oncoprint.png
primary-plus-Dysplasia-Gliosis-goi_oncoprint.png
primary-plus-Dysplasia-Gliosis-oncoprint.png
primary-plus-Dysplasia-Gliosis___CBTN-goi_oncoprint.png
primary-plus-Dysplasia-Gliosis___CBTN-oncoprint.png
primary-plus-Ependymoma-goi_oncoprint.png
primary-plus-Ependymoma-oncoprint.png
primary-plus-Ependymoma___CBTN-goi_oncoprint.png
primary-plus-Ependymoma___CBTN-oncoprint.png
primary-plus-Ewing-sarcoma-goi_oncoprint.png
primary-plus-Ewing-sarcoma-oncoprint.png
primary-plus-Ewing-sarcoma___CBTN-goi_oncoprint.png
primary-plus-Ewing-sarcoma___CBTN-oncoprint.png
primary-plus-Glial-neuronal-tumor-NOS-goi_oncoprint.png
primary-plus-Glial-neuronal-tumor-NOS-oncoprint.png
primary-plus-Glial-neuronal-tumor-NOS___CBTN-goi_oncoprint.png
primary-plus-Glial-neuronal-tumor-NOS___CBTN-oncoprint.png
primary-plus-High-grade-glioma-astrocytoma-goi_oncoprint.png
primary-plus-High-grade-glioma-astrocytoma-oncoprint.png
primary-plus-High-grade-glioma-astrocytoma___CBTN-goi_oncoprint.png
primary-plus-High-grade-glioma-astrocytoma___CBTN-oncoprint.png
primary-plus-Low-grade-glioma-astrocytoma-goi_oncoprint.png
primary-plus-Low-grade-glioma-astrocytoma-oncoprint.png
primary-plus-Low-grade-glioma-astrocytoma___CBTN-goi_oncoprint.png
primary-plus-Low-grade-glioma-astrocytoma___CBTN-oncoprint.png
primary-plus-Medulloblastoma-goi_oncoprint.png
primary-plus-Medulloblastoma-oncoprint.png
primary-plus-Medulloblastoma___CBTN-goi_oncoprint.png
primary-plus-Medulloblastoma___CBTN-oncoprint.png
primary-plus-Meningioma-goi_oncoprint.png
primary-plus-Meningioma-oncoprint.png
primary-plus-Meningioma___CBTN-goi_oncoprint.png
primary-plus-Meningioma___CBTN-oncoprint.png
primary-plus-Neuroblastoma-goi_oncoprint.png
primary-plus-Neuroblastoma-oncoprint.png
primary-plus-Neuroblastoma___GMKF-goi_oncoprint.png
primary-plus-Neuroblastoma___GMKF-oncoprint.png
primary-plus-Neurofibroma-Plexiform-goi_oncoprint.png
primary-plus-Neurofibroma-Plexiform-oncoprint.png
primary-plus-Neurofibroma-Plexiform___CBTN-goi_oncoprint.png
primary-plus-Neurofibroma-Plexiform___CBTN-oncoprint.png
primary-plus-Schwannoma-goi_oncoprint.png
primary-plus-Schwannoma-oncoprint.png
primary-plus-Schwannoma___CBTN-goi_oncoprint.png
primary-plus-Schwannoma___CBTN-oncoprint.png
primary-plus-Teratoma-goi_oncoprint.png
primary-plus-Teratoma-oncoprint.png
primary-plus-Teratoma___CBTN-goi_oncoprint.png
primary-plus-Teratoma___CBTN-oncoprint.png
primary_only-Adamantimomatous-craniopharyngioma-goi_oncoprint.png
primary_only-Adamantimomatous-craniopharyngioma-oncoprint.png
primary_only-Adamantimomatous-craniopharyngioma___CBTN-goi_oncoprint.png
primary_only-Adamantimomatous-craniopharyngioma___CBTN-oncoprint.png
primary_only-Atypical-Teratoid-Rhabdoid-Tumor-goi_oncoprint.png
primary_only-Atypical-Teratoid-Rhabdoid-Tumor-oncoprint.png
primary_only-Atypical-Teratoid-Rhabdoid-Tumor___CBTN-goi_oncoprint.png
primary_only-Atypical-Teratoid-Rhabdoid-Tumor___CBTN-oncoprint.png
primary_only-Atypical-meningioma-goi_oncoprint.png
primary_only-Atypical-meningioma-oncoprint.png
primary_only-Atypical-meningioma___CBTN-goi_oncoprint.png
primary_only-Atypical-meningioma___CBTN-oncoprint.png
primary_only-Benign-tumor-goi_oncoprint.png
primary_only-Benign-tumor-oncoprint.png
primary_only-Benign-tumor___CBTN-goi_oncoprint.png
primary_only-Benign-tumor___CBTN-oncoprint.png
primary_only-CNS-Embryonal-tumor-goi_oncoprint.png
primary_only-CNS-Embryonal-tumor-oncoprint.png
primary_only-CNS-Embryonal-tumor___CBTN-goi_oncoprint.png
primary_only-CNS-Embryonal-tumor___CBTN-oncoprint.png
primary_only-Choroid-plexus-papilloma-goi_oncoprint.png
primary_only-Choroid-plexus-papilloma-oncoprint.png
primary_only-Choroid-plexus-papilloma___CBTN-goi_oncoprint.png
primary_only-Choroid-plexus-papilloma___CBTN-oncoprint.png
primary_only-Craniopharyngioma-goi_oncoprint.png
primary_only-Craniopharyngioma-oncoprint.png
primary_only-Craniopharyngioma___CBTN-goi_oncoprint.png
primary_only-Craniopharyngioma___CBTN-oncoprint.png
primary_only-Diffuse-midline-glioma-goi_oncoprint.png
primary_only-Diffuse-midline-glioma-oncoprint.png
primary_only-Diffuse-midline-glioma___CBTN-goi_oncoprint.png
primary_only-Diffuse-midline-glioma___CBTN-oncoprint.png
primary_only-Diffuse-midline-glioma___PNOC-goi_oncoprint.png
primary_only-Diffuse-midline-glioma___PNOC-oncoprint.png
primary_only-Dysembryoplastic-neuroepithelial-tumor-goi_oncoprint.png
primary_only-Dysembryoplastic-neuroepithelial-tumor-oncoprint.png
primary_only-Dysembryoplastic-neuroepithelial-tumor___CBTN-goi_oncoprint.png
primary_only-Dysembryoplastic-neuroepithelial-tumor___CBTN-oncoprint.png
primary_only-Dysplasia-Gliosis-goi_oncoprint.png
primary_only-Dysplasia-Gliosis-oncoprint.png
primary_only-Dysplasia-Gliosis___CBTN-goi_oncoprint.png
primary_only-Dysplasia-Gliosis___CBTN-oncoprint.png
primary_only-Ependymoma-goi_oncoprint.png
primary_only-Ependymoma-oncoprint.png
primary_only-Ependymoma___CBTN-goi_oncoprint.png
primary_only-Ependymoma___CBTN-oncoprint.png
primary_only-Ewing-sarcoma-goi_oncoprint.png
primary_only-Ewing-sarcoma-oncoprint.png
primary_only-Ewing-sarcoma___CBTN-goi_oncoprint.png
primary_only-Ewing-sarcoma___CBTN-oncoprint.png
primary_only-High-grade-glioma-astrocytoma-goi_oncoprint.png
primary_only-High-grade-glioma-astrocytoma-oncoprint.png
primary_only-High-grade-glioma-astrocytoma___CBTN-goi_oncoprint.png
primary_only-High-grade-glioma-astrocytoma___CBTN-oncoprint.png
primary_only-Low-grade-glioma-astrocytoma-goi_oncoprint.png
primary_only-Low-grade-glioma-astrocytoma-oncoprint.png
primary_only-Low-grade-glioma-astrocytoma___CBTN-goi_oncoprint.png
primary_only-Low-grade-glioma-astrocytoma___CBTN-oncoprint.png
primary_only-Medulloblastoma-goi_oncoprint.png
primary_only-Medulloblastoma-oncoprint.png
primary_only-Medulloblastoma___CBTN-goi_oncoprint.png
primary_only-Medulloblastoma___CBTN-oncoprint.png
primary_only-Meningioma-goi_oncoprint.png
primary_only-Meningioma-oncoprint.png
primary_only-Meningioma___CBTN-goi_oncoprint.png
primary_only-Meningioma___CBTN-oncoprint.png
primary_only-Neuroblastoma-goi_oncoprint.png
primary_only-Neuroblastoma-oncoprint.png
primary_only-Neuroblastoma___GMKF-goi_oncoprint.png
primary_only-Neuroblastoma___GMKF-oncoprint.png
primary_only-Neurofibroma-Plexiform-goi_oncoprint.png
primary_only-Neurofibroma-Plexiform-oncoprint.png
primary_only-Neurofibroma-Plexiform___CBTN-goi_oncoprint.png
primary_only-Neurofibroma-Plexiform___CBTN-oncoprint.png
primary_only-Schwannoma-goi_oncoprint.png
primary_only-Schwannoma-oncoprint.png
primary_only-Schwannoma___CBTN-goi_oncoprint.png
primary_only-Schwannoma___CBTN-oncoprint.png
```

#### Reproducibility Checklist

- [x] The dependencies required to run the code in this pull request have been added to the project Dockerfile.
- [ ] This analysis has been added to continuous integration.

#### Documentation Checklist

- [x] This analysis module has a `README` and it is up to date.
- [x] This analysis is recorded in the table in `analyses/README.md` and the entry is up to date.
- [x] The analytical code is documented and contains comments.

### CODE REVIEW

**Comment by kgaonkar6** [comment]
Hi @logstar, thanks for the updated module. 

I haven't reviewed the code yet, but just looking at the files changed I have a few suggestions:
- PediatricOpenTargets/ticket-tracker#8 doesn't request for plots so I believe *png files are not required as outputs here. You can start a new bash script for the Open Target analysis that only generates the required frequency tables as outputs. 
- Can we combine the output frequency into a dataframe that can be given as input to create json files as the final outputs here?  @jharenza thoughts on the columns ? 

Hugo_Symbol | Frame_Shift_Del | Frame_Shift_Ins |	In_Frame_Del	| Missense_Mutation |	Nonsense_Mutation |	Splice_Site | Translation_Start_Site | total	| MutatedSamples	| AlteredSamples | n_samples | altered_sample_percentage | cohort| cancer_group | ALL/primary-only/relapse-only 
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --

**Comment by jharenza** [comment]
hi @logstar, thanks for the PR! Agree with @kgaonkar6 here - we don't need the plots. Also, I had a peek at your tables, but we would like them formatted as the SNV table excel file in [this comment](https://github.com/PediatricOpenTargets/ticket-tracker/issues/8#issuecomment-867812833). This will need to be done on an SNV level with the variant changes also captured. Note: each row will have the %altered in primary and %altered in relapse for a given SNV. 

That being said, once they are formatted, we might also want to merge them in the way that you did with the z-score tables.

**Comment by logstar** [comment]
Hi @kgaonkar6 and @jharenza. Thank you for the replies.

Sorry that I overlooked the point in the comment <https://github.com/PediatricOpenTargets/ticket-tracker/issues/8#issuecomment-867812833> that we want to generate a table like the attached spreadsheet in the issue <https://github.com/PediatricOpenTargets/ticket-tracker/issues/8>.

I was wondering if I could create a new issue and module for the intended analysis and leave the `oncoprint-landscape` module as updated here. If this is OK, I will probably create a module called mutation-frequency-tables, which generates summary tables for SNV, CNV, and fusions.

The purpose of the `oncoprint-landscape` module is no longer compatible with the current goal of creating the tables according to the spreadsheet attached in the comment <https://github.com/PediatricOpenTargets/ticket-tracker/issues/8#issuecomment-867812833> and the issue <https://github.com/PediatricOpenTargets/ticket-tracker/issues/64>. In the `oncoprint-landscape` module, each gene is summarized to generate a summary plot (and the tables in the updated module) of SNV, CNV and fusion variants. However, in the spreadsheet, each variant is summarized to generate a summary table of SNV.

**Comment by jharenza** [comment]
Hi @logstar - yeah that sounds like a good plan since this has morphed a bit. In that case, we can come back to the oncoprint module a little later.

**Comment by kgaonkar6** [comment]
Adding a new module sounds good to me! 

Just wanted to answer some remaining questions in the PR above:
>Is it appropriate to use Kids_First_Biospecimen_ID as Tumor_Sample_Barcode? 

Great question! I'm not really sure I would have assumed `sample_id` but you point out some `sample_ids` have 100-1000s matches sometimes. Let's discuss this in the  updated ticket https://github.com/PediatricOpenTargets/ticket-tracker/issues/64. 

>Do we also need to subset independent samples using independent-specimens.wgs.relapse.tsv?

Yes please, for SNV frequency tables we will be using `independent-specimens.wgs.primary.tsv` and `independent-specimens.wgs.relapse.tsv` which will provide the counts to calculate `Frequency   in primary tumors` and `Frequency in relapse tumors`

I think we can close this PR since the code update for oncoprint module is not requested (yet haha ). Do you want to keep the branch locally in-case it's requested later?

**Comment by logstar** [comment]
Hi @kgaonkar6 and @jharenza . Thank you for the replies.

I will create a new issue for generating SNV mutation frequency tables in the format of the attached spreadsheet in the comment <https://github.com/PediatricOpenTargets/ticket-tracker/issues/8#issuecomment-867812833>.

I will close this PR and keep [this branch in my own fork](https://github.com/logstar/OpenPedCan-analysis/tree/mut-freq) for future reference.

**Pull request closed without merging**
