### PR TITLE
Run gistic update

### PR DESCRIPTION
**Pull request by runjin326**
#### What scientific question is your analysis addressing?
GISTIC results are required for running HGG module. 
We want to run new PNOC samples through the HGG module and hence this needs an update.

#### What was your approach?
- File name update: `pbta-cnv-consensus.seg.gz` to `cnv-consensus.seg.gz`
- Script updates:
    - For the OpenPBTA GISTIC module, they also generate files for `short_histology` of `LGAT`, `HGAT` and `Medulloblastoma`. However, in OpenTargets, `short_histology` field no longer use those terms (longer names were used). 
    - Since we can just use consensus gistic file for modules that uses the results, I completed removed the part that run for `LGAT`, `HGAT` and `Medulloblastoma` in the OT script -original OpenPBTA scripts were kept for references though
    - `prepare_seg_for_gistic.R` is added to modify `cnv-consensus.seg.gz` to use `tumor_ploidy` value as `copy.num` when `copy.num` is NA (see README for reason of updates)
    - `run-gistic-module.sh` is modified to just run for the entire cohort 
    - `run-gistic-openpbta.sh` is renamed to `run-gistic-opentargets.sh` and is modified to run on `cnv-consensus-gistic-only.seg.gz` (modify version of `cnv-consensus.seg.gz` with NA fixed).

#### What GitHub issue does your pull request address?
https://github.com/PediatricOpenTargets/ticket-tracker/issues/115

#### Which areas should receive a particularly close look?
Please check to see whether the code changes make sense. 

#### Is there anything that you want to discuss further?
No. 

#### Is the analysis in a mature enough form that the resulting figure(s) and/or table(s) are ready for review?

No.

#### What types of results are included (e.g., table, figure)?
The module output looks as expected (not uploading to GitHub).

#### What is your summary of the results?
NA.

#### Reproducibility Checklist

- [x] The dependencies required to run the code in this pull request have been added to the project Dockerfile.
- [ ] This analysis has been added to continuous integration.

#### Documentation Checklist

- [x] This analysis module has a `README` and it is up to date.
- [ ] This analysis is recorded in the table in `analyses/README.md` and the entry is up to date.
- [x] The analytical code is documented and contains comments.

### CODE REVIEW

**Comment by kgaonkar6** [comment]
Hi @runjin326 thanks for pointing this out. I had unfortunately missed this issue before. I've opened a ticket in OpenPBTA which I'm linking here as a proposed solution as well.
https://github.com/AlexsLemonade/OpenPBTA-analysis/issues/1180

**Comment by runjin326** [comment]
@kgaonkar6, thanks so much for looking into this :) Once we figure out a solution, I can simultaneously update the module here in OT.

**Comment by runjin326** [comment]
@kgaonkar6, I have now updated the GISTIC module and it ran smoothly on my machine locally. Please review the changes whenever you get time. Thanks!

**Review by kgaonkar6 — APPROVED** [review]
Adding ploidy information to the seg file looks good to me!

**Comment by runjin326** [comment]
@kgaonkar6, thanks for reviewing this! Will merge soon!

**Pull request merged**
