### PR TITLE
V12 chordoma (5/N)

### PR DESCRIPTION
**Pull request by jharenza**
#### What scientific question is your analysis addressing?

This PR runs chordoma subtyping for v12

#### What was your approach?
I simply reran the code- since the actual subtyping requires pathology input to determine whether these samples are poorly differentiating subtype, this module only collects chordoma status. The subtypes are added during pathology review. For v12, I think we can just simply rerun this and investigate any new subtypes after v12.

#### What GitHub issue does your pull request address?
v12 release

#### Which areas should receive a particularly close look?
Since I just reran this, I did not bring in any other samples. The methyl subtypes are only "chordoma", not to the detail of poorly differentiating, so they don't add additional information to the cancer group. 

#### Is there anything that you want to discuss further?
No

#### Is the analysis in a mature enough form that the resulting figure(s) and/or table(s) are ready for review?
Yes

#### What types of results are included (e.g., table, figure)?
chordoma status table

#### What is your summary of the results?
185 samples in status table

#### Reproducibility Checklist

- [x] The dependencies required to run the code in this pull request have been added to the project Dockerfile.
- [x] This analysis has been added to continuous integration.

#### Documentation Checklist

- [x] This analysis module has a `README` and it is up to date.
- [x] This analysis is recorded in the table in `analyses/README.md` and the entry is up to date.
- [x] The analytical code is documented and contains comments.

### CODE REVIEW

**Comment by zzgeng** [comment]
In script 01-Subtype-chordoma.Rmd, from line 92-107, 
```
copy_neutral_df <- subset_metadata %>%
  # the copy events can only be taken from WGS data not RNA-seq data
  # we also only want biospecimens where a loss was not recorded to avoid duplicates
  filter(
    experimental_strategy == "WGS",
    !(Kids_First_Biospecimen_ID %in% chordoma_loss$biospecimen_id)
  ) %>%
  # if there's no loss, let's assume status is copy neutral
  mutate(status = "neutral",
         copy_number = ploidy) %>%
  # let's get the columns to match chordoma_loss
  dplyr::rename(biospecimen_id = Kids_First_Biospecimen_ID) %>%
  select(biospecimen_id, status, copy_number,ploidy)
copy_neutral_df
```

This part of code overlooked the samples with experimental_strategy including "WXS", "Targeted Sequencing" and "Methylation". and the output "chordoma_smarcb1_status.tsv" missed a few samples compared with the subtype_metadata, which was generated from line 32-38.

```
subset_metadata <- histologies_df %>%
  dplyr::filter(pathology_diagnosis == "Chordoma") %>%
  select(
    Kids_First_Biospecimen_ID, sample_id, Kids_First_Participant_ID,
    experimental_strategy,tumor_ploidy
  ) %>%
  rename(ploidy=tumor_ploidy)
```

**Comment by jharenza** [comment]
@zzgeng this is ready for re-review. I added all samples to the final output file. I initially did not since we aren't getting subtypes here, but just added them to have them. Note: RNA values are only present for RNA bs_ids and DNA for DNA ids, which is not ideal, but there are many samples with the same match id, so this could not easily be matched up. This has to do with a lot of replicate samples from the chordoma foundation data here, so I think it is OK as it is. We can update this module after v12 once we have better clinical info from them.

**Review by zzgeng — APPROVED** [review]

**Comment by atlas4213** [comment]
I tried running the code and got an error about incompatible types. 

`Quitting from lines 105-112 (01-Subtype-chordoma.Rmd) 
Error in `left_join()`:
! Can't join on `x$Kids_First_Biospecimen_ID` x `y$Kids_First_Biospecimen_ID` because of incompatible types.
ℹ `x$Kids_First_Biospecimen_ID` is of type <logical>>.
ℹ `y$Kids_First_Biospecimen_ID` is of type <character>>.
Backtrace:
 1. ... %>% bind_rows(copy_neutral_df)
 5. dplyr:::left_join.data.frame(., subset_metadata[, c("Kids_First_Biospecimen_ID", "id")])`

**Review by atlas4213 — COMMENTED** [review]
When I attempted to run this module I got an error about an incompatible type when joining the tables 

`Quitting from lines 105-112 (01-Subtype-chordoma.Rmd) 
Error in `left_join()`:
! Can't join on `x$Kids_First_Biospecimen_ID` x `y$Kids_First_Biospecimen_ID` because of incompatible types.
ℹ `x$Kids_First_Biospecimen_ID` is of type <logical>>.
ℹ `y$Kids_First_Biospecimen_ID` is of type <character>>.
Backtrace:
 1. ... %>% bind_rows(copy_neutral_df)
 5. dplyr:::left_join.data.frame(., subset_metadata[, c("Kids_First_Biospecimen_ID", "id")])`

**Comment by jharenza** [comment]
> When I attempted to run this module I got an error about an incompatible type when joining the tables
> 
> `Quitting from lines 105-112 (01-Subtype-chordoma.Rmd) Error in `left_join()`: ! Can't join on `x$Kids_First_Biospecimen_ID`x`y$Kids_First_Biospecimen_ID`because of incompatible types. ℹ`x$Kids_First_Biospecimen_ID`is of type <logical>>. ℹ`y$Kids_First_Biospecimen_ID` is of type >. Backtrace:
> 
> 1. ... %>% bind_rows(copy_neutral_df)
> 2. dplyr:::left_join.data.frame(., subset_metadata[, c("Kids_First_Biospecimen_ID", "id")])`

I am not getting any errors running this. Are you running it in the docker image, and do you have v12 data downloaded?

**Comment by atlas4213** [comment]
> > When I attempted to run this module I got an error about an incompatible type when joining the tables
> > `Quitting from lines 105-112 (01-Subtype-chordoma.Rmd) Error in `left_join()`: ! Can't join on `x$Kids_First_Biospecimen_ID`x`y$Kids_First_Biospecimen_ID`because of incompatible types. ℹ`x$Kids_First_Biospecimen_ID`is of type <logical>>. ℹ`y$Kids_First_Biospecimen_ID` is of type >. Backtrace:
> > 
> > 1. ... %>% bind_rows(copy_neutral_df)
> > 2. dplyr:::left_join.data.frame(., subset_metadata[, c("Kids_First_Biospecimen_ID", "id")])`
> 
> I am not getting any errors running this. Are you running it in the docker image, and do you have v12 data downloaded?

I did a git pull to update my repo and then ran the download data script so I should be on v12. I was just running it on the ec2 image and not in a docker container

**Comment by jharenza** [comment]
>I was just running it on the ec2 image and not in a docker container

@atlas4213 can you confirm it is running for you now in the docker container? When reviewing, you will want to rerun in the docker container

**Comment by atlas4213** [comment]
> > I was just running it on the ec2 image and not in a docker container
> 
> @atlas4213 can you confirm it is running for you now in the docker container? When reviewing, you will want to rerun in the docker container

Okay, I reran it inside the docker image and it worked with no errors. Approving

**Review by atlas4213 — APPROVED** [review]

**Pull request merged**
