### PR TITLE
rerun molecular-subtyping-hgg

### PR DESCRIPTION
**Pull request by adilahiri**
#### What scientific question is your analysis addressing?
To rerun the `molecular-subtyping-HGG` module with using the new CNV files from 207 + 235

#### What was your approach?
Checked  R scripts within the module where the CNV files from 207+235 could be used. I found that in 
line 159 of script `02-HGG-molecular-subtyping-subset-files.R` , the data file `consensus_wgs_plus_cnvkit_wxs.tsv.gz`
was being used. As this was already coded into the script, no changes were made. I did not find other locations where any other files from 207 + 235 were being used.  The module was run using EC2.

#### What GitHub issue does your pull request address?
[Issue #401
](https://github.com/PediatricOpenTargets/ticket-tracker/issues/401)

#### Which areas should receive a particularly close look?
Please verify the result files

#### Is there anything that you want to discuss further?
No

#### Is the analysis in a mature enough form that the resulting figure(s) and/or table(s) are ready for review?
Yes

#### What types of results are included (e.g., table, figure)?
Tables and Figure

#### Reproducibility Checklist

- [ ] The dependencies required to run the code in this pull request have been added to the project Dockerfile.
- [ ] This analysis has been added to continuous integration.

#### Documentation Checklist

- [ X] This analysis module has a `README` and it is up to date.
- [X ] This analysis is recorded in the table in `analyses/README.md` and the entry is up to date.
- [X ] The analytical code is documented and contains comments.

### CODE REVIEW

**Review by jharenza — COMMENTED** [review]
Hi @adilahiri for these PRs, can you report any differences in final subtypes called. It does not look like there are any diffs here, even though the `HGG_cleaned_cnv.tsv` has additions and deletions. This seems to be a case of samples just in a different order in this PR and the final table `HGG_molecular_subtype.tsv` has no changes. Just want to confirm and this info will be useful for the other modules as well. Thank you!

**Comment by adilahiri** [comment]
Yes @jharenza  I will look into it.

**Comment by adilahiri** [comment]
Hi @jharenza , you are right about the reordering.  The rows of `HGG_cleaned_cnv.tsv` in the PR are indeed ordered differently compared to the rows of the same file in dev. I tried dplyr:all_equal() to compare the file from of this PR and the corresponding file in dev and it confirmed your initial observation.
```

> all_equal(pr_df,dev_df)
[1] TRUE
> all_equal(pr_df,dev_df,ignore_row_order = FALSE) ## When you consider the ordering of the rows
[1] "Same row values, but different order" 
```

**Comment by adilahiri** [comment]
Upon rerunning the module the frequency of HGG molecular subtype did not change. 

HGG_Subtype

**Comment by adilahiri** [comment]
For TP53-NF1-Score module changes were made to the result and plots directories of the modules. In the results directory new files were added and some of the existing file were updated. Following is the list of files that changed files with a brief description of the changes:
1. **fusion_bk_tp53_loss.tsv** :  The entries in the column `sample_id` were changed from 01A (dev) to 01 (PR).
```
> fusion_bk_tp53_loss_dev_df<-fusion_bk_tp53_loss_dev_df[,-c(7)] # Delete column 7 which is sample_id
> fusion_bk_tp53_loss_pr_df<-fusion_bk_tp53_loss_pr_df[,-c(7)]  # Delete column 7 which is sample_id
> all_equal(fusion_bk_tp53_loss_dev_df,fusion_bk_tp53_loss_pr_df)
[1] TRUE
```
2. **loss_overlap_domains_tp53.tsv**:  The new PR version of this file has the following extra columns:
`Kids_First_Participant_ID `, `composition ,``tumor_descriptor`, `tp53_shuffle`            
The PR file also has 118 observations (data points/rows) compared to the dev file which has 62 observation. The `copy_number` was 1 across biospecimen in both version of the files. The ploidy was 2,3,4 across the biospecimen in each of the files.  The `domain` was "P53_tetramer, P53, P53_TAD" in both versions of the file. 
```
> colnames(loss_overlap_tp53_dev_df)
[1] "biospecimen_id" "copy_number"    "ploidy"         "domain"         "sample_id"     
> colnames(loss_overlap_tp53_pr_df)
[1] "biospecimen_id"            "copy_number"               "ploidy"                    "domain"                    "Kids_First_Participant_ID"
[6] "sample_id"                 "composition"               "tumor_descriptor"          "tp53_shuffle"             
> unique(loss_overlap_tp53_pr_df$copy_number)
[1] 1
> unique(loss_overlap_tp53_dev_df$copy_number)
[1] 1
> unique(loss_overlap_tp53_dev_df$ploidy)
[1] 2 3 4
> unique(loss_overlap_tp53_pr_df$ploidy)
[1] 2 3 4
> unique(loss_overlap_tp53_pr_df$domain)
[1] "P53_tetramer, P53, P53_TAD"
> unique(loss_overlap_tp53_dev_df$domain)
[1] "P53_tetramer, P53, P53_TAD"
```

3.  **sv_overlap_tp53.tsv**: The PR version of the file has 40 extra rows (data points/samples) compared to the dev version of the file.  The `sv_type` across each file is compared in the figure below. 

svtype

4. **tp53_altered_status.tsv**: The PR version of the file contained more observations (data points / rows) compared to the dev version.   The unique `cancer_predisposition` were  the same in both the versions of the files.  However, in the PR file the observations across each `cancer_predisposition `category increased. 
```
> table(tp53_altered_status_dev_df$cancer_predispositions)  ##dev file

                          Li-Fraumeni syndrome                      Li-Fraumeni syndrome,NF-1                                           NF-1 
                                            34                                              7                                            130 
           NF-1,Other inherited conditions NOS                                           NF-2                           NF-2,Schwannomatosis 
                                             6                                             18                                             26 
                               None documented                 Other inherited conditions NOS Other inherited conditions NOS,Schwannomatosis 
                                          3658                                            113                                              4 
                               Schwannomatosis                             Tuberous Sclerosis 
                                            10                                             28 
> table(tp53_altered_status_pr_df$cancer_predispositions) ### PR file

                          Li-Fraumeni syndrome                      Li-Fraumeni syndrome,NF-1                                           NF-1 
                                            54                                              7                                            210 
           NF-1,Other inherited conditions NOS                                           NF-2                           NF-2,Schwannomatosis 
                                            12                                             26                                             46 
                               None documented                 Other inherited conditions NOS Other inherited conditions NOS,Schwannomatosis 
                                          5301                                            183                                              6 
                               Schwannomatosis                             Tuberous Sclerosis 
                                            19                                             54  
```

`SNV_indel_counts` ranged from 0 to 5 across both the file versions. 
`CNV_loss_counts `were either 0 or 1 in both the file versions.
`SV_Counts` ranged from 0 to 2 in both the file versions. 
`Fusion_counts` were 0,1 or 59 in each version of the file. 
```
> unique(tp53_altered_status_dev_df$SNV_indel_counts)
[1] 0 1 2 4 5 3
> unique(tp53_altered_status_pr_df$SNV_indel_counts)
[1] 0 1 2 4 5 3
> unique(tp53_altered_status_dev_df$CNV_loss_counts)
[1] 0 1
> unique(tp53_altered_status_pr_df$CNV_loss_counts)
[1] 0 1
> unique(tp53_altered_status_dev_df$SV_counts)
[1] 0 2 1
> unique(tp53_altered_status_pr_df$SV_counts)
[1] 0 1 2
> unique(tp53_altered_status_dev_df$Fusion_counts)
[1]  0 59  1
> unique(tp53_altered_status_pr_df$Fusion_counts)
[1] 59  0  1
> table(tp53_altered_status_pr_df$Fusion_counts)
```
`HGP_Short` was filled with NA values across each file version. Across both the PR and Dev versions of this file majority of the observations for `CNV_loss_evidence` were filled with NA values, while a minority of the observations were flagged as 1.  For `SV_type` the PR version of the file had a few extra categories, this is shown in the code below:

```
> table(tp53_altered_status_dev_df$SV_type)

DEL, INV      INV       NA 
       1        1     6718 
> table(tp53_altered_status_pr_df$SV_type)

     DEL DEL, INV      INV INV, BND       NA 
       1        3        4        1     9060 
```

The number of distinct categories of `Fusion_Evidence` remained unchanged across both  the file version.  Both the `hotspots` and `activating` observations increased in the PR file.

```
> table(tp53_altered_status_dev_df$hotspot)

   0    1 
6521  199 
> table(tp53_altered_status_pr_df$hotspot)

   0    1 
8775  294 
> table(tp53_altered_status_dev_df$activating)

   0    1 
6673   47 
> table(tp53_altered_status_pr_df$activating)

   0    1 
8998   71 
```

For `tp53_altered`,  we had more observation for each category in the PR file compared to the dev file.
```
> table(tp53_altered_status_dev_df$tp53_altered)

activated      loss     Other 
       47       243      6430 
> table(tp53_altered_status_pr_df$tp53_altered)

activated      loss     Other 
       71       419      8579 
```

5.  **TP53_NF1_snv_alteration.tsv**:  The PR version of the file had more observations than the Dev version of the same file.The number of observation in each of the main category (listed below in code) of `Variant_Classification` remained the same. What changed  in the PR is the number of observation in the NA category of the `Variant_Classification`.

```
> table(TP53_NF1_snv_alteration_dev_df$Variant_Classification)

                 5'UTR        Frame_Shift_Del        Frame_Shift_Ins           In_Frame_Del           In_Frame_Ins                   loss 
                     1                     49                     28                      8                      4                    932 
     Missense_Mutation      Nonsense_Mutation          Splice_Region            Splice_Site Translation_Start_Site 
                   268                     73                      2                     34                      2 
> table(TP53_NF1_snv_alteration_pr_df$Variant_Classification)

                 5'UTR        Frame_Shift_Del        Frame_Shift_Ins           In_Frame_Del           In_Frame_Ins                   loss 
                     1                     49                     28                      8                      4                    932 
     Missense_Mutation      Nonsense_Mutation          Splice_Region            Splice_Site Translation_Start_Site 
                   268                     73                      2                     34                      2 

```

**Comment by jharenza** [comment]
We can close this in favor of #258

**Pull request closed without merging**
