### PR TITLE
Adding pgc-images.sbgenomics.com as registry for build step

### PR DESCRIPTION
**Pull request by kgaonkar6**
#### What scientific question is your analysis addressing?
A minor update to set the pgc-images.sbgenomics.com as registry since we are using this registry to push the docker image. 

#### What was your approach?
Adding `registry: pgc-images.sbgenomics.com` here.
 Without it I need to provide my personal docker password for the build step and switch for the docker push step. 

#### What GitHub issue does your pull request address?
NA

#### Which areas should receive a particularly close look?
The `registry: pgc-images.sbgenomics.com` is necessary to  point to the sevenbridges registry without it it points to the users docker registry.

### CODE REVIEW

**Comment by jharenza** [comment]
@migbro since dan is out this week, can you review?

**Comment by migbro** [comment]
I can by Thursday, our usual reserved review time the latest

**Review by migbro — APPROVED** [review]
assuming the registry is all that is needed, this looks good!

**Comment by kgaonkar6** [comment]
thanks @migbro !

**Pull request merged**
